### ISSUE TITLE
Cross domain embedded JBrowse ?

### ISSUE THREAD

**Issue by JoelRichardson** [GMOD/jbrowse#1000]
Hi JBrowse devs,

I’ve been working on a tool where I want to embed an existing JBrowse (specifically, MGI’s JBrowse, located at http://jbrowse.informatics.jax.org/) in an iframe. I want panning/zooming/etc control in both directions, by which I mean:

- I want to be able to tell JBrowse to go to specific coordinates
- I want to catch coordinate changes made by the user in JBrowse 

I’ve read the JBrowse docs, forum posts, etc. Here’s where I’m at:

- Embedding MGI’s JBrowse in an iframe is easy. Likewise, setting “embedded mode” parameters. (But you knew that.)
- Telling JBrowse to switch coordinates is easy, too - just change the url in the iframe’s src. 
-- HOWEVER, this causes the iframe to reload, which is distinctly less satisfying than JBrowse’s wonderful smoothness. I don’t want to reload JBrowse, I just want to tell it to move.
- Catching JBrowse coordinate changes…no luck.
-- I tried the recipe at http://gmod.org/wiki/JBrowse_FAQ#How_can_I_get_jbrowse_to_update_the_URL_of_a_parent_page_when_jbrowse_is_inside_of_an_iframe
-- Things came to a screeching halt at “iframe.contentWindow.JBrowse” due to CORS restrictions, because the new app is not served from the jbrowse.informatics.jax.org domain. 

My first question is, do you have any advice or know of APIs that I’m missing?

If not, my second question (request, actually) is, could there be? I’m specifically thinking of some kind of minimal messaging API (using window.postMessage) that would allow an embedding app to do basic stuff like pan, zoom, goto coordinates, and such, without domain restrictions.

Thanks,
Joel

**Comment by rbuels** [comment]
If your iframe isn't being served from the same domain as the controlling page, I'm afraid you're out of luck.  There's no way you can poke at the Javascript running inside the iframe in that case.

However, if the iframe is running at the same domain, or if you smooth over the CORS permissions, you can control JBrowse from external code, but it's not really supported and documented.  JBrowse 1 isn't really designed for it. The next JBrowse series (2.x) will be.

To tell JBrowse to go someplace, try something like:

```document.querySelector('iframe').contentWindow.JBrowse.navigateTo("ctgA:4000..5000")```

To listen to coordinate changes, try something like:

```
document.querySelector('iframe')
.contentWindow
.JBrowse
.subscribe( '/jbrowse/v1/n/navigate',
                    function(msg) { console.log(msg) })
```

There's a reason these things aren't documented.  They could change at any time.  But they probably won't, in the 1.x series.

Feel free to reopen if you have further questions.  👍

**Comment by erasche** [comment]
Changing coordinates can also be done like:

```javascript
JBrowse.navigateTo("chrI:100..2000");
```

which is quite easy.
