### ISSUE TITLE
README.md corrections/suggestions

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#1004]
1. [Installing JBrowse](https://github.com/GMOD/jbrowse#installing-jbrowse) section:
    * In the last release the development methodology was changed to ensure that master remains a clean representation of the last release.  Currently the text conflicts with this.
1. [Install from github repo (development)](https://github.com/GMOD/jbrowse#install-from-github-repo-development) section:
    * Can't see any reason to do a full clone (possible relation to #1003):
      * full clone: `Receiving objects: 100% (79448/79448), 157.12 MiB | 735.00 KiB/s`
      * shallow: `Receiving objects: 100% (1767/1767), 5.49 MiB | 5.12 MiB/s`

**Comment by cmdcolin** [comment]
If you clone shallow it makes it difficult to checkout remote branches. It's almost better to just have the full copy if you want to ever check out remote branches

**Comment by keiranmraine** [comment]
Yes, sorry.  I was in thinking about this from the wrong angle as I was testing how my tool interacts rather than developing JBrowse itself.

**Comment by rbuels** [comment]
Anybody care to make a pull req to update this?
