### ISSUE TITLE
configuration issues due to bug? in Util.fillTemplate

### ISSUE THREAD

**Issue by wuroger** [GMOD/jbrowse#1012]
I am trying to pull a query param value into a config line in my jbrowse.conf:
```
url = http://server.com/tracks?param={queryParams.param}
```
and I find looking around at the source a tiny bit here:

https://github.com/GMOD/jbrowse/blob/f742408dca00d42cf51bdf0ad778a5936b0db0d2/src/JBrowse/Util.js#L118-L134

on line 121, fill does actually get set to the param that I am looking for, but then instead of returning, that anonymous function overwrites it and then ends up returning back the original {queryParams.param}. 

Should fill be returned if it isn't undefined after line 121? 

Thanks!

**Comment by rbuels** [comment]
oh man you're right. fixing now, getting in just under the wire for 1.12.5

**Comment by wuroger** [comment]
Thanks!  I was a little hesitant since JS is not my forte but thought it was worth mentioning
