### ISSUE TITLE
&tracklabels=0 does not work when &nav=0

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1017]
Reported here http://gmod.827538.n3.nabble.com/Gmod-ajax-Hide-track-labels-not-working-when-nav-0-td4057922.html

Link produces error

http://jbrowse.org/code/JBrowse-1.12.5/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A9702..11748&tracks=DNA%2CTranscript%2Cvolvox_microarray_bw_density%2Cvolvox_microarray_bw_xyplot%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam_coverage%2Cvolvox-sorted_bam%2CGenes%2CCDS%2Cvolvox_sine_density%2Cvolvox_sine_xyplot%2CReadingFrame%2Cvolvox_vcf_test&highlight=&nav=0&tracklabels=0

**Comment by rbuels** [comment]
@cmdcolin to be clear, we are talking about it throwing a JS error in the log, right?  I see that, but JBrowse still starts and runs.  Is that what you're seeing too?

**Comment by rbuels** [comment]
We need to add this URL to the Selenium tests so we can at least detect this JS error.
