### ISSUE TITLE
Question: How to change font size of histogram scale 

### ISSUE THREAD

**Issue by Rhinogradentia** [GMOD/jbrowse#1020]
Hi,

I need to increase the font size of a BigWig/Histogram Y-scale. I already tried it with text2Font and labelScale. 

Is there an easy tweak I didn't find?

Thank you in advance

Best Regards,
Nadine

**Comment by rbuels** [comment]
Hi Nadine, that font size isn't configurable at present. It would be a little tough to do, but you might look at src/JBrowse/View/Ruler.js to see how it draws the ruler using dojox charting, and if you can figure out a way to tweak the font sizes that dojox/charting is using.

**Comment by Rhinogradentia** [comment]
Thank you - I will take a look.
