### ISSUE TITLE
flatfile-to-json.pl show a warning if --trackLabel contains an illegal character

### ISSUE THREAD

**Issue by dytk2134** [GMOD/jbrowse#1023]
Hi, 

I was working on adding tracks data to jbrowse by running the flatfile-to-json.pl script. I just wondering if flatfile-to-json.pl can show a warning/error when --trackLable contains an illegal character like slash.
    
Here is the example command I used:  
```
perl /bin/flatfile-to-json.pl \
--gff /data/ImmunoDB_JAKSTATs.gff3 \
--arrowheadClass trellis-arrowhead \
--getSubfeatures \
--subfeatureClasses '{ "match_part" : "blast-match_part"}' \
--cssClass container-16px \
--type match_part \
--trackLabel "ImmunoDB JAK/STAT pathway proteins tBLASTN" \
--key "ImmunoDB JAK/STAT pathway proteins tBLASTN" \
--config '{ "category": "2. tBlastn" , "metadata": {"Analysis Method" : "tblastn ncbi-blast-2.2.31+"}}'
```
It seems like the script will try to generate a directory in tracks/ named "ImmunoDB JAK/STAT pathway proteins tBLASTN" and the `urlTemplate` will also point to that directory.   
**urlTemplate in trackList.json**
```
"urlTemplate" : "tracks/ImmunoDB JAK/STAT pathway proteins tBLASTN/{refseq}/trackData.json",
```
However, it failed but generated a directory structure like this:  
```
|-- ImmunoDB JAK
     `--  STAT pathway proteins tBLASTN
            |-- NW_007518467.1
            |-- NW_007515667.1     
```
Therefore, the jbrowse can't found the tracks data. 

Thank you!

**Comment by cmdcolin** [comment]
If slash is only thing that causes problems, then maybe error and exit from flatfile-to-json like this code: https://github.com/GMOD/jbrowse/tree/warn_slashes
