### ISSUE TITLE
adding plugin hosed jbrowse

### ISSUE THREAD

**Issue by malcook** [GMOD/jbrowse#1025]
Hello,

[JBrowse 1\.13\.0](https://github.com/GMOD/jbrowse/releases/tag/1.13.0-release) installed last night from a fork of master worked great.

Until....

I tried installing an Plugin and found that JBrowse would get hang on "Loading..."

The extension was: [Sequence Motif Density Plugin](https://github.com/bhofmei/jbplugin-motifdens) created by @bhofmei 

After following her installation instructions, JBrowse could not find the plugin I registered in the config files (I tried both .text and .json).   I figured her instructions lacked the directions to re-run setup.sh, so I did and restarted the server. 

It was at this point that I'm hanging on "Loading...".

My only success in backing out of this was reinstalling JBrowse completely.

I notice a few commits today having to do with plugins, so, perhaps this is a know issue now fixed in head?

All advice appreciated (included better recovery strategy than complete reinstallation).

Cheers!

**Comment by cmdcolin** [comment]
I think the problem is that domReady was specified in the middle of the dependencies list. There is special new code in the plugin loader to make domReady an unused dependency, but since it was in the middle, it was not filtered out properly. @bhofmei, do you want to remove domReady as dependency? It should cause no problem

**Comment by cmdcolin** [comment]
Specifically in the file js/View/Dialog/MotifDensityDialog.js

**Comment by rbuels** [comment]
oh i need to patch that loader

**Comment by rbuels** [comment]
@malcook you re-ran ./setup.sh after installing her plugin right?

**Comment by malcook** [comment]
@rbuels  - thanks for asking - yes I had re-run ./setup.sh 

Alas, @bhofmei, now when I try with the latest plugin on top of fresh jbrowse clone from yesterday it interferes with the "Available Tracks" panel, which appears blank.   They re-appear if I comment out jbrowse.conf as follows:

```
# [plugins.MotifDensityPlugin]
# location = plugins/MotifDensityPlugin
```
and restart jbrowse
    
    > utils/jb_run.js 

BTW - they include most happily for me a MultiBigWig displaying various signals over yeast protein, e.g.:

![image](https://user-images.githubusercontent.com/484282/37844797-d87d891c-2e96-11e8-8fa1-359fa9d405fa.png)

**Comment by bhofmei** [comment]
I’m sorry about the issues. I’ll look into as soon as I can, but it won’t be for a few weeks. I have another project about to released which uses node v6. I can’t update node for fear from breaking something in that project and I’ve tried but failed at getting 2 versions of node to run on the same computer.

**Comment by rbuels** [comment]
@malcook @bhofmei can we move this discussion to https://github.com/bhofmei/jbplugin-motifdens/issues/2?

@malcook I can try to help out over there since @bhofmei is indisposed
