### ISSUE TITLE
Install JBrowse 1.13.0-dev error

### ISSUE THREAD

**Issue by bhofmei** [GMOD/jbrowse#1026]
I was trying to update my plugins to work with JBrowse 1.13.0 via zip download of JBrowse-1.13.0-dev at the JBrowse website. I cannot get the sample data to work. I run setup.sh (no plugins installed) and navigate to the sample data url and get this error: `TypeError: Cannot read property 'document' of null`.

I was able to get JBrowse-1.13.0 (non-dev) to work, but there seems to be an issue with the dev version which I need for plugins.

**Comment by cmdcolin** [comment]
Do you have a setup.log? It seems like it works on my machine

**Comment by kullrich** [comment]
Dear all,
same problem on my side. JBrowse-1.13.0(non-dev) works fine, even with own data.
However, after installing npm and JBrowse-1.13.0-dev to include BioNanoGenomics plugin the examples hangs at ('Loading ...').
Here are some additional warning from npm:
"""npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
"""
Architecture: Ubuntu 16.04.4 LTS

Best regards and thank you in anticipation

Kristian

**Comment by bhofmei** [comment]
I do have a setup.log (about 1700 lines) attached. Doesn't seem to have any major errors, just a few warnings. I do get a few deprecated dependencies.
```
npm WARN deprecated filesaver.js@0.2.0: Unmaintained namespace. Please use the file-saver package: https://www.npmjs.com/package/file-saver
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
```
I'm running macOS v10.12.6 and using Chrome for web browser.
[setup.log](https://github.com/GMOD/jbrowse/files/1829532/setup.log)

**Comment by cmdcolin** [comment]
Might be due to too low of a node/npm version. I can reproduce the problem if I use npm3/node6 (default on ubuntu 16).

If I get the homebrewed/linuxbrewed npm5/node9 then it works fine!

Not sure why that is, it might be worth trying to upgrade node versions to see though

**Comment by cmdcolin** [comment]
It also seemed to take forever with npm3...much faster with npm5

**Comment by bhofmei** [comment]
That must be my issue. I’m using npm3/node6 (necessary for another project). I’ll see what I can do.

**Comment by kullrich** [comment]
For me updating to npm v5.6.0 and nodejs v9.8.0 resolved the issue.
However, after installing the BioNanoGenomics plugin and repeating 'setup.sh' I now run into another error, once I want to add a BioNano track:
"""
Failed to load resource: dojox/widget/Toaster
"""
If this is an issue of the plugin or JBrowse itself I don't know, so that at the moment I will not open another issue.

Best regards
Kristian

**Comment by cmdcolin** [comment]
Might be worth contributing that fix to their repo :)

**Comment by kullrich** [comment]
Thank you, I will contact them to include it
Best regards
Kristian

**Comment by rbuels** [comment]
I think we need to add a check to setup.sh to check for sufficient npm versions.

Maybe npm >= 4, node >= 6.4?
