### ISSUE TITLE
track->open should check better for missing files

### ISSUE THREAD

**Issue by sletort** [GMOD/jbrowse#1033]
Hi,
I'm trying to load a VCF file (bgzip+tabix) with "track" -> "open track file".
But I've got this strange diagnostic message : "404 (Not Found) when attempting to fetch /undefined.tbi"
Why is it trying to load a file named "undefined" ?
My vcf is correct according vcf-validator (vcftools).

Any idea about how to understand what's wrong ?

**Comment by cmdcolin** [comment]
I would double check that your files are named with a specific pattern

file.vcf.gz
file.vcf.gz.tbi


If the file extensions don't match that, then it might end up opening the file incorrectly

**Comment by sletort** [comment]
Ok I've got it.
Tabix file has to be loaded with track -> "open track file" too, it is not loaded by default.
If possible, the check should be done right after the click on the open button.

**Comment by rbuels** [comment]
We should make this case have better error behavior.  The file-open dialog shouldn't try to open a VCF.gz unless there is a tbi.
