### ISSUE TITLE
Make consecutive features appear next to each other

### ISSUE THREAD

**Issue by nvteja** [GMOD/jbrowse#1041]
Hello Team,

Is there a way to display two consecutive features right next to each other ? When I try to display an exon and the consecutive intron as two separate features, JBrowse displays the intron below the exon.Please look at the attached image. IN the "Test_Teja" track, I would want the three features displayed in the same pane (line).

Thanks,
Teja.
<img width="1069" alt="screen shot 2018-04-19 at 4 26 46 pm" src="https://user-images.githubusercontent.com/16638984/39016456-84a7509e-43ee-11e8-916f-71e111f68fc7.png">

**Comment by cmdcolin** [comment]
You could maybe add "displayMode": "collapsed" on this track, that forces every feature onto a single line. I don't know if that would work if you had different features that were overlapping that you didn't want collapsed though

Is there any reason why you do not have that loaded as a gene/transcript?

**Comment by nvteja** [comment]
Thank you I will try the collapsed option.

This is related to my previous issue #1040. As i couldnt figure out how to click on subfeatures in the transcript feature such as exon,CDS to get specific information just for those sub features,  I thought i could try loading them as separate features.

**Comment by nvteja** [comment]
Hmm, yeah now that i think more  about it,
Collapsed option wont make sense in my case  as i dont want any overlapping features to be collapsed.

**Comment by rbuels** [comment]
Can we fold this issue into #1040 then?

**Comment by nvteja** [comment]
Sure!
