### ISSUE TITLE
Loading a gff file without having to convert to JSON

### ISSUE THREAD

**Issue by nvteja** [GMOD/jbrowse#1042]
Hello JBrowse team,

I apologize in advance if my question below has an obvious solution that I couldn't find. 

Is there a way I can load a GFF3 file into JBrowse without converting it into json by exectuing flatfile-to-json.pl ? The reason I ask is that I want to automatically keep appending data to a GFF3 file and I dont want to run flatfile-to-json.pl everytime I append some data to this file. Is this even possible?

Thanks,
Teja.

**Comment by rbuels** [comment]
sure, just use the GFF3 store. Here's a snippet from the volvox example data that shows how to do it:

```
 tracks . volvox_gff3 ]
storeClass = JBrowse/Store/SeqFeature/GFF3
urlTemplate = ../../raw/volvox/volvox.gff3
type = CanvasFeatures
metadata.description = This is just all the features in the volvox.gff3 test file, displayed directly from a web-accessible GFF3 file
category = Miscellaneous
key = GFF3 - volvox.gff3 in-memory adaptor
```

Make sense?
