### ISSUE TITLE
add-track-json.pl problem

### ISSUE THREAD

**Issue by guojinpeng** [GMOD/jbrowse#1046]
Tracklist.json also has json configuration , After the execution, there is no item just added in the Tracks list.

**Comment by cmdcolin** [comment]
What command did you run to get a problem? If you use an example like in the docs

  echo ' { "urlTemplate" : "seq/{refseq}/",
           "label" : "Another_sequence_track",
           "type" : "SequenceTrack"
         } ' | bin/add-track-json.pl data/trackList.json

Then it should append this json to the trackList.json and then it should be in your tracklist in the webbrowser.

Note: If you add two tracks that have the same "label" then that would cause a problem because "label" needs to be unique so avoid creating two tracks with the same label

**Comment by guojinpeng** [comment]
I am very sorry that I use Google Translate to communicate with you

(Currently this problem has been solved, but it is the trackList.json original content that I copied successfully before, and replaces the 1.14.1 new version of trackList.json. I am afraid to use the default or not)

Because I didn't find the option to have metadata configuration in jbrowse, so my own program follows the rules in trackList.json to generate my own tracks json configuration as follows:
`{
         "bicolor_pivot" : "zero",
         "autoscale" : "local",
         "key" : "H3K27ac",
         "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
         "urlTemplate" : "bw_file/740_sort.bw",
         "label" : "740",
         "type" : "JBrowse/View/Track/Wiggle/XYPlot",
         "metadata" : {
            "pubmedId" : "<a target='_blank' href='https://www.ncbi.nlm.nih.gov/pubmed/28947800'><img width='80' height='23' src='https://static.pubmed.gov/portal/portal3rc.fcgi/4176361/img/2318832' alt='pubmed logo'></a>",
            "agiNo" : "Histoneacetylation",
            "tissue" : "seedling",
            "genotype" : "acc1-5 acla-1i-1",
            "age" : "12-day-old",
            "id" : "740",
            "proteinName" : "H3K27ac",
            "ecotype" : "Col",
            "antibody" : "H3K27ac (Millipore 07-360)"
         }
}`
This json configuration, I put in temp.json, and then call add-track-json.pl write this configuration to trackList.json, visit jbrowse?data=data/xxx in the list on the left, find To the newly configured map, there is no other track configuration in trackList.json, which is generated by default.


The trackList.json configuration that can be successfully configured is as follows:
`{
   "tracks" : [
      {
         "chunkSize" : 20000,
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
         "category" : "Reference sequence",
         "label" : "DNA",
         "type" : "SequenceTrack",
         "seqType" : "dna",
         "key" : "Reference sequence"
      },
      {
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : "CanvasFeatures",
         "urlTemplate" : "tracks/TAIR10/{refseq}/trackData.json",
         "compress" : 0,
         "style" : {
            "className" : "feature"
         },
         "label" : "TAIR10",
         "type" : "CanvasFeatures",
         "key" : "TAIR10"
      },
      {
         "bicolor_pivot" : "zero",
         "autoscale" : "local",
         "key" : "H3K27ac",
         "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
         "urlTemplate" : "bw_file/740_sort.bw",
         "label" : "740",
         "type" : "JBrowse/View/Track/Wiggle/XYPlot",
         "metadata" : {
            "pubmedId" : "<a target='_blank' href='https://www.ncbi.nlm.nih.gov/pubmed/28947800'><img width='80' height='23' src='https://static.pubmed.gov/portal/portal3rc.fcgi/4176361/img/2318832' alt='pubmed logo'></a>",
            "agiNo" : "Histoneacetylation",
            "tissue" : "seedling",
            "genotype" : "acc1-5 acla-1i-1",
            "age" : "12-day-old",
            "id" : "740",
            "proteinName" : "H3K27ac",
            "ecotype" : "Col",
            "antibody" : "H3K27ac (Millipore 07-360)"
         }
      }
   ],
   "names" : {
      "url" : "names/",
      "type" : "Hash"
   },
   "trackSelector" : {
      "renameFacets" : {
         "submission" : "Submission ID",
         "developmental-stage" : "Conditions"
      },
      "selectableFacets" : [
         "name",
         "id",
         "agino",
         "proteinname",
         "antibody",
         "ecotype",
         "genotype",
         "age",
         "tissue",
         "pubmedId"
      ],
      "displayColumns" : [
         "key",
         "id",
         "agiNo",
         "proteinName",
         "antibody",
         "ecotype",
         "genotype",
         "age",
         "tissue",
         "pubmedId"
      ],
      "type" : "Faceted"
   },
   "formatVersion" : 1
}`

**Comment by cmdcolin** [comment]
If you run add-track-json.pl, and confirm that it adds content to trackList.json, but then cannot see the result in the webbrowser, then oftentimes you need to clear cache in the web browser.


Maybe we'll close this for now if there is no issue :)
