### ISSUE TITLE
URL link does not zoom to coords

### ISSUE THREAD

**Issue by charmichaeld** [GMOD/jbrowse#1047]
Hi, In previous version (1.12.0) I could create a link like the following and JBrowse would zoom in directly to the coordinates in the link and show the highlighted region. In version 1.14.0, this no longer works and it takes me to the whole chromosome view. The chromosome is correct and the highlight is there but the view is zoomed out to the whole chromosome.

localhost/jb/?loc=1%3A1285117..1285167&highlight=1%3A1285142..1285142

**Comment by cmdcolin** [comment]
I tried reproducing the issue with a very bare bones setup (e.g. creating a sizes.txt file with "1     100000" and loading it with prepare-refseqs.pl --sizes sizes.txt) but didn't see the bug. Any ideas @rbuels? Any more details about your setup @charmichaeld e.g. browser, has generate-names.pl been run, etc.

**Comment by charmichaeld** [comment]
The generate-names.pl is what was missing, its working now, thanks.

**Comment by cmdcolin** [comment]
No worry. I think it also should work without having to have generate-names.pl being run though so might need to keep open. There was a fix related to this that landed in 1.13.1 (see https://github.com/GMOD/jbrowse/blob/dev/release-notes.txt#L168-L170) so if it is still being seen in 1.14 that would be weird

**Comment by rbuels** [comment]
any further issues with this? closing for now, feel free to reopen if necessary
