### ISSUE TITLE
Cannot get reference sequence to be ordered by list.

### ISSUE THREAD

**Issue by nvteja** [GMOD/jbrowse#1055]
Hello,

I am trying to order my reference sequence "by_list", but for some reason I cannot get it to work. I tried ordering by other options such as "name", "length" e.t.c and they all seem to work. Can you please let me know what I am doing wrong?

Section from my jbrowse.conf
```
## uncomment to change the default sort order of the reference
## sequence dropdown
refSeqOrder = by_list
refSeqOrderList =
        + chr1
        + chr2
        + chr3
        + chr4
refSeqSelectorMaxSize = 50
```
Do I need to have every chromosome in the genome in the "refSeqOrderList" for this to work, or is it enough to specify a subset of chromosomes that I want to be on top?

Thank you,
Teja.

**Comment by rbuels** [comment]
Ah, I reproduced the problem.  You are running into an odd quirk of this configuration format, list items can only have up to 4 spaces before their `+` sign.  If you change your configuration to
```
## uncomment to change the default sort order of the reference
## sequence dropdown
refSeqOrder = by_list
refSeqOrderList =
  + chr1
  + chr2
  + chr3
  + chr4
refSeqSelectorMaxSize = 50
```
does it work?

**Comment by rbuels** [comment]
Fixing this would require a substantial rewrite of the text configuration parser, not worth it at this point, since we need to work on JBrowse 2

**Comment by nvteja** [comment]
Hello,

This still doesnt work. I tried from one space before the '+' up to four spaces. 

Do I need to specify every single chromosome in the list, or can I just specify the chromosomes that I want to appear on the top of the drop down?

Thanks,
Teja.

**Comment by cmdcolin** [comment]
@nvteja any specifics on this? Do you have an example config? I think you need to put every single refseq in the list. CC @rbuels went off my radar
