### ISSUE TITLE
Jbrowse-1.14.0 plugins not found

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1056]
Hello,

I am trying to get 1.14.0 running but I keep getting errors about plugins not being found. 

One plugin is the FeatureSequence Plugin. 

My config:
[ plugins .  FeatureSequence ]
location = plugins/FeatureSequence

I run ./setup.sh and do not get any errors.

when I try `npm run build` I get this:

```
smr@genomesdev /var/other_data/JBrowse-1.14.0$ npm run build

> @gmod/jbrowse@1.14.0 build /var/other_data/JBrowse-1.14.0
> node node_modules/webpack/bin/webpack.js --config webpack.config.js

module.js:478
    throw err;
    ^

Error: Cannot find module '/var/other_data/JBrowse-1.14.0/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

npm ERR! Linux 3.10.0-693.11.6.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @gmod/jbrowse@1.14.0 build: `node node_modules/webpack/bin/webpack.js --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @gmod/jbrowse@1.14.0 build script 'node node_modules/webpack/bin/webpack.js --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @gmod/jbrowse package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/webpack/bin/webpack.js --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @gmod/jbrowse
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @gmod/jbrowse
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /var/other_data/JBrowse-1.14.0/npm-debug.log
```
version node.js v6.14.0
version npm 3.10.10

Thank you,
Sofia

**Comment by srobb1** [comment]
@cmdcolin Thanks for the reply. Where is the node_modules directory?

**Comment by srobb1** [comment]
@cmdcolin I see (from my error message), it should be in my JBrowse directory, but it is not there.

**Comment by cmdcolin** [comment]
Oh I think you need JBrowse-1.14.0-dev release (the -dev is needed for plugins)

**Comment by srobb1** [comment]
Thank you Colin!! Your comment about the node_module directory got me thinking and so I downloaded the most recent github version, which is dev, and It is working. I read in the 1.13.0 release notes that the dev was needed for plugins, but I didn't realize that was still true with the 1.14.0 release.

But I am having problems with the gccontent plugin. let me make sure I have the most recent version of that one. If I am still having errors, I will create a new issue.

**Comment by cmdcolin** [comment]
Good to know. Might need to reiterate that notice somewhere. Glad it works though, maybe close for now :)
