### ISSUE TITLE
generate-names.pl process killed in 1.14.0, but not in 1.12.5

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1058]
@scottcain reports that generate-names.pl is being killed for some reason on his machine.  says this same run used to work in 1.12.5, now is killed.

## Gitter conversation
![image](https://user-images.githubusercontent.com/73749/40443274-ab77bc8a-5e7a-11e8-96e7-09d5e44e6e55.png)
![image](https://user-images.githubusercontent.com/73749/40443300-be0d263c-5e7a-11e8-8192-1990f1056693.png)

**Comment by rbuels** [comment]
![image](https://user-images.githubusercontent.com/73749/40444029-0cedeece-5e7d-11e8-8c92-8b4932a29b89.png)

**Comment by rdhayes** [comment]
FYI, I still routinely use --incremental and --tracks <comma-separated list> routinely to work around this situation.

**Comment by scottcain** [comment]
I could do that too, though the fact that I never had to before indicated a potential bug that I thought I should point out.

**Comment by cmdcolin** [comment]
I seem to be able to reproduce this, I tried that crashing_elegans.tar.gz. It seems to be a pretty bad memory leak(?) in 1.14.0 but not in 1.12.5. I couldn't figure out what exactly was causing the memory usage but maybe a git bisect could reveal it
