### ISSUE TITLE
How to use the feature density histograms for Tabix-indexed GFF3

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1060]
The release note of 1.12.4 says:
```
Added code to calculate feature density histograms for Tabix-indexed GFF3
(GFF3Tabix) data sources.
```

However, I am using 1.14.1 now and can't display the feature density histograms for GFF3Tabix. I didn't find any documents on setting this feature

**Comment by cmdcolin** [comment]
They are enabled automatically, but what can happen is that the storeTimeout is too small which is used for density estimation before displaying histograms, so they end up not displayed

Try adding storeTimeout=5000 or 10000 in config perhaps

**Comment by billzt** [comment]
Yes, after adding storeTimeout=10000, it is OK
