### ISSUE TITLE
bin/biodb-to-json.pl help with subclasses in configuration file

### ISSUE THREAD

**Issue by MichalCervenansky** [GMOD/jbrowse#1062]
Hello,
i am having difficulties working out how config file works and i am not able to write one for my needs. I would be super grateful for some type of tutorial. This is my config file:
    {
      "track": "odPavla",
      "feature": ["region"],
      "subfeatures": true,
      "subfeature_classes": {
        "LTR_retrotransposon": "LTR_retrotransposon",
        "polypeptide_domain": "polypeptide_domain",
        "repeat_fragment": "repeat_fragment",
        "RR_tract": "RR_tract",
        "long_terminal_repeat": "long_terminal_repeat",
        "polypeptide_conserved_region": "polypeptide_conserved_region",
        "protein_binding_site": "protein_binding_site"
        },
      "key": "region",
      "class": "transcript",
      "arrowheadClass": "transcript-arrowhead",
      "clientConfig": {
        "histScale":5
      },
      "extraData": {"feature_id": "sub {shift->attributes(\"load_id\");}"}
    }
Sub-features here aren't visible on the track. If i move them to features, than i am able to see them, but they are bellow each other. I would like them to look just like these:
{
      "track": "mRNA",
      "feature": ["mRNA"],
      subfeatures: similar to 'getSubs' in flatfile-to-json.pl.
      "subfeatures": true,
      "key": "mRNA",
      "class": "transcript",
      subfeature_classes: same as 'subfeatureClasses' in flatfile-to-json.pl.
      "subfeature_classes": {
        "CDS": "transcript-CDS",
        "five_prime_UTR": "transcript-five_prime_UTR",
        "three_prime_UTR": "transcript-three_prime_UTR"
      },
      arrowheadClass: same meaning as in flatfile-to-json.pl.
      "arrowheadClass": "transcript-arrowhead",
      clientConfig: same meaning as in flatfile-to-json.pl.
      "clientConfig": {
        "histScale":5
      },
      "urlTemplate": "http://flybase.org/cgi-bin/fbidq.html?{feature_id}",
      "extraData": {"feature_id": "sub {shift->attributes(\"load_id\");}"}
    }

Thanks for any reply.
Michal

**Comment by rbuels** [comment]
Have you gone through the JBrowse quick start guide? It is the usual entry point for new users.  After that, the JBrowse Configuration Guide (http://gmod.org/wiki/JBrowse_Configuration_Guide) is the comprehensive reference for configuration.

The gmod-ajax mailing list, though, might be the best place to get support for cases like this, a lot more people are on there than are on the github issues.  Try subscribing to the list and sending an email there: https://sourceforge.net/projects/gmod/lists/gmod-ajax
