### ISSUE TITLE
Feature Order of -strand Genes

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1071]
It seems that the order of features such as exons, CDS etc of genes on the -strand is incorrect from what a user would expect.

A user looking at a gene on the -stand would assume to look at the first `CDS` feature for an `ATG` but can't find it. They would have to skip down to the last `CDS` feature in the list to find the first exon of the gene...this is very confusing.

It would seem that these features are listed in order of 5' -> 3' relative to the reference, not the parent feature. Is there a way to change this behaviour through JBrowse configuration or by modifying information in a GFF3 file?

**Comment by cmdcolin** [comment]
This could be nice. Then again a more enhanced gene version of view details would be really good too reference: https://github.com/GMOD/jbrowse/issues/174

**Comment by nathanhaigh** [comment]
I'd prefer a 2-step resolution to this:

1. Fix the ordering for complementary strand features
2. A more gene-centric "view details" page

**Comment by rbuels** [comment]
Sounds like the feature sort order in the details view just needs to be reversed if the feature is on the - strand.

And if it doesn't actually do a sort, it should.

**Comment by rbuels** [comment]
fixed by merging #1114
