### ISSUE TITLE
Can't locate Bio/FeatureIO.pm in @INC (@INC contains: 

### ISSUE THREAD

**Issue by guojinpeng** [GMOD/jbrowse#1073]
I will report the following error when executing the 

【./bin/flatfile-to-json.pl --bed /mnt/rdata/bed/TAIR10_miRNA_modify.bed --trackType CanvasFeatures --trackLabel TAIR10_miRNA --out data/Arabidopsis/】

 script What causes this?

--------------------------- error --------------------------------------------------------

Can't locate Bio/FeatureIO.pm in @INC (@INC contains: /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.10.1/x86_64-linux-thread-multi /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.10.1 /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/x86_64-linux-thread-multi /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.10.0 /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5 /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.10.1/x86_64-linux-thread-multi /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.10.1 /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/x86_64-linux-thread-multi /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.10.0 /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/../../extlib/lib/perl5 /mnt/tomcat/webapps/jbrowse/bin/../src/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FlatFileToJson.pm line 158.
 at /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 7.
        Bio::JBrowse::ConfigurationManager::__ANON__("Can't locate Bio/FeatureIO.pm in \@INC (\@INC contains: /mnt/to"...) called at /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FlatFileToJson.pm line 158
        Bio::JBrowse::Cmd::FlatFileToJson::make_bed_stream(Bio::JBrowse::Cmd::FlatFileToJson=HASH(0x2d40690)) called at /mnt/tomcat/webapps/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FlatFileToJson.pm line 118
        Bio::JBrowse::Cmd::FlatFileToJson::run(Bio::JBrowse::Cmd::FlatFileToJson=HASH(0x2d40690)) called at ./bin/flatfile-to-json.pl line 9

**Comment by cmdcolin** [comment]
When you setup.sh did it say that perl pre-requisites installed successfully? It seems like this could happen if perl pre-requisites sort of "half installed"

**Comment by rbuels** [comment]
closing for now, please reopen if there is further work on this
