### ISSUE TITLE
Filter name search index on existing tracks

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1077]
If a track is not in the tracklist that gets a namestore hit, filter it from search results

Caveat, I think name store index is based on a numeric track index but there might be a track index track label association

Cc @fredericbga

**Comment by FredericBGA** [comment]
thank you Colin and Rob to take time to check that!

**Comment by cmdcolin** [comment]
The implementation of this is a little weird

The reason being is that the autocompletion, up to a point, will still contain all the entries, and only the final exact match will be filtered by this request

If that is reasonable I can do it, but it seems weird IMO

**Comment by cmdcolin** [comment]
This should now be implemented now in conjunction with search. The chain of logic is

- track labels array is in meta.json
- an index into track label array in meta.json is stored in the actual name store records
- if there is no track label match with the active tracks in the browser, then the info is effectively "filtered" now
