### ISSUE TITLE
Max number of features using the left side bar

### ISSUE THREAD

**Issue by ThomasLet** [GMOD/jbrowse#1078]
Hello :)

Is there a limit concerning the number of tracks that can be display using the left side bar ? Because I recently added many VCF tracks on my jbrowse (arround 20) and only the 2 first appear (I already have ~30 different tracks like genes, markers and so on...).

 My trackList.json file is well formated and when I pull up  some tracks from the bottom of the file to the top they appear and replace another one. I looked at the debug mode of my browser and there is no errors.

Do you have any idea ?

Many thanks,

Thomas

**Comment by cmdcolin** [comment]
@ThomasLet each track must have a unique track "label". If you make sure all the tracks have unique labels I believe this wouldn't happen. If there's any confusion, you can post the trackList and I can see!

**Comment by cmdcolin** [comment]
@ThomasLet any update for this? I am pretty sure there is no limit for example and I don't suspect it to be a bug necessarily at this time, so maybe close for now

**Comment by ThomasLet** [comment]
Hi cmdcolin,

many thanks for your help. Indeed the add of a label fix my problem, I thought that the "key" was suppose to handle the unicity. 

Thanks again,

Best regards,

Thomas

**Comment by cmdcolin** [comment]
It is an annoying misnomer. Glad that works though!
