### ISSUE TITLE
Modify G allele colour for better projection display

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#1079]
Need to check this doesn't clash with JBrowse default colours first:

```
--- sequence.css	2017-08-16 18:50:12.000000000 +0100
+++ jbrowse-css-sequence.css	2017-08-16 16:25:51.000000000 +0100
@@ -114,7 +114,7 @@
     background-color: #f00;
 }
 .base_g {
-    background-color: #d5bb04;
+    background-color: #FFA500;
 }
 .base_reference {
     background-color: #bbb;
```

**Comment by cmdcolin** [comment]
I like the way this looks! I think we can just add this to master :)

**Comment by cmdcolin** [comment]
![screenshot-localhost-2018 07 06-09-16-17](https://user-images.githubusercontent.com/6511937/42383594-4686d5d6-80fd-11e8-9a12-4c1c931198a7.png)
