### ISSUE TITLE
Is there a way to turn off the "Max height reached" line in JBrowse display?

### ISSUE THREAD

**Issue by SchwarzEM** [GMOD/jbrowse#1085]
JBrowse, in my hands, can sometimes have unnecessarily wide vertical distances between tracks.
I can override this behavior by editing maxHeight in the track-specific config downward, but then JBrowse automatically inserts a black line labeled "Max height reached".  Which defeats my effort to make a better figure.

Is there a way to turn this visual alarm off, so that when I tell JBrowse to put its tracks closer together vertically, it just *obeys* me silently?

**Comment by rbuels** [comment]
There isn't a configuration option for this, the thinking being that users will always want to know when some of their data is being cut off and not shown.

If you just want to hide it temporarily to make a figure, you could actually just paste this into the web developer console:

```js
document.querySelectorAll('.height_overflow_message').forEach(e => e.style.display = 'none')
```

or if you for some reason want to hide it in your entire JBrowse installation, you could just add this custom CSS (see http://gmod.org/wiki/JBrowse_Configuration_Guide#General_configuration_options for how to insert it):

```css
.height_overflow_message {
   display: none;
}
```

**Comment by rbuels** [comment]
feel free to reopen for further questions of course!
