### ISSUE TITLE
CanvasVariants RightClick Menu

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1088]
I can't seem to figure out how to add a right-click menu to a `CanvasVariants` track. Specifically one using `VCFTabix` `storeClass` defined in a `tracks.conf` file.

Is this possible and I'm just not finding/understanding the documentation?

I've managed with a `CanvasFeatures` using `NCList` `storeClass` using `menuTemplate` in a `trackList.json` file.

**Comment by cmdcolin** [comment]
For menuTemplate in tracks.conf format there is an example at the bottom of this section 

http://gmod.org/wiki/JBrowse_Configuration_Guide#Customizing_Right-click_Context_Menus

That was at least one way I had that work so I added it to the docs  there. It incorporates json into the tracks.conf format :)

Hope that helps

**Comment by nathanhaigh** [comment]
I've tried that @cmdcolin but I still don't get any sort of pop-up :(

**Comment by cmdcolin** [comment]
@nathanhaigh I added the lines

    menuTemplate+=json:{"label": "View details"}
    menuTemplate+=json:{"label": "Zoom to this gene"}
    menuTemplate+=json:{"label": "Highlight this gene"}
    menuTemplate+=json:{"label": "Open example.com in an iframe popup", "iconClass" : "dijitIconDatabase","action": "iframeDialog","url" : "http://www.example.com?featurename={name}"}


To the menuTemplate and it did give me the example iframe pop up

**Comment by rbuels** [comment]
Closing as resolved, reopen if this is still an issue.

**Comment by nathanhaigh** [comment]
Just got back to testing this. The right click doesn't work as soon as you add `displayMode = collapsed`. Is this intentional?

**Comment by cmdcolin** [comment]
This is kind of obscure but if you enable `enableCollapsedMouseover=true` then you can get the right click menus with the collapse mode on

**Comment by rbuels** [comment]
Did we disable those in collapsed mode for performance? I forget

**Comment by rdhayes** [comment]
I have dense tracks that are configured to open collapsed by default. I
believe I asked for this at one point, as the feature display is so busy
when collapsed that it's hard to discern what you are selecting in a
mouseover

My complete thought was that it would be cool to have a mouseclick event
anywhere in a collapsed track pane toggle that display to, say, compact
mode, but this hasn't been attempted yet.

Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by nathanhaigh** [comment]
For my purposes, 'normal' display without labels will work just fine.
