### ISSUE TITLE
Cannot load bam file

### ISSUE THREAD

**Issue by kalbflei** [GMOD/jbrowse#1091]
Hello,

     I have installed a new browse instance for EquCab3.  

I am trying to load a bam file onto it from a track-hub that I maintain.  the URL for the corresponding bai file is shown below.  I get an error that states I am "Blocked loading mixed active content", however we have made the modifications suggested elsewhere in the issues section to set the Access-Control-Allow-Origin to * (please see the header information below).  The header in the bam file is consistent with the dictionary file I was able to generate for the reference I am displaying.  I am at a loss.  Any help you could provide would be greatly appreciated.

Best regards,

Ted Kalbfleisch

```
ubuntu@jbrowse-web01:~$ curl -v http://server1.intrepidbio.com/FeatureBrowser/bamfilereader/record/3158749226664609709/7919444038.bam.bai | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.25.77.66...
* Connected to server1.intrepidbio.com (52.25.77.66) port 80 (#0)
> GET /FeatureBrowser/bamfilereader/record/3158749226664609709/7919444038.bam.bai HTTP/1.1
> Host: server1.intrepidbio.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 05 Jul 2018 21:57:28 GMT
< Server: Apache
< Set-Cookie: JSESSIONID=159CB9087A27DDA154B4825958B11747; Path=/FeatureBrowser; HttpOnly
< Accept-Ranges: bytes
< Content-Range: bytes 0-7798799
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With,Range
< Transfer-Encoding: chunked
< Content-Type: application/octet-stream
< 
{ [5423 bytes data]
100  5417    0  5417    0     0   4963      0 --:--:--  0:00:01 --:--:--  4965BAI]
܌?W
?
?

?|
```

**Comment by cmdcolin** [comment]
The error that I see if I create an instance and reference this file is that the server is not responding to Range request.

You mention using the CORS header for Access-Control-Allow-Origin but check also "Access-Control-Allow-Headers X-Requested-With,Range"

See here

http://gmod.org/wiki/JBrowse_Configuration_Guide#Cross-origin_resource_sharing_.28CORS.29:_showing_data_on_multiple_servers

**Comment by kalbflei** [comment]
Thank you very much for your response.  I thought we had made that modification.  At least when I look at what is returned by the URL, I do see the appropriate information in the header, specifically

< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With,Range

When I try to load this URL and the URL for its corresponding bam file, I don’t see any record on the server hosting my track hubs of these URLs being called either in the tomcat or apache2 logs.  Does JBrowse make some other call to the server to look for these access parameters?  Finally is there logging that I can turn on and view that might be more informative than the Browser Console?

Thank you again for your help.

Best regards,

Ted

**Comment by kalbflei** [comment]
Thank you very much for your reply.  I thought we had made that modification.  At least when I look at what is returned by the URL via curl, I do see the appropriate information in the header, specifically

< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With,Range

When I try to load this URL and the URL for its corresponding bam file into JBrowse, I don’t see any record on my track hub server of these URLs being called either in the tomcat or apache2 logs.  Does JBrowse make some other call to the server to look for these access parameters?  Finally is there logging that I can turn on in JBrowse to view logs that might be more informative than what I see in the Browser Console?

Thank you again for your help.

Best regards,

Ted

**Comment by cmdcolin** [comment]
There are no extended debugging flags. It is most likely hitting your servers but the access logs probably wouldn't really help as far as debugging.

Do you have a custom java servlet for serving files? It shouldn't really affect things but currently it is not giving me CORS errors but the .bai file never completes download

**Comment by kalbflei** [comment]
I do.  Interesting.  The servlet I wrote was not written to get the bai file via range request as I imagined it would only ever be downloaded in its entirety.  Is JBrowse written to get the bai file in chunks via range request? If so, I might be able to fix this on my end.

**Comment by cmdcolin** [comment]
@kalbflei the .bai file is requested in it's entirety without a Range request, but the .bam file will be fetched in chunks using Range request

**Comment by kalbflei** [comment]
I do accomodate bam range requests.  Downloading the bai file using the URL via wget, or curl does do a complete download as best I can tell.  I wonder what is different?

**Comment by cmdcolin** [comment]
I think the bai downloads for me also now. Still not working though. I was thinking that you might also need to set

    Access-Control-Expose-Headers: *

or

     Access-Control-Expose-Headers: Content-Range

I don't think that part is in the docs but if it helps let me know

**Comment by cmdcolin** [comment]
Might also add a cache header for the bai so that it doesn't have to redownload every time (7mb) :)

**Comment by cmdcolin** [comment]
Hi @kalbflei 
I am guessing that the majority of the problem now relies on CORS configuration and probably isn't strictly a jbrowse issue. If it's ok maybe we can close this for now?

I know that creating a streaming java servlet for range requests can be tricky. The GMOD/Apollo has code for this if you want to check their system out, see "JBrowseServlet" cc @nathandunn.

Otherwise if you have the option you might just want to rely on a static file server

Feel free to post back if you have any issues

**Comment by kalbflei** [comment]
Colin,

     Thank you for all of your help.  We found that modifying my track server to serve via https was the last fix required.  All works now.

Best regards,

Ted

**Comment by cmdcolin** [comment]
Awesome! Sorry to rapidly close up issues it's just a mental triage thing :)

Feel free to post back with any other issues
