### ISSUE TITLE
refactor CSI index support into a node module

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1096]

**Comment by nathanhaigh** [comment]
Also, need to support loading BAM/VCF files plus CSI index via Tracks >> Open track file or URL menu.

**Comment by rbuels** [comment]
have a look at the tribble indexes module for an example of what this might look like:

https://www.npmjs.com/package/tribble-index
https://github.com/rbuels/tribble-index

**Comment by rbuels** [comment]
this is a lower priority than the read pairs stuff, we can do it later

**Comment by cmdcolin** [comment]
I think this is part of tabix-js :)

**Comment by rbuels** [comment]
Yes csi is being supported quasi-independently by the new bam and tabix
implementations.
