### ISSUE TITLE
CSI Indexed BAM Files Fail to Load

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1097]
I'm running the latest dev code from the repo and testing the recently added CSI index support for BAM/VCF files. While I can get the tabix (CSI) indexed VCF files to work, I'm having trouble with CSI indexed BAM files.

Upon trying to load a configured CSI indexed BAM file, I get a "loading" message in the track, my CPU usage is > 100% and consumed memory increases over time until hitting swap or I kill firefox.

Here are my config for both BAM and VCF:

```
[ tracks.my_reads ]
label                   = my_reads
key                     = Reads
storeClass              = JBrowse/Store/SeqFeature/BAM
type                    = JBrowse/View/Track/Alignments2
urlTemplate             = ../{refseq}/my.bam
csiUrlTemplate          = ../{refseq}/my.bam.csi
displayMode             = compact

[ tracks.my_variants ]
label                   = my_variants
key                     = Variants
storeClass              = JBrowse/Store/SeqFeature/VCFTabix
urlTemplate             = ../{refseq}/my.bam.vcf.gz
csiUrlTemplate          = ../{refseq}/my.bam.vcf.gz.csi
displayMode             = collapsed
```

**Comment by cmdcolin** [comment]
Hmm I would be very curious if there is any sample data to recreate the bug. I made a very simplified test data where I aligned the volvox bam aligned to a gigabase coordinate and it worked ok but I'd really like to catch other bugs that exist. Thanks so much for testing this out prerelease and adding these comments though :)

**Comment by nathanhaigh** [comment]
@cmdcolin Happy to share some real data - I'll email you access details shortly.
