### ISSUE TITLE
Add support for CSI indexes for GFF3Tabix

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1104]
In addition to the recent support for CSI indexes to BAM and VCF files (#1086), we also need to support CSI indexes for GFF3Tabix.

**Comment by cmdcolin** [comment]
Should be added for BEDTabix and GFF3Tabix now :) pushed straight to dev

**Comment by cmdcolin** [comment]
CC @thomasvangurp

**Comment by cmdcolin** [comment]
Thanks for the PR @nathanhaigh ! Merged
