### ISSUE TITLE
BAM unique IDs still don't 100% work

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1108]
compare http://jbrowse.org/code/JBrowse-1.14.2/?data=%2Ftest%2Fsgn_cram&loc=SL2.50ch03%3A12350002..12350195&tracks=DNA%2Cbam&highlight=

with 
```
samtools view http://jbrowse.org/test/sgn_cram/RNAseq_mapping_def.bam SL2.50ch03:12350002-12350195
```

there should be 6 features in the bam track, but there are only 2

**Comment by rbuels** [comment]
implementation idea: do a crc32 or md5 of the bytes in their stretch of the file. would be relatively fast, but would miss exact duplicate features.

**Comment by cmdcolin** [comment]
The crc32 will get some of the way there but I don't understand these exact duplicate features

Why would these be given the exact same read name and not any differences in flags?

Here is a crc32 test I did

https://github.com/GMOD/jbrowse/compare/hash_bam_features

**Comment by cmdcolin** [comment]
With the hash_bam_features branch it returns 4 reads instead of 2 which are on dev and then there are 6 in the bam file
