### ISSUE TITLE
generate-names.pl memory usage on large VCF track

### ISSUE THREAD

**Issue by garrett-stevens** [GMOD/jbrowse#1113]
Hello there,

I'm trying to use `generate-names.pl` with an (admittedly huge) VCF track, but it keeps freezing up my machine due to using up all available memory. My track looks like this:
```json
{
  "label":"dbSNP",
  "trackType":null,
  "urlTemplate":"extra/dbsnp_20180423.vcf.gz",
  "storeClass":"JBrowse/Store/SeqFeature/VCFTabix",
  "category":"Annotations",
  "key":"dbSNP",
  "type":"CanvasVariants"
}
```
And the VCF is the dbSNP VCF pulled straight from NCBI (`ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/All_20180423.vcf.gz` and accompanying `.tbi`), about 14.6 GB. I'm running the command without specifying any memory limits:
```
bin/generate-names.pl --tracks dbSNP
```
I've tried this on a cloud machine with 244 GB of memory (AWS r4.8xlarge if you're interested) and it still ran out of memory. I'm not sure if this is a bug or just beyond the scope of what `generate-names.pl` was intended to be used for.

Thanks!

EDIT: I'm using the latest version (1.14.2) of JBrowse.

**Comment by cmdcolin** [comment]
Didn't mean to close the issue but I guess hopefully it can be closed given the workaround :)

**Comment by rbuels** [comment]
yes this is a duplicate of #1058 I think
