### ISSUE TITLE
Chromosome switching behaviour for contigs with `:` in their name

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1118]
Commits 92f4be5 and 23bd665  added support for contigs with `:` as part of their name. This has arisen in the wild with the introduction of contig `HLA-A*01:01:01:01` in the human genome assembly, hg38. In addition, sequence extracted from a longer sequence also contain `:` (e.g. `samtools faidx ref.fasta ctgA:400-500 > subseq.fasta` will result in a sequence called `ctgA:400-500`).

Normal JBrowser behaviour for switching to another sequence can be achieved by typing the full contig name into the location bar. However, if the target sequence contains a `:` in its name entering just the sequence name alone (e.g. `HLA-A*01:01:01:01` or `ctgA:400-500`) is not sufficient to switch to that sequence. Instead, either a specific point location (e.g. `HLA-A*01:01:01:01:350` or `ctgA:400-500:40`) or a range (e.g. `HLA-A*01:01:01:01:350-600` or `ctgA:400-500:40-60`) must be used to switch to those sequences.

To overcome this issue, `parseLocString` would probably need to perform a lookup of seq names before deciding what the return value should be.

Some test data for this behaviour is in `tests/data/obscure_contig_names/`.

**Comment by rbuels** [comment]
seems to me rather than making parselocstring asynchronous, jbrowse should just always check first if a string that was typed into the box is actually a reference sequence, and *then* go on to try seeing if it's a locstring, or a name of something

**Comment by rbuels** [comment]
setting high priority because we kind of need this for good support of human data
