### ISSUE TITLE
popup for a GFF3Tabix feature: multiple attribute values are rendered as a single value

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/jbrowse#1122]
Unlike with NCList StoreClass, the popup with GFF3Tabix storeClass is wrong when one attribute has multiple values: they are joined with a comma and rendered as a single one. This induces trouble to distinguish the different values (Which are the "value-separator commas" or the "inside-value commas"?) and this prevent to apply callbacks on each individual value (these callbacks are working well with the NCList StoreClass).

Here part of the popup with a NCList StoreClass (created using flatfile-to-json.pl):

![with_nclist](https://user-images.githubusercontent.com/16136876/42763442-5c8bf83e-8913-11e8-9cae-c77433bd5f8e.png)

Here the same data with the GFF3Tabix (and same track configuration except for `storeClass`, `urlTemplate` and `tbiUrlTemplate`):

![with_gff3tabix](https://user-images.githubusercontent.com/16136876/42763447-61faa4a0-8913-11e8-83ec-218c97fc28d6.png)

**Comment by cmdcolin** [comment]
@rbuels any idea about this?

The gff-js code has something related to splitting on comma but I dunno exactly how that passes through https://github.com/GMOD/gff-js/blob/master/src/util.js#L91

**Comment by rbuels** [comment]
Multiple values of the same attribute are comma separated in GFF3. Is the
JBrowse GFF driver ‘join’ing those back together? Maybe it shouldn’t.

**Comment by cmdcolin** [comment]
Should be fixed now! Thanks for the report @loraine-gueguen !!! Will include in release notes
