### ISSUE TITLE
Alternative alleles table has bad layout for VCF tracks after CRAM merge

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1127]
There was some code in CRAM to make arrays of values better, but this affected other view details phenomena

![screenshot-localhost-2018 07 18-04-49-45](https://user-images.githubusercontent.com/6511937/42870504-0c311bd8-8a46-11e8-8794-4673f77ef074.png)

**Comment by rbuels** [comment]
original change was because the details popup was blowing up when clicking on CRAM features.  if you want to back that change out and find another way to have it not blow up, that would be just fine!
