### ISSUE TITLE
Invalid BGZF block header

### ISSUE THREAD

**Issue by theChinster** [GMOD/jbrowse#1131]
I am using JBrowse to visualize data stored on a remote server over ssh port forwarding and have run into an issue with BGZF headers. However, I have also reproduced this issue running my setup locally too.

When first running JBrowse on a bam it seemed to work successfully (I could be wrong, but I don't think anything in the console is cause for concern. I think the two errors in the console are just because [I didn't run generate-names.pl](http://gmod.827538.n3.nabble.com/Gmod-ajax-names-root-json-td4051588.html) since I'm not using index features, and the warnings are because chrome doesn't cache things over a MB).
<img width="1792" alt="screen shot 2018-07-20 at 6 08 08 pm" src="https://user-images.githubusercontent.com/31998124/43027390-f2726d24-8c47-11e8-9c99-4fe695c65664.png">
However, after going to reads further and further down in the bam, I eventually got the error `invalid BGZF block header, skipping` (there is supposed to be a read in the picture below, but it is not showing up in JBrowse--it shows up in IGV).
<img width="1792" alt="screen shot 2018-07-20 at 6 50 18 pm" src="https://user-images.githubusercontent.com/31998124/43028452-0318d446-8c4e-11e8-8e6b-a4c37a059485.png">

Upon trying JBrowse with other bams, I got the same error. Interestingly, some of the reads are displayed, but others are not.

Some reads are displayed
<img width="1792" alt="screen shot 2018-07-20 at 6 29 04 pm" src="https://user-images.githubusercontent.com/31998124/43027933-d923cdb0-8c4a-11e8-8f07-2dac62ffdccf.png">
Other reads are not (there is supposed to be a read here--I checked on IGV)
<img width="1792" alt="screen shot 2018-07-20 at 6 30 46 pm" src="https://user-images.githubusercontent.com/31998124/43027965-0b844eb0-8c4b-11e8-9079-78e3fa09617c.png">

According to #552, this error is because of incorrect binary formatting. However, I am able to open the aforementioned bams with samtools, view them in IGV, manipulate them with Bio.bgzf, and I also manually checked that the first two 8-bit ints in the files are 31 and 139 respectively.

Additionally, #552 was closed because of a known Apache fix, but I am using python's simple http server module (`python3 -m http.server 8080` is the exact command), so I don't think `mime_magic` is the issue here.

Possible leads:
 - One thought is that this may have something to do with file size. I have found that reads towards the start of bams usually are displayed but reads towards the ends of bams are not.
 - I used Bio.bgzf to check out the EOF blocks (these are a block that should be in ever bam as explained in 4.1.2 on page 13 of [these specs](https://samtools.github.io/hts-specs/SAMv1.pdf)). Using Bio.bgzf._load_bgzf_block(handle), I got a block size of 28 (this was confirmed with Bio.bgzf.BgzfBlocks) but the data I got was empty instead of `\x1f\x8b\x08\x04\x00\x00\x00\x00\x00\xff\x06\x00BC\x02\x00\x1b\x00\x0\3\x00\x00\x00\x00\x00\x00\x00\x00\x00` as expected. I'm not sure if this is related but thought it should be noted.

**Comment by cmdcolin** [comment]
The issue is very likely that python http.server does not handle byte-range requests (HTTP Range header)!

http://gmod.org/wiki/JBrowse_FAQ#What_webserver_is_needed_for_JBrowse

**Comment by rbuels** [comment]
Oh man it looks like you are fetching huuuuge chunks, probably because the `Range` header on the HTTP requests are being ignored. It must be dog slow, is it?

**Comment by theChinster** [comment]
Ah yes--don't know how I missed that! Running RangeHTTPServer fixed the issue. 

And yeah not having to load hundreds of megabytes of data did make it a lot faster 👍

**Comment by cmdcolin** [comment]
Good to hear :)

I created https://github.com/GMOD/jbrowse/pull/1134 to try and provide a proper warning when the server appears to be responding to range requests badly

maybe close for now

**Comment by cmdcolin** [comment]
btw sorry you had to do all that detective work for this! glad to have a easy fix :)

**Comment by theChinster** [comment]
Thanks for making #1134! I agree with the closure. And also glad it worked out so easily!
