### ISSUE TITLE
throw some big warnings when HTTP servers don't implement Range headers

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1132]
To avoid confusion among people trying to put JBrowse on top of other things, particularly certain rather bare-bones python web servers.

**Comment by cmdcolin** [comment]
It might be better to request a specific sample file for a range request as a sanity check because, unless I am missing something, you wouldn't really know whether the http server is misbehaving until after it returns the response to download a massive file without byte-range

**Comment by cmdcolin** [comment]
I switched to using readyState 2 from xhr and then you can get status before the file is downloaded
