### ISSUE TITLE
rewrite quick-start document to assume samtools

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1137]
Quick-start should use .fa and .fai for reference sequences, GFF3Tabix for gene models, and BAM for alignments.

**Comment by nathanhaigh** [comment]
If you're assuming GFF3Tabix, perhaps it then also makes sense to assume `bgzip` compressed FASTA also?

**Comment by cmdcolin** [comment]
We are aiming to have bgzip fasta shortly so that would be ideal.

One idea I was also going to try and do is to instruct the user to setup a sample instance with sample data files. My feeling was that by providing sample data files for them to process, that they would get the feeling better
