### ISSUE TITLE
VCF 4.3 support and test suite

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1140]
I haven't observed any bugs necessarily but it could be worth ensuring VCF 4.3 support and test suite

There are a lot of specifications in VCF 4.3 but you can see a "4.2->4.3 changelog" which could highlight some key issues to watch out for

https://github.com/samtools/hts-specs/blob/master/VCFv4.3.pdf 

There is not a 4.1->4.2 changelog, and I imagine 4.3 support would be a superset of 4.2 but we could review that also

**Comment by rbuels** [comment]
Where's a good place to get some VCF 4.3 test data?

**Comment by rbuels** [comment]
@garrettjstevens is this issue combinable with the VCF parsing work you are doing now on #1199?

**Comment by garrettjstevens** [comment]
Resolved by #1227
