### ISSUE TITLE
enable switching alignments tracks between different alignments-related views

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1154]
switch an Alignments2 track between SNPCoverage, PairArcs, etc

**Comment by thomasvangurp** [comment]
@rbuels 👍 i was about to open an issue to request this. Would be great if menu entries would be available like so:
<img width="524" alt="volledige_scherm_06-08-18_19_05" src="https://user-images.githubusercontent.com/1284722/43730524-e345f5a2-99ab-11e8-8e44-a099208280ed.png">

**Comment by cmdcolin** [comment]
The paired reads view has this as a part of it

**Comment by rbuels** [comment]
Yep this is going to be done when #1235 is merged, will be coming out in JBrowse 1.16.0

**Comment by cmdcolin** [comment]
This is incorporated for Alignments2/SNPCoverage
