### ISSUE TITLE
VCF Parser not working in different version of JBrowse

### ISSUE THREAD

**Issue by FayrouzHam** [GMOD/jbrowse#1156]
Hello !
I created a VCF to integrate RNAseq data into my JBrowse. I don't have the bam or SAM file that's why I decided to use a VCF file.

Here is a part of the VCF used:

> ##FORMAT=<ID=SID,Number=1,Type=String,Description="Sample Geo Accession">
##FORMAT=<ID=GS,Number=1,Type=String,Description="Growth Stage">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample 1	Sample 2	Sample 3	Sample 4	Sample 5	Sample 6	Sample 7	Sample 8	Sample 9	Sample 10	Sample 11	Sample 12	Sample 13	Sample 14	Sample 15	Sample 16	Sample 17	Sample 18	Sample 19	Sample 20	Sample 21	Sample 22	Sample 23	Sample 24	Sample 25	Sample 26	Sample 27	Sample 28	Sample 29	Sample 30	Sample 31	Sample 32	Sample 33	Sample 34	Sample 35	Sample 36	Sample 37	Sample 38	Sample 39	Sample 40	Sample 41	Sample 42	Sample 43	Sample 44	Sample 45	Sample 46	Sample 47	Sample 48	Sample 49	Sample 50	Sample 51	Sample 52	Sample 53	Sample 54	Sample 55	Sample 56	Sample 57	Sample 58	Sample 59	Sample 60	Sample 61	Sample 62	Sample 63	Sample 64	Sample 65	Sample 66	Sample 67	Sample 68	Sample 69	Sample 70	Sample 71	Sample 72
chr00	519629	VIT_00s0145g00060	.	.	.	.	END=523434	SID:Cultivar:GS:FPKM	GSM2583781:Cabernet:Pre-veraison:0	GSM2583782:Cabernet:Pre-veraison:0	GSM2583783:Cabernet:Pre-veraison:0	GSM2583784:Cabernet:Mid-ripening:0	GSM2583785:Cabernet:Mid-ripening:0	GSM2583786:Cabernet:Mid-ripening:0	GSM2583787:Sangiovese:Pre-veraison:0	GSM2583788:Sangiovese:Pre-veraison:0	GSM2583789:Sangiovese:Pre-veraison:0	GSM2583790:Sangiovese:Mid-ripening:0	GSM2583791:Sangiovese:Mid-ripening:0	GSM2583792:Sangiovese:Mid-ripening:0	GSM2583793:Cabernet:Pre-veraison:0	GSM2583794:Cabernet:Pre-veraison:0	GSM2583795:Cabernet:Pre-veraison:0	GSM2583796:Cabernet:Mid-ripening:0	GSM2583797:Cabernet:Mid-ripening:0	GSM2583798:Cabernet:Mid-ripening:0	GSM2583799:Sangiovese:Pre-veraison:0	GSM2583800:Sangiovese:Pre-veraison:0	GSM2583801:Sangiovese:Pre-veraison:0	GSM2583802:Sangiovese:Mid-ripening:0	GSM2583803:Sangiovese:Mid-ripening:0	GSM2583804:Sangiovese:Mid-ripening:0	GSM2583805:Cabernet:Pre-veraison:0	GSM2583806:Cabernet:Pre-veraison:0	GSM2583807:Cabernet:Pre-veraison:0	GSM2583808:Cabernet:Mid-ripening:0	GSM2583809:Cabernet:Mid-ripening:0	GSM2583810:Cabernet:Mid-ripening:0	GSM2583811:Sangiovese:Pre-veraison:0	GSM2583812:Sangiovese:Pre-veraison:0	GSM2583813:Sangiovese:Pre-veraison:0	GSM2583814:Sangiovese:Mid-ripening:0	GSM2583815:Sangiovese:Mid-ripening:0	GSM2583816:Sangiovese:Mid-ripening:0	GSM2583817:Sangiovese:Pre-veraison:0	GSM2583818:Sangiovese:Pre-veraison:0	GSM2583819:Sangiovese:Pre-veraison:0	GSM2583820:Sangiovese:Pre-veraison:0	GSM2583821:Sangiovese:Pre-veraison:0	GSM2583822:Sangiovese:Pre-veraison:0	GSM2583823:Sangiovese:Pre-veraison:0	GSM2583824:Sangiovese:Pre-veraison:0	GSM2583825:Sangiovese:Pre-veraison:0	GSM2583826:Cabernet:Pre-veraison:0	GSM2583827:Cabernet:Pre-veraison:0	GSM2583828:Cabernet:Pre-veraison:0	GSM2583829:Cabernet:Pre-veraison:0	GSM2583830:Cabernet:Pre-veraison:0	GSM2583831:Cabernet:Pre-veraison:0	GSM2583832:Cabernet:Pre-veraison:0	GSM2583833:Cabernet:Pre-veraison:0	GSM2583834:Cabernet:Pre-veraison:0	GSM2583835:Sangiovese:Mid-ripening:0	GSM2583836:Sangiovese:Mid-ripening:0	GSM2583837:Sangiovese:Mid-ripening:0	GSM2583838:Sangiovese:Mid-ripening:0	GSM2583839:Sangiovese:Mid-ripening:0	GSM2583840:Sangiovese:Mid-ripening:0	GSM2583841:Sangiovese:Mid-ripening:0	GSM2583842:Sangiovese:Mid-ripening:0	GSM2583843:Sangiovese:Mid-ripening:0	GSM2583844:Cabernet:Mid-ripening:0	GSM2583845:Cabernet:Mid-ripening:0	GSM2583846:Cabernet:Mid-ripening:0	GSM2583847:Cabernet:Mid-ripening:0	GSM2583848:Cabernet:Mid-ripening:0	GSM2583849:Cabernet:Mid-ripening:0	GSM2583850:Cabernet:Mid-ripening:0	GSM2583851:Cabernet:Mid-ripening:0	GSM2583852:Cabernet:Mid-ripening:0

The RNAseq track was integrated in the TRackList.json file, here is the code to do so : 
   {
    "key" : "RNA_seq",
    "label" : "RNA_seq",
    "hooks" : {
               "modify" : "function(track, feature, featDiv){var type = feature.get('Type');if(type == 'remark'){featDiv.style.backgroundColor = 'darkcyan';};featDiv}"
    },
    "style" : {
              "description": "",
     },
     "fmtDetailValue_reference_allele" : "function(reference_allele,feature){return null}",
     "fmtDetailValue_Type" : "function(Type,feature){return 'Transcript'}",
      "fmtDetailValue_description" : "function(description,feature){return 'Vitis vinifera berries from Sangiovese and Cabernet Sauvignon cultivars were harvested at four different developmental stages (i.e., pea size (PS), pre-veraison (PV), mid-ripening (MR) and fully ripe (FR)), in three central Italian locations (i.e., Bolgheri in the Tuscany coast, Montalcino in the Tuscany Appennines and Riccione in the Adriatic coast) (Fig. 1, Supplementary Tables 1-3) during two consecutive growing seasons (2011 and 2012) in biological triplicates for a total of 144 samples. RNAseq analyses were performed on PV and MR samples, thus the high troughput sequencing derived sataset entailed 72 samples.'}",
     "fmtDetailField_Description" : "function(Description,feature){return null}",
     "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
     "tbiUrlTemplate" : "./VCF/RNAseq.vcf.gz.tbi",
     "type" : "JBrowse/View/Track/HTMLVariants",
     "urlTemplate" : "./VCF/RNAseq.vcf.gz"
      },

In my local server everything worked fine and I obtained what I wanted :
![image](https://user-images.githubusercontent.com/42037805/43590192-b8c0e79e-9670-11e8-973b-6ed4218782b0.png)

The version of JBrowse used in my localhost is the JBrowse-1.14.1.

So here is the problem. When I added my track in a virtual machine using the 1.11 version, it doesn't work :
 TypeError: ref is null

lineToFeature    http://10.0.0.253/jbrowse/gmod_jbrowse/src/JBrowse/Store/SeqFeature/VCFTabix/Parser.js:87:13
_getFeatures/</<    http://10.0.0.253/jbrowse/gmod_jbrowse/src/JBrowse/Store/SeqFeature/VCFTabix.js:121:29
_fetchChunkData/</<    http://10.0.0.253/jbrowse/gmod_jbrowse/src/JBrowse/Store/TabixIndexedFile.js:121:29
get/<    http://10.0.0.253/jbrowse/gmod_jbrowse/src/JBrowse/Store/LRUCache.js:67:17

The error is not caused by the chunk I added in the TrackList.json, but by the VCF containing the RNAseq data, BUT what I don't understand is why it works on the local host but not on the virtual machine.
How can I obtain the same results as in the local host in the VM ?

Thank you !

**Comment by cmdcolin** [comment]
I tested this small VCF snippet in the latest version (1.15.1) and it seemed to work. If I understand, it also works for you in 1.14.1?

But then, why are you going back to the older 1.11 version? I think it might be the case that older versions of JBrowse had some bugs, 1.11 is almost 5 years old. I can think of several specific changes that could cause that bug in the older versions

**Comment by cmdcolin** [comment]
I can confirm that it is a bug in 1.11 versions, but seems to work fine in current versions.

Is there anything preventing you from updating? Is this a GMOD in the Cloud virtual machine or something similar? Ideally the best path is simply upgrading :) All the data directories are backwards compatible so you could simply download the latest version and then move your existing data directories into the newer version's directory

**Comment by cmdcolin** [comment]
I guess sense this isn't a bug in recent versions AFAIK I will close for now but feel free to add more comments to this thread or on the mailing list :)

Sorry it is a helpful mental triage to close things

**Comment by FayrouzHam** [comment]
Hello cmdcolin and thank you for your feedback !
The 1.11 in the virtual machine worked just fine untill now, that's why we didn't upgrade it. But we will now as it is a bug in the 1.11 and not something wrong in my VCF.

Thank you !

**Comment by cmdcolin** [comment]
Glad to help :)

This is a very interesting use of VCF by the way, I hadn't seen gene expression coded in files like this. Let us know if there are any other problems.
