### ISSUE TITLE
Very large trackList.json makes scrolling slower

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1163]
First noticed in #1150

If you have a very large amount of data in the tracks, the basic operation of scrolling side to side for example becomes much slower

Here is a sample data directory with a big trackList.json, simply try scrolling side to side in the genome after navigating to this data dir

[parasite_wormbase_slow.tar.gz](https://github.com/GMOD/jbrowse/files/2263375/parasite_wormbase_slow.tar.gz)

The profiling shows lots of processing time in "other" and very low frame rate (1-2 fps sometimes)

![pngout](https://user-images.githubusercontent.com/6511937/43730382-21bf2570-9979-11e8-9bd8-9f6809262a16.png)

**Comment by cmdcolin** [comment]
This might affect chrome more than firefox just for reference

Even though both have slow initial loading, firefox eventually speeds up a bit and chrome remains slow as far as I can tell (windows, chrome 68, jbrowse 1.15.1/dev)

**Comment by rbuels** [comment]
why doesn't this affect the modencode faceted demo in the example data?  Does that not have a large enough track set?

**Comment by cmdcolin** [comment]
I tested on a different computer (still Win10, chrome 68) and the speed is perfectly fine and the performance profile is quite smooth

Given that the performance testing  on the slow computer doesn't yield much, it might be worth closing or deferring this
