### ISSUE TITLE
Make range requests robust to some occasional network errors

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1175]
I noticed in https://github.com/GMOD/jbrowse/issues/1155 that sometimes some occasional network errors can "crash" a track. It might be cool if the backend was able to refetch in some way

If I recall, original RemoteBinary file did do a refetch?

![error_out](https://user-images.githubusercontent.com/6511937/44102405-9598e0e6-9fb7-11e8-9994-4027c383cd3e.png)

**Comment by rbuels** [comment]
in addition: turning a track on and back off should clear any error state that it has
