### ISSUE TITLE
Base count is off (+1) in region input

### ISSUE THREAD

**Issue by sammyjava** [GMOD/jbrowse#1176]
In the region input to the right of the refseq selector, I have things like this shown:
```
Zm00001d048936_T001:1..414 (415 b)
```
But, clearly, 1..414 is 414 bases, not 415 bases. Here's a screengrab of another example:

![screenshot_2018-08-14 jbrowse xm_020551979 1 1 837](https://user-images.githubusercontent.com/5657219/44104945-6dd1749c-9fad-11e8-9123-963fbe529795.png)

**Comment by cmdcolin** [comment]
I think you're right :) thanks for reporting! should be fixed on dev branch

Will close for now
