### ISSUE TITLE
Chunk size exceeds chunkSizeLimit when loading large gffs

### ISSUE THREAD

**Issue by shihabdider** [GMOD/jbrowse#1179]
Hi,

I'm currently working on the human data import for Jbrowse. I have an issue with the chunk size limit when loading large gff3 files (in this case the gene set for the Grch38 human genome assembly from ENSEMBL). 

When trying to load this file using a GFFTABIX track, JBrowse gives the error message: 

`Error: Too much data. Chunk size [chunk size ~ 3 million bytes] exceeds chunkSizeLimit [2 million bytes]`

If I try to change the chunk size limit to accommodate (e.g if I set it to 4 million bytes), JBrowse will attempt to load the data for about a minute or two, and then crash. 

You can see the issue here:

[http://ec2-54-67-121-175.us-west-1.compute.amazonaws.com/?loc=chr1%3A97130001..110300000&tracks=DNA%2CHomo_sapiens.GRCh38.93.gff3.gz&highlight=](url)

Is there anything I can do to circumvent this?

Best,
Shihab

**Comment by cmdcolin** [comment]
This GFF contains "chromosome" level features and it is important for GFF3Tabix to set this parameter


    dontRedispatch=chromosome


This will make the problem go away. The GFF3Tabix code has additionally been upgraded in the upcoming 1.15.2 release to so smarter things that will make the initial track load (which performs a feature density estimation) better due to #1167 

Note that this GFF also contains many non coding features mixed with coding features and I believe it is really important to address #1106 in order to accomodate GFF like this

**Comment by cmdcolin** [comment]
In the meantime, you might consider making several different tracks from this one GFF with the "topLevelFeatures" defined as different things e.g. one track with topLevelFeatures=gene, another with topLevelFeatures=ncRNA, another with topLevelFeatures=pseudogene

**Comment by cmdcolin** [comment]
Here's a little sample config that shows what I mean

```
[tracks.gfftabix]
urlTemplate=Homo_sapiens.GRCh38.93.gff3.gz
type=CanvasFeatures
storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
dontRedispatch=chromosome
topLevelFeatures=gene

[tracks.gfftabix_ncrna]
urlTemplate=Homo_sapiens.GRCh38.93.gff3.gz
type=CanvasFeatures
storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
dontRedispatch=chromosome
topLevelFeatures=lnc_RNA

[tracks.gfftabix_pseudogene]
urlTemplate=Homo_sapiens.GRCh38.93.gff3.gz
type=CanvasFeatures
storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
dontRedispatch=chromosome
topLevelFeatures=pseudogenic_transcript

```

This makes different feature types have different tracks, mostly because putting everything in the same track is related to #1106. Hope that helps :)

Let us know if there are any more issues

**Comment by shihabdider** [comment]
Thank you @cmdcolin! Adding the dontRedispatch tag and splitting the gff file indeed worked. 

As a follow up I'm trying to split up a large vcf file that contains structural variants. Is it possible to use the topLevelFeatures tag to have one track for each SVTYPE (e.g one track for the copy number variations, another for indels etc.) or do I have to split the file itself?

[Here](http://ec2-18-144-75-19.us-west-1.compute.amazonaws.com/?loc=chr2%3A104740501..105393500&tracks=DNA%2Chomo_sapiens_structural_variations.vcf.gz&highlight=) is what the complete structural variant track looks like (not split)

**Comment by cmdcolin** [comment]
@shihabdider topLevelFeatures would not apply to SVTYPE. Probably splitting the file into different SVTYPE features as a pre-processing step is probably easiest thing to do
