### ISSUE TITLE
Read Splicing Missing Until Zoomed In

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1183]
A colleague was using JBrowse desktop 1.15.1 to visualise some RNA-Seq data (BAM+CSI) on a barley genome assembly. I noticed that there appeared to be no evidence of splicing between two exons (across the large intron in the middle):
![sos1](https://user-images.githubusercontent.com/2037575/44241039-9a772780-a200-11e8-98cb-dfd176c61b50.PNG)

However, after zooming (towards the right side of the big intron) in spliced reads are then displayed. The following picture was the first zoom level to display any splicing in this region:
![sos1_zoomed](https://user-images.githubusercontent.com/2037575/44241061-b37fd880-a200-11e8-85a1-fcc73b748580.PNG)

This is not good as it means a user must zoom in sufficiently to check if there is evidence for splicing.

**Comment by cmdcolin** [comment]
If the "maxHeight" of the track is changed to something larger do the spliced reads show up? I know it looks weird but it seems possible the layout algorithm would just pack the reads in a weird way that makes them hard to see for whatever reason. It has been suggested to do something that improves "sorting" of the feature packing algorithm, but I just wanted to see if this is a special case of that.

**Comment by cmdcolin** [comment]
The "hideUnsplicedReads" option could also helpful in some cases too which hides everything except spliced alignments. This is available from the track menu also, not just via config so should be able to use this in JBrowse desktop pretty easily

![t11](https://user-images.githubusercontent.com/6511937/44351999-2abba380-a471-11e8-9538-48100a556660.png)

**Comment by cmdcolin** [comment]
Any update on this?

**Comment by cmdcolin** [comment]
I guess if there is an issue with this still, feel free to post back! I'm fairly certain that this is just related to some arbitraryness of the GranularRectLayout. If that is still a problem let me know
