### ISSUE TITLE
JBrowse Desktop Linux Dependencies

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1185]
I wanted to install JBrowse Desktop on a remote server, which I can access using X11 forwarding and had issues that suggested the distributed desktop app is not as self-contained as I'd thought and actually requires dependencies to be installed.

After doing `ssh -X my_server` and trying to execute the JBrowse executable I get:

`error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

I took a look at what libraries are linked to the executable and find that there are several not found:

```bash
libgtk-3.so.0 => not found
libgdk-3.so.0 => not found
libX11-xcb.so.1 => not found
libXtst.so.6 => not found
libXss.so.1 => not found
libgconf-2.so.4 => not found
libnss3.so => not found
libnssutil3.so => not found
libsmime3.so => not found
libnspr4.so => not found
libasound.so.2 => not found
```

There are a couple of libraries shipped with JBrowse desktop which are found:

```bash
libnode.so => /tmp/JBrowse-1.15.0-desktop-linux-x64/libnode.so (0x00007f7a26826000)
libffmpeg.so => /tmp/JBrowse-1.15.0-desktop-linux-x64/libffmpeg.so (0x00007f7a23349000)
```

While others are found on my system.

So, the question is, should these be shipped with JBrowse, should the app be statically linked or do the dependencies need to be specified somewhere so that users know what needs to be installed before running.

On my setup, I'm actually using a cluster which is using modules to specify the software environment - but that's another story of how I meet the dependencies if JBrowse desktop doesn't ship with the libraries or is dynamically linked.

**Comment by rbuels** [comment]
![image](https://user-images.githubusercontent.com/73749/44245569-2b60eb00-a18e-11e8-95f4-50b099d4609b.png)

**Comment by rbuels** [comment]
![image](https://user-images.githubusercontent.com/73749/44245581-3ca9f780-a18e-11e8-8bc9-4a3f8afaf180.png)
![image](https://user-images.githubusercontent.com/73749/44245585-43d10580-a18e-11e8-96ec-7518cf338ca5.png)

**Comment by cmdcolin** [comment]
It seems like the only alternative to this would be providing packages such as .deb. This would allow pre-requisites to be specified.

I documented the need for libgconf -2-4 in our docs since this is actually needed on an ubuntu desktop distribution 4ee5bf2. For a server distribution I don't have the precise list but feel free to add if you have the list of pre-reqs needed.

Note: it's sort of annoying because libgconf does exist on ubuntu 16 by default IIRC but not ubuntu 18. Again, maybe deb packaging and similar would help

**Comment by cmdcolin** [comment]
Feel free to also add ssh tunneling to docs too if it is a helpful configuration

**Comment by rbuels** [comment]
What do you guys think about closing this and opening a different issue about creating .deb, .rpm, etc packages for JBD on Linux?

**Comment by rbuels** [comment]
ok, closing this in favor of #1197
