### ISSUE TITLE
Label linked unchangable personal configurationsettings track height

### ISSUE THREAD

**Issue by ikkextoch** [GMOD/jbrowse#1188]
Dear all,

I believe I have stumbled upon a bug that I can't find the origin of.

BAM files can be displayed in at least two track types: `JBrowse/View/Track/SNPCoverage` and `JBrowse/View/Track/Alignments2`. In JBrowse, it is possible to toggle the type and other settings in the [`Edit track configuration`-popup](http://oi67.tinypic.com/2d9787b.jpg) that appears when clicking on the "Edit config" option in the menu that is displayed when clicking on the down arrow of the track label.

When I change the height (of a BAM track in JBrowse with pre-configured type `JBrowse/View/Track/SNPCoverage`) with the Change height button in the popup menu and subsequently change the track type to `Alignments2` and back, the height of the track is fixed and cannot be set manually anymore (only with the button). This implies that the height of the track cannot be reset (to default) nor does it automatically change between different types. The height of individual reads in the `Alignments2` type is stuck at a fixed value, rather than automatically recalculated when changing the track type, which can result in very big alignments.

I have found that changing the label name in the .config file results in the loss of the original track (with manually edited settings), and the gain of a new track (with the same data, but without manually edited settings). Subsequently changing the label back to the original label results in the original track (with manually edited settings). Using a different computer to view the same track results in no altered height values.

I have tried the following approaches to resolve this issue:
-clear my cache history
-clear my cookies of the last 6 hours
-change the value of the height parameter to an empty string, while the track type is `SNPCoverage` and changing the track type simultaneously
-change the label to another name and the value of the height parameter to an empty string, while the track type is `SNPCoverage` and changing the track type together with the label in serial order and simultaneously

I don't know what other options I could try. Where could Jbrowse store info regarding local configuration settings, if not in the cookies or cache, and how can I set the height settings back to default? This bug limits the possibility to change the track height in SNPCoverage, whithout setting it for the Alignments2 too.

Info
- JBrowse-1.12.3
- Firefox 61.0.2 (64-bits)

Thanks in advance
dvdleest

**Comment by cmdcolin** [comment]
There has been a request to allow easier switching between alignments related views here https://github.com/GMOD/jbrowse/issues/1154

I think addressing that issue will help your scenario.

The specific thing you are running into is that the total track height of the SNPCoverage is stored in style.height while the individual feature heights are also stored in style.height for Alignments2 I think

The data for this height that you are having trouble resetting is stored in "html5 localstorage". Clearing cookies should clear this also but if you are in firefox you can manually go to "Inspect element->Storage->Local storage" and delete all

![t343](https://user-images.githubusercontent.com/6511937/44409785-0921f100-a531-11e8-9f08-3d3d5dae59a2.png)

**Comment by cmdcolin** [comment]
Note also, that if instead of using the "Change height" dialog box to change the height, you could use "Edit config" to change the "style": { "height": 200 } or something like that. It won't have the sticky localstorage problem that the "Change height" dialog has
