### ISSUE TITLE
JBrowse is on loading page for ever

### ISSUE THREAD

**Issue by shenweima** [GMOD/jbrowse#1191]
I have a jbrowse website [http://202.194.139.32/jbrowse/?data=Chinese_Spring](http://202.194.139.32/jbrowse/?data=Chinese_Spring).
It works well for a time, But in recent days, it works not well. It is on loading page for ever. 
I think jbrowse can't read "trackList.json" file.

**Comment by shenweima** [comment]
This is my firewall information. Would you give me other suggestion?
`fei@KL-1:~$ sudo ufw status
[sudo] password for fei: 
Status: inactive
fei@KL-1:~$ whereis iptables
iptables: /sbin/iptables /usr/share/iptables /usr/share/man/man8/iptables.8.gz
fei@KL-1:~$ iptables -L -n
iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
fei@KL-1:~$ sudo iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.2           tcp dpt:80

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
`

**Comment by cmdcolin** [comment]
I don't personally know about firewalls or iptables so I couldn't say if this config is problematic.

The only sort of workarounds I can think of is to modify your configuration to load the jbrowse code from another website that does not have this blocked, e.g. you could modify your index.html to use the <script src="http://jbrowse.org/code/JBrowse-1.12.5/src/dojo/dojo.js"> (do this for css and js too)
