### ISSUE TITLE
Large GFF3Tabix stresses machine

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1195]
It appears that loading the NCBI annotation transformed into GFF3Tabix causes some stress on the system

Here is a profiling screenshot showing 50 seconds needed to display file loaded from localhost on browser. The data directory for a Chr1 from NCBI GRCh38 is attached here too

![log](https://user-images.githubusercontent.com/6511937/44672627-032b8480-a9f7-11e8-90f1-00e06ee6129b.png)

[ncbi_human_gff.tar.gz](https://github.com/GMOD/jbrowse/files/2324798/ncbi_human_gff.tar.gz)

**Comment by cmdcolin** [comment]
Possibly move to @gmod/gff-js

**Comment by cmdcolin** [comment]
I think likely it is not a problem with gff-js itself but maybe it is due to redundant work being done e.g processing duplicate regions after redispatches, or the cache not being used, or something like this. Haven't exactly determined

**Comment by rbuels** [comment]
I'll look into this, since I'm kind of redoing the tabix code now.

**Comment by garrettjstevens** [comment]
A bit of an update here. On the current dev branch, it takes ~75 seconds on my machine for one region of this data:
![before](https://user-images.githubusercontent.com/25592344/45591546-ef9f7980-b923-11e8-90e5-ae251970b8b4.png)
And on the 1147_npm_tabix_fixtests branch it only takes ~32 seconds:
![after](https://user-images.githubusercontent.com/25592344/45591550-0e057500-b924-11e8-9807-22517044135b.png)
