### ISSUE TITLE
rewrite/refactor VCF parser into a node module

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1199]
Rewrite the stuff in JBrowse/Store/SeqFeature/VCF/Parser into a node module that streams like @gmod/gff

**Comment by garrettjstevens** [comment]
I've got this sort of working in JBrowse. The boxes and some of the details are working. I still need to get the labels and the rest of the details working.
![image](https://user-images.githubusercontent.com/25592344/45721794-80ba5e80-bb77-11e8-96d3-1831553e4cc7.png)

**Comment by garrettjstevens** [comment]
Resolved by #1227
