### ISSUE TITLE
Can't seem to get refSeqOrder (or other refSeq configs) to work

### ISSUE THREAD

**Issue by sammyjava** [GMOD/jbrowse#1202]
- JBrowse version = "1.15.4-alpha.0" (origin/dev)
- Web browser being used = Ubuntu Firefox
- Operating system if relevant = Debian (Google Cloud)
- If it is setup related, setup.log = not setup related, JBrowse generally works spiffily

I'm having a hella time getting the ref seq dropdown to do what I want. I've put the following:
```
    "refSecDropdown" : true,                                                                                                                                                                                    
    "refSecSelectorMaxSize" : 50,                                                                                                                                                                               
    "refSecOrder" : "length descending",  
```
in the top of trackList.json (just above "tracks") as well as inside the "reference sequence" track configuration (right above "useAsRefSeqStore" : 1) and in either case, I'm still left with 30 refseqs ordered alphabetically, not length descending.

Any idea what I'm doing wrong?
![2018-09-04-161358_1680x1026_scrot](https://user-images.githubusercontent.com/5657219/45060565-a1ee5b80-b05d-11e8-9e2a-1cd86d199286.png)

**Comment by sammyjava** [comment]
I'll add that I _can_ specify a list of sequences in `tracks.conf` using `refSeqOrderList`, but 
```
refSecDropdown = true                                                                                                                                                                                           
refSecSelectorMaxSize = 50 
```
still fails there as well, I'm left with 30, not 50, refseqs in the dropdown.

**Comment by cmdcolin** [comment]
Many of the config items that you list here say "refSec" instead of "refSeq"

You did specify the spelling as refSeq in the title so I'm just wondering if this is a typo

**Comment by sammyjava** [comment]
Oh, geez. I need a JBrowse spell checker. Thanks! Closing....
