### ISSUE TITLE
How to block the download of a specific track

### ISSUE THREAD

**Issue by ThomasLet** [GMOD/jbrowse#1204]
Hello,

I wanted to know if there is a way to disabled the "save track data" option when you left click on a track name ?
In fact I have many public tracks on my jbrowse but only one is a bit sensitive, is it possible to disabled this option for only one specific track ? in the trackList.json maybe ?

Thanks again for your help,

Best regards,

Thomas

**Comment by cmdcolin** [comment]
You can set "noExport": true  on the track in trackList.json http://jbrowse.org/docs/data_export.html#export-configuration

**Comment by cmdcolin** [comment]
I guess given the config option I'll close this for now. There are potentially things about private tracks that can be sort of interesting (e.g. having actual private and public tracks) which is a little different from the noExport option, but hopefully this helps

**Comment by ThomasLet** [comment]
Many thanks cmdcolin it worked !
