### ISSUE TITLE
Remove "Region sequence" from Details View

### ISSUE THREAD

**Issue by andreaminio** [GMOD/jbrowse#1211]
I'd like to remove the "Region sequence" detail from the Details View popup as I fee it is misleading for the subfeatures. 
With fmtDetailField_ I can remove some of the details showed, but I cannot find the right one for the Region Sequence nor any documentations of fmtDetailField_* available. 
I've seen suggested (in 2016) to set maxFeatureSizeForUnderlyingRefSeq to 0, but does not remove the element, just writes that is not available (which sounds more like a bed set up of the browser). Is there any more "elegant" solution with the last versions of the browser?

Andrea

**Comment by rbuels** [comment]
@andreaminio thanks for this, are the features you're displaying genes, and you'd like to not have subsequences for the exons and such?

**Comment by andreaminio** [comment]
Sorry for bumping, but I had no reply on how to solve the problem

**Comment by cmdcolin** [comment]
The latest branch "dev" merged PR #1219 which means your specific track can have

    "hideSequenceBox": true

This hides all the FASTA boxes

**Comment by cmdcolin** [comment]
Will be released in next version soon :) but close this for now!

**Comment by andreaminio** [comment]
Thanks guys, you're awesome!
