### ISSUE TITLE
update API of tribble-index node module and re-integrate it

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1212]
related to #1199, need to make the tribble indexing API compatible with the new code and republish it as @gmod/tribble-index

**Comment by garrettjstevens** [comment]
See also https://github.com/GMOD/tribble-index-js/issues/1

**Comment by rbuels** [comment]
👍👍👍👍

**Comment by garrettjstevens** [comment]
Resolved by #1227
