### ISSUE TITLE
Y-scale appears while features are displayed

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1214]
I think this issue is related to #1190

Note that removeYScale from _YScaleMixin is being called but not working properly perhaps?

![screenshot-jbrowse org-2018 09 24-12-42-28](https://user-images.githubusercontent.com/6511937/45966018-0dda3900-bff8-11e8-8473-9b95bd85bd1b.png)

Try this link, happens more often when everything is in cache too
http://jbrowse.org/code/JBrowse-1.15.3/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A20121..20814&tracks=volvox-sorted_bam%2Cvolvox_gff3_tabix&highlight=

I thought indexed stats estimation might have caused it but it happens with older versions too e.g. 1.15.0

**Comment by garrettjstevens** [comment]
When I try that link and then move my mouse's scroll wheel a bit, the bottom track actually moves and ends up on top of the top one:
![image](https://user-images.githubusercontent.com/25592344/45967477-22203500-bffc-11e8-8148-68017fe27020.png)

@cmdcolin do you think that's related or another issue altogether?

**Comment by cmdcolin** [comment]
I have seen that also though, if you have a exact way to reproduce let me know

**Comment by garrettjstevens** [comment]
I've tried it on both Chrome and Firefox on my machine and this is how I got the overlapping tracks:

* Right-click the link you pasted in the original comment and click "Open link in incognito window" (or "Open Link in New Private Window" on Firefox)
* Move my mouse to the middle of the opened window
* Scroll up a little with the scroll wheel on my mouse

Let me know if the same doesn't happen for you. Maybe there's something different about my setup.

**Comment by rbuels** [comment]
fixed by merging #1218
