### ISSUE TITLE
Broken link in http://jbrowse.org/docs

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/jbrowse#1224]
Thank you for these new docs!

I have found a broken link in the following section: http://jbrowse.org/docs/prepare-refseqs.pl.html

Here on "indexed file format tutorial":
Indexed file formats are becoming much better, so we also suggest you look at the indexed file format tutorial and consider indexed fasta or 2bit

Is this documentation stored in github somewhere, so that anyone can submit pull requests ?

**Comment by cmdcolin** [comment]
Thanks for reporting :) The majority of docs live in the repo as markdown files in docs/site/*.md

I will go ahead and fix this particular error but pull requests are welcome! If you want to preview locally you can run "npm run start" inside the website directory

**Comment by loraine-gueguen** [comment]
ok!

**Comment by cmdcolin** [comment]
Should be up :) thanks for checking the docs and let us know if anything can be done to improve...the site docs are still quite new
