### ISSUE TITLE
Long VCF features show inconsistent lengths

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse#1232]
VCF I'm using is http://s3.amazonaws.com/1000genomes/phase3/integrated_sv_map/ALL.wgs.integrated_sv_map_v2.20130502.svs.genotypes.vcf.gz

On current dev branch, take this ~13k bp feature (it's a CNV) for example:
![image](https://user-images.githubusercontent.com/25592344/46811830-83a50b00-cd41-11e8-8a8d-8a9ba59c67de.png)
When zoomed in, it only shows ~45bp long:
![image](https://user-images.githubusercontent.com/25592344/46812012-dd0d3a00-cd41-11e8-9471-091e0a66d849.png)
Then zooming out it gets longer (below ~345 bp):
![image](https://user-images.githubusercontent.com/25592344/46812242-4db45680-cd42-11e8-9ab6-13f37ec8229b.png)
(~6,800 bp)
![image](https://user-images.githubusercontent.com/25592344/46812561-f5ca1f80-cd42-11e8-9134-fae1a31b56f3.png)
Until it gets to its actual length. It never shows longer than the actual length.
![image](https://user-images.githubusercontent.com/25592344/46812603-1003fd80-cd43-11e8-97b4-df1b6ffbafb8.png)

Because of this there can be cases where the right ends of long features are supposed to be showing up when zoomed in, but they don't. For example, at this zoom level these two features overlap:
![image](https://user-images.githubusercontent.com/25592344/46812836-8ef93600-cd43-11e8-9e25-c67313f1acb9.png)
but at this level they don't:
![image](https://user-images.githubusercontent.com/25592344/46812959-cff14a80-cd43-11e8-8062-a04941bd70bd.png)

@cmdcolin or @rbuels, any suggestions on where I start looking for the cause of this?

**Comment by cmdcolin** [comment]
Can you try  pre 1.15.4? Wondering if the @gmid/tabix merge could be relevant?

**Comment by rbuels** [comment]
Yeah I would expect some kind of tabix related bug here

**Comment by garrettjstevens** [comment]
Yep, looks like it was introduced in 1.15.4, so probably tabix.

**Comment by rbuels** [comment]
Any way you can distill it to the point of writing a failing test case in
tabix-is?

**Comment by garrettjstevens** [comment]
Hmm...not sure the problems is actually in tabix-js. It seems to be parsing the correct start and end values out of the VCF. Maybe in something else that got touched in the tabix PR? I'll keep looking.

**Comment by garrettjstevens** [comment]
You are, of course, correct. It's not getting features where the length is defined in the "END=" entry in an info field. Working on a tabix-js test case now.

**Comment by rbuels** [comment]
I wonder if `tabix` itself isn't indexing those features correctly

**Comment by garrettjstevens** [comment]
The `tabix` command line utility seems to retrieve them fine. See https://github.com/GMOD/tabix-js/issues/4 for more details and a failing test case.

**Comment by garrettjstevens** [comment]
https://github.com/GMOD/tabix-js/pull/5 should fix this once merged

**Comment by garrettjstevens** [comment]
Resolved by https://github.com/GMOD/tabix-js/pull/6
