### ISSUE TITLE
VCF and BAM file error 

### ISSUE THREAD

**Issue by Koderob** [GMOD/jbrowse#1242]
# An error was encountered when displaying this track.
- JBrowse version - 1.15.2
- Web browser being used - Apache
- Operating system if relevant - Ubuntu 18.04.

When displaying VCF or Bam files it takes long time to load then ends up giving me the above stated error and message below. 
## Diagnostic message [Object Response]

Also consider submitting questions via email to gmod-ajax@lists.sourceforge.net as GitHub issues are primarily used for bugs and feature requests

**Comment by cmdcolin** [comment]
One sort of thing tht is fixed in 1.15.3 is that error message should be more informative (red #1196)

You might try upgrading for a more informative error message but if you have more details about your setup it could help.

For example the vcf.gz.tbi and Bam index .bam.bai files should be available in the data directory

**Comment by cmdcolin** [comment]
Any update on this?

**Comment by xma82** [comment]
I meet the same problem and ask if you have solved this problem, please give me some help, thanks in advance!

**Comment by cmdcolin** [comment]
Hi @xma82 I need more detail to answer this.

 Its unfortunately a little bit jbrowse's fault for providing faulty error reporting that results in this "[object response]" text which is not too helpful

Can you add more details? Also you might try looking at the "devtools" or "javascript console" to see what the error message is there and report?

**Comment by xma82** [comment]
Hi @cmdcolin，when displaying a bam files , a error happened, like this:  
**Diagnostic message**   **error: incorrect header check**

**Comment by cmdcolin** [comment]
@xma82 this is likely a server side configuration issue, see https://github.com/GMOD/jbrowse/issues/1305

**Comment by xma82** [comment]
Thank you very much! @cmdcolin, I have solved my problem through adding the line "AddType application/octet-stream .bam .bami .bai" in httpd conf file.
