### ISSUE TITLE
Make it easier to add external links in JBrowse

### ISSUE THREAD

**Issue by benwbooth** [GMOD/jbrowse#1247]
We are currently using JBrowse and Dalliance together, since JBrowse has the nice faceted track selection and incremental search, but Dalliance has SVG and PNG export capabilities. It would be nice if it were easier to add menu items in JBrowse that would point to an external page using a template, such as "https://my.page.org/dalliance/?loc={chr}:{start}-{end}&tracks={tracks}". Currently it looks like I will have to write a JBrowse plugin to get this functionality. But I think it would be useful if this were supported as a configuration option within JBrowse to make it easier for users to have this capability.

**Comment by cmdcolin** [comment]
It has currently been the case that plugins are sort of the "way to go" if modifying menus like the top menubar. It isn't really available via configuration. In that case this might overlap with #615

**Comment by cmdcolin** [comment]
If you want to see client-side jbrowse screenshot check out http://www.plantseq.org/browse ... this was done custom by the plantseq team using html2canvas https://html2canvas.hertzen.com/

**Comment by benwbooth** [comment]
Cool, but SVG format would be more suitable for producing publication-quality figures. Right now I am using Dalliance browser for this purpose.

**Comment by cmdcolin** [comment]
If it's alright, I might close for now. If you want to endeavor to make a plugin, you can check out http://jbrowse.org/docs/faq.html#how-do-i-customize-the-main-menu-bar

The list of visible tracks would be

JBrowse.view.visibleTracks()

And the chr, start, end can be obtained by

JBrowse.view.visibleRegion()
