### ISSUE TITLE
contig switch with indexed tracks fail to retrieve file sizes

### ISSUE THREAD

**Issue by luke-c-sargent** [GMOD/jbrowse#1252]
- JBrowse versions:
   - master as of 13b4941dd5665945eeaff79134c3ddbe70f2b1e6
   - releases: 1.15.4, 1.15.3, 1.15.2
- Web browser being used:
   - firefox 60.3.0esr (64-bit)
   - chrome 70.0.3538.77 (Official Build) (64-bit)

When loading up indexed tracks (tbi, bai) for the first time, they load as expected. very often, switching contigs behaves as expected. 

however, sometimes these tracks fail to load when the contig is switched -- usually when there are many other tracks being reloaded. the following error is generated:
```
Error: failed to retrieve file size for xxx
```
where xxx is the index file.

![image](https://user-images.githubusercontent.com/11185084/48086738-69c8dd80-e1b2-11e8-8368-340156e6e82d.png)

this is reproducible with the volvox sample data; simply show all tracks then switch contigs.

**Comment by luke-c-sargent** [comment]
note -- this bug is not present in 1.15.1 (the release before `http-range-fetcher` was introduced)

**Comment by cmdcolin** [comment]
Is this still reproducible?

**Comment by luke-c-sargent** [comment]
i was _not_ able to reproduce this in the dev branch

🎉

**Comment by cmdcolin** [comment]
I thought that might be the case...I am not sure what caused it still but a cache library was switched out on dev so maybe that did it

**Comment by cmdcolin** [comment]
Ooop...hit close button. I guess will keep closed though unless we see it again!
