### ISSUE TITLE
jbrowse visualization issue

### ISSUE THREAD

**Issue by julianabc29** [GMOD/jbrowse#1256]
# jbrowse visualization issue
I am using the jbrowse version 1.15, I am trying to change the gene appearance in the trackList.json file HTMLfeature:
"style": {
"className": "transcript",
"arrowheadClass": "transcript-arrowhead",
"subfeatureClasses": {
  "CDS": "transcript-CDS"
But, when I change it, a green line appear and i can´t see the exons or CDSs
![imagen](https://user-images.githubusercontent.com/41842945/48147056-6dc53000-e284-11e8-968f-267814bc8bcf.png)
How can I remove the green line?
I tried to remove it by changing all the style, but it's always present
Thanks

**Comment by julianabc29** [comment]
Yes, I hava the gff of the genes (gene, mRNA, exon and CDS
ig	gene	3337	9204	.	+	.	ID=tig..
tig	mRNA	4039	9042	.	+	.	ID=tig
tig	exon	4039	5058	100	+	.	ID=tig
tig	exon	6510	6708	100	+	.	ID=tig
tig	exon	7717	7930	100	+	.	ID=tig
tig	exon	8018	8120	100	+	.	ID=tig
tig	exon	8926	9042	100	+	.	ID=tig
tig	CDS	4038	5058	100	+	0	ID=tig
tig	CDS	6509	6708	100	+	0	ID=tig
but i don't know why the green line is showing it

**Comment by cmdcolin** [comment]
One thing that is important if you are using HTMLFeatures is to load the data at the "transcript level"

This is sort of an annoying thing to have to deal with but essentially what you need to do is run flatfile-to-json.pl with --type mRNA, or add "topLevelFeatures": "mRNA". 

The HTMLFeatures tracks can not display a three-level hierarchy of features from gene->mRNA->exon/CDS, it can only do mRNA->exon/CDS

You can switch to using CanvasFeatures to get the three level hierarchy of features without any of this trouble (use --trackType CanvasFeatures on flatfile-to-json.pl)


FAQ entry http://jbrowse.org/docs/faq.html#my-htmlfeatures-don-t-show-up-with-subfeatures-why-not

**Comment by cmdcolin** [comment]
Screenshot of the track with HTMLFeatures

![screenshot-localhost-2018 11 07-13-07-25](https://user-images.githubusercontent.com/6511937/48151018-36f41780-e28e-11e8-81d5-3da98c47f51c.png)

Using

bin/flatfile-to-json.pl --gff test.gff --trackLabel htmlfeatures --type mRNA
bin/flatfile-to-json.pl --trackType CanvasFeatures --gff test.gff --trackLabel canvasfeatures --config '{"impliedUTRs": true}'

And a GFF that has correct parent/child attributes

```
1       tig     gene    3337    9204    .       +       .       ID=tig
1       tig     mRNA    4039    9042    .       +       .       ID=tig1;Parent=tig
1       tig     exon    4039    5058    100     +       .       ID=tig2;Parent=tig1
1       tig     exon    6510    6708    100     +       .       ID=tig2;Parent=tig1
1       tig     exon    7717    7930    100     +       .       ID=tig2;Parent=tig1
1       tig     exon    8018    8120    100     +       .       ID=tig2;Parent=tig1
1       tig     exon    8926    9042    100     +       .       ID=tig2;Parent=tig1
1       tig     CDS     4038    5058    100     +       0       ID=tig3;Parent=tig1
1       tig     CDS     6509    6708    100     +       0       ID=tig3;Parent=tig1

```

**Comment by julianabc29** [comment]
Thanks @cmdcolin for your help, I am trying to change the classname using trackType CanvasFeatures, but It only changes the colors, How can I change the css className?
 I tried with feature5, transcript, helix etc ..

**Comment by cmdcolin** [comment]
If it's ok I'll close this issue for now :) Feel free to follow up with any additional comments, but since it's not necessarily a bug it'll be triaged :)
