### ISSUE TITLE
Displaying CanvasFeatures

### ISSUE THREAD

**Issue by julianabc29** [GMOD/jbrowse#1262]
HI
I am using JBrowse 1.15.4, I understand that is much better to upload the tracks in CanvaFeature because you can see GENE >mRNA>CDS. my question is, Is it possible to draw the gene, mRNA, CDS in different colors?. I mean, to see the different between gene, mRNA and CDS. and can I increase the size of the feature? I mean, make it bigger in the visualization. 
Thanks

**Comment by cmdcolin** [comment]
Are the gene, mrna, and cds all separate features? I noted in this thread that if the features are properly linked together using the Parent attribute then it displays as a single gene feature https://github.com/GMOD/jbrowse/issues/1256

If that is not what you are interested in please provide more details such as a sample of your gff, the current thing you are seeing and what you expect to be seeing.

**Comment by cmdcolin** [comment]
Sorry I am having trouble understanding/visualizing what you mean. If you can provide a screenshot of what you are seeing, and describe what you want to see instead, it would help!

**Comment by julianabc29** [comment]
I have this data
![imagen](https://user-images.githubusercontent.com/41842945/48493761-7e345800-e7fa-11e8-9846-4a7b1273345e.png)
and the corresponding visualization
![imagen](https://user-images.githubusercontent.com/41842945/48493231-77f1ac00-e7f9-11e8-8f09-3e023bf08077.png)
Is it possible to make a difference in three levels (gene, mRNA, CDS), trying to change the colors (whatever) for gene, ARN and CDS. and Can I change the size? I mean, to make the track bigger

**Comment by cmdcolin** [comment]
If you wish to change the height and color of the features, you can edit the trackList.json

"style": {
    "height": 20,
    "color": "green"
}

These can also be dynamic functions so that the height or color changes depending on the data. Does that make sense?

**Comment by julianabc29** [comment]
well, yes, thanks, @cmdcolin  But  could I change for gene : blue, mRNA: green or CDS: yellow ?

**Comment by cmdcolin** [comment]
The gene and the mRNA are basically just symbolic containers and are not explicitly drawn on the screen by default, only the subfeatures e.g. the CDS and the introns end up being drawn as boxes with a color on the screen.

What would it look like for the gene and or mRNA to be drawn?

**Comment by cmdcolin** [comment]
If it helps, you can adjust the "connectorThickness" and "connectorColor" which might match what you were looking for more

Example

         "style" : {
            "height": 20,
            "connectorThickness": 15,
            "connectorColor": "grey"
         },


![screenshot-localhost-2018 11 14-11-46-35](https://user-images.githubusercontent.com/6511937/48497931-19313000-e803-11e8-94ca-92138418f731.png)

**Comment by cmdcolin** [comment]
Note that the blue in the above screenshot are UTR which you can get by enabling "impliedUTRs" on your track (discussed in issue #1256)

**Comment by julianabc29** [comment]
yes, I think that is what i need it @cmdcolin thank you very much

**Comment by cmdcolin** [comment]
Super :) Sorry for the confusion

**Comment by cmdcolin** [comment]
I'll close for now
