### ISSUE TITLE
How to export fasta sequences of a whole region ? 

### ISSUE THREAD

**Issue by thomas77** [GMOD/jbrowse#1265]
Hello,

I would like to download the fasta sequences of my genes in a specific location (as it is possible in BED, GFF or tabulated file), I did not find out to do it, is-it possible ?

Best regards,

Thomas

**Comment by cmdcolin** [comment]
If you want to export arbitrary regions of sequence, you can use the highlight tool. You can select the highlight button, drag across a region of interest, then open up your reference sequence track and click "Save track data". This will then have an option to export the highlighted region fasta sequence. The View->Set highlight can set more precise coordinates to highlight and subsequently export

Does that make sense? The ability for JBrowse to get join multiple CDS features into a single exported sequence, but plugins such as "FeatureSequence" exist to do this

**Comment by thomas77** [comment]
Hello Colin,

thank you for your answer ! Maybe I miss something because when I highlight a specific region on my JBrowse the "save track data" button is still disable for the Reference sequence track:

![printjb](https://user-images.githubusercontent.com/2969979/48833752-60c43880-ed7c-11e8-99b1-57c85c3cc2a2.png)


I will have a look at the "FeatureSequence" plugin thank you !

Regards,

Thomas

**Comment by thomas77** [comment]
Ok I got it, it's because the region I took is too big to be export !

**Comment by cmdcolin** [comment]
There is not currently a sort of mechanism for this bulk export of multiple feature's FASTA sequences. There is an open issue here for bulk export so I'll add this issue as a subtask there !

https://github.com/GMOD/jbrowse/issues/303

**Comment by cmdcolin** [comment]
Note also if you need to export larger regions you can set maxExportSpan to a larger number, default is 500kb (set on per track basis I believe)
