### ISSUE TITLE
Unable to fetch vcf file

### ISSUE THREAD

**Issue by shenweima** [GMOD/jbrowse#1266]
- JBrowse version:  jbrowse-1.12.3-release
- Web browser being used: apache2
- Operating system if relevant: Jbrowse was installed on docker of ubuntu 16.04

This is my jbrowse http://202.194.139.32/jbrowse-1.12.3-release/?data=Chinese_Spring
I can load `wheat660K` track but not for wheat_90K.

http://202.194.139.32/jbrowse-1.12.3-release/?data=Chinese_Spring&loc=chr1A%3A498530961..498537150&tracks=IWGSC_v1.1_HC_gene%2Cwheat660K%2Cwheat_90K&highlight= 
``
![test](https://wheat-1252088472.picsh.myqcloud.com/2018-11-20-164217.png)
![](https://wheat-1252088472.picsh.myqcloud.com/2018-11-20-164941.png)
![](https://wheat-1252088472.picsh.myqcloud.com/2018-11-20-165433.png)
![](https://wheat-1252088472.picsh.myqcloud.com/2018-11-20-165841.png)
![](https://wheat-1252088472.picsh.myqcloud.com/2018-11-20-170102.png)
Also consider submitting questions via email to gmod-ajax@lists.sourceforge.net as GitHub issues are primarily used for bugs and feature requests

**Comment by shenweima** [comment]
Thanks. I have found only my IP address can't access it...

**Comment by cmdcolin** [comment]
Dang. Might be firewall related. You had also been opened that I suspected was maybe firewall related in the past https://github.com/GMOD/jbrowse/issues/1191

**Comment by cmdcolin** [comment]
I will possibly close this for now. If you find a solution or need additional help feel free to comment or follow the gmod-ajax thread
