### ISSUE TITLE
CRAM layout can get messed up

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1271]
The layout of CRAM features can get messed up possibly near block boundaries?

![screenshot-localhost-2018 11 29-09-16-28](https://user-images.githubusercontent.com/6511937/49227662-93db7d00-f3b7-11e8-9003-0665287d77a8.png)
See the screenshot there are "holes" in the layout

[pseudomonas2.tar.gz](https://github.com/GMOD/jbrowse/files/2629461/pseudomonas2.tar.gz)

To reproduce I uploaded a sample data directory. Start at the start of the chromosome and then scroll to the end of the data and the layout will be weird and mouseovers will not work at the end right where the features end

Tested on 1.15.3 and dev branch. The same thing does not appear to happen with BAM versions of the same file

**Comment by rbuels** [comment]
@cmdcolin try it in 1.15.0

**Comment by cmdcolin** [comment]
I tested in 1.15.0 and it still exhibited problem, and the BAM for same file works fine

**Comment by cmdcolin** [comment]
Now, the interesting thing is i think it is due to ID collisions. If I make a simple hashmap collision detector e.g.

 
        if(totalMap[feature.id()] && totalMap[feature.id()]!=feature.get('start')+','+feature.get('end')) {
            console.log('collision',totalMap[feature.id()],'t1',feature.get('start')+','+feature.get('end'));
        }
        else {
            totalMap[feature.id()]=feature.get('start')+','+feature.get('end');
        }

Then this outputs a lot of collisions in the areas that the layout is bad

**Comment by cmdcolin** [comment]
The reason that it is not the thing where we have broken features is becauuse the IDs are not inconsistent across blocks, but instead collide
