### ISSUE TITLE
CRAM can display features on the wrong chromosome

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1273]
If I edit volvox refSeqs.json for example to contain a fake chromosome

    [{"name": "aaa", "start": 0, "end": 50001},{"end":50001,"length":50001,"name":"ctgA","seqChunkSize":20000,"start":0},{"end":6079,"length":6079,"name":"ctgB","seqChunkSize":20000,"start":0}]

Then it will display on this fake chromosome. It will also display ctgA as it should

**Comment by cmdcolin** [comment]
noticed when I saw cram display on a mitochondrial chromosome

**Comment by rbuels** [comment]
this is probably a bug in the CRAM store in the JBrowse codebase
