### ISSUE TITLE
searchNames should wait for "loadNames" milestone to finish

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#1286]
Related to this:

https://github.com/GMOD/Apollo/issues/1942#issuecomment-447438566

JBrowse version:

1.15.4 (and possibly 1.16.0)

**Comment by cmdcolin** [comment]
Fix by https://github.com/GMOD/jbrowse/commit/eaeb49066e9574c11d7ed9583f2e810db7c44924
