### ISSUE TITLE
failed to use bgzipped fasta

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1290]
JBrowse cloned from the master branch

I use the test data in: `sample_data/raw/random_contigs.fa` as an example, and I copied it twice as `test1.fa` and `test2.fa`

Then I indexed them as:
```
samtools faidx test1.fa
```

```
bgzip -i test2.fa
samtools faidx test2.fa.gz
```

Then I imported them using `prepare-refseqs.pl`
```
./bin/prepare-refseqs.pl --indexed_fasta test1.fa --out sample_data/test1
./bin/prepare-refseqs.pl --bgzip_fasta test2.fa.gz --out sample_data/test2
```

Then I visited them in the browser:
http://path/to/jbrowse/?data=sample_data/test1
http://path/to/jbrowse/?data=sample_data/test2

I was surprised that **test1 (normal indexed FASTA) was successful** but **test2 (bzgip indexed FASTA) was failed**, and I saw such error message:

![tim 20181225093918](https://user-images.githubusercontent.com/1146090/50408861-19bcdd80-0829-11e9-8d14-88f16252d3fd.png)

**Comment by billzt** [comment]
@jbrowse @cmdcolin @rbuels @dkasenberg @enuggetry

**Comment by cmdcolin** [comment]
On my machine this procedure actually works ok and I am able to see the reference sequence just fine.

I am suspecting that your server might be sending incorrect headers causing decompression of the .fa.gz file using Content-Encoding: gzip which is not what we want (similar to this http://jbrowse.org/docs/faq.html#what-is-the-error-invalid-bgzf-header-on-my-vcf-files)

It is hard to provide a specific fix for your server without knowing the setup, but probably you'll want to add an exclusion for this somehow or just rename the file to have a different file extension e.g. if you had seq.fa.seqgz, seq.fa.seqgz.gzi, seq.fa.seqgz.fai, then run prepare-refseqs.pl --bgzip_fasta seq.fa.seqgz

Also merry christmas/holidays :) ☃️ 🎄

**Comment by cmdcolin** [comment]
Potentially also a better error message could help for point of reference here

**Comment by billzt** [comment]
OK!

Previously my configuration file of apache (`.htaccess`) has the following set:
``` ini
SetEnvIfNoCase Request_URI "\.gz$" no-gzip dont-vary
```

Here I add another set:
```ini
SetEnvIfNoCase Request_URI "\.gz\.fai$" no-gzip dont-vary
```

Then it works.

Thanks very much and merry christmas!

**Comment by billzt** [comment]
Wow, I've discovered another issue.

**Comment by billzt** [comment]
#1291
