### ISSUE TITLE
How to fit viewport vertically?

### ISSUE THREAD

**Issue by shouldsee** [GMOD/jbrowse#1296]
(Must be trivial to any front-end developer...) But how do I set jbrowser to not overflow the current viewport vertically?

**Comment by garrettjstevens** [comment]
@shouldsee Are you [embedding JBrowse](http://jbrowse.org/docs/embedding.html) (in an iframe or a div)? Also, if you could include a screenshot of what you're seeing that could help us answer your question.

**Comment by shouldsee** [comment]
I am running with `util/jb_run.js` so I guess it's a div. 

I am looking at the source.
![image](https://user-images.githubusercontent.com/8034156/50493260-4254fb00-0a14-11e9-8b6b-87d9fbf3ff0c.png)

**Comment by garrettjstevens** [comment]
@shouldsee, I'm not sure what you mean by "not overflow vertically." What would you like to have happen if there are more tracks than can fit on the screen, besides overflow with a scrollbar?

**Comment by cmdcolin** [comment]
For the wiggle tracks, there is a button "Resize quant. tracks" in the "View" menu that will specifically change the height of those wiggle tracks.

I guess it is not designed around the viewport, but you could certainly play with it to achieve the right height.

You might also consider the multibigwig plugin for compact displays of many wiggle tracks. https://github.com/elsiklab/multibigwig

**Comment by shouldsee** [comment]
@cmdcolin  Ahhh good to know! The "resize quant" button looks rather useful, so is the multibigwig! 

I haven't got time to read about plugin yet but will def give it a go!

**Comment by garrettjstevens** [comment]
@shouldsee in addition to what @cmdcolin said, for tracks that don't resize with "Resize quant. tracks" (like the "GTF-annotation" track in your screenshot), you can try altering the "display mode," either [in the config](http://jbrowse.org/docs/canvas_features.html) or in the track menu (e.g. below).
![image](https://user-images.githubusercontent.com/25592344/50494061-0d827d00-09ef-11e9-9a7d-40654e21501a.png)

**Comment by shouldsee** [comment]
Thanks. @garrettjstevens I was actually spending 20mins to figure out the default `trackType=JBrowse/View/Track/HTMLFeatures` does not come with this button and had to specify `flatfile-to-json.pl --trackType JBrowse/View/Track/CanvasFeatures`.

It was quite curious that ```--config '
{"category" : "annotation", 
"trackType": "JBrowse/View/Track/CanvasFeatures" 
    }'``` seems to get overridden by --trackType tho...

**Comment by shouldsee** [comment]
@cmdcolin Although the button rescale the view, can I also rescale the actual min-max with some other button?

**Comment by cmdcolin** [comment]
@shouldsee you need to go to "Edit config" and manually edit min_score and max_score paremeters. Note: don't add quotes around the numbers for these

**Comment by cmdcolin** [comment]
In either case, is this feature still strongly needed given the existing alternatives?

**Comment by shouldsee** [comment]
@cmdcolin I was able to hack around this with post-initialization javascript in `index.html`, with an eventDispatch added to the `main.js`. Which means I can create out-of-div buttons to achieve the functionalities at the moment. 

But I definitely would like a "recale quant." button added to adjust the min-max aside from the existing "resize quant".

index.html
```html
    <script type="text/javascript" charset="utf-8">
        setScale = function(t,min = null, max = null) { 
            // / * Set the scale of a quantitative track*/
            /\b(XYPlot|Density)/.test(t.config.type) && (function(){
                min === null || (t.config.min_score =  min);
                max === null || (t.config.max_score =  max);
                t.config.autoscale = "local";
                t.trackHeightChanged = true;
                t.changed();
            }());
        };
        
        window.addEventListener(
            "jb_loaded",function(a){
            console.log(this)
            console.log("fully loaded!");
            var jb = window.JBrowse;
                
            (jb.config.queryParams.quantMin ||
             jb.config.queryParams.quantMax) &&
            (
                min = parseInt(jb.config.queryParams.quantMin) || null,
                max = parseInt(jb.config.queryParams.quantMax) || null,
                window.setTimeout(
                    function(){
                        Array.forEach(
                                jb.view.visibleTracks(),
                                function(t){setScale(t,min,max)}
                            )
                    },1000),
                console.log('adjusted quantitative track height')
            )
        })
    </script>      
```

main.js
```
diff --git a/src/JBrowse/main.js b/src/JBrowse/main.js
index 7f7a014..2265779 100644
--- a/src/JBrowse/main.js
+++ b/src/JBrowse/main.js
@@ -109,7 +109,12 @@ function (
         // create a JBrowse global variable holding the JBrowse instance
         window.JBrowse = new Browser( config );
 
-        window.JBrowse.afterMilestone('loadRefSeqs', function() { dojo.destroy(dojo.byId('LoadingScreen')); });
+        window.JBrowse.afterMilestone('loadRefSeqs', function() { 
+            dojo.destroy(dojo.byId('LoadingScreen')); });
+        window.JBrowse.afterMilestone('completely initialized',function(){
+            var event = new Event('jb_loaded');
+            window.dispatchEvent(event);
+        });
     })
 });

```

**Comment by cmdcolin** [comment]
If this works, then great :)

I would probably suggest using the JBrowse plugin system for this, or, if you think that this change will help other users you can make a pull request to the codebase too.

In any case, I'm glad this could be resolved

**Comment by cmdcolin** [comment]
Btw, that is very clever approach in either case, very cool work :)

**Comment by shouldsee** [comment]
@cmdcolin. I’m complimented :). It was the only way for me with no pervious experience of dojo.
