### ISSUE TITLE
allowCrossOriginDataRoot parameter not set in overall configuration pileup

### ISSUE THREAD

**Issue by ikkextoch** [GMOD/jbrowse#1299]
Hi there,

I want to upgrade my browser from 1.12.3 to jbrowse-1.16.1-release (https://github.com/GMOD/jbrowse/archive/1.16.1-release.zip). I can't seem to set "allowCrossOriginDataRoot = true" with my `jbrowse.conf`. For some unknown reason, the allowCrossOriginDataRoot parameter is not set in the overall configuration pileup, regardless of where I put the statement in my `jbrowse.conf` file.

Without all the comments the conf file I use looks like the one below (alternating the lines between different options):

```
[aboutThisBrowser]
title = My Browser
description = Browser for multiple species
allowCrossOriginDataRoot = true         #Option A

[GENERAL]
plugins += HideTrackLabels
plugins += NeatCanvasFeatures
plugins += NeatHTMLFeatures
plugins += RegexSequenceSearch
plugins += GWASViewer

allowCrossOriginDataRoot = true         #Option B
include  = {dataRoot}/trackList.json
include += {dataRoot}/tracks.conf

[datasets.Species1]
allowCrossOriginDataRoot = true         #Option C
url  = ?data=https://s3.eu-central-1.amazonaws.com/MyBucket1/Species1/data
name = Species1 Genome V1.1

[datasets.Species2]
allowCrossOriginDataRoot = true         #Option C
url  = ?data=https://s3.eu-central-1.amazonaws.com/MyBucket2/Species2/data
name = Species2 Genome V3.1

[datasets.Species3]
url  = ?data=data/Species3/data
name = Species3

[datasets.Species4]
url = ?data=data/Species4/data
name = Species4

[datasets.Species5]
allowCrossOriginDataRoot = true         #Option C
url = ?data=https://s3.eu-central-1.amazonaws.com/MyBucket3/Species5/data
name = Species5 v4.0a1
```

I had high hopes for #Option B, but it didn't work out the way I hoped.

All three options as well as leaving it out entirely result in the error message:

> Error: Invalid JBrowse dataRoot setting. For security, absolute URLs are not allowed. Set `allowCrossOriginDataRoot` to true to disable this security check.

For each option I have unzipped the 1.16.1-release.zip and copied the contents to individual directories, before changing `copyN/jbrowse.conf` given the respective options, after which I ran the `setup.sh` in order to prevent interactions between possibly remaining documents when performing the setup twice in between different options.

When I remove the code from pull #1130 from my Broswer.js file (and keep the `allowCrossOriginDataRoot = true` declaration out), my browser works flawlessly.

**Comment by cmdcolin** [comment]
The allowCrossOriginDataRoot parameter is actually very low level, e.g. before configuration loading even happens, so you have to specify this parameter in index.html or directly in Browser.js

```
diff --git a/index.html b/index.html
index 3e9c6fa..47224ee 100644
--- a/index.html
+++ b/index.html
@@ -34,7 +34,7 @@
   </head>

   <body>
-    <div class="jbrowse" id="GenomeBrowser">
+    <div class="jbrowse" id="GenomeBrowser" data-config='"allowCrossOriginDataRoot": true'>
       <div id="LoadingScreen" style="padding: 50px;">
         <h1>Loading...</h1>
       </div>

```

**Comment by cmdcolin** [comment]
Let me know if that helps, I actually made this part of index.html by default except false, and added docs now sine there were not previously any

**Comment by ikkextoch** [comment]
Yes this works exactly as expected. thank you very much for clarifying this!
