### ISSUE TITLE
Looking for a way to use a plugin which can design PCR primers

### ISSUE THREAD

**Issue by hchintalapudi** [GMOD/jbrowse#1301]
# Creating an issue

If you are creating a new issue please report

- JBrowse version 1.16.1 dev
- Web browser being used Internet explorer
- Operating system if relevant
- If it is setup related, setup.log

Also consider submitting questions via email to gmod-ajax@lists.sourceforge.net as GitHub issues are primarily used for bugs and feature requests

Hi
I'm working on a website update which uses Jbrowse and I want to create a plugin in JBrowse for some FST sequence features which when clicked creates PCR primers for the end user to download.
I looked at some JBrowse blogs and wrote a plugin file which opens a primer design site when user right clicks and selects the primer design option. That's almost as far I could get. I want to know a way to either:
1) make the plugin paste the selected feature sequence into the opened primer design site in the new tab, so that the user can set all the parameters and get the desired primers OR
2) make the plugin  spit out primers to be downloaded upon clicking the 'design primers' option.
I am new to JBrowse and javascript and hence any help or suggestions are sincerely appreciated.

**Comment by cmdcolin** [comment]
You could try https://github.com/jimhu-tamu/hulab-jbrowse/ which contains a PrimerDesigner plugin

Just clone this repo and move the "PrimerDesigner" folder to your plugins directory

Then you can add "plugins": ["PrimerDesigner"] or similar to your config

This plugin is based on highlighting a region of interest

It would be very interesting to get a proper primer designer suite but this plugin could be a stepping stone? Let me know if it helps

**Comment by cmdcolin** [comment]
Note that this has a server side cgi component too so it's a little complex https://github.com/jimhu-tamu/hulab-jbrowse/blob/master/PrimerDesigner/bin/primer-designer.pl

**Comment by hchintalapudi** [comment]
Thanks for the reply.
I installed the plugin and followed the server side instructions too. Every single step. 
But it does not work for some reason. 
The Jbrowse menu shows the option ‘PrimerDesigner’ but when I highlight a gene and click this option, there is no action. Nothing happening. 

Himanshu Chintalapudi

**Comment by cmdcolin** [comment]
I would imagine the server side is misconfigured if it is doing nothing.

I have not set it up before, but I think that's where I would look if it is not doing anything on click. It requests a specific URL path for one thing, so I'd check that that exists :)

**Comment by hchintalapudi** [comment]
I’m glad you are replying.
Yes I made sure everything is correct in the primer-designer.pl file
I made changes that the primer3 binary is in /usr/local/bin 
However my guess is the perl module Bio::PrimerDesigner.pm is not installed properly or the location of installation is different than what is required.
I have never used CPAN shell before but I installed this perl module today in the morning.
But primer-designer.pl file cannot locate this module. 
Where should this .pm module be installed? 
Also when I emailed the author of this plugin (Nathan Liles) he said this plugin is meant for GBrowse and he no longer provides support for this plugin. 

ThAnk you. 

Himanshu Chintalapudi

**Comment by cmdcolin** [comment]
Typically perl modules are installed using cpan e.g. `sudo cpan Bio::PrimerDesigner`

**Comment by hchintalapudi** [comment]
Actually I did that too.
I'm surprised that JBrowse being so popular and there is nobody using such
plugins for PrimerDesign.
I

**Comment by hchintalapudi** [comment]
Yes. I agree. I am aware of that. I in fact tried NCBI Primer blast and Primer3 and liked them very much. I also recognize the save data feature on JBrowse. 
But I am talking about the end users’ experience as I am working on a website that researches of different backgrounds may access. So I was instructed to come up with a solution of a plugin which returns the primers on the same screen rather than saving the sequence and opening another website in another tab and then optimizing the settings to design the primers. I know its just one extra step and not much of a hassle, but I’m talking about a work related task and I have to do what I was told to do. 
This has been frustrating me for weeks now. 
And I’m totally challenged in javascript and know nothing in RESTful APIs. 

Himanshu Chintalapudi

**Comment by hchintalapudi** [comment]
What? Really? 
I would SINCERELY appreciate it Sir.
I am dying to get this done.
Please send me the code.
Thank you so much. 

Himanshu Chintalapudi

**Comment by cmdcolin** [comment]
Here is a list of instructions with my code modifications included on the fork

https://github.com/cmdcolin/JBrowse-PrimerDesigner

As you can see, this was not extremely straightforward but I think it can be done. Download the modified plugin and cgi script from there and try it out. Hope this helps

**Comment by hchintalapudi** [comment]
Sure. I will try it as soon as I reach work tomorrow. I’m working on a virtual machine for this project. So cannot try it right now.
Thank you so much for the help. 

Himanshu Chintalapudi

**Comment by hchintalapudi** [comment]
Also, one more thing. I created the cgi-bin in /usr/lib using sudo mkdir
and gave root permissions to that directory. So should I copy the
primer-designer.pl file to cgi-bin directory or /cgi-bin/bin/ ? I did not
understand Step 7 in your readme file.
Sorry if I'm asking too many questions.
Thanks.

**Comment by cmdcolin** [comment]
In my setup I put it in /usr/lib/cgi-bin/bin/primer-designer.pl and then also created a tmp directory in /usr/lib/cgi-bin/tmp

**Comment by hchintalapudi** [comment]
ok. I did the same. I think you mentioned /usr/bin/cgi-bin/tmp instead of
/usr/lib/cgi-bin/tmp in Step 8. That's why I got confused.

**Comment by hchintalapudi** [comment]
It does not work.
When I added the code to httpd.conf and tried to reboot apache using
apachectl restart command, I get the following error:

Job for httpd.service failed because the control process exited with error
code. See "systemctl status httpd.service" and "journalctl -xe" for details.

**Comment by hchintalapudi** [comment]
Ok. I think the problem is that my httpd.conf file has:

 ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
</IfModule>
#
# "/var/www/cgi-bin" should be changed to whatever your ScriptAliased
# CGI directory exists, if you have that configured.
#
<Directory "/var/www/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>
<IfModule mime_module>

So should I erase this and write your piece of code?
Or should I change these parameters to us/lib/cgi-bin?

**Comment by cmdcolin** [comment]
It doesn't really matter that much where the cgi-bin directory is located. Just make sure that cgi is working with something like "Your first CGI program" from these docs https://httpd.apache.org/docs/2.4/howto/cgi.html#page-header

**Comment by hchintalapudi** [comment]
I tried the cgi perl script (first.pl). On cmd line it gives the output, but not on the browser. 


Himanshu Chintalapudi

**Comment by cmdcolin** [comment]
@hchintalapudi I can't really help setting up CGI on your server, sorry. I documented how I did it but it shouldn't be that hard to find a tutorial for your environment

**Comment by hchintalapudi** [comment]
I understand.
Thank you for your support.
And Sorry for the inconvenience.  

Himanshu Chintalapudi

**Comment by hchintalapudi** [comment]
Hi.
I hope I'm not bugging you too much.
I figured out that my cgi is up and running. But I was having problems with
Bio::PrimerDesigner plugin from the beginning.
I tried to install with sudo yum and CPAN (no apt since my Linux is CentOS,
not Ubuntu) and I am getting errors when running the ./Build test. Same
error with CPAN installation (sudo cpan Bio::PrimerDesigner) too. The error
looks something like this:

  Failed test 'Call to remote server'
at t/remote.t line 20.
Looks like you failed 1 test of 5.

Test Summary Report
-------------------
t/remote.t         (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
Files=8, Tests=72,  1 wallclock secs ( 0.04 usr  0.02 sys +  0.64 cusr
0.11
csy
s =  0.81 CPU)
Result: FAIL
Failed 1/8 test programs. 1/72 subtests failed.

I just want to know if you faced any similar errors while installing
Bio:PrimerDesigner.pm module.
Because, I think in my case this could be the reason why PrimerDesigner is
not working on JBrowse.

Thank you.

**Comment by cmdcolin** [comment]
Sorry I'll close this for now. If there are questions please refer to the plugin issues

**Comment by hchintalapudi** [comment]
Hi Colin.
I talked to my supervisor and have the official access to share my screen to show my issues via  go to meeting. I am supposed to talk via conference where one or two members of my team are also present just to monitor my activity.
I’m just waiting to co-ordinate a perfect time.

Thanks.

Himanshu Chintalapudi

**Comment by hchintalapudi** [comment]
Sure. Thanks

Himanshu Chintalapudi
