### ISSUE TITLE
Unable to fetch BAM -  incorrect header check

### ISSUE THREAD

**Issue by niccw** [GMOD/jbrowse#1305]
I am using Apache on CentOS and have already disabled the mime_magic module according to the [http://gmod.org/wiki/JBrowse_Configuration_Guide#Apache_Configuration_Note](http://gmod.org/wiki/JBrowse_Configuration_Guide#Apache_Configuration_Note).
(I commented the `LoadModule mime_magic_module ...` and restarted apache, am I missing something?)

ps: I also tested the same set of data and tracks.conf on Ubuntu and everything works fine.

![image](https://user-images.githubusercontent.com/18115638/51611703-30398000-1f20-11e9-8a62-8b962f3959ac.png)

Thanks!
Nicola

**Comment by cmdcolin** [comment]
You may be on the right track with disabling mime_magic. That think that error is basically a newer version of the "Not a BAM file" error that is cited there

I guess I would make sure that the module is disabled completely, maybe run `sudo a2dismod mime_magic` and restart apache, clear cache in webbrowser, etc.

**Comment by niccw** [comment]
Thanks!  I forgot to clear cache. After clearing cache it works perfectly now.

**Comment by cmdcolin** [comment]
Awesome, good to hear :)
