### ISSUE TITLE
Dragging the view beyond the edge of the chromosome

### ISSUE THREAD

**Issue by ikkextoch** [GMOD/jbrowse#1308]
Hey guys,

My colleague just noticed that roughly since JBrowse version 12 it is possible to view beyond the scope of the loaded chromosome. We can do this by displaying the right edge of a chromosome, and then manually dragging the track pane from right to left. Zooming out to view the entire chromosome, by using the zoom buttons, and subsequently dragging the track pane to the left makes it possible to view as far as up to at least 5 times the size of the loaded chromosome.

Are other people able to reproduce this?

Cheers,
dvdleest

**Comment by cmdcolin** [comment]
I've seen this bug where there is a type confusion in refseqs.json and it has the length of the chromosome being a string instead of a numeric. Does that look possible? I think the bug is fixed but some older data directories might be have that issue

**Comment by cmdcolin** [comment]
Any update? It could possibly be prevented against by providing extra back compatibility but I think re-running prepare-refseqs would fix :) Let me know if there are any other issues

**Comment by ikkextoch** [comment]
The reference that we're using is stored in an indexed fasta file which is included in the trackList.json as follows:
```
      ...
      {
         "seqType" : "dna",
         "key" : "Reference sequence",
         "useAsRefSeqStore" : 1,
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "urlTemplate" : "seq/AsparagusCHR_V1.1.fa",
         "showForwardStrand": true,
         "showColor": true,
         "compress" : 1,
         "label" : "DNA",
         "type" : "SequenceTrack",
         "category" : "Reference sequence",
         "faiUrlTemplate" : "seq/AsparagusCHR_V1.1.fa.fai"
      },
      ...
```

So prepare-refseqs wasn't used to visualize the sequence.

**Comment by cmdcolin** [comment]
Can you report the actual version of jbrowse you are using

Note that JBrowse 1.15.1 introduced a bugfix "Fix bug where prepare-refseqs with indexed FASTA would allows scrolling past the end of the chromosome (@cmdcolin)."
