### ISSUE TITLE
Saving HTMLVariants track to GFF3

### ISSUE THREAD

**Issue by dionnezaal** [GMOD/jbrowse#1309]
We were very excited to see the fix for exporting to GFF3 in the latest version of JBrowse (1.16.2). It works perfectly with the CanvasFeatures track. Thank you!

We were also happy to see that we could now save HTMLVariants tracks to GFF3 files. We only found a small bug. The annotation column of the GFF3 does contain some fields like description, reference_allele, name which are exported correctly, but some fields like alternative_alleles are exported as the following: 

```
alternative_alleles=[object Object];
```

**Comment by cmdcolin** [comment]
Thanks for reporting, that can be verified. Some aspects of this can be verified far back even to much older versions, I saw this in 1.12.5 for example. We'll take  a look at it. In some sense it would be nice to simply get VCF export back also, is that something of interest?

**Comment by cmdcolin** [comment]
I created a workaround that simply dumps json into the value field. This is a little weird by gff standards but gff doesn't seem to have a notion of nested values so that seemed reasonable.

We'll keep VCF export on the horizon but hopefully this helps somewhat
