### ISSUE TITLE
perl5 modules missing in linux desktop version 1.16.2

### ISSUE THREAD

**Issue by surh** [GMOD/jbrowse#1312]
After unzipping the JBrowse-1.16.2-desktop-linux-x64.zip release, I cannot run the perl utilities in the bin directory because the src/perl5/ directory is empty.

**Comment by cmdcolin** [comment]
The desktop version is basically designed so that you do not need to use any perl scripts, you can do stuff in the user interface. I think that is why they are not there. Does that make sense or are you still trying to use the perl scripts with the desktop version?

**Comment by surh** [comment]
Well, I am able to format the data myself and use the desktop version, but I thought it would be nice to have the perl scripts available and integrate them in my workflow. That way, if something fails in the future, it is probably not due to some silly formatting error I made.

It is just a suggestion, I can always get the perl5 modules manually from the github repo.

Keep up the great work!

**Comment by cmdcolin** [comment]
Thanks. I guess the general idea was to try to allow users to open files directly with the "Open track" things inside the GUI but it's really true that having the perl tools helps in some cases. I guess if you have your workflow figured out that is good, it may be hard to make this generic enough for everyone especially in a cross platform way.

Note you can use this command to install JBrowse commands and dependencies separate from jbrowse itself.

cpanm https://github.com/gmod/jbrowse.git

This is not really a good substitute for the JBrowse code not being on cpan, but does make it easily installable.

**Comment by cmdcolin** [comment]
If it's ok, I will close this for now as it will likely not change. Let us know if there is any more feedback!
