### ISSUE TITLE
Installation error on Ubuntu 18.04

### ISSUE THREAD

**Issue by royfrancis** [GMOD/jbrowse#1313]
I get the following error when installing.

```
$./setup.sh

Gathering system information ...done.
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
Installing node.js dependencies and building with webpack ...done.
Installing Perl prerequisites ... failed.  See setup.log file for error messages. As a first troubleshooting step, make sure development libraries and header files for GD, Zlib, and libpng are installed and try again.

Formatting Volvox example data ... failed.  See setup.log file for error messages.

Formatting Yeast example data ... failed.  See setup.log file for error messages.
```

Tried to install additional packages as suggested [here](http://gmod.org/wiki/JBrowse_Troubleshooting). Now it's another error.

```
sudo apt-get install build-essential libpng-dev zlib1g-dev libgd2-xpm-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgd2-xpm-dev
```

[Here](https://bugs.launchpad.net/ubuntu/+source/fceux/+bug/1779613), it is suggested that `libgd2-xpm-dev` is deprecated and `libgd-dev` may be used instead. But, installing that doesn't fix the issue.

jbrowse-1.16.2-release
Ubuntu 18.04
I have added [this plugin](https://github.com/cmdcolin/mafviewer) in the plugins directory. Not sure if that matters.

**Comment by cmdcolin** [comment]
See #1310 bioperl made a big change to their system. I would recommend manually installing bioperl like this

```
rm -rf extlib
bin/cpanm -v --notest -l extlib/ Bio::Perl@1.7.2
./setup.sh
```

That will get the last working bioperl version

We're working to release a new jbrowse with proper fixes

**Comment by royfrancis** [comment]
That worked! Thanks.
