### ISSUE TITLE
strange behaviour related to CORS when loading BAM files

### ISSUE THREAD

**Issue by trstickland** [GMOD/jbrowse#1315]
I noticed strange behaviour when loading a BAM file ("Open track file or URL", providing URL for .bam and .bai files).

I has an error in the URL for the .bai file, which would be expected to result in a 404.   However I saw a CORS error message in the console:  _blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present_    Either one of these errors would be plausible enough, but seeing both struck me as rather odd.

Digging deeper there was a request getting a 404 followed by the CORS error message.  I'm guessing the 404 was a response to the CORS preflight???

In the event of preflight fail, does jBrowse perhaps follow up with an attempt to do a "normal" HTTP request -- assuming perhaps that preflight fails because there's no CORS support on the server, but a regular HTTP GET might just work..?      Pure guesswork on my part, but it would explain why I see a 404 followed by a CORS error saying the request had been blocked.

This is pretty obscure and may not warrant attention (one way or another my attempt to load a non-existent file was going to fail anyway) but I thought I'd raise it for information/discussion

**Comment by cmdcolin** [comment]
There are some circumstances where JBrowse avoids performing a preflight request, which helped JBrowse acccess some files using rawgit historically, but in general, if preflight is failing, then the CORS setup of the server is probably going to be problematic for JBrowse in some other way. For example, it needs to have the preflight to succeed in order to do byte-range requests. So re-requesting without preflight is probably going to be of limited use. I would check out your cors setup if possible if the server is in your control (of course, with cors it is not always in your control). If you have a link to a file that causes this error let me know

**Comment by cmdcolin** [comment]
Note: The code for avoiding preflight in JBrowse currently is adding "X-Requested-With": null to headers

**Comment by cmdcolin** [comment]
Also note: it does help to report jbrowse version and info such things to us even if it is a general inquiry

**Comment by trstickland** [comment]
Sorry, this is 1.16.2

The problem can be recreated by simply taking a working URL and changing the file name to something that doesn't exist; the actual example was attempting to load
https://ngs.sanger.ac.uk/production/pathogens/Plasmodium/berghei/K173/K173.sorted.markdup.bam and https://ngs.sanger.ac.uk/production/pathogens/Plasmodium/berghei/K173/K173.sorted.markdup.bam.bai
(the latter doesn't exist, as the file is "wrongly" named K173.sorted.bam.bai)

I was trying to figure out why a CORS error appears in the browser console, when the preflight gets a 404 response...

![jbrowse](https://user-images.githubusercontent.com/33544033/53095934-e7241e00-3515-11e9-9bd6-df740a03c521.png)

As I said, this was always going to fail -- the file doesn't exist!   It's just curious that a 404 ends up triggering a CORS error message.

It's worth being aware of, anyway -- to avoid going down the route of looking for CORS configuration errors when it's something far simpler :-/

**Comment by cmdcolin** [comment]
This is actually pretty common for the server side to return a CORS configuration error when you request the wrong file. I think we'll close this for now :) will keep this in mind though...
