### ISSUE TITLE
Searching for annotation id names failed

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1316]
Hi,
I use Jbrowse within Apollo 2.3.1. Unfortunately, I am not able to find gene Ids with this method 
![screen shot 2019-02-21 at 12 48 51 pm](https://user-images.githubusercontent.com/588297/53140853-c2917a00-35d9-11e9-90e9-a7ef4b25a33b.png)

And I also tried to search within Jbrowse's tracks panel but it did not work and it didn't show me how many fereatues each track has.

![screen shot 2019-02-21 at 12 59 04 pm](https://user-images.githubusercontent.com/588297/53140926-04babb80-35da-11e9-935f-06b123c025ee.png)

Furthermore, I tried to use Jbrowse's `Search Features` but no results have been found:

![screen shot 2019-02-21 at 11 13 54 am](https://user-images.githubusercontent.com/588297/53136183-d3d28a80-35c9-11e9-809d-f9e877a25604.png)

I loaded the data in the following way:
```
cd ~/Apollo-2.3.0/jbrowse/bin
perl prepare-refseqs.pl --fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
perl prepare-refseqs.pl --indexed_fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
perl flatfile-to-json.pl --gff /data/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019"
perl generate-names.pl --verbose --out /data/apollo/
```

What did I miss?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Do you have a sample of the GFF?

One thing that might be relevant is that you are searching for transcript IDs but you have loaded gene level features. In this case JBrowse actually only indexes the top level feature e.g. the gene ID rather than all the transcript IDs

I guess this is not documented very well but you'd need to create some separate track in order to index the transcript level names

**Comment by cmdcolin** [comment]
Note: the separate track that I refer to above could be created using the following

```
perl flatfile-to-json.pl --gff /data/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019_mRNAs" --type mRNA
perl generate-names.pl --verbose --out /data/apollo/
```

That would load mRNA features and then re-running generate-names would index them

**Comment by mictadlo** [comment]
Please find below few lines of my GFF3 file:

```
##gff-version 3
NbV1Ch01        NbGenome        gene    98177   99675   .       -       .       ID=Nb3PK39646.path1;Name=Peroxidase 40
NbV1Ch01        NbGenome        mRNA    98177   99675   .       -       .       ID=Nb3PK39646.mrna1;Parent=Nb3PK39646.path1;Name=Nb3PK39646;coverage=99.8;identity=99.9;matches=1011;mismatches=1;indels=0;unknowns=0
NbV1Ch01        NbGenome        exon    98177   98571   100     -       .       ID=Nb3PK39646.mrna1.exon4;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 620 1014 +
NbV1Ch01        NbGenome        CDS     98177   98571   100     -       2       ID=Nb3PK39646.mrna1.cds4;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 620 1014 +
NbV1Ch01        NbGenome        exon    98679   98844   100     -       .       ID=Nb3PK39646.mrna1.exon3;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 454 619 +
NbV1Ch01        NbGenome        CDS     98679   98844   100     -       0       ID=Nb3PK39646.mrna1.cds3;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 454 619 +
NbV1Ch01        NbGenome        exon    99134   99325   99      -       .       ID=Nb3PK39646.mrna1.exon2;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 262 453 +
NbV1Ch01        NbGenome        CDS     99134   99325   99      -       0       ID=Nb3PK39646.mrna1.cds2;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 262 453 +
NbV1Ch01        NbGenome        CDS     99417   99674   100     -       0       ID=Nb3PK39646.mrna1.cds1;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 4 261 +
NbV1Ch01        NbGenome        exon    99417   99675   100     -       .       ID=Nb3PK39646.mrna1.exon1;Parent=Nb3PK39646.mrna1;Name=Nb3PK39646;Target=Nb3PK39646 3 261 +
###
NbV1Ch01        NbGenome        gene    783759  784058  .       -       .       ID=Nb3PK18592.path1;Name=NA
NbV1Ch01        NbGenome        mRNA    783759  784058  .       -       .       ID=Nb3PK18592.mrna1;Parent=Nb3PK18592.path1;Name=Nb3PK18592;coverage=100.0;identity=100.0;matches=300;mismatches=0;indels=0;unknowns=0
...
```
Should I use `--type mRNA` or `--type gene`?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Try --type mRNA

**Comment by mictadlo** [comment]
Hi,
I tried what you suggested but now no tracks can be selected within Apollo:
```
ubuntu@ip-10-23-2-113:/data/apollo$ rm -r seq test.fasta test.results trackList.json tracks tracks.conf 
ubuntu@ip-10-23-2-113:/data/apollo$ cd ~/Apollo-2.3.0/jbrowse/bin
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl prepare-refseqs.pl --fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl prepare-refseqs.pl --indexed_fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl flatfile-to-json.pl --gff /data/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019"
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl flatfile-to-json.pl --gff /data/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019_mRNAs" --type mRNA
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl prepare-refseqs.pl --fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
```

What did I miss?

Michal

**Comment by cmdcolin** [comment]
Can you clarify what you mean by no tracks are selectable?
Also
You don't need to run prepare-refseqs.pl more than once
And
You didn't rerun generate-names.pl (maybe you ran prepare-refseqs accidentally instead?)

**Comment by mictadlo** [comment]
I deleted all the input files and started from scratch with those commands:

```
/data/apollo$ rm -r seq test.fasta test.results trackList.json tracks tracks.conf 
ubuntu@ip-10-23-2-113:/data/apollo$ cd ~/Apollo-2.3.0/jbrowse/bin
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl prepare-refseqs.pl --fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl prepare-refseqs.pl --indexed_fasta /data/apollo/NbV1ChF.fasta --out /data/apollo/
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl flatfile-to-json.pl --gff /data/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019"
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl flatfile-to-json.pl --gff /data/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019_mRNAs" --type mRNA
ubuntu@ip-10-23-2-113:~/Apollo-2.3.0/jbrowse/bin$ perl generate-names.pl --verbose --out /data/apollo/
Tracks:
    DNA
WARNING: No feature names found for indexing, only reference sequence names will be indexed.
Sampled input stats:
                     total namerec bytes 399
                       namerecs buffered 19
           record stream estimated count 0
        namerecs converted to operations 19
                   avg record text bytes 21
        operation stream estimated count 0
                      name input records 19
                         operations made 152
                       total input bytes 0
Removing existing contents of target dir /data/apollo/names
Hash store cache size: 2684 buckets
Using 1 chars for sort log names (16 sort logs)

Tracks:
    DNA
WARNING: No feature names found for indexing, only reference sequence names will be indexed.
Sampled input stats:
                     total namerec bytes 399
                       namerecs buffered 19
           record stream estimated count 0
        namerecs converted to operations 19
                   avg record text bytes 21
        operation stream estimated count 0
                      name input records 19
                         operations made 152
                       total input bytes 0
Removing existing contents of target dir /data/apollo/names
Hash store cache size: 2684 buckets
Using 1 chars for sort log names (16 sort logs)
```
No tracks apper here anymore:
![screen shot 2019-02-22 at 8 12 53 am](https://user-images.githubusercontent.com/588297/53205578-6c284800-367a-11e9-9014-b6c1870759cb.png)

What did I miss?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Your flatfile-to-json commands should include `--out /data/apollo/` on them

**Comment by mictadlo** [comment]
Thank you. The missing `--out /data/apollo/` caused the problem.

**Comment by bioinfx** [comment]
12 | # 生成 ./data/names/usr/bin/perl bin/generate-names.pl
-- | --

**Comment by bioinfx** [comment]
generate-names.pl
This script builds indexes of features by label (the visible name below a feature in JBrowse) and/or by alias (a secondary name that is not visible in the web browser, but may be present in the JSON used by JBrowse).

To search for a term, type it in the autocompleting text box at the top of the JBrowse window.

Basic syntax:

bin/generate-names.pl [options]
Note that generate-names.pl does not require any arguments. However, some options are available:

**Comment by terrymun** [comment]
> One thing that might be relevant is that you are searching for transcript IDs but you have loaded gene level features. In this case JBrowse actually only indexes the top level feature e.g. the gene ID rather than all the transcript IDs
> 
> I guess this is not documented very well but you'd need to create some separate track in order to index the transcript level names

@cmdcolin Just a suggestion: would it make sense to add this to the [`generate-names.pl` documentation](https://jbrowse.org/docs/generate-names.pl.html)? It took me awhile to figure out why individual subfeature IDs are not searchable :) the text in the documentation threw me off a little bit, because it says (emphasis my own):

> By default, the Name, ID, and Alias fields, **for all feature types** (gene, mRNA, CDs, exon, etc.), are indexed by generate-names.pl

...which gives the impression that all subfeature fields are also automatically indexed, instead of only top-level like you've mentioned.

**Comment by cmdcolin** [comment]
this is a good point, it should be clarified in the docs probably. It would be a somewhat better behavior for it to index some subfeatures e.g. transcripts of a gene but that is indeed not the behavior now

**Comment by terrymun** [comment]
@cmdcolin Probably an off-topic comment (respective to this issue), but it will be nice to have subfeature level indexing. I understand that this can potentially be computationally expensive if there are multiple levels of subfeatures (with one-to-many relationships).

Perhaps a meaningful approach will be to stick to the default, i.e. only index top-level features (depth=1), and then offer a new setting that allows us to specify the depth of subfeature indexing (depth=n), if this is to be implemented ;) just my 2 cents of course.

**Comment by cmdcolin** [comment]
If needed to get that functionality "today" I'd load the track with --type mRNA (instead of at the gene level, load at the transcript level for example) and then run generate-names and optionally then delete that track. Not very nice but could be a stop gap solution

We're working on the name indexing for jbrowse 2 now and will definitely keep this in mind there also...
