### ISSUE TITLE
Blat search results in a panel

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1317]
Hi,
The Blat search is very nice but it would be good if search results would be in a panel.  The current popup is blocking to analyse hits.

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
The Blat search results are an apollo feature, not JBrowse :)

It requires a server backend in order to perform the search which is why it is this way

**Comment by mictadlo** [comment]
Thank you for the information and I posted it here https://github.com/GMOD/Apollo/issues/2066
