### ISSUE TITLE
BigWig file caused: An error was encountered when displaying this track

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1318]
Hi,
I loaded BigWig files in the following way:

```
~/Apollo/jbrowse/bin$ perl add-bw-track.pl --bw_url /data/apollo/DT_Wlp2.bw --plot --label "DT_Wlp2.bw" --in /data/apollo/trackList.json
```
```
cat trackList.json 
...
{
   "urlTemplate" : "/data/apollo/DT_Wlp2.bw",
   "type" : "JBrowse/View/Track/Wiggle/XYPlot",
   "autoscale" : "local",
   "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
   "label" : "DT_Wlp2.bw",
   "bicolor_pivot" : "zero",
   "key" : "DT_Wlp2.bw"
}
```

Which caused the following problem:
![screen shot 2019-02-26 at 12 22 10 pm](https://user-images.githubusercontent.com/588297/53382885-66579d00-39c1-11e9-95f5-a83e912ddff2.png)

What did I miss?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Try with just --bw_url DT_Wlp2.bw

The reason is that this argument is actually treated as a url which by  relative to the data directory itself, not an actual file path

**Comment by mictadlo** [comment]
Thank you it works.
