### ISSUE TITLE
flatfile-to-json caused few warnings for bed files

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1323]
Hi,
During loading of bed files from MACS2 few warnings appeared with `flatfile-to-json`:

```
perl /home/ubuntu/Apollo/jbrowse/bin/flatfile-to-json.pl --bed LabK4.bed --compress --trackType CanvasFeatures --trackLabel "LabK4.bed" --out /efs/apollo/
expected 8 blocks, got 0 lengths and 0 offsets for feature MACS2_peak_1 at /home/ubuntu/Apollo/jbrowse/bin/../src/perl5/Bio/FeatureIO/bed.pm line 320, <GEN0> line 1.
expected 646 blocks, got 0 lengths and 0 offsets for feature MACS2_peak_2 at /home/ubuntu/Apollo/jbrowse/bin/../src/perl5/Bio/FeatureIO/bed.pm line 320, <GEN0> line 2.
...
expected 5 blocks, got 0 lengths and 0 offsets for feature MACS2_peak_1338 at /home/ubuntu/Apollo/jbrowse/bin/../src/perl5/Bio/FeatureIO/bed.pm line 320, <GEN0> line 1338.

--------------------- WARNING ---------------------
MSG: Bio::SeqFeature::Generic=HASH(0x5555b391c648) is not contained within parent feature, and expansion is not valid, ignoring.
---------------------------------------------------
expected 166 blocks, got 0 lengths and 0 offsets for feature MACS2_peak_1340 at /home/ubuntu/Apollo/jbrowse/bin/../src/perl5/Bio/FeatureIO/bed.pm line 320, <GEN0> line 1340.
```

What did I miss?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
If you have sample data it would help :)

**Comment by cmdcolin** [comment]
I checked this file that you sent via email and I ran the same command locally and it produced no warnings and the track loaded fine :)

**Comment by mictadlo** [comment]
What else could cause the problems?

**Comment by cmdcolin** [comment]
Is there any indication that there is a problem rather than just warning? The difference between my setup and your setup could be just sort of unimportant if there is no problem in your resulting files.

**Comment by cmdcolin** [comment]
The alternative to using flatfile-to-json is to read this directly. This jbrowse plugin can parse narrowpeak files directly from a tabixed version of them https://github.com/cmdcolin/narrowpeak


I think the files that macs2 outputs are often narrowpeak files so you could use this plugin

**Comment by cmdcolin** [comment]
Closing for now
