### ISSUE TITLE
TypeError: Cannot read property 'search' of undefined on the web page.

### ISSUE THREAD

**Issue by harika91** [GMOD/jbrowse#1325]
- JBrowse version - 1.16.3 and 1.12.4
- Chrome
- It is set up related. 

Steps followed to upgrade:
Current version of jbrowse is 1.12.3
Removed comments for sample data tracks on jbrowse.conf file.
Ran setup.sh file.

Error on Jbrowse page on the browser(jbrowse/index.html?data=sample_data/json/volvox) after installing using setup.sh

Browser.js:428 TypeError: Cannot read property 'search' of undefined
    at Object._setLabelAttr (MenuItem.js:38)
    at Object.set (_WidgetBase.js:843)
    at Object._applyAttributes (_WidgetBase.js:505)
    at Object.inherited (declare.js:214)
    at Object._applyAttributes (_CssStateMixin.js:64)
    at Object.create (_WidgetBase.js:437)
    at Object.postscript (_WidgetBase.js:366)
    at new <anonymous> (declare.js:432)
    at Object.renderDatasetSelect (Browser.js:1067)
    at Object.<anonymous> (Browser.js:797)

**Comment by cmdcolin** [comment]
You are referring to 3 different jbrowse versions and it's sort of unclear what your actual setup is, can you provide more detail please

**Comment by harika91** [comment]
I am trying to install 1.16.3. It failed and i tried 1.12.4 as well. Both gave same error.
First i got the Jbrowse zip file from https://github.com/GMOD/jbrowse/archive/1.16.3-release.zip
unzipped it. I changed the jbrowse.conf file by removing comments on the sample data tracks.
Then i ran setup.sh script. It ran successfully. 
But when i open the sample_data track it shows the below error

![error](https://user-images.githubusercontent.com/33872527/53811067-17a88680-3f1e-11e9-9834-ad982028b363.PNG)

**Comment by cmdcolin** [comment]
If you uncomment the lines in jbrowse.conf for the sample datasets then you would end up with this

```
[datasets.volvox]
url  = ?data=sample_data/json/volvox
name = Volvox Example
[datasets.modencode]
url  = ?data=sample_data/json/modencode
name = MODEncode Example
[datasets.yeast]
url  = ?data=sample_data/json/yeast
name = Yeast Example            
```                                                

For me this works fine
Do you want to attach your jbrowse.conf file

**Comment by harika91** [comment]
I have done the same.
[jbrowse.txt](https://github.com/GMOD/jbrowse/files/2931559/jbrowse.txt)

**Comment by cmdcolin** [comment]
Your file contains a space at the start of each of those line for those config lines. The parser for the conf file format is pretty sensitive and probably is getting confused by that

**Comment by harika91** [comment]
Thank you. It worked now.

**Comment by harika91** [comment]
One more question. I have a plugin to be copied to plugins. I have added it to the jbrowse.conf file.
I ran the setup.sh script. But i see an error on the page 

could not load plugin RGDcollapseTracks: not-a-module

Did i miss anything?

**Comment by cmdcolin** [comment]
Your plugins should be written as modules so if you are just importing some plain js file it probably won't work. I don't have your source code. Alternatively you could use the collapsedCategories configuration instead of this plugin. This configuration might not have been available when you made this plugin

Example

```
[trackSelector]
collapsedCategories=Category 1,Category 2
```

**Comment by harika91** [comment]
Thanks. It worked
