### ISSUE TITLE
VCF files fetch failed

### ISSUE THREAD

**Issue by DuraSnow** [GMOD/jbrowse#1331]
some problem like this

<img width="930" alt="屏幕快照 2019-03-11 10 16 35" src="https://user-images.githubusercontent.com/14949151/54096421-c4837780-43e6-11e9-88af-9ca0580dd3c4.png">

**Comment by cmdcolin** [comment]
This is generally due to your server returning an incorrect response, here it is a http 200 response when it should be a http 206 for the range request. What server are you using?

**Comment by cmdcolin** [comment]
Hi @DuraSnow I think this is basically a server configuration issue. If you would like to get any troubleshooting please comment back but since it is not a bug I'll close for now
