### ISSUE TITLE
Refactoring into modern source codes

### ISSUE THREAD

**Issue by kaorun343** [GMOD/jbrowse#1333]
If you're interested in to refactor the source codes into modern codes, I'd like to try this.

* Use ES2015+ features (i.e. ES6 class, let/const, arrow function)
* Use ES2015 module system instead of AMD

**Comment by cmdcolin** [comment]
before addressing any topic like this, is this for Google Summer of Code or for what purpose?

**Comment by kaorun343** [comment]
This is not for any contests.

The reason why I suggested this is that this repository's code size is so huge and deeply depends on dojo. IMHO, at least, the domain layer should not be depend on a specific library.  Also, as new syntaxes / features of JavaScript are provided, especially the new module system, it's good to apply them into this repository, I thought.

Of course, I really understand that this suggestion doesn't provide any values for users,  such as bugs or new features.
If you're not interested in this, please close this.

**Comment by cmdcolin** [comment]
No worries, I just wanted to make sure you had a chance to make your position available. But indeed we are not interested in radically changing anything on the jbrowse 1 codebase. 

Instead we are now developing jbrowse 2 in this repo https://github.com/GMOD/jbrowse-components  and this is written using lots of modern js features

Note that jbrowse 1 does use dojo-webpack-plugin with babel and such so modernized javascript can be used in this repo, it's just the bulk of our modernization will happen on jbrowse-components repo

**Comment by cmdcolin** [comment]
Also see our data adapters e.g. https://github.com/GMOD/cram-js

I welcome you to stay involved but I guess I'll close for now!

**Comment by kaorun343** [comment]
Thanks for your explanation!
I'll check the new repository.
