### ISSUE TITLE
variable speed of generate-names on similar GFF3Tabix files

### ISSUE THREAD

**Issue by tougai** [GMOD/jbrowse#1334]
# Creating an issue

If you are creating a new issue please report

- JBrowse version
- Web browser being used
- Operating system if relevant
- If it is setup related, setup.log

Also consider submitting questions via email to gmod-ajax@lists.sourceforge.net as GitHub issues are primarily used for bugs and feature requests

**Comment by tougai** [comment]
i've sent an email to mailing list instead

**Comment by cmdcolin** [comment]
This could be relevant https://github.com/GMOD/jbrowse/issues/1326

Note that the mailing list messages are added to a spam queue that needs moderation (not under my control currently) so your message might get lost
