### ISSUE TITLE
generate-names.pl does not work with {refseq} in urlTemplate

### ISSUE THREAD

**Issue by FredericBGA** [GMOD/jbrowse#1335]
generate-names.pl fails to create an index when the storeClass is not `NCList` (formated with flatfile-to-json.pl)  and when data are splited in chromosomes files.

I set up two tracks, with same data, one with all data in one single VFC file. The other has its data in one file per chromosome. I then use {refseq} in the urlTemplate.

It works well on JBrowse interface.

But when I try to index the data, it fails `VCF file './../vcf/sample-{refseq}.vcf.gz' not found, or not readable. Skipping.` as `refseq` is not replaced by any value...
The full log:
> /softs/bioinfo/jbrowse/bin/generate-names.pl -out . --compress --incremental --verbose
> Tracks:
>     ONE
>     TEN
>     refseqs
> VCF file './../vcf/sample-{refseq}.vcf.gz' not found, or not readable.  Skipping.
> Sampled input stats:
>                    avg record text bytes 95.8648648648649
>                       name input records 37
>         operation stream estimated count 385
>            record stream estimated count 55
>                      total namerec bytes 3547
>                        total input bytes 5336
>                          operations made 278
>                        namerecs buffered 37
>         namerecs converted to operations 37
> Hash store cache size: 2684 buckets
> Using 1 chars for sort log names (16 sort logs)

my configuration file:
>       {
>          "compress" : 1,
>          "key" : "ONE",
>          "label" : "ONE",
>          "metadata" : {
>             "description" : "TEST one vcf. 12-03-2019"
>          },
>          "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
>          "style" : {
>             "className" : "feature"
>          },
>          "type" : "JBrowse/View/Track/CanvasVariants",
>          "urlTemplate" : "../vcf/ONE.sort.vcf.gz"
>       },
>       {
>          "compress" : 1,
>          "key" : "TEN",
>          "label" : "TEN",
>          "metadata" : {
>             "description" : "TEST ten vcf. 12-03-2019"
>          },
>          "storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
>          "style" : {
>             "className" : "feature"
>          },
>          "type" : "JBrowse/View/Track/CanvasVariants",
>          "urlTemplate" : "../vcf/sample-{refseq}.vcf.gz"
>       }

**Comment by cmdcolin** [comment]
One workaround would be to create a combined vcf tabix track for the generate-names.pl purpose with same track label but then change back to using the {refseq} urlTemplate at runtime.

**Comment by FredericBGA** [comment]
> One workaround would be to create a combined vcf tabix track
How can I do that? could you help me? I only find details on combination tracks from the menu bar on the interface.

**Comment by cmdcolin** [comment]
I mean to concatenate all VCF files (I think you can even just concatenate the literal .vcf.gz files) and use the resulting file in your indexing.

    cat *.vcf.gz > combined.vcf.gz

Then set urlTemplate to combined.vcf.gz temporarily, and then you can delete the combined.vcf.gz and change urlTemplate back

**Comment by cmdcolin** [comment]
I will probably close this for now. There are quite a few instances like this that could be considered bugs but that would be hard to fix currently. For example urlTemplate can be a remote file, and generate-names does not handle that either. In any case, please comment back if you have any other issues
