### ISSUE TITLE
is it possible to change data and attributes of a track

### ISSUE THREAD

**Issue by julianabc29** [GMOD/jbrowse#1344]
# is it possible to change data and attributes of a track

Hi, I am using JBrowse and I am uploading Canvas features tracks from a gff3 format. when I do click on the track, I can see the whole information

![color](https://user-images.githubusercontent.com/41842945/54787171-ea83f580-4bf8-11e9-99f6-98f2a59115a0.png)

I want to know if, is it possible to change that information, eg: I want to add information about the protein: reaction, pathway, etc .. To try to connect the gene -ARN-protein and protein (enzyme) reaction-pathway.
I hope I have explained everything clearly 
Thanks

**Comment by cmdcolin** [comment]
@julianabc29 You can add this information directly to the GFF3 column 9 as metadata attributes possibly. That would be easiest probably.
