### ISSUE TITLE
splicing the mRNA and translating the spliced sequences into the amino acid sequence

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1349]
Hi, 
It is probably well explained in the manual, and apologies for this request, but we are having trouble locating some information. Our Apollo instance displays the gene structure (exons and introns) in our annotation track and when a gene is “right mouse clicked” a pop-up box is displayed showing “Region Sequence” and when the  “show subfeatures” button is clicked it displays a pop-up with “mRNA sequence” and individual boxes of the exon sequences. Unfortunately, the mRNA sequence appears to be the unspliced “region sequence” and neither this nor the individual exon sequences are translated. Can you please tell us where we turn on and control features such as splicing the mRNA and translating the spliced sequences into the amino acid sequence?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
There are currently plugins that implement this functionality, see https://github.com/twsaari/FeatureSequence

**Comment by mictadlo** [comment]
Thank you @cmdcolin for pointing me to this plugin. Unfortunately, when I do a right-click menu option to launch FeatureSequence on my annotation track it does not launch the actual plugin. 

I did the following steps:
```
~/Apollo/jbrowse/plugins$ git clone https://github.com/tsaari88/FeatureSequence

~/Apollo/jbrowse$ vim jbrowse_conf.json
// top-level JBrowse configuration file.  Treated the same as
// jbrowse.conf, but this one is in JSON format.
//
// Unless generating configuration from scripts, most users will
// prefer to add variables to jbrowse.conf instead of this file, since
// jbrowse.conf is much easier to hand-edit.
{
"plugins": [ "FeatureSequence" ],
}

/efs/apollo$ vim trackList.json

{
   "category" : "Annotations",
   "compress" : 1,
   "key" : "NbanotFeb2019v7",
   "label" : "NbanotFeb2019v7",
   "storeClass" : "JBrowse/Store/SeqFeature/NCList",
   "trackType" : "HTMLFeatures",
   "type" : "HTMLFeatures",
   "urlTemplate" : "tracks/NbanotFeb2019v7/{refseq}/trackData.jsonz",
   "menuTemplate" : [
      {},
      {},
      {
         "content" : "function(track,feature){return track.browser.plugins.FeatureSequence.callFxn(track, feature); }",
         "label" : "View Feature Sequence",
         "action" : "contentDialog",
         "iconClass" : "dijitIconBookmark"
      }
   ]

}
```
I do not know whether I have to restart Apollo or am I missing anything?

Could @cmdcolin and @twsaari or anyone else please help me?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
If nothing happens it means probably that the plugin was not loaded properly (it's hard to tell, would need to look at javascript console)

Apollo loads plugins differently than regular jbrowse from what I remember, please see https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=plugin#jbrowse-plugins

cc @nathandunn

**Comment by mictadlo** [comment]
I tried this one which caused the Apollo not willing to start:

```
jbrowse {

    plugins {
          FeatureSequence{
               included = true
          }
}
}
```

What did I miss?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
@mictadlo  because they are not part of the JBrowse release, but a separate plugin, they should look like this:

https://github.com/GMOD/Apollo/blob/develop/sample-h2-apollo-config.groovy#L140-L144

I'll update the doc to point to this.

**Comment by mictadlo** [comment]
Unfortunately, it still does not work. I changed the following files:

```
vim Apollo/apollo-config.groovy
... 
jbrowse {
    plugins {
        SashimiPlot {
           git = 'https://github.com/twsaari/FeatureSequence'
           branch = 'master'
           alwaysPull = "true"
        }
    }
}
```

```
vim /efs/apollo/trackList.json
....
      {
         "category" : "Annotations",
         "compress" : 1,
         "key" : "NbanotFeb2019v7",
         "label" : "NbanotFeb2019v7",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : "HTMLFeatures",
         "type" : "HTMLFeatures",
         "urlTemplate" : "tracks/NbanotFeb2019v7/{refseq}/trackData.jsonz",
         "menuTemplate" : [
            {},
            {},
            {
               "content" : "function(track,feature){return track.browser.plugins.FeatureSequence.callFxn(track, feature); }",
               "label" : "View Feature Sequence",
               "action" : "contentDialog",
               "iconClass" : "dijitIconBookmark"
            }
         ]
      }
```
Where did I do a mistake or should I add any additional files?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
@mictadlo  If you specify a JBrowse section in the `apollo-config.groovy`, you need to specify the entire section unfortunately.   So it needs the `git` section:

```
jbrowse {
    git {
        url = "https://github.com/gmod/jbrowse"
        branch = "1.16.3-release"
		branch = "dev"
		alwaysPull = false 
		alwaysRecheck = false 
    }
    plugins {
        SashimiPlot {
           git = 'https://github.com/twsaari/FeatureSequence'
           branch = 'master'
           alwaysPull = "true"
        }
    }
}
```

remember to do an `apollo clean-all` first.   

If it fails for some reason, any build or failure details would be great, etc.

**Comment by mictadlo** [comment]
Thank you it works.

**Comment by mictadlo** [comment]
Hi all,
Do you know how to enable translating the spliced sequences into the amino acid sequence?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
If it does not do that automatically, there are apps on the web that can do the translation e.g https://web.expasy.org/translate/

**Comment by mictadlo** [comment]
Would anyone be interested to implement the translation into the FeatureSequence plugin?

**Comment by nathandunn** [comment]
It’s possible someone has done (or has a similar need) it if you post it on the jbrowse list.  

More than likely you’ll have to do it yourself though.   But the community is very helpful if you have questions. 

Nathan

**Comment by mictadlo** [comment]
Ok, I'm waiting to get permission to post on GMOD mailing list. Could you please share with me what kind of development environment e.g. docker do you use?

**Comment by nathandunn** [comment]
You could use docker for the database, but would be best to review these directions here:

https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html <https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html>

Feel free to post here: https://groups.google.com/a/lbl.gov/forum/#!forum/apollo <https://groups.google.com/a/lbl.gov/forum/#!forum/apollo> and apollo@lbl.gov <mailto:apollo@lbl.gov> at the same time. 


You’ll basically be reimplementing this method adding your bit in here:

https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/_FeatureDetailMixin.js#L73-L93 <https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/_FeatureDetailMixin.js#L73-L93>

You could to this in JBrowse directly by editing the above (which Apollo will inherit) or as part of Apollo only.  

If you do it as part of Apollo only then you’ll want to add the mixing method here:

https://github.com/GMOD/Apollo/blob/develop/client/apollo/js/View/Track/DraggableHTMLFeatures.js <https://github.com/GMOD/Apollo/blob/develop/client/apollo/js/View/Track/DraggableHTMLFeatures.js> 

Feel free to ask questions on both lists and the JBrowse Gitter channel as you need help. 

Cheers,

Nathan

**Comment by nathandunn** [comment]
FYI https://github.com/GMOD/Apollo/issues/732

**Comment by nathandunn** [comment]
I think the only caveat here is that Apollo is aware of non standard translation codes, unlike JBrowse.
