### ISSUE TITLE
How can I update tracks with a multiple genes in gff format

### ISSUE THREAD

**Issue by anajulia95** [GMOD/jbrowse#1351]
Hi
I know that if I update a gff file as bin/flatfile-to-json.pl --trackType CanvasFeatures --gff test.gff --trackLabel transcripts
I am going to have:
![transcripts](https://user-images.githubusercontent.com/49414964/55753325-9c9c2980-5a0f-11e9-9705-6d23864e1e1a.png)
but I have 500 genes in one file gff format, I want to have the whole genes in every track  with trackLabel like my example. but It's very tedious to split the file for every gene to have every gene with a trackLabel.
Is there a way to update trackLabels more efficient? It's very tedious to split and update gene by gene
Thanks

**Comment by cmdcolin** [comment]
There are different methods to seach for genes than with the tracklist. Generally you run bin/generate-names.pl and then you can use view->search or type the gene name in the location bar e.g. where it says "scaffold23:123..456"

**Comment by anajulia95** [comment]
@cmdcolin so can I type "bin/generate-names.pl IDgene" in my gff file?

**Comment by cmdcolin** [comment]
You can just type `bin/generate-names.pl` on the command line, similar to how you ran `bin/flatfile-to-json.pl` for example

**Comment by cmdcolin** [comment]
Close for now, let me know if there are any other questions
