### ISSUE TITLE
where can I upload my annotations from jbrowse on web

### ISSUE THREAD

**Issue by anajulia95** [GMOD/jbrowse#1352]
I want to upload my jbrowse visualization on web, I have read about Co-Ge and Araport, but I have had a lot ot errors trying to install Co-Ge plugin. Is there a way to upload my jbrowse visualization 
Thanks

**Comment by cmdcolin** [comment]
JBrowse consists ultimately consists of a set of static files and doesn't really require any server configuration. It is therefore generally easy to host JBrowse...you can just upload the entire jbrowse directory to a web server. It's a little hard to provide tips, but CoGe and Araport might not be the answer, they are kind of their own websites and I am not sure they would just host your jbrowse instance for you but you could contact them to see. The coge plugin is definitely a different thing entirely as it just provides some utilities that coge has to your instance.

**Comment by cmdcolin** [comment]
I guess the long short of it is that there is not really a "jbrowse hub" that I know of that just hosts arbitrary jbrowse instances (although that would be cool) so it helps to get more information about what resources are available to you (do you have a lab webserver, a cloud server, anything like this)

**Comment by cmdcolin** [comment]
Close for now
