### ISSUE TITLE
BigWig/BigBed fail in IE10

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1354]
IE10 _getResponseArrayBuffer catches exception with "could not convert response to ArrayBuffer" for bigwig/bigbed tracks

**Comment by cmdcolin** [comment]
note this did work in 1.12.4 for example, before webpackified stuff, but depending on point of view ie10 support might be unnecessary

**Comment by rbuels** [comment]
i don't think we need to worry about IE10 anymore

**Comment by cmdcolin** [comment]
ok I'll just close then
