### ISSUE TITLE
How Can I upload many track at the same time?

### ISSUE THREAD

**Issue by anajulia95** [GMOD/jbrowse#1355]
I upload a file.gff like:

`bin/flatfile-to-json.pl --trackType CanvasFeatures --gff file.gff --trackLabel NAMETRACK` 

But I have 150 files.gff and It is very tedious to upload these files one by one.
Is there a script or command to upload all my files once and for all ?

Thanks

**Comment by colindaven** [comment]
Hi Ana,

I have written a couple of PERL script like this to input these files into JBrowse.

So it's a bit more general purpose than yours, I'll include it here anyway. Then I run a "runbatch" script wrapper around the main script if I want to add many files to JBrowse. Very useful for large BED or bigwig collections in my experience.

Your might be happy with this:

```
#!/bin/bash
# Add gff in current directory to JBrowse
for i in `ls *.gff`

        do
                echo $gff
                bin/flatfile-to-json.pl --trackType CanvasFeatures --gff $gff --trackLabel $gff 
             

done


```


Unless you always work from the JBrowse directory, you could just add the full path to `flatfile-to-json.pl` to your script.

**Comment by anajulia95** [comment]
Thanks @colindaven. it works perfectly :+1:

**Comment by cmdcolin** [comment]
Glad this works...I suppose close for now
