### ISSUE TITLE
Integer overflow with BAM files

### ISSUE THREAD

**Issue by slbai01** [GMOD/jbrowse#1357]
Hi,

When I used jbrwose to visualize the wheat genome, the genome file and GFF file could be displayed normally, but when I visualized the bam file, I encountered "Error: Integer overflow".

Then I followed the bam file according to the chromosome and found that the bam with a chromosome length greater than 512Mb would encounter the same error (eg. Chr2), and the bam less than 512Mb could be displayed (eg. Chr4). 

I tried both Apache and Nginx web services and couldn't solve the problem.

Here is the code I used for mapping. I hope to help solve this problem.

```shell
~/programs/minimap2-2.16_x64-linux/minimap2 --split-prefix prefix -t $thread -ax splice -uf --secondary=no -C5 $ref_fa $fasta > minimap2.sam && samtools view -bS minimap2.sam | samtools sort > minimap2.sort.bam  && samtools index minimap2.sort.bam
```

If you are creating a new issue please report

- JBrowse version  
JBrowse-1.16.4

- Web browser being used  
Google Chrome | 73.0.3683.103  
Safaria 12.0.3   

- Operating system if relevant
macOS Mojave 10.14.3

![image](https://user-images.githubusercontent.com/15275132/56857822-7e896f80-69a4-11e9-86dc-e21e192b25a0.png)

**Comment by cmdcolin** [comment]
You will need to create a CSI index file for your BAM as BAI indexes can't support chromosomes greater than 2^29-1 which is approx 536870912.

Just recreate the file with `samtools index -c yourfile.bam`. You might need to update your samtools as newer samtools should actually throw an error trying to create this index file.

JBrowse 1.16.4 made sure to check for this and throw a nicer error message for tabix files but didn't have the error for BAM yet, the next version of JBrowse will throw a nicer error for this scenario

**Comment by slbai01** [comment]
Thank you for your answer.

Initially I encountered an error when indexing with a high version of samtools, but I stupidly changed the low version of samtools for indexing.
Now, I get the index in *csi format, but how should I use it in jbrwose? I only found the `baiUrlTemplate` parameter.

**Comment by cmdcolin** [comment]
It is called csiUrlTemplate for the CSI file :)
