### ISSUE TITLE
TypeError : n[6] is undefined

### ISSUE THREAD

**Issue by SaurabhWhadgar** [GMOD/jbrowse#1358]
# TypeError : n[6] is undefined : Jbrowse error while displaying VCF files
![Screenshot from 2019-05-03 10-31-00](https://user-images.githubusercontent.com/50226745/57120661-752b4900-6d90-11e9-9a15-aeed43718138.png)

- JBrowse version : 1.16.4
- Web browser being used : Mozilla Firefox
- Operating system if relevant  : Ubuntu
- If it is setup related, setup.log : Not related
-File path is okay.
-Followed instruction given on Jbrowse Installation Guide.

Does anyone know why this error is coming ? Where to search for solution ? 
Error while displaying VCF file in jbrowse, ( Reference (.fa) seq.) is working fine.

**Comment by garrettjstevens** [comment]
I would guess that there is something in your VCF that is different from what JBrowse expects. If you can share the VCF or a snippet of it with us, it could help us determine if that is the case.

**Comment by SaurabhWhadgar** [comment]
Here are screenshot of vcf file (First track in jbrowse).
![acau_boliva](https://user-images.githubusercontent.com/50226745/57155569-6fb61900-6df9-11e9-9341-8025e076e024.png)
![acau_boliva_2](https://user-images.githubusercontent.com/50226745/57155570-704eaf80-6df9-11e9-93b3-54619bba174c.png)

Thank You so much for your reply. I'll look into that. If you could tell me the problem in vcf file, it would be really helpful.

**Comment by cmdcolin** [comment]
@SaurabhWhadgar  This seems like a malformed VCF. It's hard to read the screenshot (please just copy and paste actual text next time) but you can see the INFO and FORMAT columns appear to be absent.

**Comment by cmdcolin** [comment]
Meant to say that the FORMAT and BAM/caudatus_1.sorted.bam columns are absent

**Comment by cmdcolin** [comment]
@SaurabhWhadgar Any updates on this? Can you possibly share the VCF that caused this

**Comment by SaurabhWhadgar** [comment]
@cmdcolin As you suggested, the VCF file was malformed. I have corrected that file and its working fine now. Thank you so much for the suggestion. Sorry for being late to reply.
