### ISSUE TITLE
link as an attribute from gff3 not clickable

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1363]
Hi,
I added `link` as an attribute into my gff3 file in the following way:

```
##gff-version 3
NbV1Ch01        NbGenome        gene    10602   11559   .       -       .       ID=Nbv6.1trP63519.path2;Name=Uncharacterized protein TCM_044860
NbV1Ch01        NbGenome        mRNA    10602   11559   .       -       .       ID=Nbv6.1trP63519.mrna2;Parent=Nbv6.1trP63519.path2;Name=Nbv6.1trP63519 - Uncharacterized protein TCM_044860;coverage=100.0;identity=98.8;matches=949;mismatches=9;indels=3;unknowns=0;link=http://sefapps02.qut.edu.au/atlas/tREXXX2new6.php?TrID=Nbv6.1trP63519
NbV1Ch01        NbGenome        CDS     10602   11223   98      -       0       ID=Nbv6.1trP63519.mrna2.cds1;Parent=Nbv6.1trP63519.mrna2;Name=Nbv6.1trP63519;Target=Nbv6.1trP63519 338 961 .
NbV1Ch01        NbGenome        exon    10602   11559   98      -       .       ID=Nbv6.1trP63519.mrna2.exon1;Parent=Nbv6.1trP63519.mrna2;Name=Nbv6.1trP63519;Target=Nbv6.1trP63519 1 961 .
```

However, it is not possible to click on the link but I found a GBrowse site where they somehow added multiple clickable links.

![Screen Shot 2019-05-17 at 8 15 31 PM](https://user-images.githubusercontent.com/588297/57921869-c1729f00-78e1-11e9-9448-7f612eda62d6.png)
![Screenshot_2019-05-17 Brassica napus pangenome 7 kbp from chrA01 1 7,000](https://user-images.githubusercontent.com/588297/57921886-cc2d3400-78e1-11e9-9a26-6db1419b0854.png)

How is possible to do it Jbrowse?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
You can URL encode a link with <a href="yourlink">My App</a> like this in the gff

ctgA    est     EST_match       8000    9000    .       -       .       ID=Match6;Name=agt767.3;Target=agt767.3 1 1001;link=%3Ca%20href%3D%22http%3A%2F%2Fsefapps02.qut.edu.au%2Fatlas%2FtREXXX2new6.php%3FTrID%3DNbv6.1trP63519%22%3EMy%20App%3C%2Fa%3E

Then add "unsafePopup": true to your track config e.g. 

      {
         "unsafePopup":true,
         "label" : "My track",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "type" : "CanvasFeatures",
         "urlTemplate" : "tracks/test/{refseq}/trackData.json"
      }

**Comment by cmdcolin** [comment]
Alternatively you can just have it like you have currently and use the fmtDetailValue callback

NbV1Ch01        NbGenome        mRNA    10602   11559   .       -       .       ID=Nbv6.1trP63519.mrna2;Parent=Nbv6.1trP63519.path2;Name=Nbv6.1trP63519 - Uncharacterized protein TCM_044860;coverage=100.0;identity=98.8;matches=949;mismatches=9;indels=3;unknowns=0;link=http://sefapps02.qut.edu.au/atlas/tREXXX2new6.php?TrID=Nbv6.1trP63519


and then in your config


    {
      "fmtDetailValue_link": "function(value) { return `<a href=${value}>My app</a>`; }",
      "label": "test2",
      "storeClass": "JBrowse/Store/SeqFeature/NCList",
      "type": "CanvasFeatures",
      "urlTemplate": "tracks/test2/{refseq}/trackData.json"
    }

  {
     "fmtDetailValue_link": "function(value) { return '<a href=\"'+link+'"\>My app</a>'; }"
     "label" : "My track",
     "storeClass" : "JBrowse/Store/SeqFeature/NCList",
     "type" : "CanvasFeatures",
     "urlTemplate" : "tracks/test/{refseq}/trackData.json"
  }

**Comment by mictadlo** [comment]
I tried your second option but no Pop shows up with the below configuration:

```
      {
         "fmtDetailValue_Link": "function(value) { return `<a href=${value}>Atlas</a>`; }",
         "compress" : 1,
         "key" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
         "label" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : "HTMLFeatures",
         "type" : "HTMLFeatures",
         "urlTemplate" : "tracks/Gmp_NbV1_TrV6_Prm_Feb2019v2-link2/{refseq}/trackData.jsonz"
      }
```
What did I miss?

Thank you in advance,

MIchal

**Comment by cmdcolin** [comment]
If no popup shows it means the javascript "crashed" in some sense. You can check your javascript devtools to see what happened.

You might try this instead to see if it helps

        "fmtDetailValue_Link": "function(value) { return '<a href='+value+'>Atlas</a>'; }",

**Comment by mictadlo** [comment]
I tried the new "fmtDetailValue_Link" but it does show any pop either and the devtools show nothing. However, the link works when I go to view details. In the meantime I tried also to add an entry to a menu right-click menu in the below way:
```
{
   "fmtDetailValue_Link": "function(value) { return '<a href='+value+'>Atlas</a>'; }",                                                                                  
   "compress" : 1,
   "key" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
   "label" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
   "storeClass" : "JBrowse/Store/SeqFeature/NCList",
   "style" : {
      "className" : "feature"
   },
   "trackType" : "HTMLFeatures",
   "type" : "HTMLFeatures",
   "urlTemplate" : "tracks/Gmp_NbV1_TrV6_Prm_Feb2019v2-link2/{refseq}/trackData.jsonz",
  {
    "label" : "Open Atlas in an iframe popup",
    "title" : "The magnificent example.com (feature {name})",
    "iconClass" : "dijitIconDatabase",
    "action": "iframeDialog",
    "url" : "http://sefapps02.qut.edu.au/atlas/tREXXX2new6.php?TrID={name}"
  }
}
```

However, it caused not allowing Jbrowse to start at all:

```
{
   "fmtDetailValue_Link": "function(value) { return '<a href='+value+'>Atlas</a>'; }",                                                                                  
   "compress" : 1,
   "key" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
   "label" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
   "storeClass" : "JBrowse/Store/SeqFeature/NCList",
   "style" : {
      "className" : "feature"
   },
   "trackType" : "HTMLFeatures",
   "type" : "HTMLFeatures",
   "urlTemplate" : "tracks/Gmp_NbV1_TrV6_Prm_Feb2019v2-link2/{refseq}/trackData.jsonz",
  {
    "label" : "Open Atlas in an iframe popup",
    "title" : "The magnificent example.com (feature {name})",
    "iconClass" : "dijitIconDatabase",
    "action": "iframeDialog",
    "url" : "http://sefapps02.qut.edu.au/atlas/tREXXX2new6.php?TrID={name}"
  }
}
```

Why Jbrowse did not start?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
You should at the very least make sure you use valid JSON. You can use an online app such as https://jsonlint.com/ to check it. Command line apps to validate exist too e.g. npm install -g jsonlint; jsonlint trackList.json

**Comment by mictadlo** [comment]
I have forgotten to add `"menuTemplate" `

```
      {
         "fmtDetailValue_Link": "function(value) { return '<a href='+value+'>Atlas</a>'; }",
         "compress" : 1,
         "key" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
         "label" : "Gmp_NbV1_TrV6_Prm_Feb2019v2-link2",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : "HTMLFeatures",
         "type" : "HTMLFeatures",
         "urlTemplate" : "tracks/Gmp_NbV1_TrV6_Prm_Feb2019v2-link2/{refseq}/trackData.jsonz",
         "menuTemplate" : [
         {
           "label" : "Open Atlas in an iframe popup",
           "title" : "The magnificent example.com (feature {name})",
           "iconClass" : "dijitIconDatabase",
           "action": "iframeDialog",
           "url" : "http://sefapps02.qut.edu.au/atlas/tREXXX2new6.php?TrID={name}"
        }
        ]
      }
```

However, the `{name}` is `Nbv6.1trP63519 - Uncharacterized protein TCM_044860 `  rather than only 
is there a way to shorten it in Jbrowse?

```
##gff-version 3
NbV1Ch01        NbGenome        gene    10602   11559   .       -       .       ID=Nbv6.1trP63519.path2;Name=Uncharacterized protein TCM_044860
NbV1Ch01        NbGenome        mRNA    10602   11559   .       -       .       ID=Nbv6.1trP63519.mrna2;Parent=Nbv6.1trP63519.path2;Name=Nbv6.1trP63519 - Uncharacterized protein TCM_044860;coverage=100.0;identity=98.8;matches=949;mismatches=9;indels=3;unknowns=0;link=http://sefapps02.qut.edu.au/atlas/tREXXX2new6.php?TrID=Nbv6.1trP63519
NbV1Ch01        NbGenome        CDS     10602   11223   98      -       0       ID=Nbv6.1trP63519.mrna2.cds1;Parent=Nbv6.1trP63519.mrna2;Name=Nbv6.1trP63519;Target=Nbv6.1trP63519 338 961 .
NbV1Ch01        NbGenome        exon    10602   11559   98      -       .       ID=Nbv6.1trP63519.mrna2.exon1;Parent=Nbv6.1trP63519.mrna2;Name=Nbv6.1trP63519;Target=Nbv6.1trP63519 1 961 .
```

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
If you have control over the gff production, I'd avoid storing "annotation data" like that in Name and instead store it in Note e.g.

    Name=Nbv6.1trP63519;Note=Uncharacterized protein TCM_044860

But as a workaround you can make a callback

    "title": "function(config, feat) { feat.get('name').replace(/ -.*/,''); }",

**Comment by mictadlo** [comment]
Thank you it worked.
