### ISSUE TITLE
"start" attribute in last column of GFF3 file results in bad coordinates for the feature in GFF3Tabix mode

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/jbrowse#1364]
We have such a GFF3 file:
~~~~
myspecies-F_contig1   Gmove   mRNA    50689   50902   .       +       .       ID=mRNA.myspecies-F_contig1.8.1;Name=mRNA.myspecies-F_contig1.8.1;start=0;stop=0;cds_size=213;model_size=214;exons=1
myspecies-F_contig1   Gmove   CDS     50689   50901   .       +       .       Parent=mRNA.myspecies-F_contig1.8.1
~~~~

case 1- In GFF3Tabix mode, this GFF3 results in wrong coordinates for the mRNA:
<img width="795" alt="position_wrong" src="https://user-images.githubusercontent.com/16136876/58031262-5cf15300-7b20-11e9-852f-ac33e2f64a70.png">

case 2- Removing the "start" and "stop" attributes in last column results in right coordinates:
<img width="778" alt="position_right" src="https://user-images.githubusercontent.com/16136876/58031277-624e9d80-7b20-11e9-8afd-a67926911fc8.png">

case 3- In NCList mode, keeping the original GFF3, results in right coordinates, with a "start2" attribute displayed in the popup window:
<img width="310" alt="nclist_position_right" src="https://user-images.githubusercontent.com/16136876/58031288-67135180-7b20-11e9-83ee-e3f7db381bcb.png">

I guess, in case 1, the "start" attribute in last column of the GFF3 is used as the start coordinate for the feature sequence whereas it should not.

- JBrowse version: 1.16.1
- Web browser being used: firefox
- Operating system if relevant: CentOS 6.3

**Comment by abretaud** [comment]
Ah, just had the same problem today, I ended up removing the start/stop attributes from GFF. I guess it's the tabix indexing that interprets badly the start attributes

**Comment by loraine-gueguen** [comment]
Yes I think so

**Comment by cmdcolin** [comment]
technically this is due to the jbrowse feature model. JBrowse has the "SimpleFeature" type that just does

feature.get('start') to refer to the column 3, and then it ends up overwriting that with the attribute named start

We would have to emulate the behavior of NCLIst e.g. renaming it 'start2' to make it work

**Comment by cmdcolin** [comment]
added my proposed fix to the dev branch. hope that is acceptable!
