### ISSUE TITLE
hiding URL within an iframeDialog

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1365]
Hi,
Is it possible to hide the URL within an iframeDialog?

```
            {
               "action" : "iframeDialog",
               "iconClass" : "dijitIconDatabase",
               "label" : "Gene Expression",
               "title" : "{Name}",
               "url" : "http://sefapps02.qut.edu.au/atlas/tREX10.php?TrID={Name}"
            },
```

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Is there any reason why not, you mean the title of the iframe dialog?

**Comment by cmdcolin** [comment]
I am afraid that unless there is a compelling reason I will have to close issue

**Comment by cmdcolin** [comment]
will close for now but post back if needed

**Comment by mictadlo** [comment]
I mean only to remove the URL (http://sefapps02.qut.edu.au/atlas/tREX10.php?TrID=Nbv6.1trP4919). Without the URL it looks more like a plugin.

![image](https://user-images.githubusercontent.com/588297/58611240-ca0ba200-82f1-11e9-9438-d1bf11152bea.png)

**Comment by cmdcolin** [comment]
I added this feature under the name `hideIframeDialogUrl`

Usage like this

            {
               "action" : "iframeDialog",
               "hideIframeDialogUrl": true,
               "iconClass" : "dijitIconDatabase",
               "label" : "Open example.com in an iframe popup",
               "title" : "The magnificent example.com (feature {name})",
               "url" : "http://www.example.com?featurename={name}"
            },

Can clone from github dev branch or wait until next release
