### ISSUE TITLE
How to add a csi index in a gff file

### ISSUE THREAD

**Issue by juancrescente** [GMOD/jbrowse#1369]
I've added a big gff track, but JBrowse says:

"Error: tabix index contains too many bins, please use a CSI index"

So I create a CSI index using:

"tabix -p gff -C Triticum_aestivum.IWGSC.43.sorted.gff3.gz"

But now I cannot find how to specify this index in the tracks.conf

JBrowse 1.16.4

**Comment by juancrescente** [comment]
This is my config file:

> ➜  data cat tracks.conf
> [GENERAL]
> refSeqs=Triticum_aestivum.IWGSC.dna.toplevel.fa.fai
> [tracks.refseq]
> urlTemplate=Triticum_aestivum.IWGSC.dna.toplevel.fa
> storeClass=JBrowse/Store/SeqFeature/IndexedFasta
> type=Sequence
> [tracks.genes]
> urlTemplate=Triticum_aestivum.IWGSC.43.sorted.gff3.gz
> csiUrlTemplate=Triticum_aestivum.IWGSC.43.sorted.gff3.gz.csi
> #storeClass=JBrowse/Store/SeqFeature/CSI
> type=CanvasFeatures
> chunkSizeLimit=1500000
>

**Comment by cmdcolin** [comment]
You can use csiUrlTemplate


```
[tracks.yourtrack]
urlTemplate=file.gff.gz
csiUrlTemplate=file.gff.gz.csi
storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
type=CanvasFeatures
```

The storeClass and type will be inferred to be this automatically so you can actually just use

```
[tracks.yourtrack]
urlTemplate=file.gff.gz
csiUrlTemplate=file.gff.gz.csi
```

Note that "yourtrack" there is a "track label" and an important identifier. Use key=My Gene Predictions to add more sophisticated track display name

Also be aware of limitations of GFF3Tabix, notably that it does re-fetching of regions to resolve parent->child relationships. this mspaint diagram will help explain:

![image](https://user-images.githubusercontent.com/6511937/58293577-07bd7780-7d94-11e9-960a-ffee8ab290ea.png)

Using things like dontRedispatch and topLevelFeatures are workarounds for this in GFF3Tabix but still it can be problematic for large gene sets.


Using plain flatfile-to-json is can be less problematic for these cases

**Comment by cmdcolin** [comment]
In the above diagram, to correctly render the gene group, we would need information about T1, T2, and T3 to correctly render the gene glyph

**Comment by juancrescente** [comment]
I've changed that  but still having some issues loading this big gff file. 
Using chrome I got the following errors in console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
/jbrowse/data/names/root.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)
0.bundle.js:8 o
A @ 0.bundle.js:8
```

This is my config

```

[GENERAL]
refSeqs=Triticum_aestivum.IWGSC.dna.toplevel.fa.fai
[tracks.DNA]
urlTemplate=Triticum_aestivum.IWGSC.dna.toplevel.fa
storeClass=JBrowse/Store/SeqFeature/IndexedFasta
type=Sequence
[tracks.Genes]
urlTemplate=Triticum_aestivum.IWGSC.43.filtered.sorted.gff3.gz
csiUrlTemplate=Triticum_aestivum.IWGSC.43.filtered.sorted.gff3.gz.csi
type=CanvasFeatures
chunkSizeLimit=1200000

```

This is the installation

http://139.59.141.246/jbrowse/?loc=1A%3A293113007..293113053&tracks=Genes%2CDNA&highlight=

**Comment by cmdcolin** [comment]
That error is just saying that generate-names.pl hasn't been run essentially

**Comment by cmdcolin** [comment]
If your gff still isn't loading it would be unrelated to that error. You might need to set dontRedispatch=chromosome for example of you have chromosome level features

**Comment by juancrescente** [comment]
mm I do not have chromosole-level features, since I removed them. 

This is the script I've used to generate the data:

```
mkdir data
cd data

curl -L ftp://ftp.ensemblgenomes.org/pub/plants/release-43/fasta/triticum_aestivum/dna/Triticum_aestivum.IWGSC.dna.toplevel.fa.gz > Triticum_aestivum.IWGSC.dna.toplevel.fa.gz
curl -L ftp://ftp.ensemblgenomes.org/pub/plants/release-43/gff3/triticum_aestivum/Triticum_aestivum.IWGSC.43.gff3.gz > Triticum_aestivum.IWGSC.43.gff3.gz
samtools faidx Triticum_aestivum.IWGSC.dna.toplevel.fa

awk '{ if(($3 == "gene") || ($3 == "exon") || ($3 == "five_prime_UTR") || ($3 == "three_prime_UTR") ) { print } }' Triticum_aestivum.IWGSC.43.gff3 > Triticum_aestivum.IWGSC.43.filtered.gff3

(grep ^"#" Triticum_aestivum.IWGSC.43.filtered.gff3; grep -v ^"#" Triticum_aestivum.IWGSC.43.filtered.gff3 | grep -v "^$" | grep "\t" | sort -k1,1 -k4,4n) > Triticum_aestivum.IWGSC.43.filtered.sorted.gff3

bgzip Triticum_aestivum.IWGSC.43.filtered.sorted.gff3

tabix -p gff -C Triticum_aestivum.IWGSC.43.filtered.sorted.gff3.gz

```

So I'm only keeping genes, exons and UTRs features.

**Comment by juancrescente** [comment]
> dontRedispatch=chromosome

This seems to did the trick :)

**Comment by cmdcolin** [comment]
Glad that helps. We could maybe consider making the dontRedispatch=chromosome a default and/or making a special README page about gff3 tabix, since it's sort of finicky

**Comment by cmdcolin** [comment]
Close for now
