### ISSUE TITLE
Modify left click pop-up static code in JBrowse version 1.16.3

### ISSUE THREAD

**Issue by thomas77** [GMOD/jbrowse#1372]
Hello !

On a old JBrowse version I was able to edit the left click pop-up (when clicking on a specific feature like gene for example) to add some static text: you can see this example [here](https://urgi.versailles.inra.fr/jbrowse/gmod_jbrowse/?data=myData%2FWheat%2Fannotation%2F3B&loc=traes3bPseudomoleculeV1%3A82455094..82455353&tracks=Markers&highlight=). 

To do that I duplicated the files "CanvasFeatures.js" and "_FeatureDetailMixin.js" to add this little portion of html code. Then I called these files in my trackList.json file like this:
`         "type" : "JBrowse/View/Track/CanvasFeaturesForWheat"
`

My problem is that I'm not able to do that with my new version of JBrowse (1.16.3), I saw that these files are called by a bundle.js file that seem's to call all the files from the outside:
`(function(){(this||window).webpackJsonp.registerAbsMids({"JBrowse/Browser":125,"JBrowse/Util":329,"JBrowse/QueryParamConfigMapper":330,"JBrowse/Model/XHRBlob":331,"JBrowse/Store/SeqFeature":332,"JBrowse/Model/SimpleFeature":333,"JBrowse/Store/DeferredFeaturesMixin".....`

Could you please help me to modifiy the files I want ?

Best regards,

Thomas

**Comment by cmdcolin** [comment]
@thomas77 with the latest version of jbrowse, you have to rebuild the codebase when you make modifications

To setup a development environment with the latest version of jbrowse you can

a) retrieve a git clone of jbrowse e.g. `git clone https://github.com/gmod/jbrowse`
b) add your new files to the source directory
c) run `./setup.sh`
d) run `npm run watch` which will update the build with your files

**Comment by cmdcolin** [comment]
Then you simply modify code in another window and refresh browser to see your changes as usual (just leave the `npm run watch` command running in background)

**Comment by cmdcolin** [comment]
Also, if you think this change, for example adding an optional header at the top of the view details panel, can be generally useful, feel free to make a pull request!

**Comment by cmdcolin** [comment]
Let me know if there are any issues, since this is not really a bug or feature request I'll close for now
