### ISSUE TITLE
Always getting `Cannot get size of BigWig/BigBed file, widest zoom level not available`

### ISSUE THREAD

**Issue by lukaw3d** [GMOD/jbrowse#1375]
With new http-range-fetcher, bigwig always shows a warning
`cannot get size of BigWig/BigBed file, widest zoom level not available`

## Code

You would probably need to use `response.headers['content-range']` in here, not just response.buffer:
https://github.com/GMOD/jbrowse/blob/318a24342880cce870f5b0b7a95fe186a1d3919f/src/JBrowse/Model/XHRBlob.js#L200-L208

- old code did this:
 https://github.com/GMOD/jbrowse/blob/f13c6fddc2c1faea4eacd30a4efe7fc665216081/src/JBrowse/Store/RemoteBinaryFile.js#L254-L260

## Version info

JBrowse version: 1.16.4
Web browser being used: Chrome 75

**Comment by cmdcolin** [comment]
Thanks for noticing this. I think it should be restored now on a commit to dev branch https://github.com/GMOD/jbrowse/commit/5f6c036fb71518e2f20995b49c5f57570e474f01

**Comment by cmdcolin** [comment]
Note there is also a fix on dev branch for accessing the smallest zoom level...https://github.com/GMOD/jbrowse/issues/1359

Pending release as 1.16.5 hopefully soon (if anyone needs it sooner than later let me know :))

**Comment by lukaw3d** [comment]
That's a pretty fix
