### ISSUE TITLE
JBrowse rendered ugly if both UTR and exon exists

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1378]
In the GFF3 file of GENCODE release, the five_prime_UTR or three_prime_UTR are co-existed with exon features. Also, I add "exon" to the config json file in order to show many non-coding processed transcripts:
```
"subParts": "CDS,UTR,five_prime_UTR,three_prime_UTR,exon",
```

 As a result, it rendered ugly.

![TIM截图20190612164308](https://user-images.githubusercontent.com/1146090/59336429-2084d180-8d31-11e9-83b4-0abf65283641.png)

Although I can manually write a script to pre-process the GFF3 file to remove the "exon" line in all protein-coding transcripts, I still eager to know whether there are any methods to allow JBrowse to ignore the "exon" features in protein-coding transcripts

**Comment by cmdcolin** [comment]
Is there any particular reason why you are specifying subParts at all? JBrowse should automatically be able to figure this out. You don't want to have both exon and CDS in subParts really

**Comment by cmdcolin** [comment]
Did that work to not specify it :)?

**Comment by billzt** [comment]
Well, if I didn't specify it, the protein coding transcripts are OK, but the non-coding transcripts are wrong (only arrows are shown), as the non-coding transcripts are listed in GFF3 files like this:

```
transcript   transcript_type="lincRNA"
exon
exon
exon
```

The protein-coding transcripts are like this:
```
transcript   transcript_type="protein-coding"
exon
primer_five_UTR
exon
CDS
exon
CDS
exon
primer_three_UTR
```

**Comment by cmdcolin** [comment]
@billzt if you use column 3 type as any one of these:

    noncodingType: ['ncRNA', 'lnc_RNA', 'lncRNA', 'miRNA']

Then it should display the noncoding types correctly also. It is configurable via noncodingType to add new ones also, but I think having both of them being transcript needs to change (needs to be unique somehow)

**Comment by cmdcolin** [comment]
Note that noncodingType was added in 1.16.1

**Comment by billzt** [comment]
Yeah, I've noticed the `noncodingType` attritute alreay, however I need the change the 3rd column. Besides, there are about >50 kinds of noncoding transcripts and therefore I'd rather not change the original GFF file.

**Comment by cmdcolin** [comment]
You can make a glyph callback perhaps

**Comment by billzt** [comment]
Thanks, I'll try the glyph callback
