### ISSUE TITLE
Increase feature density

### ISSUE THREAD

**Issue by mariene** [GMOD/jbrowse#1379]
Hello,

I'm using JBrowse version 1.12 and I'm trying to display all my consensus copies. I'm suppose to see ~150 copies but the JBrowse only displays a few of them. I tried to increase the 'maxHeight' and 'maxFeaturesScreenDensity' but nothing change. 

You can see below an example (There are only ~ 20 copies but when I download the data I get 150 copies).

![jb](https://user-images.githubusercontent.com/10711252/59357853-d64d2180-8d2b-11e9-8ba4-adb8d59378c7.png)

Could you please tell me which parameters should I change to see all my copies ?

Best regards,

Mariène

**Comment by cmdcolin** [comment]
There's nothing in this screenshot that shows me that JBrowse is "limiting" the amount of features being displayed. When, for example, maxHeight is surpassed, then it will show a bar that says "Max height reached". The maxFeatureScreenDensity is a little different and it changes from feature display to feature density histograms if it is surpassed.

Is there any solid indication that not all the data is displayed? Do you have a sample gff we can check out by chance?

**Comment by mariene** [comment]
Hi cmdcolin, thank you for your answer,

We do not have "Max height reached" message.

Below is a screenshot in "normal" mode, you can see that there are not a lot of copies.

![jb2](https://user-images.githubusercontent.com/10711252/59359634-fdf1b900-8d2e-11e9-8f3d-6830fe9699e9.png)


I downloaded the GFF file corresponding to this area and I obtained a GFF file with 161 lines (you can check the lines number in the bottom right of the file below).

![GFF](https://user-images.githubusercontent.com/10711252/59359710-224d9580-8d2f-11e9-969b-bf4296b472f0.png)


Thank you

**Comment by cmdcolin** [comment]
You can see that the data actually contains parent features and child features. JBrowse groups these together under a single feature. I would imagine it is displaying the correct number of features in this case. Note that many of the child features appear to overlap each other so that is why it's sort of hard to see the child features. If you wanted to load the child features as individual features you could use

    bin/flatfile-to-json.pl --gff yourfile.gff --type "ConsensusCopy part" --trackLabel childfeatures

**Comment by cmdcolin** [comment]
@mariene is this resolved now? I saw you also have posts on intermine mailing list, wondering if that is different

https://lists.intermine.org/pipermail/dev/2019-June/004353.html

**Comment by mariene** [comment]
My problem is not solved yet. I think that it is not due to Jbrowse because I tested my dataset on a standalone version of JBrowse and it shows all the sequences. 
However, the version in Intermine only shows 161 out of 239 sequences. I am trying to retrieve the files generated by the version in Intermine to understand what is going on but I cannot find them.

**Comment by cmdcolin** [comment]
@mariene I believe Intermine uses a REST API, not files, to generate the tracks.

**Comment by mariene** [comment]
Yes you're right IntermIne uses a REST API to generate the json files, that's why it's hard to fix because I do not see any errors in my browser console.

**Comment by cmdcolin** [comment]
@mariene any update? I'd try and make a clear case to the intermine folks about a specific feature or something that you are certain is not showing up. If the above problem that I addressed is fixed I suppose I will close for now

**Comment by mariene** [comment]
I have no more answers from intermine. I try to find out where is the problem but I'm a little bit stuck.

**Comment by cmdcolin** [comment]
@mariene I would recommend finding a specific feature that you are expecting to show up that is not showing up, that's kind of the only way I can conceive to see that you are not receiving the correct features.
