### ISSUE TITLE
labels and descriptions disappeared when zoom out

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1381]
See the screenshots: labels and descriptions can only been seen if zooming in enough. When I zoom out, they disappeared quickly, even if there's enough blank on the screen.

zoom out (no labels, even if the screen if blank enough):
![TIM截图20190613083346](https://user-images.githubusercontent.com/1146090/59395364-2244a880-8db6-11e9-9ea7-b516fe2ba055.png)

zoom in:
![TIM截图20190613083405](https://user-images.githubusercontent.com/1146090/59395365-22dd3f00-8db6-11e9-8287-26e24969c439.png)

**Comment by cmdcolin** [comment]
If this is a gff3tabix you can set topLevelFeaturesPercent to something like 0.1 which says you have many more exons than genes and therefore it assumes the feature density to be lower leading to better display of labels and features

**Comment by billzt** [comment]
Resolved!
