### ISSUE TITLE
Error : HTTP 500 when fetching" bai

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1382]
Hi all,
I loaded my BAM file with `perl /home/ubuntu/Apollo/jbrowse/bin/add-bam-track.pl --bam_url wholeplant.sorted.bam  --label Whole_Plant_v2 --key "Whole_Plant_v2" -i /efs/apollo/trackList.json`

This is `trackList.json` entry for the BAM:
```
      {
         "urlTemplate" : "wholeplant.sorted.bam",
         "label" : "Whole_Plant_v2",
         "key" : "Whole_Plant_v2",
         "type" : "JBrowse/View/Track/Alignments",
         "category" : "RNA-Seq alignments",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM"
      }
```

Unfortunately, I got `Error : HTTP 500 when fetching" https://...bai`.

What did I miss?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Http 500 is internal server error

You might need to ask the Apollo people. At the very least your bam file and Bai file should be in the Apollo data directory as that command does not copy any data, it just writes the tracklist entry

**Comment by mictadlo** [comment]
The above is a new BAM file but I have older BAM on Apollo working without any problem.

**Comment by cmdcolin** [comment]
In this case it's unclear what the issue is without seeing any server log, I'd suggest checking the Apollo Catalina log or similar cc @nathandunn

**Comment by nathandunn** [comment]
Like @cmdcolin said .. will need the error logs as a 500 error is a server error.

Also, if you test it on jbrowse by itself I’m curious if it renders without error.

Nathan

**Comment by mictadlo** [comment]
Hi,
It sees the below new command works:

```
/efs/apollo$ perl /home/ubuntu/Apollo/jbrowse/bin/add-bam-track.pl --bam_url /efs/apollo/wholeplant.sorted.bam  --label Whole_Plant_v2 --key "Whole_Plant_v2" -i /efs/apollo/trackList.json
```

Thank you for your all help.

Best wishes,

Michal
