### ISSUE TITLE
Change the style

### ISSUE THREAD

**Issue by Julianne95** [GMOD/jbrowse#1390]
Hi, I am using JBrowse and I want to know How Can I get this style:
![Captura de pantalla de 2019-06-26 08-50-37](https://user-images.githubusercontent.com/49414964/60185897-5c6b6c80-97f0-11e9-9d35-e655826c20e2.png)
I Tried with feature5, feature4, but I don't see it in the manual.

Thanks

**Comment by cmdcolin** [comment]
These are enabled by a special plugin and track type

See https://github.com/GMOD/jbrowse/tree/master/plugins/NeatCanvasFeatures
https://github.com/GMOD/jbrowse/tree/master/plugins/NeatHTMLFeatures

**Comment by anajulia95** [comment]
Thanks @cmdcolin :)

**Comment by cmdcolin** [comment]
No worries. I'll close for now
