### ISSUE TITLE
Customize the main menu bar 

### ISSUE THREAD

**Issue by Julianne95** [GMOD/jbrowse#1391]
Hi I would like to customize the main menu bar like this 
https://popfly.uab.cat/?loc=2L%3A1..23011544&tracks=DNA%2Cgene_annotations%2Cinversions%2Crecombination%2CRRC_100kb&highlight=
I know that I have to add the Plugin RegexSequenceSearch, but I do not know what to edit. Should I edit the plugin, the tracklist.json or JBrowse.conf?. How can I change color, words, style, etc.. ?
Thanks

**Comment by cmdcolin** [comment]
The most common way to add changes is via a jbrowse plugin. JBrowse plugins can include CSS and javascript to customize the main menu bar. Here is a short FAQ entry to add entries to the main menu bar. https://jbrowse.org/docs/faq.html#how-do-i-customize-the-main-menu-bar

I don't necessarily have advice ready on how to customize the look and feel of the menu bar like this link has. I might just email that group to see if they have advice. Plugins can add CSS to customize the look and feel.

**Comment by cmdcolin** [comment]
If it is not immediately obvious from my above answer, it does not simply involve editing the configs.

**Comment by cmdcolin** [comment]
I might close for now. If there are other questions let me know
