### ISSUE TITLE
Zoom to this gene is missing in the menu

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1394]
Hi,
I am using the following configuration for our annotation.

```
      {
         "category" : "vi. Tracks Dev",
         "compress" : 1,
         "key" : "braker-NbAllMerged-BAM-soft_utr",
         "label" : "braker-NbAllMerged-BAM-soft_utr",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : "HTMLFeatures",
         "type" : "HTMLFeatures",
         "urlTemplate" : "tracks/braker-NbAllMerged-BAM-soft_utr/{refseq}/trackData.jsonz"
      }
```
However, I am missing `Zoom to this gene` in the below menu:
![Screen Shot 2019-07-02 at 7 42 48 AM](https://user-images.githubusercontent.com/588297/60468456-0473b080-9c9d-11e9-90d6-f00e7a91b2a1.png)

How is it possible to add?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
Zoom to this gene is only available in CanvasFeatures

**Comment by mictadlo** [comment]
Do you have any plans to add this feature to HTMLFeatures?

**Comment by cmdcolin** [comment]
I think we will not add it to HTMLFeatures. It is not really a critical feature and some people code their menuTemplates on specific order of features in the menuTemplate. If you want, you can manually make a menuTemplate entry for this feature using a callback.

**Comment by mictadlo** [comment]
Do you have an example?
