### ISSUE TITLE
Alignments color coding

### ISSUE THREAD

**Issue by mictadlo** [GMOD/jbrowse#1396]
Hi,
For our BAM files, I used 

```        
"type" : "JBrowse/View/Track/Alignments",
```
and I do not understand what the the strippes in the alignment maeans 
![image](https://user-images.githubusercontent.com/588297/60557217-fb134280-9d87-11e9-8f63-c7c629a7f707.png)

By any chance, do you have a colour scheme description for `Alignments`?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
@nathandunn I think this is an apollo specific style right? do you have the scheme for the stripes

**Comment by nathandunn** [comment]
I don't know what the stripes are either.   Is this in Apollo or JBrowse @mictadlo ?

There is some information here: 

http://gmod.org/wiki/JBrowse_Configuration_Guide#Alignments 

JBrowse actually implements this as well (minus the stripes, but I haven't ever seen that).  Apollo had to add back the positive (red) negative (blue) strands.   That is all they mean. 

We'd have to take a look at your specific BAM details to get a better idea.

**Comment by nathandunn** [comment]
@mictadlo  how is this related to this? https://github.com/GMOD/Apollo/issues/2195

JBrowse has a base track and then Apollo over-rides it (if you are using apollo).

**Comment by mictadlo** [comment]
Yes, it is related to GMOD/Apollo#2195 . I am using Apollo some regions that have even more red and blue stripes. Would you like that I send you the files?

**Comment by nathandunn** [comment]
@mictadlo  Maybe you can click on "view details" and see what we get first.   Getting onto the server would probably be more useful.  You can email at `nathandunn@lbl.gov`

**Comment by cmdcolin** [comment]
I'm going to guess it corresponds to the "not proper" flag of BAM. Again the strips are apollo specific but this is the jbrowse coloring scheme here

https://jbrowse.org/docs/alignments.html#alignments2-coloring-schemes


See also "read mapped in proper pair" https://broadinstitute.github.io/picard/explain-flags.html
