### ISSUE TITLE
swipe scroll on mac and chrome triggers forward or back scroll

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#1397]
When scrolling to the left or the right on the mac in Chrome with JBrowse 1.16.5 (and similarly Apollo) it triggers a back or forward scroll.  Per topic: https://groups.google.com/a/lbl.gov/forum/#!topic/apollo/Dk2AUoyQJY4

- JBrowse version: 1.16.5 
- Web browser being used:  Chrome
- Operating system if relevant: Mac
- This occurs in and outside an iFrame 

More details:
- when tracklist=1 I see the affect when scrolling to the right (if there is forward history), but but not the left
- when tracklist=0 (as it in Apollo most of the time) you always see the affect (if there is history forward or back)

**Comment by nathandunn** [comment]
Not observed at all in JBrowse2 AFAICT

**Comment by nathandunn** [comment]
Usually this is when something on the page hits a horizontal scroll limit (at least with trello).

**Comment by nathandunn** [comment]
Works with all versions 1.12 to 08c9e7ed8b6dec94700951e0a857967797a6edca  (June 12th) . . I'll roll it forward and see

**Comment by nathandunn** [comment]
This fails: 8a041eb63122860adb138fe3f89f4922c3fbdd64

**Comment by nathandunn** [comment]
Testing:
-  08c9e7ed8b6dec94700951e0a857967797a6edca (works from above)
- 829d6a6c7320c693045d79db4bb1894ed958fff3 (works)
- e9c2ef8a7216b9788882394d909df15f529b5c8c (failure here 💥 )

**Comment by cmdcolin** [comment]
I see. That's unfortunate. We'll have to roll back that change I guess. There is a config flag you can add to jbrowse.conf "alwaysStopScrollBubble=true" that may help this. Can you try that

**Comment by nathandunn** [comment]
@cmdcolin  that definitely fixes it.  Could we just change the default to true?  It might be the simpler fix.

**Comment by cmdcolin** [comment]
Yes that should be fine actually. That code change was only designed to affect vertical scrolling but  is somehow affecting left right scrolling with the mac touchpad...works fine with my touchpad weirdly enough. We can either try to fix that just turn that config item to true by default

**Comment by nathandunn** [comment]
@cmdcolin  I'm not sure the behavior its trying to fix, but setting it to true by default works for me.  Do you want to make that fix or should I?

**Comment by cmdcolin** [comment]
This change should fix it instead https://github.com/GMOD/jbrowse/commit/4b44f87993980a2d0fe5086299b37709dc921a76

I just pushed it it to dev in case you want to test

**Comment by cmdcolin** [comment]
Thanks for catching this

**Comment by nathandunn** [comment]
@cmdcolin  Tested and works.   Thanks for the fix!
