### ISSUE TITLE
Dowloading protein sequence

### ISSUE THREAD

**Issue by anabc29** [GMOD/jbrowse#1398]
Hi.
I am using JBrowse and I would like to know that Is it possible to download Amino Acid sequences?
These are the default parameters
![Captura de pantalla de 2019-07-03 14-20-17](https://user-images.githubusercontent.com/41842945/60619527-80a1ed00-9d9e-11e9-94fc-c6af491b0424.png)

I can download mRNA and CDS but It is so much work to translate the sequences into protein?

Is there a config or parameter to do that?
Thanks

**Comment by cmdcolin** [comment]
This is commonly done using a plugin like this which does extra work on top of the default jbrowse feature details 

https://github.com/twsaari/FeatureSequence

**Comment by cmdcolin** [comment]
Maybe close for now :) saw the other thread was sort of related
