### ISSUE TITLE
adding config on the terminal 

### ISSUE THREAD

**Issue by anabc29** [GMOD/jbrowse#1399]
Hi , I am trying to add this config on  the terminal
  

> "compress" : 0,
>          "gradient" : true,
>          "key" : "ASM",
>          "label" : "Genes",
>          "menuTemplate" : [
>             {
>                "action" : "contentDialog",
>                "content" : "function(track,feature){return track.browser.plugins.FeatureSequence.callFxn(track, feature); }",
>                "iconClass" : "dijitIconPrint",
>                "label" : "View Feature Sequence"
>             }

using these command

`bin/flatfile-to-json.pl --gff docs/tutorial/data_files/volvox.gff3 --trackType CanvasFeatures --trackLabel Genes --menuTemplate '{content : function(track,feature){return track.browser.plugins.FeatureSequence.callFxn(track, feature); }, label : View Feature Sequence, action : contentDialog, iconClass : dijiIconBookmark}'`

What am i doing wrong?

what should i put the command in the terminal?
sometimes It is easier to add the information throught the terminal. so I would avoid to edit trackList.json

Thanks

**Comment by cmdcolin** [comment]
There is no "--menuTemplate" option, just the "--config" option (and also "--clientConfig" for modifying inside the "style" section)


```
    bin/flatfile-to-json.pl --gff docs/tutorial/data_files/volvox.gff3 --trackType CanvasFeatures --trackLabel Genes2 --config '{"menuTemplate": [{"content" : "function(track,feature){return track.browser.plugins.FeatureSequence.callFxn(track, feature); }", "label" : "View Feature Sequence", "action": "contentDialog", "iconClass" : "dijitIconBookmark"}]}' --out sample_data/json/volvox   
```

**Comment by cmdcolin** [comment]
I think I can close for now
