### ISSUE TITLE
How to sort alignment by start location and others as IGV does ?

### ISSUE THREAD

**Issue by jmercier-lbi** [GMOD/jbrowse#1400]
Dear,

To ease the mapping view we would like to sort alignment by start location ... and it  is done by IGV

Below Example show (i) the initial state, (ii) the context menu and (iii) finally the result from IGV

1. initial state

![igv_sort_alignment_by_0](https://user-images.githubusercontent.com/39800718/60884578-83448c80-a24d-11e9-82cb-5dbb1bca4101.png)

2.  context menu

![igv_sort_alignment_by_1](https://user-images.githubusercontent.com/39800718/60884586-88094080-a24d-11e9-8ad5-f5b4ea790532.png)

3.  Result

![igv_sort_alignment_by_2](https://user-images.githubusercontent.com/39800718/60884592-8b9cc780-a24d-11e9-9de2-83a60e249617.png)

Thanks for your help

best regards

**Comment by cmdcolin** [comment]
This is a little difficult just because of how JBrowse layouts work as far as I know, but is something that could be considered. It would probably just have to sort of destroy the current layout and redo it in the current view in a special way. It does seem very useful to obtain this visualization.

**Comment by rbuels** [comment]
Shouldn't be too hard to clear the layout and re-render with a different
sorting.  Could you add this as a feature req in the JB2 issues?

**Comment by jmercier-lbi** [comment]
Thanks for expertizing and your awesome works

**Comment by jmercier-lbi** [comment]
thanks @rbuels , should I do any action ?

**Comment by cmdcolin** [comment]
See maxime-bc comment, this feature was added to jbrowse 2 now (which is still alpha software). Likely won't be backporting unfortunately, but look forward to jbrowse 2!
