### ISSUE TITLE
How Can I change the name "Genome" from the menu bar

### ISSUE THREAD

**Issue by CCarine** [GMOD/jbrowse#1401]
Hi 
I would like to change the word Genome from the menu bar for my organism name.
![genome](https://user-images.githubusercontent.com/52763414/61008719-faede680-a335-11e9-80e7-69b2102899f7.png)

Any idea?
Thanks

**Comment by cmdcolin** [comment]
@CCarine I would recommend adding

classicMenu=true

To your jbrowse.conf

And then configuring the dataset selector

https://jbrowse.org/docs/faq.html#what-is-the-dataset-selector

This will do a little more than just change Genome to your organism name, but I think it will suit your purpose

**Comment by cmdcolin** [comment]
When you have done this, it will look something like this (where Volvox Example is what your species name could be)

![localhost_jbrowse__data=sample_data%2Fjson%2Fvolvox loc=ctgA%3A10224 10500 tracks=DNA%2Cvolvox-long_reads%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam highlight=](https://user-images.githubusercontent.com/6511937/61009153-ba936600-a33f-11e9-87a8-d45c6b74dcbe.png)

**Comment by CCarine** [comment]
Thanks :) it worked perfectly

**Comment by cmdcolin** [comment]
Cool glad it could help. I suppose close for now
