### ISSUE TITLE
dynamix error

### ISSUE THREAD

**Issue by Julianne95** [GMOD/jbrowse#1405]
Hi
I am using JBrowse 16.6, I installed Dynamix and I followed the whole manual https://git.embl.de/monfort/dynamix
When I run
 
`python2.7 dynamix add-dx-data -g genes_group --id lamu -f /media/jbrowse/scaffolds_277_to_1318txt --index-features --display-name="MO"`
it turns with this error

> Traceback (most recent call last):
>   File "dynamix", line 19, in <module>
>     __CURRENT_DIR = os.environ['PWD']
>   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
>     raise KeyError(key)
> KeyError: 'PWD'
> 
whats going on ?
Any idea?
Thanks

**Comment by cmdcolin** [comment]
We can't provide support for dynamix really, I would suggest posting this issue at the link you gave (I think there is an issue board there)

**Comment by cmdcolin** [comment]
If it's alright I'll close for now
