### ISSUE TITLE
missing documentation on config file for biodb-to-json.pl

### ISSUE THREAD

**Issue by theBowja** [GMOD/jbrowse#1407]
Hi,

At [this link](https://github.com/GMOD/jbrowse/wiki/JBrowse_Configuration_Guide#biodb-to-jsonpl), the quoted text has a link that leads to nowhere.

> This script uses a [config file](https://github.com/JBrowseDev/Current/Usage/ConfigFiles) to produce a set of feature tracks in JBrowse. It can be used to obtain information from any database with appropriate [schema](https://github.com/Glossary#Database_Schema), or from flat files. Because it can produce several feature tracks in a single execution, it is useful for large-scale feature data entry into JBrowse.

Furthermore, as a new user attempting to setup jbrowse, I am unable to determine what exactly I need in my config to [extract data from my Chado database](http://gmod.org/wiki/JBrowse_Configuration_Guide#Using_JBrowse_with_Existing_Databases). If anyone could explain maybe in simple steps I would appreciate it a lot. Thanks

**Comment by cmdcolin** [comment]
Hi there. The documentation for jbrowse is a little scattered all over the place. Currently the authoritative docs are on http://jbrowse.org/docs/biodb-to-json.pl.html

The github wiki version and the gmod.org wiki ones still exist just to avoid breaking all the links...kinda confusing i know


The docs are a little lacking in examples like simple sample configs for chado but here is an example from the mailing list archives

http://gmod.827538.n3.nabble.com/Gmod-ajax-Importing-from-Chado-DB-td4046821.html

**Comment by cmdcolin** [comment]
The idea from the config listed is that it will extract all mRNA features from chado, there are definitely other advanced configs that can be done. If you have specific needs let us know

**Comment by theBowja** [comment]
Thanks for finding an example. I tried running prepare-refseqs.pl with my conf file and it's telling me that 'relations "cv" does not exist'. I'm using tripal so my tables are actually prefixed with chado (chado.cv). I wonder how I can resolve this?

**Comment by theBowja** [comment]
Ok I resolved this by [altering the search path](https://stackoverflow.com/questions/2875610/permanently-set-postgresql-schema-path) for my user
ALTER ROLE drupal SET search_path TO "$user",public,chado;

**Comment by cmdcolin** [comment]
Good to know, I understand that tripal uses the multiple schemas to one database. I guess if that solution works that is great, there might be a way to configure biodb to also look in the chado schema also but I haven't checked.

If you want to contribute to the docs feel free to send PR to  https://github.com/GMOD/jbrowse/blob/master/docs/site/biodb_to_json.md and we can incorporate

**Comment by cmdcolin** [comment]
If it's alright I will close for now. Maybe we can try and restore that link in the future
