### ISSUE TITLE
fetch size limit exceeded BAM alignment file

### ISSUE THREAD

**Issue by nextgenusfs** [GMOD/jbrowse#1414]
Getting an error from a BAM file:
```
Error: data size of 207,938,862 bytes exceeded fetch size limit of 100,000,000 bytes
```
This seems to be different than the `chunkSize` errors that have been reported.  Is the `fetch size limit` something that can be adjusted?

**Comment by cmdcolin** [comment]
There is a parameter that can be set in the config called fetchSizeLimit that is sort of new. You can increase it in trackList.json or tracks.conf (however it's configured)

Possibly we could consider removing fetchSizeLimit as it's just arbitrary, and maybe even chunkSizeLimit as we're starting to get a better handle on some things that used to cause us problems (recent tabix and bam work for basically downloading the whole file has been in the works)

**Comment by nextgenusfs** [comment]
Cool, thanks!

**Comment by cmdcolin** [comment]
CLose for now, let me know if there are any other issues
