### ISSUE TITLE
Opening file with .fasta extension makes jbrowse desktop crash

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#1415]
The Browser.js checks for the extension of refSeq.url and if it is something like fai it uses it as the refSeq provider. This is pretty ok for fai since it is always fai, but unindexed fasta was added and it only checks for .fa, and crashes on .fasta

It should probably, if properly done, not use extension except as a heuristic (e.g. have refSeq.storeClass and refSeq.url being set) of course the heurstic will be kept for backwards compatibility and convenience though

**Comment by cmdcolin** [comment]
short term fix is to just rename .fasta to .fa before opening unindexed fasta in client

**Comment by cmdcolin** [comment]
only affects jbrowse desktop

**Comment by cmdcolin** [comment]
reported by @iankorf

**Comment by iankorf** [comment]
OK, so I'm changing all my *.fasta to *.fa, but I actually store as *.gz. New error though: doesn't get past the file load dialog even when the BGZIP file type is recognized properly. This is with a file named as *.fa.gz.

**Comment by cmdcolin** [comment]
With loading a bgzip refseq it requires to put three files, the file.fa.gz, the file.fa.gz.fai (eg. from running samtools faidx file.fa.gz), and the file.fa.gz.gzi (made from using bgzip -i)

It might be possible to give a better error message for when this isn't inputted right

**Comment by iankorf** [comment]
I now have a related problem. I can load a *.gff3 but not a *.gff3.gz. The latter looks like jbrowse is trying to read the *.gff3.gz as json. The error message looks similar to the *.fasta vs *.fa. Is there a better file extension than .gff3? I suppose I could solve all my file reading problems by keeping everything uncompressed, but I'd rather not.

I also have an unrelated problem in that the GFF3 file from TAIR10 has CDS features that reference protein sequences as parents, but those protein sequences are not part of the FASTA file.

"some features reference other features that do not exist in the file or in the same ### scope"

Do I have to remove protein parents from the GFF, add protein sequences to the FASTA, or is there some way for jbrowse to ignore such references?

**Comment by cmdcolin** [comment]
For gff3.gz it actually assumes that it is a bgzip'd gff3 file so it also wants a tabix index. Preparsing bgzip+tabix gff3 is a little intricate but can be done with various gff3 sorting tools and tabix

Also I think we saw this specific issue with TAIR here https://github.com/GMOD/gff-js/issues/4

I suggested perhaps making the GFF3 parser less strict to allow this but there is also a suggested command to help preprocessing at that link (including the gff3 sort)


Also thank you for providing all this feedback...it's very useful to hear about these problems especially related to jbrowse desktop

**Comment by cmdcolin** [comment]
I am not sure if that command addresses the CDS feature with protein parents but let me know if it does or if that seems relevant cc @nathanhaigh

**Comment by cmdcolin** [comment]
Fixed on dev branch, pending release
