### ISSUE TITLE
turn on tracks

### ISSUE THREAD

**Issue by Julianne95** [GMOD/jbrowse#1416]
Hi I am using Jbrowse
when I run jbrowse I have to select the tracks to  see them
I would like to know, How can I configure tracks.conf in such a way that when I run jbrowse I see the tracks selected and I do not have to select it to show them?
I hope I have made this sufficiently clear. 
Thanks

**Comment by cmdcolin** [comment]
Copied from an answer I wrote elsewhere:

>There are several options for tracks to load by default `defaultTracks`, `forceTracks`, and `alwaysOnTracks`. Example: you can add `defaultTracks=snps,genes,bam1,bam2` at the top of your tracks.conf. Note: defaultTracks is overridden by cookies/previous sessions, and forceTracks is overridden by URL lists of tracks, and alwaysOnTracks always loads the tracks, so these three options provide three different levels of forcing the track to be displayed.

Reference page:
http://jbrowse.org/docs/global_options.html

**Comment by Julianne95** [comment]
thanks @cmdcolin  it worked perfectly :D

**Comment by cmdcolin** [comment]
Glad to help :)
