### ISSUE TITLE
Add sequence search track: too long names

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#1417]
File -> Add sequence search track, input a sequences of about 20-30 bases

The label is solong that it covers the shown track!:
![1](https://user-images.githubusercontent.com/1146090/63004681-8a466680-bead-11e9-910e-fb09426c2555.jpg)

What should be better is:
![2](https://user-images.githubusercontent.com/1146090/63004759-b95cd800-bead-11e9-9ae5-01929a3b427e.jpg)

I think this could be done (input a short name) in the pop dijitDialog in future.

**Comment by colindaven** [comment]
+1 True, had same usability issue here

**Comment by cmdcolin** [comment]
I know this doesn't really answer the question but if you are doing serious sequence searches with JBrowse, I would recommend setting up a BLAT/BLAST backend e.g. with sequenceserver. I  think the RegexSequenceSearch doesn't necessarily scale too well and has some known issues with longer sequences #833

**Comment by cmdcolin** [comment]
I guess if it is desirable we can try and find fixes for things like #833 but that's just my perspective on sequence searching

**Comment by billzt** [comment]
@cmdcolin Thanks for your suggestion. How to setup a BLAT/BLAST backend within JBrowse? Would it be difficult?

**Comment by cmdcolin** [comment]
There is not necessarily a prescribed way to do this

It would be nice to have "recipes" for example, but I have only done it with sequenceserver https://jbrowse.org/docs/faq.html#how-can-i-link-blast-results-to-jbrowse

**Comment by billzt** [comment]
Well, infact I mainly use this "search" function to locate primer/oligo sequences in 10~30nt, which seem not suitable to be searched in BLAST.

**Comment by cmdcolin** [comment]
Maybe BLAT then, which would need a custom backend

**Comment by ValWood** [comment]
The label obscuring the data is an issue with many track types. 
https://github.com/pombase/website/issues/1596
Scrolling left and right the required amount to see the features and labels clearly is too tricky...

It would be nice if there was a bit of headroom between the label and the data track.

**Comment by cmdcolin** [comment]
One option that globally affects all tracks is setting

https://jbrowse.org/docs/global_options.html

trackLabels=no-block

In the jbrowse.conf. It is a valid concern. Might be interesting if the user can toggle this setting per track, or toggle the setting without having the admin reconfigure it

**Comment by cmdcolin** [comment]
Add the option to create your own track label to the dev branch of this repo

**Comment by cmdcolin** [comment]
feature added in 1.16.11
