### ISSUE TITLE
 BigWig track load slowly

### ISSUE THREAD

**Issue by jmsong2** [GMOD/jbrowse#1418]
Hi all,

I used add-bw-track.pl to add a new BigWig file to trackList.json and it worked. 
`../bin/add-bw-track.pl   --bw_url test.out.bg.bw  --label testbw --min_score 0 --max_score 500`

But I found that the track load slowly in browser (about 1 min per 10 Kb window).

Could you give me some advice to speed up that?  Thanks a lot!

- JBrowse version:  JBrowse 1.16.6
- Web browser being used: chrome
- Operating system if relevant: CentOS release 6.5

**Comment by cmdcolin** [comment]
Do you happen to have the ability to share the file? I am not sure what could cause very long load time offhand...is there anything unusual like it has a very large number of scaffolds?

**Comment by jmsong2** [comment]
Sure. This is my test BigWig file only including one scaffold. But my reference had ~3000 scaffolds.
http://rice.hzau.edu.cn/rice/download_ext/test.out.bg.bw

**Comment by cmdcolin** [comment]
I am able to load this file into a simple browser but I'd not seeing any slowness, it renders in less than 1 second at different scales

**Comment by jmsong2** [comment]
Amazing. Did you used the same add command ? This is my jbrowser url: http://cbi.hzau.edu.cn/rape/jbrowse/index.html?data=pan_ref2%2Fdata&loc=scaffoldA01%3A3071291..3078386&tracks=DNA%2Ctestbw&highlight=

It does load slowly. Any other reason?

**Comment by cmdcolin** [comment]
I can see when I visit your link that it loads slowly, yet with the same data on my local machine it loads pretty nice and fast locally. Do you think you have anything weird happening with firewall?

Locally there are 4 range requests for test.out.bg.bw http://localhost/jbrowse/?data=data&loc=scaffoldA01%3A3070371..3077466&tracks=test&highlight=
4 / 45 requests
1.0 MB / 9.9 MB transferred
1.0 MB / 9.9 MB resources
Finish: 1.9 min
DOMContentLoaded: 249 ms
Load: 797 ms

On your site it makes many more requests for the exact same region http://cbi.hzau.edu.cn/rape/jbrowse/index.html?data=pan_ref2%2Fdata&loc=scaffoldA01%3A3070371..3077466&tracks=DNA%2Ctestbw&highlight=
22 / 57 requests
7.5 MB / 9.1 MB transferred
7.5 MB / 10.9 MB resources
Finish: 1.3 min
DOMContentLoaded: 1.64 s
Load: 6.12 s

**Comment by cmdcolin** [comment]
One thing I can see is your server might be sending lots of "no cache" headers in the response, and this means that jbrowse is doing many re-requests for the data

**Comment by jmsong2** [comment]
Thank you very much. How can I reduce "no cache" headers in the response? And the jbrowse is still running with "flatfile-to-json.pl" in my Linux server. I am not sure whether it is related.

**Comment by cmdcolin** [comment]
This is a random idea but could you try an older version of jbrowse say 1.11.6?

**Comment by jmsong2** [comment]
OK. I will try it. Straightforward, is there any way that I can add BigWig or BedGraph file to "tracks" file instead of reading the raw file directly, like bed or gff with "flatfile-to-json.pl"? And then it also can finish showing density plot in jbrowse.

**Comment by cmdcolin** [comment]
I'm not sure what you mean exactly, can you elaborate

**Comment by jmsong2** [comment]
Sorry. If I want show a density plot in jbrowse, is there any other way to finish it except for using "add-bw-track.pl"?

**Comment by jmsong2** [comment]
I found that GFF and Bed tracks load quickly in my jbrowse. So I want to know if GFF or BedGraph could show in density plot style.

**Comment by cmdcolin** [comment]
If you made your file an actual BED the 5th column as score, you might be able to load the track with flatfile-to-json.pl  --trackType JBrowse/View/Track/Wiggle/Density  --bed yourfile.bed --trackLabel density_track I think.

If this has high density per-base pair data I think it will not be performant though

**Comment by jmsong2** [comment]
Thank you for advice. I will try it.

**Comment by jmsong2** [comment]
Hi, I changed Jbrowse version to JBrowse-1.12.3 and it worked well. Thanks again.

**Comment by cmdcolin** [comment]
Good to know, here is a possibly relevant issue so that we could address it in the latest versions of jbrowse https://github.com/rbuels/http-range-fetcher/issues/5
