### ISSUE TITLE
Changing track color according the length

### ISSUE THREAD

**Issue by ThomasLet** [GMOD/jbrowse#1420]
Hello,
I'm using JBrowse version 1.14 on chrome. I want to change my track color according to the track length and I'm using this code:
` {
         "compress" : 0,
         "key" : "sRNA",
         "label" : "sRNA",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature",
            "showLabels": false,
            "color": "function(feature) {return feature.length>30 ? 'blue':'red';}"
         },
         "trackType" : "CanvasFeatures",
         "type" : "CanvasFeatures",
         "urlTemplate" : "tracks/sRNA/{refseq}/trackData.json"
      },
`
It's not working because all my tracks all still red, no matter the lenght value, any idea ?

Regards,

Thomas

**Comment by cmdcolin** [comment]
Close for now, hope that helps :)
