### ISSUE TITLE
remove many tracks at the same time

### ISSUE THREAD

**Issue by Julboteroc** [GMOD/jbrowse#1422]
Hi
How can I remove many tracks at the same time?
Thanks

**Comment by cmdcolin** [comment]
Can you clarify what you are trying to accomplish? Are you referring to the command line tools or the user interface of jbrowse? There aren't any "bulk remove" in the UI but you could script something via the command line tools to bulk remove.

**Comment by Julboteroc** [comment]
Hi
@cmdcolin,  I am referring to the command line 
remove-track.pl --trackLabel  --delete
I have many trackLabels , and when I want to remove 10, I have to apply this command 10 times. Is there a way to remove it applying this command once (in a script) ?
Thanks

**Comment by cmdcolin** [comment]
I would just use bash scripting tools to accomplish this

`for i in tracklabel_1 tracklabel_2 tracklabel_3; do bin/remove-track.pl --trackLabel $i --delete; done;`

**Comment by cmdcolin** [comment]
If it's ok I'll close for now, let me know if this has problems
