### ISSUE TITLE
Chromatin interaction

### ISSUE THREAD

**Issue by yangyongsan-bio** [GMOD/jbrowse#1430]
I would like to ask JBrowse to show the interaction between the two regions. If so, how should we import the data?

**Comment by cmdcolin** [comment]
The sashimiplot plugin can draw an arc between two regions. It can load data from a simple bed file

Chr1 2000 3000 5

Would draw an arc between those two places with score 5

https://github.com/elsiklab/sashimiplot

It doesn't represent cross chromosomal interactions but could maybe add that with a vertical line or similar

**Comment by yangyongsan-bio** [comment]
Can this plugin be used with jbrowse?

**Comment by cmdcolin** [comment]
yes, that particular link is designed for use in jbrowse. setting up plugins involves using a github clone of jbrowse or the "dev" release, then run git clone https://github.com/elsiklab/SashimiPlot in the plugins folder then re-run setup.sh

you can test that it works by checking out http://localhost/jbrowse/?data=plugins/SashimiPlot/test/data after following those steps

**Comment by yangyongsan-bio** [comment]
Hello, I put the package downloaded from https://github.com/elsiklab/sashimiplot into the /plugins path and re-run setup.sh, but it seems to be bad
![图片](https://user-images.githubusercontent.com/55840134/65832709-1c89b900-e2fa-11e9-8183-d70453197f5c.png)

**Comment by cmdcolin** [comment]
Can you ensure that you are using a github clone of jbrowse or a "dev" release of jbrowse? That is needed for plugins

**Comment by cmdcolin** [comment]
Hi there, let me know if there is any more help I can add
