### ISSUE TITLE
Running JBrowse does not work

### ISSUE THREAD

**Issue by RaniaAssab** [GMOD/jbrowse#1431]
Good morning,

I have installed JBrowse in my computer (Ubuntu 18) and after running ./setup.sh, the volvox example format is done but the link it gives me **http://your.jbrowse.root/index.html?data=sample_data/json/volvox** does not work. I do not understand why...

Thank you very much in advance

Best regards,
Rania Assab

**Comment by cmdcolin** [comment]
Hi there, let me know if there is any update. I'll close for now

**Comment by RaniaAssab** [comment]
Hi 
,
Thank you very much!
I answer very very very late but yes I figured out that I had to change the name :)

Thank you again
