### ISSUE TITLE
maker2jbrowse slow?

### ISSUE THREAD

**Issue by ViriatoII** [GMOD/jbrowse#1437]
Hello,

I would like asking how long should I expect maker2jbrowse to run. I ran it for 18 hours with 2 CPUs and it didn't finish.   Is it faster if I specify these parameters?

>    --ds_index <file.log>, -d <file.log>
        Take filenames from a MAKER master datastore index file (e.g.
        my_genome_master_datastore_index.log).
    --sortMem int
        Set --sortMem for flatfile-to-json.pl

I have an input gff file of 2.5 Gb.

I have seen some issues related to large gff files, but didn't see runtimes.
https://github.com/GMOD/jbrowse/issues/626

Thank you,
Ricardo

**Comment by cmdcolin** [comment]
The flatfile-to-json step can be fairly time consuming for various reasons. One of them is a sort step that I sometimes wonder if it can be optimized or even removed if presorting can be ensured. Do you know what version you are using? Also for interest could you try with an older version of jbrowse in case there is a performance regression (say 1.11.6?)

If you have the test file it can help too...understandably it's a big file though

**Comment by ViriatoII** [comment]
Thank you, seems to be solved!
