### ISSUE TITLE
setup.sh having a problem with nodejs v12.x

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#1442]
Just been doing some test with setting up a new VM running JBrowse. I thought i'd test it with different versions of nodejs. Things work fine up to v10.x (LTS) but v12.x (LTS) fail with lots of v8 deprecation messages.

**Comment by cmdcolin** [comment]
Any specific version?

```
./setup.sh 
Gathering system information ...done.
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
Installing node.js dependencies and building with webpack ...done.
Installing Perl prerequisites ...done.

Formatting Volvox example data ...done.
To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.

Formatting Yeast example data ...done.
To see the yeast example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/yeast.
cdiesh-Precision-7540% nvm version
v12.10.0
```

**Comment by nathanhaigh** [comment]
I'm migrating my wheat jbrowse instance to a new VM so started to set it up with the same version of JBrowse (`v1.16.3`) but incremented the `nodejs` until it failed with `v12.x`. I'll test with a later version of JBrowse and report back.

**Comment by cmdcolin** [comment]
If you find a reproducible use case let me know :) maybe close for now
