### ISSUE TITLE
Unable to load  */jbrowse.conf status:0

### ISSUE THREAD

**Issue by jmsong2** [GMOD/jbrowse#1444]
Hi all,

This is my URL of jbrowser: http://cbi.hzau.edu.cn/bnapus/PanBrowser/index.html?data=panref%2Fdata

the JBrowse can be successfully visited in the my own network, 
but not the someone's network (such as some school nets).

They got the following error page:

```
Congratulations, JBrowse is on the web!
However, JBrowse could not start, either because it has not yet been configured and loaded with data, or because of an error.

If this is your first time running JBrowse, click here to follow the Quick-start Tutorial to show your data in JBrowse.

However, it appears you have successfully run ./setup.sh, so you can see the Volvox test data here.

Otherwise, please refer to the following resources for help in setting up JBrowse to show your data.

Quick-start tutorial - get your data visible quickly with minimum fuss
JBrowse Configuration Guide - a comprehensive reference
JBrowse wiki main page
biodb-to-json.pl configuration reference
HTMLFeatures CSS class reference - prepackaged styles (CSS classes) for HTMLFeatures tracks
Error message(s):
RequestError: Unable to load http://cbi.hzau.edu.cn/bnapus/PanBrowser/jbrowse.conf status: 0.
```

Could you give me some advices? 

Thanks a lot!

JBrowse version: JBrowse-1.12.3
Web browser being used: chrome
Operating system if relevant: CentOS release 6.5

**Comment by cmdcolin** [comment]
Status 0 failures are commonly due to firewall issues (or CORS, but CORS does not seem relevant)

This has been seen in several issues before https://github.com/GMOD/jbrowse/issues?q=is%3Aissue+firewall+is%3Aclosed

One recommendation included downgrading jbrowse to before jbrowse.conf existed. There could be other workarounds but if you have any control over the firewall this may be something to check

**Comment by jmsong2** [comment]
Thanks for your reply.
The "firewall" is firewall of web server which installed JBrowser or the windows firewall of other users?

**Comment by jmsong2** [comment]
This is my firewall information of web server.
```
root:~$ service iptables status
iptables: Firewall is not running.

```

**Comment by cmdcolin** [comment]
I can't necessarily say but it appears that since it is not visible to external users, it may be that the network of the institution is the issue

**Comment by jmsong2** [comment]
Thank you. I will communicate with the network administrator.

**Comment by cmdcolin** [comment]
If it's alright I'll close for now. If needed let me know if it needs reopening. There only other option is downgrading to before .conf files were used, it would be difficult to make the current code not use .conf files
