### ISSUE TITLE
GFF3Tabix histogram performance

### ISSUE THREAD

**Issue by Bjoernsen** [GMOD/jbrowse#1445]
I have 2 tracks for the same GFF3 file (360 MB). One uses the precalculated trackData.json, the second one uses the tabix index.

When I add the first track to a whole chromosome view, the histogram is rendered within 1 second.

When I add the second track (same zoom level), it takes 25-30 seconds to render all parts of histogram.

What can I do to improve the performance?

- JBrowse Version: 1.16.5
- Browse: Chrome, Firefox

first track:
```json
{
  "category" : "Annotation",
  "compress" : 0,
  "key" : "some.gff3",
  "label" : "some.gff3",
  "storeClass" : "JBrowse/Store/SeqFeature/NCList",
  "trackType" : "CanvasFeatures",
  "urlTemplate" : "tracks/some.gff3/{refseq}/trackData.json"
}
```

second track:
```json
{
   "category" : "Annotation",
   "compress" : 0,
   "key" : "some.gff3",
   "label" : "some.gff3",
   "storeClass" : "JBrowse/Store/SeqFeature/GFF3Tabix",
   "trackType" : "CanvasFeatures",
   "urlTemplate" : "path/to/some.gff3.gz"
}
```

**Comment by cmdcolin** [comment]
NCList tracks has pre-calculated histograms so they are fast, and GFF3Tabix has some performance characteristics that will make it much slower for histograms. It's unfortunate aspect of GFF3Tabix, but it does something called redispatching and generally doesn't really have fast histogram calculation. GFF3Tabix in general can be slower than NClist if performance is a concern. I can elaborate on this if you're interested but I'd also suggest you want histograms I'd recommend making a pre-calculated histogram for GFF3Tabix

    [tracks.yourtrack]
    urlTemplate=yourfile.gff.gz
    type=CanvasFeatures
    histograms.storeClass=JBrowse/Store/SeqFeature/BigWig
    histograms.urlTemplate=yourfile.coverage.bw

**Comment by cmdcolin** [comment]
In the above configuration yourfile.coverage.bw can be manually pre-calculated e.g. use bedtools genomecov, then bedGraphToBigWig or similar

**Comment by Bjoernsen** [comment]
@cmdcolin The BigWig way works like a charm. Thank you!
