### ISSUE TITLE
dontRedispatch not working

### ISSUE THREAD

**Issue by juancrescente** [GMOD/jbrowse#1447]
In JBrowse 1.16.6 I cannot hide the chromosome features in a gff.

Thius is my gff setup

[tracks.genes]
csiUrlTemplate=Triticum_aestivum.IWGSC.45.clean.sorted.gff3.gz.csi
dontRedispatch=chromosome
type=CanvasFeatures
key=Annotation
urlTemplate=Triticum_aestivum.IWGSC.45.clean.sorted.gff3.gz
storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
category=IWGSC RefSeq

This is the live setup
http://165.227.95.85/jbrowse/?loc=1B%3A273132420..273132489&tracks=refseq%2CWSC-2-5%2Cgenes&highlight=

**Comment by cmdcolin** [comment]
dontRedispatch is not designed to hide features but to optimize the request

If you know that your track contains genes and that's all you care about, you can set

topLevelFeatures=gene

**Comment by cmdcolin** [comment]
(that optimization, just for more info, is to not try to fetch subfeatures of the "chromosome" feature, which would otherwise require downloading everything between the start and end of the "chromosome" feature)

**Comment by juancrescente** [comment]
got it! thanks!
