### ISSUE TITLE
Error !!! loading bam file !!!!!

### ISSUE THREAD

**Issue by rapaJiahe** [GMOD/jbrowse#1448]
Hello jbrowse team,

i can't add bam file into tracks. I gave the specific error message below.
![IR2K@FEN_OIK93X0`{TRK8O](https://user-images.githubusercontent.com/45040790/68865732-3f4b2200-072e-11ea-8c8b-dbf4d3ba9b9d.png)

{
         "urlTemplate" : "bamfile/Chiifu_v1.5_to_TUE.sorted.bam",
         "key" : "Chiifu_v1.5_to_TUE.sorted.bam",
         "type" : "JBrowse/View/Track/Alignments2",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "label" : "Chiifu_v1.5_to_TUE.sorted.bam"
    }

version： Release 1.16.6     2019-07-12 01:20:19 UTC

I hope to get your help.

**Comment by Trandamere** [comment]
hi
 How do you fix it?
