### ISSUE TITLE
'incorrect header check' after running generate-names.pl

### ISSUE THREAD

**Issue by jamesabbott** [GMOD/jbrowse#1449]
# Pre-requisites

Please try clearing your browser cache and refreshing to see if this affects your error

Done...didn't help!

# Creating an issue

If you are creating a new issue please report

- JBrowse version: 1.16.6
- Web browser being used: Opera and firefox - same result
- Operating system if relevant: CentOS 6.10
- If it is setup related, setup.log

I'm just setting up a new instance and have my reference sequence (human chr1), and gff annotations from ensembl which were displaying fine. Having now run generate_names.pl (both without arguments, and with --hashBits 16 --completionLimit 0) I now get a popup in the annotation track reporting 'Error: Incorrect header check'. 

Looking in the apache error log shows entries such as coinciding with the requests:

[Thu Nov 14 17:15:03 2019] [error] [client 10.205.128.26] File does not exist: /servers/private/EDC_exomes/jbrowse/data/names/dfa/9.json

The names directory does contain a considerable number of hashed directory names and a meta.json file, but dfa does indeed not contain 9.json.
The browser console shows (with paths made relative for legibility):

error: incorrect header check
    at unzip (jbrowse/dist/0.bundle.js:8:387339)
    at t.<anonymous> (jbrowse/dist/0.bundle.js:14:243891)
    at l (jbrowse/dist/0.bundle.js:8:271255)
    at Generator._invoke (jbrowse/dist/0.bundle.js:8:271043)
    at Generator.t.<computed> [as next] (jbrowse/dist/0.bundle.js:8:271677)
    at r (jbrowse/dist/0.bundle.js:8:124221)
    at s (jbrowse/dist/0.bundle.js:8:124419) Error: incorrect header check
    at unzip (0.bundle.js:8)
    at t.<anonymous> (0.bundle.js:14)
    at l (0.bundle.js:8)
    at Generator._invoke (0.bundle.js:8)
    at Generator.t.<computed> [as next] (0.bundle.js:8)
    at r (0.bundle.js:8)
    at s (0.bundle.js:8)

which suggets to me it's trying to unzip something, although I didn't use the --compress option, and I doubt it relates to the bgzipped gff file since these worked fine until I ran generate_names.pl

Any suggestions as to what is going wrong here?

Many thanks
James

**Comment by cmdcolin** [comment]
Hi there

This is pretty weird. If you can run the code in "development mode" e.g. from a github clone of jbrowse, we can get better error messages. It's hard to see. I somehow doubt that this is related to the generate-names, as this code is specifically from the bgzip parsing and none of the generate-names.pl code uses bgzip parsing

Sorry for the delayed reply

I

**Comment by cmdcolin** [comment]
@jamesabbott any updates?

**Comment by cmdcolin** [comment]
I would clear cache or regenerate the tabix index, most often I have seen that be the cause of the problem because then the code that fetches the chunks of the tabix data gets a invalid chunk causing "incorrect header check" from the internal gzip code

Let me know if that helps
