### ISSUE TITLE
html formatting in CanvasVariants mouse over?

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1450]
- JBrowse 1.16.6
- Chrome

I have a function I have been using with CanvasVariants track. It used to nicely format the returned string in my mouse hover, now it gets displayed exactly as printed including the html. How can I nicely format my hover?

Thank you,
Sofia

```
getImpact  = function( feature ) {
    var ann = feature.get('ANN');
    var ann_str = ann['values'][0];
    var ann_array = ann_str.split('|');
    var snpeff_gene_name = ann_array[3];
    var snpeff_transcript_name = ann_array[6];
    var snpeff_impact = ann_array[2];
    var snpeff_region = ann_array[1];
    var variant_description = feature.get('description');
    return "<strong><u>" + variant_description +  "</u></strong></span><br><strong>Impact</strong>: " +snpeff_impact + "<br><strong>Type</strong>: " + snpeff_region + "<br><strong>Gene Name</strong>: " + snpeff_gene_name + "<br><strong>TranscriptID</strong>:" + snpeff_transcript_name ;
  }
```

**Comment by cmdcolin** [comment]
The "unsafeMouseover": true on the track config will enable this

 It was a recently change to add this flag, sorry for the breakage

It could probably have been rolled out a bit differently, but that config will fix it

**Comment by srobb1** [comment]
@cmdcolin 
Perfect!! Thanks! It definitely fixed it.

Sofia
