### ISSUE TITLE
Questions from a potential user

### ISSUE THREAD

**Issue by hexylena** [GMOD/jbrowse#1451]
I have a user (@mvdbeek) who loves IGV but would switch if the following features were present? Maybe some of these exist and I can point them to the documentation, otherwise, maybe potential hackathon/hacktoberfest ideas for new contributors?

- Highlighting by arbtirary read tags
- Highlighting Soft-clipped reads (or showing the clipped portion in lighter grey)
- Jumping between read mates
- Quick extraction of mapped regions (select region, right click, and you can download a bam?)

**Comment by cmdcolin** [comment]
We'd love to support any and all use cases. Currently I would say these scenarios are not streamlined in jbrowse

1) You can use color callbacks to make arbitrary tag highlighting. For example making style.color=function(feature) { return feature.get('RG') === 1 ? 'green': 'red' } <-- that type of thing for making a custom color highlight
2) Displaying soft clipped reads is feature that I wasn't aware of but seems important to many users, but in any case it's not available in jbrowse 1
3) There is a currently built in right-click->jump to mate feature, but not a split screen, its a new tab or new iframe popup
4) There is not data extract in SAM/BAM, there is the "Save track data" default built in reserialization as GFF just as it exists for all feature tracks. Save track data can do whole track, region you are looking at, or currently highlighted region


These are good thoughts. We are currently developing jbrowse 2, so it's hard to actively work on these in jbrowse 1 but PR and similar are quite welcome

**Comment by cmdcolin** [comment]
Some of these features will be prioritzed in jbrowse 2 rather than jbrowse 1. Probably close for now. Things like "sort by base" and similar igv-isms are starting to be incorporated to jbrowse 2, with further stuff ahead

**Comment by hexylena** [comment]
Sounds good :+1:
