### ISSUE TITLE
What is the purpose of having tabix GFF? 

### ISSUE THREAD

**Issue by asumann** [GMOD/jbrowse#1453]
I use JBrowse version 1.16.6-desktop on macOS. I want to understand the purpose of using tabix.

I followed the steps for indexing gff. That I unzipped the resulted gz file. Then I uploaded sorted gff that comes after unzipping of gz file. Nothing has changed for size of the file I uploaded to see annotations. It has only become sorted which was done even before tabix. Finally, JBrowse open the two files(sorted and unsorted) at the same time. Maybe I am missing a step before uploading the indexed file.

So my question: What is the purpose of using tabix for gff files? 

As it can be clear from my question, I am a novice in bioinformatics. Yet, I count on the community here. Hope I can hear any help.

**Comment by cmdcolin** [comment]
Hi there
The purpose of tabix indexing, and most indexing in general, is it allows your to skip to only the part of the file that you need. When you use gff3tabix, this can allow jbrowse to do quick coordinate range queries. With plain gff, it actually has to read the whole file into memory

I hope that helps explain the purpose. If you have any further questions on the specifics of how you open that data let me know

**Comment by asumann** [comment]
Thanks a lot for the background about indexing and for your prompt reply!!

Let me go step by step for uploading indexed gff:
I sort my gff- zip - tabix. Then I open the zipped file and upload sorted gff. However, it does open the file as quick as it does for the same file before indexing. I want to know if what I am doing is the correct way to open indexed files. If not, I would love to hear more about the process. Thanks again!!

**Comment by cmdcolin** [comment]
If you are able to view your data in both indexed and unindexed form, I'd just say whichever feels comfortable. I'd probably by default switch to indexing if your data is bigger than say 5MB although I haven't benchmarked those numbers

**Comment by cmdcolin** [comment]
Close for now, feel free to ask any other questions tho
