### ISSUE TITLE
VCF track doesn't load from remote server: 'error decompressing chunk....'

### ISSUE THREAD

**Issue by vaneet-lotay** [GMOD/jbrowse#1454]
I'm using JBrowse v1.16.6 on the Chrome browser within Windows.  I've added configuration stanzas for 4 VCF variants tracks in JBrowse under the Xenopus tropicalis 9.1 genome.  While testing the tracks, when I load them from a folder within the same server which JBrowse is installed in, all 4 load just fine.

Because of storage concerns, we wanted to store the VCF and other large files on a remote virtual machine server, but we mounted the server on to a folder within the JBrowse main directory in the JBrowse machine.  We've currently loaded many other bigwig tracks succesfully using this mounted server folder with no issues, they all load fine in JBrowse.  When I try to load the 4 VCF files using this mounted folder from the remote virtual machine, 2 of them load fine, the other 2 fail with this error message shown below in the screenshot.  I also included the console log from the Chrome browser if that helps.

![VCF_bug](https://user-images.githubusercontent.com/40072920/70075064-3e810f80-15b9-11ea-9686-128fe2100783.png)

The files have been archived using bgzip with index files created by tabix on the remote server.  Is there something that doesn't work well in the decompression when reading the file from a remote server? Is there any way to load VCF files directly in their unzipped form, if that helps?  Because we would have the storage space for that.  Please let me know how I can fix this issue....Thanks!

**Comment by cmdcolin** [comment]
@vaneet-lotay do you have a link to the instance by chance? Feel free to email me if it helps

**Comment by vaneet-lotay** [comment]
I'm setting up a private test instance to replicate the issue, will e-mail it to you when it's ready

**Comment by vaneet-lotay** [comment]
Hey Colin,

Well I guess I fixed the problem myself when I was setting up test instances of the issue.  I think I didn't compress them properly most likely.  Sorry for the disruption

**Comment by cmdcolin** [comment]
Glad ya figured it out :)
