### ISSUE TITLE
Use jbowser as a node module using jb_run.js.cmd When running, returns "Cannot GET /"

### ISSUE THREAD

**Issue by reBiocoder** [GMOD/jbrowse#1455]
![TZNHY0~UZ1(}GI J@E2 _V1](https://user-images.githubusercontent.com/39401819/72674587-6e299f80-3ab3-11ea-96ac-7ece23bf0ed3.png)
![JMYWDSZ{C_3UC{GAXTTBP4S](https://user-images.githubusercontent.com/39401819/72674605-944f3f80-3ab3-11ea-935e-6d5c5caf858a.png)

**Comment by cmdcolin** [comment]
The command is sensitive to the relative directory it is run in, so possibly from the SiteFront directory

    .\node_modules\.bin\jb_run.js.cmd

See https://github.com/GMOD/jbrowse#installing-as-an-npm-module

**Comment by reBiocoder** [comment]
> The command is sensitive to the relative directory it is run in, so possibly from the SiteFront directory
> 
> ```
> .\node_modules\.bin\jb_run.js.cmd
> ```
> 
> See https://github.com/GMOD/jbrowse#installing-as-an-npm-module

thanks!

**Comment by reBiocoder** [comment]
> The command is sensitive to the relative directory it is run in, so possibly from the SiteFront directory
> 
> ```
> .\node_modules\.bin\jb_run.js.cmd
> ```
> 
> See https://github.com/GMOD/jbrowse#installing-as-an-npm-module

thank you very much! But`node_modules\.bin\jb_setup.js.cmd`   isn't  running,
![ST $H6D4TH2V8(O> The command is sensitive to the relative directory it is run in, so possibly from the SiteFront directory
> 
> ```
> .\node_modules\.bin\jb_run.js.cmd
> ```
> 
> See https://github.com/GMOD/jbrowse#installing-as-an-npm-module

thank you very much! But`node_modules\.bin\jb_setup.js.cmd`   isn't  running:


![Z4%S FGJU _I0LNUFXV`VFH](https://user-images.githubusercontent.com/39401819/72675521-5ad10100-3ac0-11ea-9b16-fe3c8580d98f.png)


![98GB1L7Y6MWG9J4}Y IT@)Q](https://user-images.githubusercontent.com/39401819/72675514-3c6b0580-3ac0-11ea-8b08-ed44362df187.png)


I don't know what happened

**Comment by cmdcolin** [comment]
jb_setup.js runs a bash shell script called setup.sh. the main thing it does is install perl dependencies. running jb_setup.js  does not work on windows.  sorry but jbrowse has a long history of only running on linux type systems. 

note that jbrowse is setup for you now and can "run" per se, but you just can't run flatfile-to-json.pl and prepare-refseqs.pl and such. you can still load data using things like this tutorial though http://jbrowse.org/docs/tutorial.html

it's tough to provide windows support so I'd probably recommend switching to linux but if this stage of things suffices then that is good

**Comment by reBiocoder** [comment]
> jb_setup.js运行一个名为setup.sh的bash shell脚本。它的主要作用是安装perl依赖项。在Windows上无法运行jb_setup.js。抱歉，jbrowse有很长的历史，只能在linux类型的系统上运行。
> 
> 请注意，jbrowse现在已为您设置，并且本身可以“运行”，但是您不能运行flatfile-to-json.pl和prepare-refseqs.pl等。您仍然可以通过http://jbrowse.org/docs/tutorial.html使用本教程中的内容加载数据[](http://jbrowse.org/docs/tutorial.html)
> 
> 提供Windows支持很困难，所以我可能会建议切换到linux，但是如果这个阶段足够，那很好
thank you!
