### ISSUE TITLE
After embedding jbrowser into an webpage using iframe, height and width cannot be adaptive

### ISSUE THREAD

**Issue by reBiocoder** [GMOD/jbrowse#1456]
After embedding jbrowser into an webpage using iframe, height and width cannot be adaptive

![@R$Y0X8(Y`1$G 94OM%1TPA](https://user-images.githubusercontent.com/39401819/72682591-8c21ef00-3b09-11ea-941f-fa341e744ac5.png)

error:
1.bundle.js:1 JBrowse container element #GenomeBrowser has no width, please set one with CSS. Setting fallback width of 640 pixels

2.JBrowse container element #GenomeBrowser has no height, please set one with CSS. Setting fallback height of 480 pixels

**Comment by cmdcolin** [comment]
Can you show how it is embedded in the HTML?

**Comment by reBiocoder** [comment]
![0NV(Z@BGHX4JM01LGQJEOJQ](https://user-images.githubusercontent.com/39401819/72705729-2ed47f00-3b97-11ea-918b-ef387942f058.png)


> Can you show how it is embedded in the HTML?

![0NV(Z@BGHX4JM01LGQJEOJQ](https://user-images.githubusercontent.com/39401819/72705754-3c8a0480-3b97-11ea-9ac6-bdea4cbdb3e9.png)

code:
`<div class="layui-tab-item">
      <iframe  height="800px" width="800px"  frameborder="0" src="http://119.23.246.30:8003/index.html?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A1..9999&tracks=DNA%2Cvolvox-paired_bam%2Cvolvox-sorted_cram%2Cvolvox-long_reads&highlight=ctgA%3A23606..23705%20(%2B%20strand)%20(ctgA_23606_24017_4%3A0%3A0_1%3A1%3A0_d77)"></iframe></div>
`

**Comment by reBiocoder** [comment]
> Can you show how it is embedded in the HTML?

Sorry i just saw the news

**Comment by cmdcolin** [comment]
If I make an iframe exactly like this I don't see the same error weirdly enough...I may have slightly different setup e.g. I don't know what class="layui-tab-item" is, maybe when the tab is not focused it causes issues...


![_home_cdiesh_src_gmod_jbrowse_test html](https://user-images.githubusercontent.com/6511937/72754846-2aec3100-3b86-11ea-8f5a-228247869102.png)

**Comment by reBiocoder** [comment]
> If I make an iframe exactly like this I don't see the same error weirdly enough...I may have slightly different setup e.g. I don't know what class="layui-tab-item" is, maybe when the tab is not focused it causes issues...
> 
> ![_home_cdiesh_src_gmod_jbrowse_test html](https://user-images.githubusercontent.com/6511937/72754846-2aec3100-3b86-11ea-8f5a-228247869102.png)

Thanks! Because vue.js has a little problem in the tab conversion of css
