### ISSUE TITLE
trackMetadata url: why not relative to data directory?

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/jbrowse#1457]
Hi,

I raise a question sent one year ago on gmod-ajax@lists.sourceforge.net: https://sourceforge.net/p/gmod/mailman/message/36516621

I wonder why the URL for metadata sources is relative to the JBrowse directory and not to the directory where the configuration file (trackList.json) is located, as is the case for all other url parameters in trackList.json (`urlTemplate`) ? Is there a reason for that ? Maybe because one single metadata source was intended to be used for all data repositories ?

I have one different trackMetadata file for each of my ~100 data repositories (~100 strains) which I would like to put into the related data repository (next to trackList.json), and I do not find it wise for maintenance reason to have a piece of absolute path (between the JBrowse and the data repository) in my trackList.json.

I guess I can use symbolic links to avoid using the path into the trackList.json, but whatever, I will have to manage this path somewhere.

Extract from http://jbrowse.org/docs/track_metadata.html#track-metadata-options: 

> "-url - a URL (relative to JBrowse root directory, or absolute URL)"

TrackList.json configuration exemple :

```
{
 "trackMetadata": {
     "sources": [
          { "type": "csv", "url": "data/private/species/this_particular_strain.csv" }
     ]
},
   "tracks" : [
      {
         "category" : "Reference sequence",
         "chunkSize" : 20000,
         "label" : "DNA",
         "seqType" : "dna",
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "type" : "SequenceTrack",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-"
      },
      {
         "compress" : 0,
         "label" : "this_strain.gff",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : "CanvasFeatures",
         "type" : "CanvasFeatures",
         "urlTemplate" : "tracks/this_strain.gff/{refseq}/trackData.json"
      },
      {
         "autoscale" : "local",
         "bicolor_pivot" : "zero",
         "label" : "bwFilename.bw",
         "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
         "type" : "JBrowse/View/Track/Wiggle/XYPlot",
         "urlTemplate" : "flat_data/RNAseq/coverage/RNAseq_this_strain_conditionX.bw"
      }
]
}
```

For the `trackMetadata` configuration, I would like to be able to write:

```
"trackMetadata": {
     "sources": [
          { "type": "csv", "url":  "this_particular_strain.csv" }
     ]
},
```

Thanks

**Comment by cmdcolin** [comment]
This is a good question, and thanks for "driving the issue forward" after over a year of asking

I made a possible solution here for solving this, it uses "relativeUrl" instead of "url" for backwards compatibility https://github.com/GMOD/jbrowse/pull/1458

**Comment by cmdcolin** [comment]
If you want to test that out on this branch that would be great. I think we are about due for a new jbrowse 1 release soon so would be good to get that in

**Comment by cmdcolin** [comment]
Thanks so much, fixed on dev pending release
