### ISSUE TITLE
Switching BAM track to coverage cannot be undone

### ISSUE THREAD

**Issue by hexylena** [GMOD/jbrowse#1459]
- JBrowse version: 1.16.5
- Web browser being used: Firefox 71.0
- Operating system if relevant: Ubuntu

![afbeelding](https://user-images.githubusercontent.com/458683/72829219-a7fad180-3c7e-11ea-85b0-28ebef928fe4.png)

Switching the track visualisation type to other types works...except for switching to coverage. There the menu changes, irreversibly (until you refresh the page), and you cannot change it back to another track visualisation type (cloud, pairs, etc)

![afbeelding](https://user-images.githubusercontent.com/458683/72829271-c2cd4600-3c7e-11ea-97aa-5350742bff85.png)

**Comment by cmdcolin** [comment]
The "View alignments" is supposed to switch it back, does that work?

**Comment by hexylena** [comment]
Yep, that works exactly. I'm sorry I missed that, I was looking for the identical menu of  "Track viz types" and didn't think to even try that option, was just missing the switcher I used for the other 4/5 types. Ok, I guess this isn't a bug but just strange. Thanks for the quick reply
