### ISSUE TITLE
SyntaxError: Unexpected token < when parsing null/trackList.json.

### ISSUE THREAD

**Issue by reBiocoder** [GMOD/jbrowse#1460]
![P
{(_V$RXN6JY~}@BU8V%Y](https://user-images.githubusercontent.com/39401819/73132313-7609b680-4054-11ea-9940-034debb58780.png)

**Comment by cmdcolin** [comment]
Can you describe more what caused this to happen?

**Comment by reBiocoder** [comment]
> Can you describe more what caused this to happen?
When I upload a .fna file, it returns an error
![1 H5Y %BW_{V{MKH}31YV6E](https://user-images.githubusercontent.com/39401819/73157510-2d1d3500-411c-11ea-821f-e2f9c7bb9a1f.png)

**Comment by cmdcolin** [comment]
What version of JBrowse do you have? I am not seeing this problem on my version (latest, or really any 1.16.* version)

**Comment by reBiocoder** [comment]
> What version of JBrowse do you have? I am not seeing this problem on my version (latest, or really any 1.16.* version)
i use vue.js build this project.i add this Folder.in one component.
![EW`QC %61@USVA JNLID3_7](https://user-images.githubusercontent.com/39401819/73329394-87db9b80-4298-11ea-945f-0546a59b298f.png)
The entire jbrowse project was put in my static folder,
![QX L~HTA3)(EE(ML4C R2FH](https://user-images.githubusercontent.com/39401819/73329450-b78aa380-4298-11ea-9922-89b4a376b87f.png)

**Comment by cmdcolin** [comment]
Do you see this same error if you try this on http://jbrowse.org/code/JBrowse-1.16.6

**Comment by reBiocoder** [comment]
> Do you see this same error if you try this on http://jbrowse.org/code/JBrowse-1.16.6

Thank you, it may be a problem that I did not understand myself, I tried to read the documentation again.
