### ISSUE TITLE
Embedding credentials in URL

### ISSUE THREAD

**Issue by wccropper** [GMOD/jbrowse#1461]
- JBrowse 1.16.7
- Firefox/Chrome
- Host: CentOS7, Client: Mac & ArchLinux

Unable to add tracks using embedded username/password in a webdav url. Complains about the embedded credentials. The URL with embedded credentials does work with the Linux Desktop client. The URL is a webdav in front of iRODS using davrods.

**Comment by cmdcolin** [comment]
>Complains about the embedded credentials

Is there an error message?

I am also wondering if there is some better way of doing thi also like a proper "iRODS or cyverse jbrowse plugin" that properly authenticates or something...I had imagined something like this before but wasn't sure what might help. Just an idea though

**Comment by wccropper** [comment]
![jbrowse_error_tobe_anonymized](https://user-images.githubusercontent.com/18536217/73480423-7610fb80-435f-11ea-946d-02ec158032af.png)

**Comment by rbuels** [comment]
Browsers are removing support for URLs with embedded credentials, since they don't view them as good security practice.

A JBrowse 1 plugin for this would seem to be the way forward here, if there is a developer willing to take it on.

**Comment by cmdcolin** [comment]
This is not a JBrowse issue per se, so maybe close for now. let us know if theres anything that we can do though
