### ISSUE TITLE
Jbrowse vertical lines

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1463]
How can I remove the background vertical lines from the view. I need to do this for someone who wants to take some images for publication, then I can set bring them back up. 

Thank you,
Sofia

**Comment by rbuels** [comment]
This is a hack but if you need to do this for just a one-off thing you can run this snippet in the web browser development tools:

`document.querySelectorAll('.gridline').forEach(n => n.parentNode.removeChild(n))`

**Comment by srobb1** [comment]
PERFECT!!!!!!!!!! This is exactly what I needed.

Thank you!
