### ISSUE TITLE
Browser only displays the last Dataset 

### ISSUE THREAD

**Issue by ilaydabozan** [GMOD/jbrowse#1467]
I'm trying to upload couple reference genomes and using Dataset Selector to achieve this.
When I try to navigate through the site even though URL is updated only the last dataset entry is displayed in the browser. I tried deleting and adding new ones but regardless it is always the last one. Selecting any genome from the Genome dropdown menu also doesn't show up the right result it shows the last dataset.
How can I fix this issue? 

Best,
Ilayda

**Comment by cmdcolin** [comment]
Can you paste your configuration for the dataset selector?

**Comment by ilaydabozan** [comment]
This is my jbrowse.conf;

#### JBrowse main configuration file

## uncomment the section below to customize this browser's title and description
#  [aboutThisBrowser]
#  title = <i>Oryza sativa</i>
#  description = Browser for O. sativa transcripts and RNA-seq data,
#    produced by the Smith laboratory at Example State University.

## uncomment and edit the example below to configure a faceted track selector
#  [trackSelector]
#  type = Faceted
#  displayColumns =
#    + label
#    + key
#    + organism
#    + technique
## optionally sort the faceted track selector by column (use the names from displayColumns)

# initialSortColumn=label

## optionally give different names to some of the data facets using renameFacets
#  [trackSelector.renameFacets]
#  submission = Submission ID
#  developmental-stage = Conditions
#  cell-line = Cell Line
#  key = Dataset
#  label = Track

# # uncomment this section to get hierarchical trackselector options
# [trackSelector]
# # optionally turn off sorting for the hierarchical track selector
# sortHierarchical = false
## set collapsed categories for the hierarchical track selector
# collapsedCategories = Reference sequence,Quantitative / XY Plot
## set category ordering in the hierarchical track selector
# categoryOrder = BAM, Transcripts, Quantitative/Density, VCF

## configure where to get metadata about tracks.  always indexes the
## `metadata` part of each track config, but this can be used to load
## additional metadata from CSV or JSON urls
# [trackMetadata]
# sources = data/trackMetadata.csv


[GENERAL]


## add a document.domain to set the same-origin policy
# documentDomain=foobar.com

## use classic jbrowse menu with file instead of track and genome
#classicMenu = true

## hide open genome option
#hideGenomeOptions = true

## enable or disable high resolution rendering for canvas features. set to auto, disabled, or numerical scaling factor. default: 2
# highResolutionMode=auto

## uncomment to change the default sort order of the reference
## sequence dropdown
# refSeqOrder = length descending

## Uncomment to prevent HTML tracks from displaying gene subfeatures (enabled by default)
# inferHTMLSubfeatures = false

## to set a default data directory other than 'data', uncomment and
## edit the line below
# dataRoot = data

## optionally add more include statements to load and merge in more
## configuration files

include = {dataRoot}/potato-adj1/data/trackList.json
include += {dataRoot}/potato-adj1/data/tracks.conf

include += {dataRoot}/potato-adj2/data/trackList.json
include += {dataRoot}/potato-adj2/data/tracks.conf

include += {dataRoot}/potato-ajh/data/trackList.json
include += {dataRoot}/potato-ajh/data/tracks.conf

include += {dataRoot}/potato-cha/data/trackList.json
include += {dataRoot}/potato-cha/data/tracks.conf

include += {dataRoot}/potato-cur/data/trackList.json
include += {dataRoot}/potato-cur/data/tracks.conf

include += {dataRoot}/potato-gon1/data/trackList.json
include += {dataRoot}/potato-gon1/data/tracks.conf

include += {dataRoot}/potato-gon2/data/trackList.json
include += {dataRoot}/potato-gon2/data/tracks.conf

include += {dataRoot}/potato-juz/data/trackList.json
include += {dataRoot}/potato-juz/data/tracks.conf

include += {dataRoot}/potato-buk/data/trackList.json
include += {dataRoot}/potato-buk/data/tracks.conf

include += {dataRoot}/potato-phu/data/trackList.json
include += {dataRoot}/potato-phu/data/tracks.conf

include += {dataRoot}/potato-tbr/data/trackList.json
include += {dataRoot}/potato-tbr/data/tracks.conf

include += {dataRoot}/potato-stn/data/trackList.json
include += {dataRoot}/potato-stn/data/tracks.conf

# include += ../url/of/my/other/config.json
# include += another_config.conf

## uncomment and edit the example below to enable one or more
## JBrowse plugins
# [ plugins.MyPlugin ]
# location = plugins/MyPlugin
# [ plugins.AnotherPlugin ]
# location = ../plugin/dir/someplace/else

## edit the datasets list below to add datasets to the jbrowse dataset
## selector

[datasets.adg1]
url  = ?data={dataRoot}/potato-adj1/data/
name = Adg1

[datasets.adg2]
url  = ?data={dataRoot}/potato-adj2/data/
name = Adg2

[datasets.ajh]
url  = ?data={dataRoot}/potato-ajh/data/
name = Ajh

[datasets.cha]
url  = ?data={dataRoot}/potato-cha/data/
name = Cha

[datasets.cur]
url  = ?data={dataRoot}/potato-cur/data/
name = Cur

[datasets.gon1]
url  = ?data={dataRoot}/potato-gon1/data/
name = Gon1

[datasets.gon2]
url  = ?data={dataRoot}/potato-gon2/data/
name = Gon2

[datasets.juz]
url  = ?data={dataRoot}/potato-juz/data/
name = Juz

[datasets.buk]
url  = ?data={dataRoot}/potato-buk/data/
name = Buk

[datasets.phu]
url  = ?data={dataRoot}/potato-phu/data/
name = Phu

[datasets.tbr]
url  = ?data={dataRoot}/potato-tbr/data/
name = Tbr

[datasets.stn]
url  = ?data={dataRoot}/potato-stn/data/
name = Stn

# [datasets.modencode]
# url  = ?data=sample_data/json/modencode
# name = MODEncode Example

# [datasets.yeast]
# url  = ?data=sample_data/json/yeast
# name = Yeast Example

----------------------------------
Example trackList.json

{
   "formatVersion" : 1,
   "refSeqs" : "seq/renamed.l200_tbr_contigs.reduced.fa.fai",
   "tracks" : [
      {
         "category" : "S. tuberosum subsp. tuberosum (TBR)",
         "faiUrlTemplate" : "seq/renamed.l200_tbr_contigs.reduced.fa.fai",
         "key" : "S. tuberosum subsp. tuberosum (TBR)",
         "label" : "DNA",
         "seqType" : "dna",
         "storeClass" : "JBrowse/Store/SeqFeature/IndexedFasta",
         "type" : "SequenceTrack",
         "urlTemplate" : "seq/renamed.l200_tbr_contigs.reduced.fa",
         "useAsRefSeqStore" : 1
      }
   ]
}

-----------------------------
Example tracks.conf

[general]
dataset_id = tbr

---------------------------

Thank you!

**Comment by cmdcolin** [comment]
Alrighty, so there are a couple sort of odd things about your setup

You should not have {dataRoot} in your dataset configs I think

https://jbrowse.org/docs/dataset_selector.html

E.g. just have

``
[datasets.adg1]
url  = ?data=potato-adj1/data/
name = Adg1
```

Then once you navigate to this URL e.g. http://localhost/jbrowse/?data=potato-adj1/data


Then JBrowse will AUTOMATICALLY load potato-adj1/data/trackList.json. It is not necessary for you to configure, via the includes in jbrowse.conf, to manually load those files

**Comment by cmdcolin** [comment]
Let me know if that makes sense or if I can clarify further

**Comment by ilaydabozan** [comment]
I deleted the {dataRoot}

**Comment by ilaydabozan** [comment]
{dataRoot} is specified in the embedded HTML for the browser. When I deleted the {dataRoot} mentions as you suggested it didn't make any changes. And when I delete the includes in jbrowse.conf I believe it is not able to automatically find the trackList.json because the browser fails to load.

Was I able to understand your points?

**Comment by cmdcolin** [comment]
You do need at least two includes to get the default behavior, that being the default lines in the jbrowse.conf saying include+={dataRoot}/tracks.conf include+= {dataRoot}/trackList.json 

That may be the source of some confusion. I'd recmmend hjust leaving those as is and not touching them :)

The way they work is that, when you navigate to your specific data directory, these are the lines that cause it to incldue tracks.conf and trackList.json inside that specific data directory.

Now to fix your setup I created a data directory called potato-adj1/data which looks like so

```
➜  jbrowse git:(dev) ✗ find potato-adj1
potato-adj1
potato-adj1/data
potato-adj1/data/seq
potato-adj1/data/seq/refSeqs.json
potato-adj1/data/seq/e94
potato-adj1/data/seq/e94/19a
potato-adj1/data/seq/e94/19a/a1
potato-adj1/data/seq/e94/19a/a1/ctgB-0.txt
potato-adj1/data/seq/704
potato-adj1/data/seq/704/8cb
potato-adj1/data/seq/704/8cb/1b
potato-adj1/data/seq/704/8cb/1b/ctgA-1.txt
potato-adj1/data/seq/704/8cb/1b/ctgA-2.txt
potato-adj1/data/seq/704/8cb/1b/ctgA-0.txt
potato-adj1/data/trackList.json
potato-adj1/data/tracks.conf
```

Then the trackList is just default, no hand editing

potato-adj1/data/trackList.json
```
{
   "formatVersion" : 1,
   "tracks" : [
      {
         "category" : "Reference sequence",
         "chunkSize" : 20000,
         "key" : "Reference sequence",
         "label" : "DNA",
         "seqType" : "dna",
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "type" : "SequenceTrack",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-"
      }
   ]
}

```

The tracks.conf contains the hand edited dataset_id

potato-adj1/data/tracks.conf

```
[GENERAL]
dataset_id=adg1

```



Then we have the jbrowse.conf which has all the datasets (I turned on classicMenu=true because I like that too)

```
#### JBrowse main configuration file

## uncomment the section below to customize this browser's title and description
# [aboutThisBrowser]
# title = <i>Oryza sativa</i>
# description = Browser for O. sativa transcripts and RNA-seq data,
#   produced by the Smith laboratory at Example State University.

## uncomment and edit the example below to configure a faceted track selector
# [trackSelector]
# type = Faceted
# displayColumns =
#   + label
#   + key
#   + organism
#   + technique
## optionally sort the faceted track selector by column (use the names from displayColumns)
# initialSortColumn=label
## optionally give different names to some of the data facets using renameFacets
# [trackSelector.renameFacets]
# submission = Submission ID
# developmental-stage = Conditions
# cell-line = Cell Line
# key = Dataset
# label = Track

## uncomment this section to get hierarchical trackselector options
# [trackSelector]
## optionally turn off sorting for the hierarchical track selector
# sortHierarchical = false
## set collapsed categories for the hierarchical track selector
# collapsedCategories = Reference sequence,Quantitative / XY Plot
## set category ordering in the hierarchical track selector
# categoryOrder = BAM, Transcripts, Quantitative/Density, VCF

## configure where to get metadata about tracks.  always indexes the
## `metadata` part of each track config, but this can be used to load
## additional metadata from CSV or JSON urls
# [trackMetadata]
# sources = data/trackMetadata.csv


[GENERAL]
classicMenu=true

## add a document.domain to set the same-origin policy
# documentDomain=foobar.com

## use classic jbrowse menu with file instead of track and genome
#classicMenu = true

## hide open genome option
#hideGenomeOptions = true

## enable or disable high resolution rendering for canvas features. set to auto, disabled, or numerical scaling factor. default: 2
# highResolutionMode=auto

## uncomment to change the default sort order of the reference
## sequence dropdown
# refSeqOrder = length descending

## Uncomment to prevent HTML tracks from displaying gene subfeatures (enabled by default)
# inferHTMLSubfeatures = false

## to set a default data directory other than 'data', uncomment and
## edit the line below
# dataRoot = data

## optionally add more include statements to load and merge in more
## configuration files
include  = {dataRoot}/trackList.json
include += {dataRoot}/tracks.conf
# include += ../url/of/my/other/config.json
# include += another_config.conf

## uncomment and edit the example below to enable one or more
## JBrowse plugins
# [ plugins.MyPlugin ]
# location = plugins/MyPlugin
# [ plugins.AnotherPlugin ]
# location = ../plugin/dir/someplace/else

## edit the datasets list below to add datasets to the jbrowse dataset
## selector

# [datasets.volvox]
# url  = ?data=sample_data/json/volvox
# name = Volvox Example

# [datasets.modencode]
# url  = ?data=sample_data/json/modencode
# name = MODEncode Example

# [datasets.yeast]
# url  = ?data=sample_data/json/yeast
# name = Yeast Example
[datasets.adg1]
url  = ?data=potato-adj1/data/
name = Adg1

[datasets.adg2]
url  = ?data=potato-adj2/data/
name = Adg2

[datasets.ajh]
url  = ?data=potato-ajh/data/
name = Ajh

[datasets.cha]
url  = ?data=potato-cha/data/
name = Cha

[datasets.cur]
url  = ?data=potato-cur/data/
name = Cur

[datasets.gon1]
url  = ?data=potato-gon1/data/
name = Gon1

[datasets.gon2]
url  = ?data=potato-gon2/data/
name = Gon2

[datasets.juz]
url  = ?data=potato-juz/data/
name = Juz

[datasets.buk]
url  = ?data=potato-buk/data/
name = Buk

[datasets.phu]
url  = ?data=potato-phu/data/
name = Phu

[datasets.tbr]
url  = ?data=potato-tbr/data/
name = Tbr

[datasets.stn]
url  = ?data=potato-stn/data/
name = Stn




```

Then going to http://localhost/jbrowse/ has the dataset selector

![localhost_jbrowse__data=potato-adj1%2Fdata%2F loc=ctgA%3A23819 23880 tracks=DNA highlight=](https://user-images.githubusercontent.com/6511937/74189317-26171c00-4c1e-11ea-8129-dd3fafe79352.png)
![localhost_jbrowse_](https://user-images.githubusercontent.com/6511937/74189318-26171c00-4c1e-11ea-90ee-3063cb16ae47.png)

**Comment by ilaydabozan** [comment]
Hello,

First of all I'd like to thank you for taking your time and explaining the process to me step by step. I got everything to work. 
I believe I was having the issue because I was trying to do it with HTML embedded Jbrowse, and it did not work, but once I tried it on the full page (default index.html) Jbrowse it worked flowless. 

Thank you again for your time and effort.
Ilayda
