### ISSUE TITLE
Unable to load file jbrowse.conf

### ISSUE THREAD

**Issue by callum-b** [GMOD/jbrowse#1480]
I just recently dowloaded and unzipped JBrowse 1.16.5 from [here](http://jbrowse.org/blog/2019/06/12/jbrowse-1-16-5.html). I ran setup.sh, no problem, but when I open ~/JBrowse-1.16.5/index.html with firefox (Mozilla Firefox 68.5.0esr), it gives me the message:
### Congratulations, JBrowse is on the web!
However, JBrowse could not start, either because it has not yet been configured and loaded with data, or because of an error.
RequestError: Unable to load file:///home/my.name/JBrowse-1.16.5/jbrowse.conf?v=0.9392181756672745 status: 0.

I am using it through an ssh -X connection, onto a debian 10 server.
I doubt this is a setup issue, but I'll include [setup.log](https://github.com/GMOD/jbrowse/files/4306683/setup.log) anyways. Perl gives me warnings but no error messages.

**Comment by cmdcolin** [comment]
JBrowse requires a web server to work, so just opening up file:///path/to/jbrowse/index.html doesn't work. There are some small number of features that can work without a web server but it really does need it. I suggest booting up a simple HTTP server and running JBrowse inside it (JBrowse is just static js and css but it uses things like HTTP range requests which requires a web server to interpret, the filesystem cannot interpret those)

See https://jbrowse.org/docs/faq.html#what-webserver-is-needed-for-jbrowse

**Comment by cmdcolin** [comment]
If you want to try to force the usage of the filesystem you can edit index.html and set cacheBuster: false and it may get a little farther into the loading

**Comment by callum-b** [comment]
Yes, it was a webserver issue. My bad for not catching that I guess.
It could be useful to include a message such as "Have you checked your webserver parameters?" in the error message somewhere to help clueless people like me.

**Comment by cmdcolin** [comment]
Glad that helps. I agree it would be good to have some error. I'll maybe close for now though! Let us know if there are any other issues
