### ISSUE TITLE
off exon when zoomed out, on exon when zoomed in

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#1483]
- JBrowse version: 1.16.8
- Web browser being used: Chrome

From Grove at wormbase:

< Hi all, I'm not sure this warrants a ticket, but I wanted to get some feedback on a minor visual Alliance variant JBrowse issue. I was looking at a worm gene model (the slo-1 gene) in JBrowse with the Variants track loaded. I was quite zoomed out so that I could see most or all of the gene, and when I hover my cursor over the coordinates indicator I get the red line that shows you how features line up along the gene model. What I noticed is that when zoomed out, two variants (eg142 and ky389) appear to be missense variants but look like they are exclusively within introns. Zooming in, however, it is clear that these are definitely positioned within exons, it's just that they appear to be in introns when zoomed out. My suspicion is that the variant glyph has its left-most edge aligned perfectly with the coordinate for the variant, rather than being glyph-center-aligned, therefore when aligning the diamond glyph through its center to the gene model when you're zoomed out, it looks as though the variant actually lies in an intron. I'm attaching some screenshots of these variants when zoomed out and zoomed in. Would it be possible to make sure the variant (and other) glyphs align precisely with the genome coordinate through the exact center of the glyph, instead of with the left-most edge?

https://stage.alliancegenome.org/jbrowse/?data=data%2FCaenorhabditis%20elegans&tracks=Variants%2CAll%20Genes&highlight=&lookupSymbol=pg52&loc=V%3A18482709..18517777

![image](https://user-images.githubusercontent.com/751274/76351608-fa458f80-62ca-11ea-80d3-dcddd2937dcd.png)

When zoomed in:

https://stage.alliancegenome.org/jbrowse/?data=data%2FCaenorhabditis%20elegans&tracks=Variants%2CAll%20Genes&highlight=&lookupSymbol=pg52&loc=V%3A18504826..18505341

![image](https://user-images.githubusercontent.com/751274/76351619-016c9d80-62cb-11ea-92c1-67e0839cb22b.png)

Another example:

https://stage.alliancegenome.org/jbrowse/?data=data%2FCaenorhabditis%20elegans&tracks=Variants%2CAll%20Genes&highlight=&lookupSymbol=pg52&loc=V%3A18485345..18520413

![image](https://user-images.githubusercontent.com/751274/76351687-1f3a0280-62cb-11ea-97c9-ef0ca0a63b30.png)

and when zoomed in: 

https://stage.alliancegenome.org/jbrowse/?data=data%2FCaenorhabditis%20elegans&tracks=Variants%2CAll%20Genes&highlight=&lookupSymbol=pg52&loc=V%3A18492242..18493089

![image](https://user-images.githubusercontent.com/751274/76351725-2f51e200-62cb-11ea-859b-30a5bb6b514c.png)

**Comment by nathandunn** [comment]
FYI @cmdcolin  this is the thing we'd talked about.

**Comment by cmdcolin** [comment]
I think this is not a bug with jbrowse strictly but more to do with the diamond glyph. The diamond glyph is likely extending to the right of the actual feature boundaries rather than being centered on it

IIRC the Diamong glyph used here is not one that is packaged in jbrowse

**Comment by nathandunn** [comment]
I think I'm going to close this one then unless @scottcain  re-opens it.

**Comment by nathandunn** [comment]
thanks!
