### ISSUE TITLE
EMBL GenBank export/ question

### ISSUE THREAD

**Issue by ValWood** [GMOD/jbrowse#1498]
I know this  is probably not something you a particularly want to do, but our biologist users sometimes ask about exporting GenBank EMBL format files. Is this  on the cards/likely?

**Comment by ValWood** [comment]
background https://github.com/pombase/website/issues/1509

I can't find any option to download gff. Can you point me to that>

**Comment by cmdcolin** [comment]
generally speaking, our roadmap is 95% working on jbrowse 2, not a lot of time for jbrowse 1 currently.  that said, we definitely welcome PR to this repo and will review and accept and make occasional releases. if this is highly desirable, we'd love a PR! happy to help onramp anyone interested in trying to add this feature too.

**Comment by rbuels** [comment]
There is existing support for downloading GFF, however. Click a track's
menu (the down-arrow next to its label) and then click the "save track
data" menu option.

**Comment by ihh** [comment]
@ValWood further to Rob and Colin's comments, if someone wanted to add GenBank export as an option, they would probably do well to start looking at the GFF3 export driver code in here: https://github.com/GMOD/jbrowse/tree/3c78cd6fca67730a256c468b8ccb227df5b629e8/src/JBrowse/View/Export

**Comment by ValWood** [comment]
Hi @ihh  it isn't something we would have time to look at right now (probably around ~500 on  @kimrutherford , our solo developer's huge TODO list ). A few  PomBase users have enquired over  the past years (a few anonymously in our survey so it isn't possible to find out exactly why they need EMBL/GenBank), and somebody asked via the HD last week- soI thought I'd have a look if anything was easily available. The particular enquirer located what the needed from Ensembl  and was happy  so I closed the ticket at our end.  However, if you  ever do this , let us know and we will announce to the  PomBase community, but happy for you to close this ticket if it isn't on you radar.  I think it's only something biologists who have grown up with the format are still using :) If I could find out why they want it I could probably reeducate them.


We are however updating our FAQ to explain how to export feature regions in gff ;)

**Comment by cmdcolin** [comment]
I would imagine we will close for now since we got a workaround :)
