### ISSUE TITLE
support Hi-C data？

### ISSUE THREAD

**Issue by shenweima** [GMOD/jbrowse#1499]
I see a jbrowse support hic data, but I don't know whether our jbrwose support it.This is the website [delta](http://delta.big.ac.cn/jbrowse/index.html?data=1499137860032&loc=11%3A3160001..9505000&tracks=TAD%2CInteraction%2CLCR_Gene%2CLCR%2CGM12878_H2AZ_signal&organism=hg19&sb=90&highlight=)
![image](https://user-images.githubusercontent.com/8536868/81363032-e07ec800-9114-11ea-9713-971a7c7188be.png)
And the [ configuration   information ](http://delta.big.ac.cn/circosweb/pages/download/genome_view.pdf)
I have gff3 format ,but I don't know how to do, Could you give me some suggestions?

**Comment by cmdcolin** [comment]
I don't know the details of this browser but you could use https://github.com/elsiklab/sashimiplot it is just made for drawing arcs

**Comment by cmdcolin** [comment]
It looks like they use server side rendered tiles which would be harder to configure than just something like sashimiplot

**Comment by cmdcolin** [comment]
Look at the BEDTabix configuration for sashimiplot, that is the easiest to setup IMO

**Comment by cmdcolin** [comment]
An example of drawing a hic contact matrix could possibly be adapted from code in https://github.com/elsiklab/multivariantviewer also

**Comment by shenweima** [comment]
Thanks，I will try sashimiplot in bed format. But,I am not sure  the detail of  bed file.

**Comment by cmdcolin** [comment]
Probably just simple 5 column bed (chr,start,end,name,score) should work, it also uses strand column 6 if available but that should be optional

**Comment by cmdcolin** [comment]
Feel free to add issue to sashimiplot if there are any updates
