### ISSUE TITLE
JBrowse shows an error if all the features are on one strand.

### ISSUE THREAD

**Issue by ValWood** [GMOD/jbrowse#1500]
JBrowse shows an error if all the features are on one strand.

See
https://github.com/pombase/website/issues/784

Previously we made this go away by flagging the conflicts in the reverse strand, but with the new mitochondrial genome we no longer have any strand independent features.

Any suggestions?

CC @kimrutherford

**Comment by cmdcolin** [comment]
Added a comment on #784, it would be related to the server returning a HTTP 200 for something that should be given a 404 error I believe

**Comment by kimrutherford** [comment]
Returning 404 fixed things.  Thanks for your help Colin.

**Comment by cmdcolin** [comment]
No worries :)
