### ISSUE TITLE
BigBED file is not showing subparts

### ISSUE THREAD

**Issue by fbemm** [GMOD/jbrowse#1502]
- JBrowse version --> 1.16.8
- Web browser being used --> Firefox
- Operating system if relevant --> Ubuntu

I am trying to create Gene Annotation Track from a BigBED file. 
The file was generate by CAT and works with the UCSC assemblyHubs.

```
       {
           "category" : "Annotation",
           "key" : "CAT Consensus",
           "label" : "CAT Consensus",
           "storeClass" : "JBrowse/Store/SeqFeature/BigBed",
           "type" : "CanvasFeatures",
           "urlTemplate" : "consensus.bb",
           "style.label" : "gene_name,name,id",
           "style.description" : "gene_biotype"
       }
```

What I see is:

![Screenshot from 2020-05-15 15-29-13](https://user-images.githubusercontent.com/8361254/82055488-dd5d7c00-96c0-11ea-8f4c-1d703e751513.png)

Details show that there are blocks defined:

![Screenshot from 2020-05-15 15-25-28](https://user-images.githubusercontent.com/8361254/82055523-eb130180-96c0-11ea-8a0a-0ab8693602c5.png)
![Screenshot from 2020-05-15 15-26-08](https://user-images.githubusercontent.com/8361254/82055524-ebab9800-96c0-11ea-8151-55b09f7bc381.png)

Is there something that needs to be configured that the subparts are actually shown?

Thx,
F

**Comment by cmdcolin** [comment]
you might have to add this to your track config

    "glyph": "JBrowse/View/FeatureGlyph/UCSC/BED"

**Comment by fbemm** [comment]
Indeed! Thx

These kind of tracks will stay not draggable in WebApollo correct?

**Comment by cmdcolin** [comment]
Yes it's true this won't be draggable. It used to be the we could
