### ISSUE TITLE
Bam file caused: An error was encountered when displaying this track

### ISSUE THREAD

**Issue by Trandamere** [GMOD/jbrowse#1503]
Hi:
I had a problem loading the BAM file.
![QQ截图20200519163015](https://user-images.githubusercontent.com/24996924/82303940-3ba29b80-99ee-11ea-9dc3-e6b34eee9387.png)
```
add-bam-track.pl --bam_url Sex.sorted.bam --label PH1-sex --key "ph1-sort-sex" -i trackList.json
```

```
      {
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "urlTemplate" : "Sex.sorted.bam",
         "type" : "JBrowse/View/Track/Alignments2",
         "key" : "ph1-sort-sex",
         "label" : "PH1-sex"
      }
```

**Comment by cmdcolin** [comment]
It is important to have a webserver to "run" jbrowse on, because opening jbrowse up by just double clicking index.html in your file explorer won't work with things like bam files. See https://jbrowse.org/docs/faq.html#what-webserver-is-needed-for-jbrowse

**Comment by Trandamere** [comment]
Thank you！
