### ISSUE TITLE
representing newlines in the track metadata

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/jbrowse#1504]
- JBrowse version: 1.16.1
- Web browser being used: chrome (83.0.4103.61)

Apologies if this has been documented elsewhere... In previous versions of Jbrowse (1.12.4), I was able to represent newlines in the track metadata (in the `trackList.json` file) using `<br>` tags:
<img width="634" alt="Screen Shot 2020-05-22 at 11 34 58 AM" src="https://user-images.githubusercontent.com/5487172/82694353-5b210a80-9c20-11ea-8bc3-88e8903891f5.png">

This isn't possible in Jbrowse 1.16.1 anymore (note the `<br>` tags displaying):

<img width="1139" alt="Screen Shot 2020-05-22 at 11 35 53 AM" src="https://user-images.githubusercontent.com/5487172/82694403-6bd18080-9c20-11ea-818d-7a934d06cccc.png">
 

Do you have any suggestions for formatting newlines in the newest jbrowse versions?

Here's the metadata snippet if it helps:

```
         "metadata" : {
            "Track legend" : "These Tophat RNA-seq mapping results are displayed so that the parts corresponding to the actual reads are colored in dark blue while the introns spanning the predicted splicing sites are light blue. Indels and substitutions identified during the mapping are also color marked:<br>Red - deletion in the read relative to the reference<br>Green - insertion in the read relative to the reference<br>Yellow - mismatch (hover over the mismatch to see what the snp is)"
         },
```

Thanks for the help!

**Comment by cmdcolin** [comment]
You can add "unsafePopup" to the track config to fix this

I know this could be pretty annoying if you have many tracks. It might be that we can add a quick fix that makes this a global setting or even does away with this with a smarter sanitize-html plugin

But unsafePopup is a works-right-now solution

**Comment by mpoelchau** [comment]
Thanks @cmdcolin!

Dumb question: Where do I put unsafePopup in trackList.json? (We aren't using tracks.conf right now)

**Comment by cmdcolin** [comment]
It would look like

```
{
"urlTemplate": "yourfile",
"label": "yourlabel",
"unsafePopup": true
}
```

Also certainly don't feel pressure to use tracks.conf, it's just an alternative config format

**Comment by mpoelchau** [comment]
Thanks for the feedback, @cmdcolin ! 

Another dumb question - does "unsafePopup" imply that the html in my tracklist.json file is a security risk - and if so, are there guidelines on how to change it?

**Comment by cmdcolin** [comment]
If you were to use this setting on a uncontrolled input from http://notmysite.com/malicious_file.gff and the file got replaced with some stuff that had HTML in the gff column 9, it might render `<script>alert('you got hacked'); maybe_steal_your_cookies()</script>` 

It's fairly low risk and you control your gff. I also think that potentially we could use a method such as html sanitization instead of unsafePopup type flags, as that would basically remove the need for this flag in all but the wildest cases where you want to include script in your gff column 9...
