### ISSUE TITLE
The display of strand specific RNA seq

### ISSUE THREAD

**Issue by Trandamere** [GMOD/jbrowse#1505]
Hi:
   Does the JBrowse display the strand specific RNA seq like this?
![QQ截图20200524163510](https://user-images.githubusercontent.com/24996924/82749644-2efeb880-9ddd-11ea-95af-aa6fc493bda4.png)
I  didn't find the parameters in the add-bam-track.pl

**Comment by Trandamere** [comment]
![QQ截图20200524163510](https://user-images.githubusercontent.com/24996924/82749692-856bf700-9ddd-11ea-80ca-2134233d553e.png)

**Comment by cmdcolin** [comment]
You can use the colorByOrientation option. There isn't a special command line option for this in add-bam-track.pl but you can use

    bin/add-bam-track.pl --label test --bam_url volvox-sorted.bam --in sample_data/json/volvox/trackList.json --config '{"colorByOrientation": true}'

**Comment by Trandamere** [comment]
Hi:
 the --config '{"colorByOrientation": true}' dosen't worlk
```
add-bam-track.pl --bam_url Coni_1.bam --label Coni_1.bam --key "Coni_1.bam" -i trackList.json --config '{"colorByOrientation": true}'
```
The BAM file's color is gone
![QQ截图20200524203313](https://user-images.githubusercontent.com/24996924/82754603-7a768e00-9e00-11ea-96e4-098eb74c46d2.png)
My bam file like this:
![QQ截图20200524204519](https://user-images.githubusercontent.com/24996924/82754607-87937d00-9e00-11ea-94f5-9b3ff549a70e.png)
Should i use the 'useXS'?

**Comment by cmdcolin** [comment]
Sorry I identified the wrong config

colorByOrientation is specific to paired-end mispairings and showing badly paired reads e.g. each pair pointing in the same direction

For paired-end stranded RNA-seq you might want

"useReverseTemplate": true


This variable is the most likely one to result in the expected coloring, but requires, again, paired end and stranded RNA-seq


You could also try

useXS: true


useXS infers the strandedness of the reads that are splice aligned, so only the reads that cross a splice junction will have the color, based on that XS tag in the BAM


But dont use both at the same time

**Comment by Trandamere** [comment]
Tnank you 
I's work with useXS: true
