### ISSUE TITLE
Cannot load BAM files

### ISSUE THREAD

**Issue by abs-yy** [GMOD/jbrowse#1512]
Hi, I've been trying to start a JBrowse 1.16.9 at my new web server (CentOS Linux release 7.5.1804 (Core)), but I haven't been able to load BAM files.
The setup.sh seems to have worked out fine, but when I load the sample data I can't visualize only the BAM files. I'm using a Mac, and in Safari (13.1) I get a error saying "Error: problem decompressing block: incorrect gzip header check" and in Google Chrome (83.0.4103.61) I get "HTTP undefined when fetching http://***/JBrowse-1.16.9/sample_data/raw/volvox/volvox-samspec.bam bytes 0-262143". Cleaning up the cache did not change anything. Remaking the bam index didn't either.

Is there any requirement's that I missed that I messed up during the install?

Thanks for the help!

**Comment by cmdcolin** [comment]
Might be related to https://jbrowse.org/docs/alignments.html#apache-configuration-note

The error message changed when we made our bam parser an npm module but I think it might apply

**Comment by abs-yy** [comment]
Worked like a charm!
Thank you!
