### ISSUE TITLE
Scheduling time get overwritten when mention in default_args

### ISSUE THREAD

**Issue by vikrant-sinha** [GMOD/jbrowse#1516]
I was trying schedule a dag with schedule_interval as part of default_args using cron expression like ```"0 5 * * *" ``` but it gets over written by default ```timedelta(days=1) ```, then mention it as dag argument instead and it works fine.

**Comment by cmdcolin** [comment]
Is this question about jbrowse?

**Comment by vikrant-sinha** [comment]
I am sorry , wrong repo :(
