### ISSUE TITLE
About the callback function of color（CanvasFeatures）

### ISSUE THREAD

**Issue by reBiocoder** [GMOD/jbrowse#1520]
# Pre-requisites

Please try clearing your browser cache and refreshing to see if this affects your error

# Creating an issue

If you are creating a new issue please report

- JBrowse version
1.16.9
- Web browser being used
chrome
- Operating system if relevant
- If it is setup related, setup.log
- question
my code:
` ./bin/flatfile-to-json.pl --gff GCF_000155635.1.gff --trackLabel "999" --trackType CanvasFeatures --out test_data/ --config '{"impliedUTRs": true}' --clientConfig '{"color": "function(feature) { console.log(feature)}"}'
`
Console:
![8XDKG_}KHJCG}9Q_V(RBCJ8](https://user-images.githubusercontent.com/39401819/85923421-733e1680-b8bd-11ea-92d0-8fb9e5eb6d8a.png)

so,i don't use `feature.get('type')`  to get "mRNA,CDS and gene..."

why? Thank you!

**Comment by cmdcolin** [comment]
You can use feature.get('type')

That array structure is not meant to be accessed by hand, it is called an nclost, you use feature.get('type') and other properties to use it

**Comment by reBiocoder** [comment]
> You can use feature.get('type')
> 
> That array structure is not meant to be accessed by hand, it is called an nclist typed array, you use feature.get('type') and other properties to use it
but when i use code ` --clientConfig '{"color": "function(feature) { console.log(feature.get('type'))}"}'`, browser get error:
![11EK( FT)L)`DU06VO27{ X](https://user-images.githubusercontent.com/39401819/85924236-72a87e80-b8c3-11ea-9ef3-a56d1fc71997.png)

**Comment by garrettjstevens** [comment]
@reBiocoder looks like the single quotes around `'type'` are getting removed:
```
$ echo '{"color": "function(feature) { console.log(feature.get('type'))}"}'
{"color": "function(feature) { console.log(feature.get(type))}"}
```

 This might work: `--clientConfig $'{"color": "function(feature) { console.log(feature.get(\'type\'))}"}'`

**Comment by cmdcolin** [comment]
You can see that you have so for quotes I side of single quotes in your command. That may result in something weird happening. You may need to escape the quotes on the command line. You can hand edit the trackList.json file also

**Comment by reBiocoder** [comment]
> You can see that you have single quotes inside of single quotes in your command. That may result in something weird happening. You may need to escape the quotes on the command line. You can hand edit the trackList.json file also


thank you very much!

**Comment by reBiocoder** [comment]
> @reBiocoder looks like the single quotes around `'type'` are getting removed:
> 
> ```
> $ echo '{"color": "function(feature) { console.log(feature.get('type'))}"}'
> {"color": "function(feature) { console.log(feature.get(type))}"}
> ```
> 
> This might work: `--clientConfig $'{"color": "function(feature) { console.log(feature.get(\'type\'))}"}'`



thank you very much!
