### ISSUE TITLE
After initializing the page, the left tracks column is not automatically checked

### ISSUE THREAD

**Issue by reBiocoder** [GMOD/jbrowse#1521]
i use `flatfile-to-json.pl` create a data set,but when i open url: `http://127.0.0.1:8002/data=data`, i find left tracks are not automatically checked.
![W6 EL4H IOTDL}RM1@TVWB3](https://user-images.githubusercontent.com/39401819/85935478-ea0dfa80-b923-11ea-929b-646a6f88aa33.png)

How do I make the tracks automatically checked when the page is initialized？

**Comment by cmdcolin** [comment]
You can use defaultTracks or forceTracks or alwaysOnTracks, these are global config options http://jbrowse.org/docs/global_options.html

These configs take a string that is a comma separated list of track labels (see label in the trackList.json)

Alternatively you can add the track label to the URL

http://127.0.0.1:8002/?data=data&tracks=trackLabel1

**Comment by reBiocoder** [comment]
@cmdcolin  thank you,cmdcolin!  But I have another question： I can highlight the gene I am currently querying？  
![3DL%)JBVX6_YQQF 3EHE0DG](https://user-images.githubusercontent.com/39401819/85937448-3c581700-b936-11ea-8e06-1a4f7aa31d76.png)

**Comment by cmdcolin** [comment]
there is  not really anything built in like that. there is a url parameter called highlight but it doesnt highlight specific features, just regions

**Comment by reBiocoder** [comment]
> there is not really anything built in like that. there is a url parameter called highlight but it doesnt highlight specific features, just regions


This project is already great, thank you very much！
