### ISSUE TITLE
Can loops called from CHIA-PET/HI-CHIP data can be load into JBrower ？

### ISSUE THREAD

**Issue by kunproj** [GMOD/jbrowse#1522]
Hi,

I am using JBrowser for the first time and encountered some problems.
I have 'loops file' called from CHIA-PET/HI-CHIP data and want to visualize in the browser, 

My 'loops file' format like this:
[likp@genome ~]$ less my_intra.loop_counts.bedpe

chr22 17056668 17062575      chr22 18084924 18092691 . 1
chr22 17072959 17077823      chr22 17072959 17077823 . 1
chr22 17072959 17077823      chr22 17099173 17116036 . 2
chr22 17099173 17116036      chr22 17099173 17116036 . 2
chr22 17099173 17116036      chr22 17334334 17347700 . 1

I want to link two coordinates.
could you help me？
@leto @jbrowse @skinner @hyphaltip @cjfields

**Comment by cmdcolin** [comment]
If you only care about the large scale pattern of the loop on a single chromosome, you could convert to a simple format like

chr22 17056668 18084924 (e.g. cut -f 1,2,5 > junctions.bed)

And then plot with sashimiplot https://github.com/elsiklab/sashimiplot

**Comment by cmdcolin** [comment]
Note also that we are working in the jbrowse 2 realm on Hi-C visualization. See https://github.com/GMOD/jbrowse-components/pull/1021

**Comment by cmdcolin** [comment]
we had a couple recommendations here...maybe close for now....let us know if there are any more issues :)
