### ISSUE TITLE
jbrowse.org's Volvox demo 404s

### ISSUE THREAD

**Issue by lyijin** [GMOD/jbrowse#1523]
Hi there,

It's been ages since I used JBrowse, wanted to quickly check out the newer bells and whistles in the current version.

I noticed that the Volvox JBrowse page, linked from the Demo page (http://jbrowse.org/en/demos.html) produces a 404 error on Firefox and Chrome.

The current link on that page that 404s out for me is
https://jbrowse.org/code/JBrowse-1.16.9/?loc=ctgA%3A9900..32510&amp;tracks=DNA%2CTranscript%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam%2Cvolvox_microarray_bw_xyplot%2Cvolvox_microarray_bw_density&amp;data=sample_data%2Fjson%2Fvolvox&amp;highlight=

I checked my old genome browser, and the Volvox test page had an additional argument "?data=sample_data%2Fjson%2Fvolvox" that is not present in the 404'd link.

With a bit of URL hacking, this link works
https://jbrowse.org/code/JBrowse-1.16.9/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A9900..32510&amp;tracks=DNA%2CTranscript%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam%2Cvolvox_microarray_bw_xyplot%2Cvolvox_microarray_bw_density&amp;data=sample_data%2Fjson%2Fvolvox&amp;highlight=

but I'm not sure whether this was what you intended the link to be, hence raising this issue.

Cheers for writing JBrowse.

**Comment by cmdcolin** [comment]
Thanks! I went ahead and updated the demo link, should be on the site soon :) 25fdb00ad5

**Comment by cmdcolin** [comment]
Should be fixed, thanks for reporting
