### ISSUE TITLE
Error: not displaying index.html on Ubuntu 16.04

### ISSUE THREAD

**Issue by AlexLc6** [GMOD/jbrowse#1525]
When I open the http://127.0.0.1/jbrowse/JBrowse-1.12.3/docs/tutorial/index.html, the website shows "404 Not Found".In addition, when I opened the file:///var/www/jbrowse/JBrowse-1.12.3/index.html?When data=sample_data/ JSON /volvox, the page is “blank”. I don't know what caused this. 
Attachment 1 is the graph of "404 Not Found", Attachment 2 is the graph of "blank error" and Attachment 3 is set.log.
Please help me. Thank you very much!

JBrowse-version:1.12.3
Web browser: Firefox
Ubuntu 16.04

![404 Not Found](https://user-images.githubusercontent.com/67823786/86511037-e0a2f780-be27-11ea-83c6-8cad7206c2ca.png)
![blank](https://user-images.githubusercontent.com/67823786/86511043-e8fb3280-be27-11ea-873d-ad69f90cc5c9.png)
[setup.log](https://github.com/GMOD/jbrowse/files/4872683/setup.log)

**Comment by cmdcolin** [comment]
Dup of #1526
