### ISSUE TITLE
Error: jbrowse‘s index.html cannnot display

### ISSUE THREAD

**Issue by AlexLc6** [GMOD/jbrowse#1526]
When I open the http://127.0.0.1/jbrowse/JBrowse-1.12.3/docs/tutorial/index.html, the website shows "404 Not Found".In addition, when I opened the file:///var/www/jbrowse/JBrowse-1.12.3/index.html?When data=sample_data/ JSON /volvox, the page is “blank”. I don't know what caused this.
Attachment 1 is the graph of "404 Not Found", Attachment 2 is the graph of "blank error" and Attachment 3 is set.log.
Please help me. Thank you very much!

JBrowse-version:1.12.3
Web browser: Firefox
Ubuntu 16.04
![404 Not Found](https://user-images.githubusercontent.com/67823786/86511863-96be0f80-be2f-11ea-8556-9adc9ba88c55.png)
![blank](https://user-images.githubusercontent.com/67823786/86511867-9e7db400-be2f-11ea-96e4-a1f973d99ccf.png)
[setup.log](https://github.com/GMOD/jbrowse-components/files/4872788/setup.log)

**Comment by AlexLc6** [comment]
> You have a trailing dot on the URL that causes the 404
> 
> http://127.0.0.1/jbrowse/JBrowse-1.12.3/docs/tutorial/index.html.
> 
> I don't necessarily suggest this tutorial though, I'd use the tutorial on jbrowse.org
> 
> Also this link discusses why opening up with file:/// does not really work
> 
> https://jbrowse.org/docs/faq.html#what-webserver-is-needed-for-jbrowse

http://127.0.0.1/jbrowse/JBrowse-1.12.3/docs/tutorial/index.html
This URL without a dot is also a 404 error. I attempted.

**Comment by cmdcolin** [comment]
Possibly try putting jbrowse in the folder /var/www/html


I think many webservers these days use /var/www/html instead of just /var/www

**Comment by AlexLc6** [comment]
> Possibly try putting jbrowse in the folder /var/www/html
> 
> I think many webservers these days use /var/www/html instead of just /var/www

It not work.

**Comment by cmdcolin** [comment]
If you are using something like nginx which it appears you are, and create a simple text file in /var/www/html/index.html that says hello world, then you should be able to visit 

http://127.0.0.1/

and get hello world in the browser

 If that is not working then you have to figure out how your webserver is setup, it's not necessarily jbrowse's realm to figure out what webserver setup is being used

JBrowse is basically no different from this, it is just html, js and css, and it is just a subfolder inside of your webserver html directory

**Comment by AlexLc6** [comment]
I have found the reason, thank you very much! 😄
