### ISSUE TITLE
Category Flag for flatfile-to-json.pl

### ISSUE THREAD

**Issue by mwylerCH** [GMOD/jbrowse#1539]
Hi,
would it not be handy to add a '--category' flag to flatfile-to-json.pl for the hierarchical track selector?
Or I'm missing a faster option then to subsequently modify the entries in trackList.json?

**Comment by cmdcolin** [comment]
You can use the --config argument to specify generic JSON to attach to the track entry

    bin/flatfile-to-json.pl --gff file.gff3 --config '{"category": "My Category"}' --trackLabel my_track

It might be nice to have a special flag but flatfile-to-json perhaps, but hopefully that helps

**Comment by mwylerCH** [comment]
Many thanks for the quick and helpful reply.
I will close the issue, from my side it's fine.
