### ISSUE TITLE
syntaxError for gff file when gff is empty for current chromosome

### ISSUE THREAD

**Issue by jjjscuedu** [GMOD/jbrowse#1540]
Dear all,

When I config my gff annotation for one track, there is an error like the following:

SyntaxError: Unexpected token < in JSON at position.

![image](https://user-images.githubusercontent.com/5130367/91003108-fc927080-e602-11ea-882b-07719355901e.png)

After I check, there is no annotation for the current chromosome/scaffold.

However, I cannot delete this chromosome, because other track have annotation for this chromosme.

Hence, can anyone give me some suggestion how to avoid this problem?

Thanks a lot!

jingjing

**Comment by cmdcolin** [comment]
You might need to make sure requests for nonexistent files.return status404

This is what jbrowse is running into here, some page is returning maybe HTML for this request and it tries to interpret it as json. If the server returned 404 it would work though

This was seen here recently https://github.com/pombase/website/issues/784

**Comment by cmdcolin** [comment]
seems like an issue server side config...outside jbrowse scope...maybe close for now

**Comment by cmdcolin** [comment]
let us know if anything comes up though :)
