### ISSUE TITLE
Privacy concerns and google analytics in Europe

### ISSUE THREAD

**Issue by Jungal10** [GMOD/jbrowse#1541]
I am preparing a genome browser using JBrowse capabilities that will be hosted by my university in Germany.

While all the setup was no issue, there are serious concerns about user data privacy policy and the usage of Google Analytics.
It was suggested to alternatively use Matomo as it follows the general privacy policy of the university.
I also read in your documentation about the ```suppressUsageStatistics``` option. Would this be enough to circumvent the privacy issue? And if so, it is unclear to me how to set up that option. Can you help me with that?

How do you comply with this type of issue in Europe? Are there any guidelines that I can follow?

A second concern was in addition to retrieving data from "amaranthgdb.org"; some data is also retrieved from "mathjax.rstudio.com" and from "jbrowse.org" (which apparently forwards the request to a web tracking service hosted by Amazon Web Services ("mdvkjocq3e.execute-api.us-east-1.amazonaws.com").

Is it possible to change this with appropriate configuration entries, so that the data is not fetched from outside?

I really appreciate any help you can provide.

Best,
José

**Comment by cmdcolin** [comment]
Hi there,
You can add the line

```
suppressUsageStatistics=true
```

To the jbrowse.conf, or

```
{
    "suppressUsageStatistics":true
}
```

In the jbrowse_conf.json

That will get rid of the jbrowse.org/amazonaws and google analytics requests

We try not to be invasive with our tracking but understand the concern. Can't really speak to the european requirements about this necessarily but adding suppressUsageStatistics should be sufficient to not require any warning.

Anything related to amaranthgdb.org or mathjax.rstudio.org is probably not from us, that might be browser extensions or the host of the jbrowse instance

**Comment by cmdcolin** [comment]
If you want to alternatively configure some other script e.g. Matomo, you can certainly edit the jbrowse index.html for example to add custom script tags or tracking elements too

**Comment by Jungal10** [comment]
Thank you for the clear explanation and great help, as always!
