### ISSUE TITLE
Does JBrowse have parameters that control the order in which labels are displayed?

### ISSUE THREAD

**Issue by Trandamere** [GMOD/jbrowse#1545]
![sort](https://user-images.githubusercontent.com/24996924/93179731-a9768e00-f768-11ea-8406-cf329bbc7c21.png)
For example, I want "Genome Assembly of PH1" to be first.

**Comment by cmdcolin** [comment]
Adding these lines to your jbrowse.conf


```
[trackSelector]
sortHierarchical=false
```

Will disable the sorting by alphabetical order. Therefore categories and tracknames will appear relative to how they are ordered in the trackList.json

**Comment by Trandamere** [comment]
Thanks
