### ISSUE TITLE
question about targets and onclick

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1549]
Hello,

I am trying to get just the name portion of target in the url value for t his onclick.
```
         "onClick" : {
            "label" : "search at NCBI",
            "url" : "http://www.ncbi.nlm.nih.gov/nuccore/{target}"
         },
```
Currently I get the target name plus the range.  `http://www.ncbi.nlm.nih.gov/nuccore/DC616874.1%20544%20649%20-`

When I try to put a function or a subroutine into the "url" field, it does not get resolved, the actual function gets printed. How can I use a function here in the onclick to give me a value for url?

So if I write my onclick like this:
```
         "onClick" : {
            "label" : "search at NCBI",
            "url" : "{get_target_name}"
         },
```

and use this function:
```
get_target_name = function (feature) {
  var target = feature.get('target');
  var each = target.split(" ");
  var t_name = each[0];
  return "http://www.ncbi.nlm.nih.gov/nuccore/"+t_name;
}
```

I get this:
![Screen Shot 2020-09-28 at 3 15 49 PM](https://user-images.githubusercontent.com/1072991/94487088-a2567380-019d-11eb-892c-e7624a061cbc.png)

Thank you,
Sofia

**Comment by cmdcolin** [comment]
The docs for this are quite sprawling but to get a custom feature callback, see https://jbrowse.org/docs/mouse_configs.html#click-configuration-options

I might suggest changing this to

```

"onClick": {
"label": "search at NCBI",
"action": "{get_target_name}"
}
```

And then (kind of weird but it is mentioned in the docs) you use this.feature.get('target') instead of just feature.get('target'), and then manually call window.open( "http://www.ncbi.nlm.nih.gov/nuccore/"+t_name)

**Comment by srobb1** [comment]
Thanks for pointing me to this spot in the docs. I usually go to the jbrowse config and when I do go to the docs I can never seem to find what I want. I need to spend more time learning how to navigate the docs.

I could not get this to work with the modifications you suggested, but after looking at the docs I figured this out, and it is working well.

```
"onClick" : {
            "label" : "function(){ var t_name = this.feature.get('target').split(' ')[0]; return 'Search ' + t_name +' at NCBI'}",
            "url":"function(){var t_name = this.feature.get('target').split(' ')[0]; return 'http://www.ncbi.nlm.nih.gov/nuccore/' + t_name;}",
            "action" : "newWindow"
         },
```

Thanks a bunch for your help Colin!
Sofia

**Comment by cmdcolin** [comment]
The number of things that can be turned into a callback in the jbrowse config surprises me endlessly. Nice :)
