### ISSUE TITLE
Ubuntu 18.04 Can't install this JBrowser-1.16.10

### ISSUE THREAD

**Issue by linjiahao962889027** [GMOD/jbrowse#1551]
# My Quesetion

Gathering system information ...done.
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
Minimal release, skipping node and Webpack build (note: this version will not allow using plugins. Use a github clone or a dev version of JBrowse to use plugins
Installing Perl prerequisites ... failed.  See setup.log file for error messages. As a first troubleshooting step, make sure development libraries and header files for GD, Zlib, and libpng are installed and try again.

Formatting Volvox example data ... failed.  See setup.log file for error messages.

Formatting Yeast example data ... failed.  See setup.log file for error messages.
# Issue
I try my best to install JBrowser，but I failed.
**operating system：**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
WSL2，Windows10（2004，19041.508）
# setup.log
Gathering system information ...
============== System information ====
+ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
+ uname -a
Linux DESKTOP-EHN7URP 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
+ sw_vers
./setup.sh: line 89: sw_vers: command not found
+ grep MemTotal /proc/meminfo
MemTotal:        6260080 kB
+ echo

+ echo

done.

NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.

Minimal release, skipping node and Webpack build (note: this version will not allow using plugins. Use a github clone or a dev version of JBrowse to use plugins

Installing Perl prerequisites ...
+ bin/cpanm -v --notest -l extlib/ Bio::Perl@1.7.2
cpanm (App::cpanminus) 1.7043 on perl 5.026001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/linjiahao/.cpanm/work/1602518217.31866
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Bio::Perl (== 1.7.2) on cpanmetadb ...
--2020-10-12 23:56:57--  http://cpanmetadb.plackperl.org/v1.0/history/Bio::Perl
Resolving cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)... 151.101.110.217
Connecting to cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)|151.101.110.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 792 [text/plain]
Saving to: ‘STDOUT’

     0K                                                       100% 46.1M=0s

2020-10-12 23:56:57 (46.1 MB/s) - written to stdout [792/792]

--> Working on Bio::Perl
Fetching http://backpan.perl.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... --2020-10-12 23:56:57--  http://backpan.perl.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz
Resolving backpan.perl.org (backpan.perl.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘backpan.perl.org’
Unpacking BioPerl-1.007002.tar.gz
OK

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack BioPerl-1.007002.tar.gz: no directory
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... --2020-10-12 23:57:07--  http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz
Resolving www.cpan.org (www.cpan.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘www.cpan.org’
Unpacking BioPerl-1.007002.tar.gz
OK

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack BioPerl-1.007002.tar.gz: no directory
! Failed to fetch distribution BioPerl-1.007002
+ bin/cpanm -v --notest -l extlib/ Bio::Perl@1.7.2
cpanm (App::cpanminus) 1.7043 on perl 5.026001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/linjiahao/.cpanm/work/1602518237.31880
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Bio::Perl (== 1.7.2) on cpanmetadb ...
--2020-10-12 23:57:17--  http://cpanmetadb.plackperl.org/v1.0/history/Bio::Perl
Resolving cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘cpanmetadb.plackperl.org’
Searching Bio::Perl (== 1.7.2) on metacpan ...
--2020-10-12 23:57:27--  http://api.metacpan.org/v0/file/_search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22query%22%3A%7B%22nested%22%3A%7B%22query%22%3A%7B%22custom_score%22%3A%7B%22query%22%3A%7B%22constant_score%22%3A%7B%22filter%22%3A%7B%22and%22%3A%5B%7B%22term%22%3A%7B%22module.authorized%22%3Atrue%7D%7D%2C%7B%22term%22%3A%7B%22module.indexed%22%3Atrue%7D%7D%2C%7B%22term%22%3A%7B%22module.name%22%3A%22Bio%3A%3APerl%22%7D%7D%2C%7B%22term%22%3A%7B%22module.version%22%3A%22v1.7.2%22%7D%7D%5D%7D%7D%7D%2C%22metacpan_script%22%3A%22score_version_numified%22%7D%7D%2C%22score_mode%22%3A%22max%22%2C%22path%22%3A%22module%22%7D%7D%7D%7D%2C%22fields%22%3A%5B%22date%22%2C%22release%22%2C%22author%22%2C%22module%22%2C%22status%22%5D%7D
Resolving api.metacpan.org (api.metacpan.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘api.metacpan.org’
! Could not find a release matching Bio::Perl (== 1.7.2) on MetaCPAN.
Searching Bio::Perl on mirror http://www.cpan.org ...
Downloading index file http://www.cpan.org/modules/02packages.details.txt.gz ...
--2020-10-12 23:57:37--  http://www.cpan.org/modules/02packages.details.txt.gz
Resolving www.cpan.org (www.cpan.org)... 151.101.110.217, 2a04:4e42:36::729
Connecting to www.cpan.org (www.cpan.org)|151.101.110.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2341147 (2.2M) [application/x-gzip]
Saving to: ‘/home/linjiahao/.cpanm/sources/http%www.cpan.org/02packages.details.txt.gz’

     0K .......... .......... .......... .......... ..........  2%  197K 11s
    50K .......... .......... .......... .......... ..........  4%  376K 8s
   100K .......... .......... .......... .......... ..........  6%  217K 9s
   150K .......... .......... .......... .......... ..........  8%  641K 7s
   200K .......... .......... .......... .......... .......... 10%  208K 8s
   250K .......... .......... .......... .......... .......... 13%  469K 7s
   300K .......... .......... .......... .......... .......... 15%  139K 8s
   350K .......... .......... .......... .......... .......... 17%  120K 9s
   400K .......... .......... .......... .......... .......... 19% 90.8K 10s
   450K .......... .......... .......... .......... .......... 21%  128K 10s
   500K .......... .......... .......... .......... .......... 24% 74.6K 11s
   550K .......... .......... .......... .......... .......... 26%  100K 11s
   600K .......... .......... .......... .......... .......... 28%  121K 11s
   650K .......... .......... .......... .......... .......... 30%  121K 11s
   700K .......... .......... .......... .......... .......... 32%  172K 10s
   750K .......... .......... .......... .......... .......... 34%  144K 10s
   800K .......... .......... .......... .......... .......... 37%  180K 10s
   850K .......... .......... .......... .......... .......... 39%  185K 9s
   900K .......... .......... .......... .......... .......... 41%  169K 9s
   950K .......... .......... .......... .......... .......... 43%  142K 8s
  1000K .......... .......... .......... .......... .......... 45%  122K 8s
  1050K .......... .......... .......... .......... .......... 48%  182K 8s
  1100K .......... .......... .......... .......... .......... 50%  153K 8s
  1150K .......... .......... .......... .......... .......... 52%  164K 7s
  1200K .......... .......... .......... .......... .......... 54%  146K 7s
  1250K .......... .......... .......... .......... .......... 56%  123K 7s
  1300K .......... .......... .......... .......... .......... 59%  178K 6s
  1350K .......... .......... .......... .......... .......... 61%  212K 6s
  1400K .......... .......... .......... .......... .......... 63%  146K 5s
  1450K .......... .......... .......... .......... .......... 65%  162K 5s
  1500K .......... .......... .......... .......... .......... 67%  135K 5s
  1550K .......... .......... .......... .......... .......... 69%  105K 5s
  1600K .......... .......... .......... .......... .......... 72%  114K 4s
  1650K .......... .......... .......... .......... .......... 74%  138K 4s
  1700K .......... .......... .......... .......... .......... 76%  158K 4s
  1750K .......... .......... .......... .......... .......... 78%  104K 3s
  1800K .......... .......... .......... .......... .......... 80%  148K 3s
  1850K .......... .......... .......... .......... .......... 83% 89.6K 3s
  1900K .......... .......... .......... .......... .......... 85%  109K 2s
  1950K .......... .......... .......... .......... .......... 87%  131K 2s
  2000K .......... .......... .......... .......... .......... 89%  147K 2s
  2050K .......... .......... .......... .......... .......... 91%  116K 1s
  2100K .......... .......... .......... .......... .......... 94%  142K 1s
  2150K .......... .......... .......... .......... .......... 96%  145K 1s
  2200K .......... .......... .......... .......... .......... 98%  171K 0s
  2250K .......... .......... .......... ......               100%  157K=16s

2020-10-12 23:57:57 (143 KB/s) - ‘/home/linjiahao/.cpanm/sources/http%www.cpan.org/02packages.details.txt.gz’ saved [2341147/2341147]

Uncompressing index file...
Found Bio::Perl 1.007004 which doesn't satisfy == 1.7.2.
+ set -e
+ bin/cpanm -v --notest -l extlib/ Bio::Perl@1.7.2
cpanm (App::cpanminus) 1.7043 on perl 5.026001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/linjiahao/.cpanm/work/1602518278.31898
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Bio::Perl (== 1.7.2) on cpanmetadb ...
--2020-10-12 23:57:58--  http://cpanmetadb.plackperl.org/v1.0/history/Bio::Perl
Resolving cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)... 151.101.78.217
Connecting to cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)|151.101.78.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 792 [text/plain]
Saving to: ‘STDOUT’

     0K                                                       100% 54.0M=0s

2020-10-12 23:57:58 (54.0 MB/s) - written to stdout [792/792]

--> Working on Bio::Perl
Fetching http://backpan.perl.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... --2020-10-12 23:57:58--  http://backpan.perl.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz
Resolving backpan.perl.org (backpan.perl.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘backpan.perl.org’
Unpacking BioPerl-1.007002.tar.gz
OK

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack BioPerl-1.007002.tar.gz: no directory
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... --2020-10-12 23:58:08--  http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz
Resolving www.cpan.org (www.cpan.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘www.cpan.org’
Unpacking BioPerl-1.007002.tar.gz
OK

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack BioPerl-1.007002.tar.gz: no directory
! Failed to fetch distribution BioPerl-1.007002

Formatting Volvox example data ...
+ rm -rf sample_data/json/volvox
+ bin/prepare-refseqs.pl --fasta docs/tutorial/data_files/volvox.fa --out sample_data/json/volvox
Can't locate local/lib.pm in @INC (you may need to install the local::lib module) (@INC contains: /home/linjiahao/JBrowse-1.16.10/bin/../src/perl5/../../extlib/lib/perl5 /home/linjiahao/JBrowse-1.16.10/bin/../src/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/linjiahao/JBrowse-1.16.10/bin/../src/perl5/JBlibs.pm line 25.
Compilation failed in require at bin/prepare-refseqs.pl line 5.
BEGIN failed--compilation aborted at bin/prepare-refseqs.pl line 5.

Formatting Yeast example data ...
+ rm -rf sample_data/json/yeast/
+ bin/prepare-refseqs.pl --fasta sample_data/raw/yeast_scaffolds/chr1.fa.gz --fasta sample_data/raw/yeast_scaffolds/chr2.fa.gzip --out sample_data/json/yeast/
Can't locate local/lib.pm in @INC (you may need to install the local::lib module) (@INC contains: /home/linjiahao/JBrowse-1.16.10/bin/../src/perl5/../../extlib/lib/perl5 /home/linjiahao/JBrowse-1.16.10/bin/../src/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/linjiahao/JBrowse-1.16.10/bin/../src/perl5/JBlibs.pm line 25.
Compilation failed in require at bin/prepare-refseqs.pl line 5.
BEGIN failed--compilation aborted at bin/prepare-refseqs.pl line 5.

# Quickly
I hope I can get help quickly.

**Comment by cmdcolin** [comment]
@linjiahao962889027 Hi there

There seem to be several domain resolution errors

"Resolving backpan.perl.org (backpan.perl.org)... failed: Temporary failure in name resolution."
"Resolving api.metacpan.org (api.metacpan.org)... failed: Temporary failure in name resolution."
"Resolving www.cpan.org (www.cpan.org)... failed: Temporary failure in name resolution."


You could re-try running setup.sh and see if these go away?

Alternatively, note that you do not *need* the Perl tools of jbrowse. You can use jbrowse without running prepare-refseqs.pl or flatfile-to-json.pl, etc. Using generate-names.pl is helpful though.

For general track purposes, you can use indexed file formats such as indexed BAM, tabix VCF, indexed FASTA, bigwig, tabix GFF3 etc. and these do not require perl loading scripts, just hand editing the config file. Your jbrowse is likely already setup, just without the sample data.


See this tutorial for the indexed file formats tutorial https://jbrowse.org/docs/tutorial.html

See this for the "classic quick start guide" which uses the perl loading scripts https://jbrowse.org/docs/tutorial_classic.html

**Comment by linjiahao962889027** [comment]
@cmdcolin 
You are right, according to your tutorial, I loading indexed fasta. 
Maybe , I can't visit the backpan.perl.org and api.metacpan.org by using Chinese net. But the information from the setup.sh is very unfriendly，I still consider it maybe cause by defected the dependency package/lib. 
In fact I try use those command:
```
rm -rf extlib
bin/cpanm -v --notest -l extlib/ Bio::Perl@1.7.2
./setup.sh
```
and
```
rm -rf extlib # inside the jbrowse directory
cpanm https://github.com/bioperl/bioperl-live/archive/release-1-7-2.tar.gz
./setup.sh
```
to resolving my problem. When I use `cpanm https://github.com/bioperl/bioperl-live/archive/release-1-7-2.tar.gz`, the system remind me that I success，but the setup.sh still give me the same information which remind me that I failed.
I think it might be better to integrate Perl program dependency packages that need to be installed over the network into the installation package.

**Comment by cmdcolin** [comment]
The BioPerl installation is pinned to 1.7.2 which is kind of annoying and should probably be made a bit better. We have to manually use BioPerl@1.7.2 because BioPerl@1.7.3 and later drastically reorganized the BioPerl installation (see https://metacpan.org/changes/distribution/BioPerl)

If we upgraded to the latest BioPerl it might help things somewhat, I can't recall what is holding us back
