### ISSUE TITLE
Feature Request: Possibility to enter a key value when using "sequence search track"

### ISSUE THREAD

**Issue by Rhinogradentia** [GMOD/jbrowse#1553]
Hi,

while I was using the "sequence search track" feature a lot lately I thought it would be a huge relief if I could be able to enter a track-key in the pop-up for the search. The sequence can be quite long and will cover the track otherwise and doing it manually afterward is quite cumbersome and time-consuming.

Thanks a lot in advance
Best,
Nadine

**Comment by cmdcolin** [comment]
This was also requested here https://github.com/GMOD/jbrowse/issues/1417

You also have to be careful with long searches using this plugin
https://github.com/GMOD/jbrowse/issues/833

I would recommend possibly alternatives to the sequence search track as it does have downsides listed in 833 but if it is sufficient for you we could consider adding this feature

**Comment by Rhinogradentia** [comment]
Hi Colin,

thank you for your answer. I'm aware that longer sequences sometimes make problems with the sequence search. 
Nonetheless, this would be really helpful - even for shorter sequences. 

So, if it isn't very laborious I would be really glad for this to be possible. 

Best,
Nadine

**Comment by cmdcolin** [comment]
Should be fixed on the dev branch of this repo, since indeed it was not too bad. Just wanted to make sure you knew the limitations

If you want to create your own build


git clone https://github.com/GMOD/jbrowse
cd jbrowse
yarn
yarn build


Then the dist folder will contain the build

**Comment by Rhinogradentia** [comment]
Thank you very much - this is great!
Best,
Nadine

**Comment by Rhinogradentia** [comment]
Hi Colin,

I'm sorry, but I'm stuck a little bit with this - what do I have to do once yarn build created the js files. Do I have to move them somewhere?

The dist directory contains the following after running 'yarn build':
```
⇒  ls dist 
0.bundle.js           11.bundle.js          14.bundle.js          3.bundle.js           6.bundle.js           9.bundle.js           main.bundle.js
1.bundle.js           12.bundle.js          15.bundle.js          4.bundle.js           7.bundle.js           browser.bundle.js     run_jasmine.bundle.js
10.bundle.js          13.bundle.js          2.bundle.js           5.bundle.js           8.bundle.js           dojo
```

Thank you a lot in advance.
Best,
Nadine

**Comment by cmdcolin** [comment]
@Rhinogradentia it's a little funky, I guess my general thing for doing a proper build would be

make -f build/Makefile release-min

This would generate a zip release like the ones we upload

Note that this requires DateTime and Text::Markdown from cpan so it's a little tricky but ya. I ran this process and here is the latest dev branch


[JBrowse-1.16.11-alpha.0.zip](https://github.com/GMOD/jbrowse/files/5455165/JBrowse-1.16.11-alpha.0.zip)
This build above is from commit 99e4bab and includes the regexsequencesearch tracklabel option

**Comment by Rhinogradentia** [comment]
Great! Thank you a lot.
Best,
Nadine
