### ISSUE TITLE
JBrowse install on Mac Big Sur

### ISSUE THREAD

**Issue by coralzhang** [GMOD/jbrowse#1570]
I have the latest Mac Big Sur 11.1 and want to follow the steps here on install the JBrowse. 
https://jbrowse.org/docs/installation.html 
When I run set.sh, I have problems setup the Yeast data. Here is the output message of installation

> 
> Gathering system information ...done.
> NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
> Minimal release, skipping node and Webpack build (note: this version will not allow using plugins. Use a github clone or a dev version of JBrowse to use plugins
> Installing Perl prerequisites ...done.
> 
> Formatting Volvox example data ...done.
> To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.
> 
> Formatting Yeast example data ... failed.  See setup.log file for error messages.

Here are parts in the setup.log

> Formatting Yeast example data ...
> + rm -rf sample_data/json/yeast/
> + bin/prepare-refseqs.pl --fasta sample_data/raw/yeast_scaffolds/chr1.fa.gz --fasta sample_data/raw/yeast_scaffolds/chr2.fa.gzip --out sample_data/json/yeast/
> dyld: lazy symbol binding failed: Symbol not found: _inflateInit2_
>   Referenced from: /Users/xx/Sites/jbrowse/JBrowse-1.16.10/bin/../src/perl5/../../extlib/lib/perl5/darwin-thread-multi-2level/auto/PerlIO/gzip/gzip.bundle
>   Expected in: flat namespace
> 
> dyld: Symbol not found: _inflateInit2_
>   Referenced from: /Users/xx/Sites/jbrowse/JBrowse-1.16.10/bin/../src/perl5/../../extlib/lib/perl5/darwin-thread-multi-2level/auto/PerlIO/gzip/gzip.bundle
>   Expected in: flat namespace
> 
> ./setup.sh: line 239: 39033 Abort trap: 6           bin/prepare-refseqs.pl --fasta sample_data/raw/yeast_scaffolds/chr1.fa.gz --fasta sample_data/raw/yeast_scaffolds/chr2.fa.gzip --out sample_data/json/yeast/

I used home-brew to install zlib and related packages 

> brew install zlib
> brew install libpng
> brew install perl
> brew install cpanminus
> cpanm Bio::Perl
> brew install libpng
> brew install zlib
> export LDFLAGS="-L/usr/local/opt/zlib/lib"
> export CPPFLAGS="-I/usr/local/opt/zlib/include"

**Comment by cmdcolin** [comment]
I would be carefull about using

(a) a cpanm version of BioPerl, JBrowse actually needs a specific version of BioPerl because version 1.7.0 of bioperl changed a ton of stuff, and this may collide with JBrowse
(b) using a homebrew version of perl in general?

**Comment by coralzhang** [comment]
Thanks for the response! 
Do you have suggestions for a more appropriate installation of the Bioperl? 
In addition, why only Yeast has issue but not volvox??

**Comment by cmdcolin** [comment]
The setup.sh program will automatically install a BioPerl locally (jbrowse uses cpanm -l extlib to install jbrowse's perl dependency into a local lib folder named extlib)

And then the yeast fails because it runs bin/prepare-refseqs.pl --fasta file.fasta.gz instead of just file.fasta

If this is the only failure you can certainly avoid using prepare-refseqs.pl on fasta.gz files :)

**Comment by coralzhang** [comment]
Thanks for explaining! 
Does that mean if I do not feed gz file to my current JBrowse set up, I should be fine?
Another way to solve my problem would be to know how do you think that I should do so that my pl file be able to deal with gz file? I have no problem with installing the perl modules as you can see from my setup.log

**Comment by coralzhang** [comment]
It seems that this is because the perl5 installed by the JBrowse cannot access the gzip file. Does this raise a flag about my perl installation although seems like no error output in the step of perl installation?

**Comment by cmdcolin** [comment]
>I suppose if I avoid feeding gz file to my current JBrowse set up, I should be fine?

probably yes

>But I still wonder how I should do so that my pl file is able to deal with gz file? I have no problem with installing the perl modules as you can see from my setup.log

Symbol not found: inflateInit2 suggests that the perl was not built with zlib correctly or somehow not linking to zlib  correctly (which it is trying to find with dynamically linking), which could be related to the homebrew perl perhaps but I can't be sure

You can just test and see if things generally work "well enough" for you. 

Note that the perl programs are not essential to using jbrowse, you can create a jbrowse instance pretty much without them, see https://jbrowse.org/docs/tutorial.html (except generate-names.pl)

**Comment by coralzhang** [comment]
Ok. Makes sense. So far I tried to avoid using gz files and seems to work without any error. other scripts for indexing and building names seem to be running ok as well.
