### ISSUE TITLE
Cannot be displayed on the external network

### ISSUE THREAD

**Issue by dbx-git** [GMOD/jbrowse#1571]
Hello!
I deployed jbrowse on the server inside the school, and it can be displayed on the web page, but this is only limited to the network inside the school. When I use the external network, jbrowse will only display "loadling" all the time. By consulting the information, some people say It's because the server firewall blocks the .conf file, but I don't know how to solve this problem, can you help me? thank you very much!

**Comment by cmdcolin** [comment]
This has come up intermittently before ....kind of hard to fix

Ref 

https://github.com/GMOD/jbrowse/issues/1444
https://github.com/GMOD/jbrowse/issues/942

Downgrading is one option to 1.10.* tag versions of jbrowse

The other is more involved and involves making a custom build that avoids using the .conf syntax. That would probably start by converting the jbrowse.conf file to jbrowse_conf.json syntax. If you want to go down this path and need help let me know.  
Otherwise downgrading may be sufficient, I know that's not the best option but if you don't use newer features it might be ok


Can also consider jbrowse 2 if you are making a new instance, we're starting to get it feature ready :) see http://jbrowse.org/jb2/

**Comment by dbx-git** [comment]
Thank you very much for your reply. We hope to convert the jbrowse.conf file to jbrowse_conf.json syntax according to your method and try again. But can you tell me how this should be converted?The following is the provided json file, do we want to write in it ourselves?

// top-level JBrowse configuration file.  Treated the same as
// jbrowse.conf, but this one is in JSON format.
//
// Unless generating configuration from scripts, most users will
// prefer to add variables to jbrowse.conf instead of this file, since
// jbrowse.conf is much easier to hand-edit.
{

}

**Comment by dbx-git** [comment]
I always forgot to say that our version number is JBrowse-1.16.10.

**Comment by cmdcolin** [comment]
Here is a proposal for a setup that might work. Minimal steps to try to make it work:

Step 1. delete jbrowse.conf
Step 2. make jbrowse_conf.json with these contents

```
{
    "include": ["{dataRoot}/trackList.json"],
    "browserRoot": "./"
}

Alternative approach if this still fails: I made a custom jbrowse build that doesn't even try to fetch  jbrowse.conf

kind of experimental but worked in some basic test

[JBrowse-1.16.10-noconf.zip](https://github.com/GMOD/jbrowse/files/5871262/JBrowse-1.16.10-noconf.zip)


The patch for that was used for this is

```
diff --git a/src/JBrowse/Browser.js b/src/JBrowse/Browser.js
index f106dfe10..5d2227685 100644
--- a/src/JBrowse/Browser.js
+++ b/src/JBrowse/Browser.js
@@ -2323,7 +2323,6 @@ _configDefaults: function() {

         refSeqs: "{dataRoot}/seq/refSeqs.json",
         include: [
-            'jbrowse.conf',
             'jbrowse_conf.json'
         ],
         nameUrl: "{dataRoot}/names/root.json",
```

**Comment by dbx-git** [comment]
Thank you very much for your answers. Through our verification, the installation package you provided to us is very effective, and all problems are solved. Thanks again.

**Comment by cmdcolin** [comment]
awesome:) good to know

**Comment by cmdcolin** [comment]
it might be possible to make some sort of config option available so that the default jbrowse can have this and not require a custom build...maybe leaving this open to track that

**Comment by cmdcolin** [comment]
maybe close for now. it is sort of an obscure issue for conf files to be rejected, and this PR can be referred to in the future if needed
