### ISSUE TITLE
Save a static version Jbrowse on figshare

### ISSUE THREAD

**Issue by Jungal10** [GMOD/jbrowse#1575]
We have recently used JBrowse to generate our Population genetics genome browser for amaranth PopAmaranth](https://amaranthgdb.org/popamaranth.html).

First and foremost, thank you for all the help in the process to make it possible.

What we would like to do now is to keep a static version available offline that we could add to figshare together with the raw data. Is this possible in any way or the interested party would have to always run it through a web server to have it working on their machines?

**Comment by cmdcolin** [comment]
It is not possible to use fully without a web server. In some very limited cases it is allowed but any usage of things like bigwig or BAM or binary files that use range requests does not work without a web server to respond to range requests. If needed, it can be as simple as instructing users to launch a simple temporary server like `npx http-server`, that should be sufficient to browse data locally on http://localhost:8080


Random TLDR info:

Another option for running without a webserver is instructing users to use jbrowse desktop, and they can use the "Open data directory" function on a data directory that you share, but this may be difficult if you use plugins for various reasons (jbrowse versions 1.13 and greater require rebuilds to use plugins, hence need custom version of jbrowse desktop etc.)...we restored the ability in jbrowse 2 to load plugins without webpack rebuilds of the main app but that is a whole different system :)

**Comment by cmdcolin** [comment]
Also as far as making an the instance available, you can likely copy your entire jbrowse directory that you currently have on your webserver likely, as that should statically rehost just fine

**Comment by Jungal10** [comment]
The solution will go then for a bit both. Having it permanently on figshare with instructions for the curious minds in the future and just people pointing to our web browser and get some visits.

Thank you!

**Comment by cmdcolin** [comment]
hopefully fixed now :)
