### ISSUE TITLE
Visualize multiple values per site in the same bigwig track

### ISSUE THREAD

**Issue by yzhang2168** [GMOD/jbrowse#1577]
I need to display a track of numerical data, where each x-axis point has multiple values. Is there a way to display such data? I'm open to line graph (a sample file is attached), bar graph (min and max as the bottom/top edge of the box). Some other genome browsers have a function to overlay tracks - I'm open to this option too if available.
<img width="1112" alt="Screen Shot 2021-03-02 at 6 24 42 PM" src="https://user-images.githubusercontent.com/33489605/109742814-93c51b80-7b84-11eb-80f9-4714970ac3c1.png">

**Comment by cmdcolin** [comment]
You could probably try using the multibigwig plugin. The multibigwig plugin is capable of loading multiple bigwig files into the same track


https://github.com/elsiklab/multibigwig

If your data is not amenable to bigwig, you can create a custom data adapter that does the similar thing and still use multibigwig, but probably the easiest thing is to use multiple bigwigs

**Comment by yzhang2168** [comment]
Great! Does it also support bar graphs overlaid with somewhat transparent colors?

**Comment by cmdcolin** [comment]
If you specify both 

"nonCont": true,
"fill": true

and then provide a color with a transparency then it can be done

![localhost_jbrowse__data=plugins%2FMultiBigWig%2Ftest%2Fumd31 loc=GK000001 2%3A53101573 53107161 tracks=MultiXYPlot%2CMultiXYPlot_fill%2CRefSeq_proteincoding highlight=](https://user-images.githubusercontent.com/6511937/109749648-5074a800-7b98-11eb-8345-18f98f3fcdd5.png)

See the "fill" track examples in both test/data/tracks.conf and test/umd31/tracks.conf

**Comment by cmdcolin** [comment]
Note also you can open up the examples like that using http://localhost/jbrowse/?data=plugins/MultiBigWig/test/data and http://localhost/jbrowse/?data=plugins/MultiBigWig/test/umd31

**Comment by yzhang2168** [comment]
Awesome! Exactly what I was looking for. Let me play around with it.

**Comment by zwallace425** [comment]
Hi, I'm collaborating with @yzhang2168 on this here and I'm having some issues trying to get the multibigwig plugin working.  I followed the install procedure, cloning the repo into the plugins folder in Jbrowse and adding "plugins": ["MultiBigWig"] to trackList.json.  I also added the JSON snippet to the tracks array in trackList.json, like the fourth example under "Example Configs" in the Readme, except with the names of my bigwig files I want to combine.  When I run Jbrowse in my localhost, the track label is appearing, but the actual graph for the track is not.  The data seems to be getting loaded, as when I access "save track data" and view, I can see the data in bedgraph format.  Any idea why the actual multibigwig graph is failing to appear? Thanks!

**Comment by cmdcolin** [comment]
hi @zwallace425 

are you able to load the sample configs such as http://localhost/jbrowse/?data=plugins/MultiBigWig/test/data

can you share your config?

**Comment by zwallace425** [comment]
Yeah I could get those sample configs going, although it's just a bunch of BigWig tracks and not the MultiBigWig track, if that's what it's supposed to be?

And here's the config I added into Jbrowse trackList.json file.  My BigWig tracks are in the data folder.

{
      	 "storeClass" : "MultiBigWig/Store/SeqFeature/MultiBigWig",
     	  "urlTemplates" : [
        	   "ace2_binding_max.bw",
        	   "rbd_expression_max.bw"
            ],
     	  "showTooltips": true,
     	  "label" : "Multibigwig",
     	  "type" : "MultiBigWig/View/Track/MultiWiggle/MultiXYPlot"
}

**Comment by cmdcolin** [comment]
Hmm

I tried to run a couple tests and just make sure I have some example configs that use just filenames in the urlTemplates array, it seemed to work(commit: https://github.com/elsiklab/multibigwig/commit/283c46a10c4f424b5b5b47407a8683ca9a5d2050)

Screenshot
![t1](https://user-images.githubusercontent.com/6511937/110176502-a035b800-7dc0-11eb-8217-53feca4ddba6.png)

If your data isn't too big you could try to make a zip archive of your data directory and send it to me colin.diesh@gmail.com

**Comment by zwallace425** [comment]
Sure I can send it to you. The data is not that big and is just BigWig files that display bar graphs at a particular region of the genome.  Unless the fact that they are bar graphs is an issue?

**Comment by zwallace425** [comment]
I think I figured it out, but what I had to do was duplicate the Jbrowse/data directory and place it in the Jbrowse/plugins/MultiBigWig/test/ directory, and call that newly imported folder mydata.  So if I run https://localhost/jbrowse/?data=plugins/MultiBigWig/test/mydata, I get what I want.  However, this obviously isn't the way this should be implemented, so I'm still wondering how to make the MultiBigWig track as a default when loading the Jbrowse web server and not have to use the key/value in the URL to get my MultiBigWig track

**Comment by cmdcolin** [comment]
this may have been addressed by the plugin recommendation...feel free to open future issues in multibigwig
