### ISSUE TITLE
Question: align CanvasFeatures to the top

### ISSUE THREAD

**Issue by Bjoernsen** [GMOD/jbrowse#1578]
I have a track that gets its data from an external API using `"storeClass" : "JBrowse/Store/SeqFeature/REST"`.

Unfortunately, the resulting `CanvasFeatures` elements are not aligned to the top and are producing something like stairs. Furthermore, they are wasting space and I see quite often `max hight reached`

`HTMLFeatures`  does not have the aligning issue. Is there a way to modify the CanvasFeatures?

![image](https://user-images.githubusercontent.com/4971650/109952570-47422300-7cdf-11eb-8c9a-eee412204d26.png)

```json
# CanvasFeatures
{
   "baseUrl" : "...",
   "category" : "...",
   "displayMode" : "compact",
   "label" : "canvas",
   "storeClass" : "JBrowse/Store/SeqFeature/REST",
   "style" : {
      "maxDescriptionLength": 1,
      "height": 20,
      "featureScale" : 0.05,
      "borderColor": "white",
      "borderWidth": "0.2",
      "connectorThickness": 0,
      "marginBottom": 100,
      "color": "function(feature) { return feature.get('color'); }"
   },
   "type" : "CanvasFeatures"
},
# HTMLFeatures
{
   "baseUrl" : "...",
   "category" : "...",
   "displayMode" : "compact",
   "label" : "html",
   "storeClass" : "JBrowse/Store/SeqFeature/REST",
   "hooks": {
          "modify": "function( track, f, fdiv ) { fdiv.style.background = f.get('color'); fdiv.title = f.get('name'); }"
   },
   "type" : "HTMLFeatures"
}

```

**Comment by cmdcolin** [comment]
Oftentimes weirdness with the layout is a result of the features not being given a uniqueID or being given an inconsistent uniqueID (different requests to the REST API for the same data should produce the same ID)

However you are mentioning this may be due to HTMLFeatures vs CanvasFeatures...
This is kind of weird. I'd check the features do get proper uniqueIDs and if there is a reproducible test case that would be great

**Comment by Bjoernsen** [comment]
@cmdcolin Thank you!

After using a correct uniqueID, everything works.

![image](https://user-images.githubusercontent.com/4971650/109959639-11556c80-7ce8-11eb-856e-7f1388fe2fc9.png)

**Comment by Bjoernsen** [comment]
I just zoomed out. The features now starts at the top, but I can still see the stairs. What might be the reason? It is the same for the html and the canvas track.

Each feature has now a real unique id and it will always be the same id.

![image](https://user-images.githubusercontent.com/4971650/109961137-df450a00-7ce9-11eb-8d04-fd75d5bb96f4.png)

**Comment by cmdcolin** [comment]
There may be minor imperfect feature packing in some cases
The packing, or layout, is done by GranularRectLayout, which basically keep a bitmap in memory at low resolution, and then fills them in with feature positions

If interested you can try to modify the core JS code for the feature layout, adjusting the pitchX (which is the resolution) to something like 1 but it might be that what you see is the best it can do

**Comment by cmdcolin** [comment]
Also now if the vertical positioning is very important like for laying out rows as samples maybe consider something like the multivariantviewer plugin or a similar custom track type

**Comment by Bjoernsen** [comment]
I will take a look at the multivariantviewer plugin.  

Thanks!
