### ISSUE TITLE
Vhost SSL setting gave 403 error, http works

### ISSUE THREAD

**Issue by demis001** [GMOD/jbrowse#1584]
# Setting SSL using bitnami wordpress with jbrowse as subdomain
1. JBrowse-1.16.11
2. Ubuntu
3. google chrome and firefox

I configured SSL that works with  wordpress site and  phmyadmin  subdomain BUT failed for jbrowse subdomain. The subdmain configured properly for both phpmyadmin and jbrowse the same way. I used similar `htaccess.conf` file and `httpd-vhosts.conf`. I changed the entire jbrowse dir to 777 and setup the owner to proper user 'daemon` incase it was a  permission issue. For some reason the http link works (http://jb2.test.org), but I got 403 error when I changed to (https://jb2.test.org). I used the same ssl key, cert and chain for the main site, phpmyadmin and jbrowse subdomains. I don't know what went wrong, any idea?

htaccess.conf for jbrowse

```
# BEGIN rlrssslReallySimpleSSL rsssl_version[3.3]
<IfModule mod_rewrite.c>
Header Set Access-Control-Allow-Origin "*"
RewriteEngine on
RewriteBase /jbrowse/
RewriteCond %{HTTPS} !=on [NC]
RewriteCond %{REQUEST_URI} ^/jbrowse [NC]
RewriteRule .* https://%{REMOTE_ADDR}%{REQUEST_URI} [R=301]
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END rlrssslReallySimpleSS
```
httpd-vhost.conf for jbrowse

```
VirtualHost *:80>
    ServerName jb2.test.org
    ServerAlias www.test.org/jbrowse
    DocumentRoot "/opt/wordpress/apps/jbrowse"
    Include "/opt/wordpress/apps/jbrowse/conf/httpd-app.conf"
</VirtualHost>

<VirtualHost *:443>
    ServerName jb2.test.org
    ServerAlias www.test.org/jbrowse
    DocumentRoot "/opt/wordpress/apps/jbrowse"
    ### following three lines are for CORS support
    Header add Access-Control-Allow-Origin "*"
    Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
    Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
    SSLEngine on
    SSLCertificateFile "/opt/wordpress/apps/jbrowse/conf/certs/seeqtl.crt"
    SSLCertificateKeyFile "/opt/wordpress/apps/jbrowse/conf/certs/seeqtl.key"
    SSLCertificateChainFile "/opt/wordpress/apps/jbrowse/conf/certs/seeqtl.chain"
    <Directory /opt/wordpress/apps/jbrowse/>
        DirectoryIndex index.php
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
```
@demis001

**Comment by cmdcolin** [comment]
JBrowse technically has no server side code, and I can't necessarily speak to the details of apache server setup...certainly jbrowse doesn't require mod_rewrite. You might be able to look in your system logs for httpd related errors that might help explain the reason for the 403

**Comment by cmdcolin** [comment]
may close for now..let us know if anything else comes up though
