### ISSUE TITLE
Failed to load resource: JBrowse/View/Track/Alignment2.

### ISSUE THREAD

**Issue by JojoZhangxinye** [GMOD/jbrowse#1589]
JBrowse version: 1.16.4
Web browser: Chrome

After formatting reference sequences using bin/prepare-refseqs.pl, I add a stanza with the relative URL of the file to my data/tracks.conf file. I can see the reference sequences accurately, but when I tick BAM data in the left bar, it jumps to "Congratulation" page and reports error message"Failed to load resource: JBrowse/View/Track/Alignment2."

**Comment by cmdcolin** [comment]
@JojoZhangxinye it should be spelled with a plural Alignments, this may fix it...

JBrowse/View/Track/Alignments2

Let me know if that helps!

**Comment by JojoZhangxinye** [comment]
It helps!!!
Thanks!!!

**Comment by cmdcolin** [comment]
no worries, let us know if anything else comes up
