### ISSUE TITLE
JS class name of the glyph available options

### ISSUE THREAD

**Issue by demis001** [GMOD/jbrowse#1591]
Would you please point me the docs where can I find all available glyph options (JS class name for glyph)?

I want to know what available options to pass to the "glyph" something like 

glyph = JBrowse/View/FeatureGlyph/Box
glyph = JBrowse/View/FeatureGlyph/Segments
glyph = JBrowse/View/FeatureGlyph/Diamond

I am trying move the application from gbrowse to jbrowse and want some equevlant glyph class with gbrowse version 1.

gbrowse glyph equivelent for  `processed_transcript`, `segments`, `xyplot`, `dot`, `box`

I appriciate if someone convert the following  `gbrowse track.conf` file to `jbrowse tracks.conf` as close as possible:
`score_color`,  `score_height`  and `get_balloon_hover` are a Perl function in the config file. I will use as an example to convert to jbrowse. `hapmap3_LCL_meta` is a gff file. 

```
[cis meta]
feature      = cis_eQTL_segment:hapmap3_LCL_meta
label        = 1
glyph        = segments
box_subparts = 3
fgcolor      = \&score_color
height       = \&score_height
bgcolor      = grey
key          = hapmap LCL cis-eQTL meta-analysis
label density = 2000
bump density  = 2000
balloon hover width = 380
link = sub {
         my ($feature, $panel, $track) = @_;
         #return ;
         my $mytype=$feature->type;
         if ("$mytype" eq "cis_eQTL_hapmap3_LCL_meta:hapmap3_LCL_meta") {
           return "https://www.test.org/gb2/gbrowse/gbrowse_details/seeQTL?"."ref=".$feature->ref.";start=".$feature->start.";end=".$feature->end.";name=".$feature->name.";class=".$feature->class.";feature_id=".$feature->primary_id.";db_id=".$feature->gbrowse_dbid;
         }
         else {
           return ;
         }
       }
balloon hover = \&get_balloon_hover
```
etc ...

Thanks!
@demis001

jbrowse version 1.16.11 dev version

**Comment by cmdcolin** [comment]
Generally, you don't have to manually modify glyph configs unless you are trying to do something custom

To address the things you mentioned e.g. hover, color, and height, you can use these links as a reference

* balloon hover - see mouseover https://jbrowse.org/docs/mouse_configs.html#customizing-mouse-over-behavior

* color - see https://jbrowse.org/docs/faq.html#how-do-i-customize-feature-colors-with-canvasfeatures

* height - style->height can take a callback function similar to color

**Comment by demis001** [comment]
@cmdcolin 

Do you think the script in jbrowse output tracks.conf? I thought it output `tracksList.json` and then convert that to `tracks.conf` if you perfer the conf  text format. How about the `JS class name for glyph`? Where can I find avialable options?

**Comment by cmdcolin** [comment]
We don't have scripts that output to tracks.conf format automatically. See https://jbrowse.org/docs/configuration_file_formats.html

The format can be hand edited though

A minimal track definition for tracks.conf looks like this

```
[tracks.mytrack]
urlTemplate=myfile.bam
```

That is all that is needed, and it will infer storeClass, type, so the slightly expanded version of that is

```
[tracks.mytrack]
urlTemplate=myfile.bam
type=Alignments2
storeClass=JBrowse/Store/SeqFeature/BAM
```

But as noted above, the type and storeClass are automatically inferred and don't have to be manually specified

Then you can add extra customization as needed

See the list of files in https://github.com/GMOD/jbrowse/tree/master/src/JBrowse/View/FeatureGlyph for options for glyphs

A glyph is the code that draws a single feature basically

Modifying a glyph using the config file is not super common, generally what is done is you choose which track type a data file uses and the track type chooses glyphs intelligently

**Comment by cmdcolin** [comment]
Note also that anything in tracks.conf can be expressed in trackList.json format too, it is just an alternative different syntax for config files

**Comment by demis001** [comment]
Much thanks! that is exactly, what I am looking for. 

Best,
@demis001

**Comment by cmdcolin** [comment]
let me know if there are any more concerns
