### ISSUE TITLE
Feature request: Absolute paths in configs 

### ISSUE THREAD

**Issue by Gogis0** [GMOD/jbrowse#1594]
In config files, the attribute 'urlTemplate' assumes that the path to the data is relative to the config location. Wouldn't it be useful to support absolute paths, so that the data can be stored anywhere in the filesystem, regardless of the location of the config file?

**Comment by cmdcolin** [comment]
Is this referring to jbrowse desktop or just a normal jbrowse on the web?

At least on the web, absolute paths in urlTemplate should work, an absolute path would for example start with a slash and then it would be resolved relative to the base of the server e.g. urlTemplate=/path/to/my/file.bw would be http://yourserver.com/path/to/my/file.bw. Alternatively, urlTemplate can be an absolute URL starting with http(s)://

**Comment by cmdcolin** [comment]
are there any other concerns about this?

**Comment by cmdcolin** [comment]
let me know if there is anything else we can do...

**Comment by Gogis0** [comment]
@cmdcolin Sorry for the long delay. Thank you for answering my question, I think you made it clear for me. This issue may therefore remain closed.
