### ISSUE TITLE
Available tracks window size

### ISSUE THREAD

**Issue by demis001** [GMOD/jbrowse#1595]
Would you please tell me which css file define the `Available tracks` left side window size? I want to change it. It is too wide, want to resize it. Please let me know where it is hardcoded in the css file or java script.

![available_tracks](https://user-images.githubusercontent.com/8713514/116143789-9423f380-a6a9-11eb-8fea-e567a997dafb.png)

@demis001

**Comment by demis001** [comment]
coudn't find any css ID in css folder, here is where it defind after inspecting the source file

`widgetid="hierarchicalTrackPane"`

**Comment by cmdcolin** [comment]
I posted about this here previously, it's not necessarily an easy thing to do now but instructions are there... https://github.com/GMOD/jbrowse/issues/1592#issuecomment-815175852

**Comment by cmdcolin** [comment]
It can also be dragged to adjust width by the user

**Comment by demis001** [comment]
By the way, thanks for your help. Finished the one I was working last time, sticked with gbrowse for that one. 

https://seeqtl.org/

I am working with the second app, jbrowse1  will work for this one.

@demis001

**Comment by cmdcolin** [comment]
Super :) glad that helps. Website looks great, really interesting to see quantitative trait graphs in the browser...
