### ISSUE TITLE
Feature start offset of one between Front-end and JS object

### ISSUE THREAD

**Issue by Bjoernsen** [GMOD/jbrowse#1596]
Currently, I am playing around with JavaScript and how to access the feature data. During my tests, I recognized that there is an offset of 1 for the feature start between the JBrowse Front-end and the JavaScript object.

The front-end says that my feature starts at the position `...970`, whereas the JavaScript object says it starts at `...969`. The underlying GFF3 file says it starts at `...970`

The stop/end position is the same.

Where does this offset come from? Is it always the case?

![image](https://user-images.githubusercontent.com/4971650/116364219-4243b080-a804-11eb-9f5a-b10510f89c71.png)

![image](https://user-images.githubusercontent.com/4971650/116364234-47086480-a804-11eb-9e3e-e12a9fef2844.png)

- JBrowse version: `1.16.11`
- Web browser being used `Chrome`
- Operating system if relevant `Windows 10`

**Comment by cmdcolin** [comment]
Internally the data is represented using zero-based coordinates but is presented with one-based coordinates. The gff file format is also one-based so the raw file gets converted to zero-based internally before again going back to one-based when displayed

Faq entry https://jbrowse.org/docs/faq.html#what-type-of-coordinate-system-does-jbrowse-use

**Comment by Bjoernsen** [comment]
ah, ok. Thank you!
