### ISSUE TITLE
JBrowser configuration

### ISSUE THREAD

**Issue by werhmk** [GMOD/jbrowse#1603]
Hi, how can I remove the vertical bar in background by setting the configuration file? As the red arrows showed in the figure.
![Jbrower1](https://user-images.githubusercontent.com/18350866/118435826-46cbfc80-b712-11eb-8da5-249704f35eae.jpg)

**Comment by cmdcolin** [comment]
you can add this to your index.html

```
<style>
            .jbrowse div.gridline {
                border: none !important;
            }
            .jbrowse div.gridline_major {
                border: none !important;
            }
        </style>

```

**Comment by werhmk** [comment]
> you can add this to your index.html
> 
> ```
> <style>
>             .jbrowse div.gridline {
>                 border: none !important;
>             }
>             .jbrowse div.gridline_major {
>                 border: none !important;
>             }
>         </style>
> ```

Thanks, I will try.

**Comment by cmdcolin** [comment]
maybe can close for now :)
