### ISSUE TITLE
What these values consist of "3a6/c61/ab" in the last end point when we hit hit track information......seq/3a6/c61/ab/110-38.txt ?

### ISSUE THREAD

**Issue by sarimurrab** [GMOD/jbrowse#1604]
What these values consist of "3a6/c61/ab" in the last end point when we hit track information......seq/3a6/c61/ab/110-38.txt . These value are changing based on the sequences for Chr-01, Chr02....etc. So, what these values are in actual?

**Comment by cmdcolin** [comment]
the values are a crc32 of the reference sequence name, split into groups of three chars, and then 110 is the reference sequence name.

search 110 here https://crccalc.com/ for crc32, the result is  0x3A6C61AB

38 is the "chunk number" e.g. there is a sequence chunk size "20000" default and then 38 would be the sequence between 38*20000 - 39*20000

note that this may be an internal detail, if you are trying to make a rest api to respond to these requests, you might instead consider serving this data as a static asset

**Comment by rbuels** [comment]
Or consider making a REST endpoint that provides the JBrowse REST API: https://jbrowse.org/docs/data_formats.html#jbrowse-rest-feature-store-api
