### ISSUE TITLE
Search by gene name

### ISSUE THREAD

**Issue by fuzing** [GMOD/jbrowse#1608]
It would be useful to be able to search by gene name.   Every one of my users is requesting this feature - they invariably end up using the UCSC genome browser to find their target and then return to enter the chromosome and offsets - which is a clear friction point.

Any update on this would be useful/helpful.

Thank you for the great work.

**Comment by cmdcolin** [comment]
i think this was meant and cross posted to jbrowse 2 forum https://github.com/GMOD/jbrowse-components/discussions/2085
