### ISSUE TITLE
RequestError: Unable to load http://ip/jbrowse/JBrowse-1.16.11/data/CSV21/trackList.json?v=0.08820448948622106 status: 403.

### ISSUE THREAD

**Issue by xiaoaozqd** [GMOD/jbrowse#1610]
# Pre-requisites

Please try clearing your browser cache and refreshing to see if this affects your error
confirmed

# Creating an issue
![image](https://user-images.githubusercontent.com/10625828/129442010-2edfa83f-3f2d-426f-a6e6-06af2825c104.png)

volvox example is OK
![image](https://user-images.githubusercontent.com/10625828/129442022-ec6503a9-9ef9-4037-8fe7-a64d2a80476a.png)

Wheat genome report an error: Unable to load http://ip/jbrowse/JBrowse-1.16.11/data/CSV21/trackList.json?v=0.08820448948622106 status: 403.
![image](https://user-images.githubusercontent.com/10625828/129442003-39966c6e-a9d7-4d62-8120-4816b9ddf16b.png)

The data files are in the same Dir
![image](https://user-images.githubusercontent.com/10625828/129442074-0d48c599-8d0d-469f-bce3-f85af0cec25a.png)

If you are creating a new issue please report

- JBrowse version
JBrowse-1.16.11

- Web browser being used
chrome

- Operating system if relevant
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- If it is setup related, setup.log
[setup.log](https://github.com/GMOD/jbrowse/files/6986237/setup.log)

Also consider submitting questions to http://biostars.org, https://bioinformatics.stackexchange.com/

You can also try our chat https://gitter.im/GMOD/jbrowse if you don't suspect it to be a bug

You can also try the subscribing and sending email to gmod-ajax@lists.sourceforge.net but this frequently gets caught in a spam filter

**Comment by cmdcolin** [comment]
@xiaoaozqd the status 403 may indicate a permission issue e.g. the webserver may not have permission to read these files. opening up permissions on the CSV21 folder using chmod or chown to make the files accessible by the webserver may help

**Comment by xiaoaozqd** [comment]
> @xiaoaozqd the status 403 may indicate a permission issue e.g. the webserver may not have permission to read these files. opening up permissions on the CSV21 folder using chmod or chown to make the files accessible by the webserver may help

Thank you for your comment!  The permission of volvox and CSV21 are the same. While the volvox can display success.

**Comment by cmdcolin** [comment]
might need to check both these directories for permission/ownership also

/home/back/zengqd/Wheat/CSV21
and
/home/back/zengqd/Wheat/CSV21/CSV21


I general, you'd actually have to check the entire tree that the webserver has access to all of these

/home/
/home/back/
/home/back/zengqd/
/home/back/zengqd/Wheat/
...

but since the volvox example works I think the parent directories above Wheat would be ok

you can check e.g. http://172.26.1.8/jbrowse/JBrowse-1.16.11/data/CSV21/trackList.json in a tab in your browser to see if it is accessible too, it likely is not anything related to jbrowse unless your server doesn't like the ?v= query string (which can be disabled, but it helps avoid stale cache files)

hope that helps!

**Comment by xiaoaozqd** [comment]
> might need to check both these directories for permission/ownership also
> 
> /home/back/zengqd/Wheat/CSV21
> and
> /home/back/zengqd/Wheat/CSV21/CSV21
> 
> I general, you'd actually have to check the entire tree that the webserver has access to all of these
> 
> /home/
> /home/back/
> /home/back/zengqd/
> /home/back/zengqd/Wheat/
> ...
> 
> but since the volvox example works I think the parent directories above Wheat would be ok
> 
> you can check e.g. http://172.26.1.8/jbrowse/JBrowse-1.16.11/data/CSV21/trackList.json in a tab in your browser to see if it is accessible too, it likely is not anything related to jbrowse unless your server doesn't like the ?v= query string (which can be disabled, but it helps avoid stale cache files)
> 
> hope that helps!

Thank you again!
You are right!
My browser has no accessible to CSV21/trackList.json, while it has accessible to volvox/trackList.json
![image](https://user-images.githubusercontent.com/10625828/129463688-ab3f0a2b-8a8b-4c54-8806-d89bb211bbdc.png)
![image](https://user-images.githubusercontent.com/10625828/129463691-be3d4084-c459-4247-87fb-2eac7e4210c8.png)
Which maks me confused is the directories for CSV21 and volvox have the same permission/ownership
![image](https://user-images.githubusercontent.com/10625828/129463791-976820ff-4fa8-4ee2-a160-8f5cb478ca38.png)

**Comment by cmdcolin** [comment]
this is my guess, but maybe check the permissions on the folders themselves, specifically these folders

/home/back/zengqd/Wheat/CSV21
/home/back/zengqd/Wheat/CSV21/CSV21

**Comment by xiaoaozqd** [comment]
> this is my guess, but maybe check the permissions on the folders themselves, specifically these folders
> 
> /home/back/zengqd/Wheat/CSV21
> /home/back/zengqd/Wheat/CSV21/CSV21
Thank you again! It seems no different.
![image](https://user-images.githubusercontent.com/10625828/129464153-43758454-b8ed-4450-a72f-ed08b5ba5eaa.png)
![image](https://user-images.githubusercontent.com/10625828/129464155-5e237032-6780-47aa-82c3-831648f3195f.png)
![image](https://user-images.githubusercontent.com/10625828/129464167-73a02f43-ab84-42a1-bda1-a928a45b1639.png)

**Comment by cmdcolin** [comment]
hmmm, i'm not sure! I guess maybe check some of the questions and answers on stackoverflow about 403 errors or other guides... example https://stackoverflow.com/a/18447506/2129219

it is a little outside the scope of jbrowse specifically since it does not run on the server side, but generally happy to at least try to help :)

**Comment by cmdcolin** [comment]
since it's a bit outside the jbrowse scope, might close for now. let me know if there are any issues
