### ISSUE TITLE
Some question about y-axis scales on track

### ISSUE THREAD

**Issue by ydy1127** [GMOD/jbrowse#1611]
Hi，

   I have set the min_score（0） and max_score（1500） manually, but y-axis scales on track is from 0 to 2000. 
 
  
![image](https://user-images.githubusercontent.com/44722259/129867506-0d95fc61-3246-4556-aefa-155ba8f3f22a.png)
![image](https://user-images.githubusercontent.com/44722259/129867617-f0f82de5-44f7-4614-85d3-76c822bc58af.png)

  How to set the JBrowse to display the expected y-axis(0-1500)?

**Comment by cmdcolin** [comment]
Is this a custom plugin that does this dialog box? If so it is very nice :)!

The thing you are running into probably is that JBrowse tries to "round up" in some cases, apparently pretty aggressively e.g. 1500->2000

I think if you set "fixBounds":false on the track config, then it will not do the rounding. It can also have string values corresponding to the type of scale fixing it tries to do e.g. "none" (similar to false IIRC) and "micro", "minor","major" (default major I believe)

**Comment by cmdcolin** [comment]
See also https://jbrowse.org/docs/bigwig.html

**Comment by ydy1127** [comment]
Hi,

   Thanks for your reply. I have try to set "fixBounds":false on the track config.
    
![image](https://user-images.githubusercontent.com/44722259/129995358-c3626a0b-4329-4802-bf71-5c58039b4f4e.png)
    
   As shown in the figure above, the y-axis still shows "0-2000". So, we tried to change some source code which refers to "fixBounds", including "jbrowse/src/JBrowse/View/Ruler.js","jbrowse/src/JBrowse/View/Track/_YScaleMixin.js"，”jbrowse/src/JBrowse/View/Track/Wiggle/XYPlot.js“.  But none of them solved the problem.

  We think it might be because of the step size of the y-axis. Because when we set "0-11", it will show "0-20";Set "0-110" display "0-200" to look like the step size is an integer multiple of 10, although this makes for a more aesthetically pleasing display of the axes. When we focus on certain region, whether we can change the configuration or code to address this limitation?

**Comment by cmdcolin** [comment]
Hmm, If I understand everything, I think it works for me
I try with a sample track

set 

maxScore=123
fixBounds=false

Then the scale it precisely at 123


maxScore=123
fixBounds=true

Rounds up to 130

Note that fixBounds:false was added in 1.16.2

**Comment by ydy1127** [comment]
Thanks for your reply. 

We thought maybe the version we were using was too low (JBrowse 1.11.5) . We have been using this version on our server for a long time. Is there any way to solve this problem on our old version?

**Comment by cmdcolin** [comment]
you could try to backport this patch I think it is fairly small https://github.com/gmod/jbrowse/pull/1306

**Comment by ydy1127** [comment]
Thank you very much. 

Follow the link you provided，we changed as follows:

1，/var/www/html/jbrowse/src/JBrowse/View/Ruler.js

line 61 change to : fixLower: this.fixBounds ? (typeof this.fixBounds=='string' ? this.fixBounds : 'major') : 'none',
line 62 change to : fixUpper: this.fixBounds ? (typeof this.fixBounds=='string' ? this.fixBounds : 'major') : 'none',

2，/var/www/html/jbrowse/src/JBrowse/View/Track/Wiggle/XYPlot.js 

line 71change to : fixBounds: 'fixBounds' in this.config ? this.config.fixBounds : true,

In addition, we restarted the network service after modifying the files.  However, it still does not solve the problem.

Do we need to change anything else, or reinstall and configure JBrowse for the modified ".js" file to take effect.

**Comment by cmdcolin** [comment]
You may need to use the "dev" package e.g. JBrowse-1.11.5-dev.zip instead of JBrowse-1.11.5.zip

If you are using the non-dev package, then editing those files will have no effect, as most of the data will have been compiled/minified into src/dojo/dojo.js


https://jbrowse.org/releases/JBrowse-1.11.5-dev.zip

**Comment by ydy1127** [comment]
OK. Thank you very much! I will try this method.

**Comment by cmdcolin** [comment]
let me know if there are any other issues...maybe close for now
