### ISSUE TITLE
ItemRgb not working for me

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1615]
- JBrowse version: 1.16.9
- Web browser being used: Chrome

I have a bed file with rgb values in the 9th column.  I would like to use these values to color my features. I see in the documentation that I should be able to add `"ItemRgb": true` to my config. I have done this but the colors do not change. Is there something I am missing? 

Thank you,
Sofia

Bed file line:
```
chr81   50142   51060   chr77_unloc.5   12760   +       50142   51060   255,253,153
```

Config:
```
{
  "maxFeatureSizeForUnderlyingRefSeq": 250000,
  "subfeatureDetailLevel": 2,
  "maxFeatureScreenDensity": 0.5,
  "enableCollapsedMouseover": false,
  "disableCollapsedClick": false,
  "maxFeatureGlyphExpansion": 500,
  "maxHeight": 600,
  "histograms": {
    "description": "feature density",
    "min": 0,
    "height": 100,
    "color": "goldenrod",
    "clip_marker_color": "red"
  },
  "style": {
    "_defaultHistScale": 4,
    "_defaultLabelScale": 30,
    "_defaultDescriptionScale": 120,
    "showLabels": true,
    "showTooltips": true,
    "label": "name,id",
    "description": "note, description",
    "className": "feature"
  },
  "displayMode": "normal",
  "events": {},
  "menuTemplate": [
    {
      "label": "View details",
      "title": "{type} {name}",
      "action": "contentDialog",
      "iconClass": "dijitIconTask"
    },
    {
      "iconClass": "dijitIconConnector"
    },
    {
      "iconClass": "dijitIconFilter"
    }
  ],
  "compress": 0,
  "key": "chr81msk_net",
  "label": "chr81msk_net.bed",
  "storeClass": "JBrowse/Store/SeqFeature/NCList",
  "ItemRgb": true,
  "trackType": "CanvasFeatures",
  "type": "JBrowse/View/Track/CanvasFeatures",
  "urlTemplate": "tracks/chr81msk_net.bed/{refseq}/trackData.json",
  "baseUrl": "https://simrbase.stowers.org/jbrowse/data/kPetMar1_v1/",
  "index": 26,
  "metadata": {}
}
```

**Comment by cmdcolin** [comment]
I think itemRgb is not by default enabled for tracks loaded with flatfile-to-json

It was a feature added for bigbed and for BED tabix tracks

It also is a setting that is available for only this glyph type: "glyph":"JBrowse/View/FeatureGlyph/UCSC/BED"

And then finally, it is a typo in the docs. It is itemRgb (lower case) instead of ItemRgb, but its enabled by default on that glyph type

**Comment by cmdcolin** [comment]
excellent :) it should definitely be easier to do stuff like this, as having those colors is really important.  we still need to port similar functionality to jbrowse 2 so will keep in mind

**Comment by cmdcolin** [comment]
maybe can close for now
