### ISSUE TITLE
Links for older releases on the website are 404s

### ISSUE THREAD

**Issue by kevinlul** [GMOD/jbrowse#1616]
This is not an issue with JBrowse per se, but the website. The links for old releases are dead, for example https://jbrowse.org/blog/2017/05/02/jbrowse-1-12-3-index.html. The corresponding GitHub Releases link is also dead https://github.com/GMOD/jbrowse/releases/tag/1.12.3-release

**Comment by cmdcolin** [comment]
thanks for catching....correct links should be here for jbrowse desktop and web versions


-   [JBrowse-1.12.3.zip](https://jbrowse.org/releases/JBrowse-1.12.3/JBrowse-1.12.3.zip) 
-   [JBrowse-1.12.3-dev.zip](https://jbrowse.org/releases/JBrowse-1.12.3/JBrowse-1.12.3-dev.zip) 
-   [JBrowse-1.12.3-desktop-osx.zip](https://jbrowse.org/releases/JBrowse-1.12.3/JBrowse-1.12.3-desktop-osx.zip)  (OSX)
-   [JBrowse-1.12.3-desktop-win.zip](https://jbrowse.org/releases/JBrowse-1.12.3/JBrowse-1.12.3-desktop-win.zip)  (Windows)

**Comment by cmdcolin** [comment]
pushed to website so should update there soon too also...if you know of any other broken links let me know and can try to restore

**Comment by kevinlul** [comment]
Thank you! I'm not sure about the others. I thought perhaps old minor releases were all removed if there was an update with the same major release number. I'm trying to sort out what's vendor code and what's custom code in an old installation. The links on the website work now too, though the link in GitHub Releases is still dead.

**Comment by cmdcolin** [comment]
ya it is unintentional. versions of jbrowse up to probably about 1.12.3 which you linked were uploaded to a wordpress site and then we transitioned away from that, so they are only available on our s3 bucket instead of on the github releases download page

**Comment by cmdcolin** [comment]
glad this one could be fixed though, thanks for the report :)
