### ISSUE TITLE
HTML linkouts in 1.16.11-release not rendering in the About this track panel

### ISSUE THREAD

**Issue by childers** [GMOD/jbrowse#1617]
After updating our JBrowse to 1.16.11-release and Apollo 2.6.5, we noticed that html specified in the config files is no longer rendering in the "About this track" pop up panel. 
See [This instance](https://apollo.nal.usda.gov/apollo/4453621/jbrowse/index.html?loc=NC_057421.1%3A16438266..24658432&tracks=DNA%2CAnnotations%2CVencan_ASM1945775v1_RNA-Seq-alignments_2021-09-27&highlight=) as an example where you click on the "About this track" to see the raw html not rendered neatly into links. Please see the image below for more information.  

Did the syntax for rendering html in the configuration files change? I looked in the configuration documentation but did not see anything about it. 

<img width="1200" alt="Screen Shot 2021-11-12 at 11 52 04 AM" src="https://user-images.githubusercontent.com/421248/141504481-a9c5fdf9-8143-4c0b-9619-1a4d4d61c7a4.png">

**Comment by cmdcolin** [comment]
Have to use the setting "unsafePopup":true on the tracks

see
https://jbrowse.org/docs/mouse_configs.html#rendering-html-in-popups

**Comment by cmdcolin** [comment]
might close for now, let me know if this needs anything more
