### ISSUE TITLE
Adding .bam and .bai from a server to the track.

### ISSUE THREAD

**Issue by adaware-loxo** [GMOD/jbrowse#1639]
Hi,
I have deployed Jbrowse on a EC2 instance.
I wanted to access Bam file which are present in a particular folder in the EC2 instance.

Is there a way to give access to the Jbrowse server to access that particular folder and search for that file ?

**Comment by cmdcolin** [comment]
jbrowse is not a server side application, so it can only read files that are available from the 'web folder' (e.g. /var/www/html if you are using apache/nginx)

you can add a symlink inside the /var/www/html/ folder to your folder of interest to make your folder available to the web server

**Comment by cmdcolin** [comment]
sometimes you may need to configure your web server to follow those symlinks potentionally too, e.g. https://superuser.com/questions/244245/how-do-i-get-apache-to-follow-symlinks

**Comment by adaware-loxo** [comment]
Thanks, I was able to add them as symlinks!
