### ISSUE TITLE
url controllable Highlighting in JB2

### ISSUE THREAD

**Issue by thomasvangurp** [GMOD/jbrowse#1642]
In JB1 we had:

highlight | Set a highlighted genomic region, specified as "chr:start..end"
-- | --

does this exist in JB2 and do i miss something or is this still TBD?

**Comment by cmdcolin** [comment]
this doesn't exist yet but it's being worked on with a recent pr here https://github.com/GMOD/jbrowse-components/pull/3648

that pr doesn't have the URL parameter but that should be relatively easy to add too

I can keep you posted with any updates

**Comment by cmdcolin** [comment]
this is now added to jb2 with the url parameter like &highlight=chr1:1-100 :)
