### ISSUE TITLE
[Question] Is there any hideURIs option like JBrowse 2?

### ISSUE THREAD

**Issue by shreyas-a-s** [GMOD/jbrowse#1650]
There is a [hideUris](https://jbrowse.org/jb2/docs/config/formatabout/#slot-configurationformatabouthideuris) option for configuring jbrowse 2 which lets us hide the uri locations from being seen by user. Currently when user selects a track and clicks `Edit config`, they gets the url of the fasta, gff3 files which I would like to prevent. Is there any way I can achieve this?

Thanks in advance.

**Comment by cmdcolin** [comment]
i am not sure we have one, sorry :) some complicated plugin may be able to remove e.g. the edit config entirely but it would all be a bit of 'security by obscurity' as someone can check the network tab to see the urls after all

**Comment by shreyas-a-s** [comment]
It's totally ok. No problem at all. I was just curious that's all.

And yeah that's a valid point. That is, normal users won't be bothered to check the url and tech-savy users have other means of finding urls other than just looking at the `edit config` even if it is hidden. Hence there's not really a great advantage of hiding it.

Thanks for the reply.
