### ISSUE TITLE
Adding New Reference

### ISSUE THREAD

**Issue by marcodimarsico** [GMOD/jbrowse#1655]
Hi, thank you very much for this amazing tools. 
I am currently using jbrowse version 1.12.4. 

With the instance that I am currently using I have no trouble showing all the tracks that I have:
- I see the reference genome;
- I see the annotation;
- I see the custom annotation based on the previous one
- I see all the tracks such as VCF, bigwig, BAM

Now I want to add an additional reference genome, with a new annotation and all the tracks associated to them.
I created a new folder in which I would call the DNA sequence and an additional one for the annotation (both by using the prepare-refseqs.pl and flatfile-to-json.pl scripts). 
When I load the jbrowse, I can see the elements in the menu but:
1) on the visualization panel it reports that "No sequence is available"
2) the annotation tracks seems empty (I guess that it is associated to the previous error, since it seems that the new reference cannot be loaded. 

I add this block of information in the trackList.json (since it is the one that I am using and not the tracks.conf)

```json
     {
         "category" : "New sequence",
         "chunkSize" : 20000,
         "key" : "New sequence",
         "label" : "NEWDNA",
         "seqType" : "dna",
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "type" : "SequenceTrack",
         "urlTemplate" : "new/seq/{refseq_dirpath}/{refseq}-"
      },
```

```json
    {
         "category" : "New sequence",
         "compress" : 0,
         "key" : "NewAnnotation",
         "label" : "NewAnnotation",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : "CanvasFeatures",
         "type" : "CanvasFeatures",
         "urlTemplate" : "data/tracks/NewAnnotation/NewAnnotation/{refseq}/trackData.json"
      },
```

I would really appreciated your help.

PS: json file is file, it is not corrupted or bad formatted. 

Thanks in advance.

**Comment by cmdcolin** [comment]
jbrowse 1 is only capable of loading one reference sequence at a time.

the only thing that jbrowse 1 can do to hav multiple genomes loaded is to make separate 'data folders' and then use ?data=datafolder1 and ?data=datafolder2 in the url to go btween them




for truly loading multiple genoms in a single tracklist, i recommend using jbrowse 2 (which i what I work on most of the time now). it is capable of loading multiple genomes in a single instance, showing the alignment between them in synteny style views, and much more (see https://jbrowse.org/jb2/ and our github https://github.com/GMOD/jbrowse-components)

**Comment by marcodimarsico** [comment]
thank you very much for your help!
