### ISSUE TITLE
display local files

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#173]
- [x] BAM
- [x] BigWig
- [x] GFF3
- [x] Wiggle
- [ ] bigBed
- [ ] bed
- [ ] bedGraph
- [ ] FASTA
- [ ] 2bit

**Comment by cmdcolin** [comment]
seems like we got most of this now, including opening custom ref genomes client side

only missing bigBed/bedgraph but I know bigbed is elsewhere. maybe close for now
