### ISSUE TITLE
switch to disable toolbar display only

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#255]
On 05/14/2013 05:57 AM, Martin Asser Hansen wrote:
> Hello,
> 
> 
> I was playing around with the embedded mode turning off nav, tracklist 
> and overview as described in the documentation:
> 
> http://gmod.org/wiki/JBrowse_Configuration_Guide#Embedded_mode
> 
> Is there a way of hiding the top menu only? (The blue bar with the 
> Volvox Example drop down menu, File, View and Help)

**Comment by cmdcolin** [comment]
This was actually squeezed into the 1.11.6 release. This issue could be closed probably

**Comment by cmdcolin** [comment]
&menu=0 in the url or show_menu: 0 in the conf
