### ISSUE TITLE
Support direct access to bgzip/tabix'ed GFF/BED flat files and/or BigBed files

### ISSUE THREAD

**Issue by benwbooth** [GMOD/jbrowse#265]
It would be more convenient if all the track data could be stored as standalone direct access files, like the BAM, BigWig, and VCF tracks are currently stored. GFF3/2 and BED files could be stored as bgzip/tabix'ed files like the VCF files. Then the flatfile-to-json.pl script could be deprecated.

**Comment by zhjilin** [comment]
Sorry to bring up this topic, I am wondering  if anyone has implemented the GFF3Tabix or BEDTabix?  Just in case I am not going to repeat others' work :/. 
I would be very glad to help to run some test, as I need this function to improve the way of visualizing our data as well.

**Comment by cmdcolin** [comment]
Hi @zhjilin check out pull request #670 this adds the ability for gff3 tabix

**Comment by zhjilin** [comment]
Nice work @cmdcolin  !  ( BED format is much easier than GFF3, I could do a BED tabix myself later  :)

**Comment by cmdcolin** [comment]
BED and BED tabix would be great. Especially if it was just the simple types of BED files...I remember using those a lot

**Comment by keiranmraine** [comment]
+1 for tabix BED support, it would be 90% of what I'd need to get copynumber segments into a track

**Comment by cmdcolin** [comment]
BED and GFF tabix on master branch now :)

**Comment by bslaff** [comment]
What's the best way to view custom bed files in JBrowse, like encode narrowpeak?

**Comment by cmdcolin** [comment]
@bslaff you can make a small adapter that derives from the BEDTabix class. I did this for another BED-like format recently so I made a narrowpeak adaptor here :) https://github.com/cmdcolin/narrowpeak

**Comment by bslaff** [comment]
Thanks very much!

**Comment by bslaff** [comment]
When using GFF tabix, is there a way to disappear the feature labels?
In this screen shot, the top track is an import of the gencode v19 gene annotation using flatfile-to-json. The bottom track is the same annotation using GFF tabix. In the trackList.json I have used the config
"style" : {
            "className" : "feature",
            "showLabels" : "false",
            "displayMode" : "compact"
         },
But we still get this kind of cluttered display with all the feature labels
![tabix_vs_importjson_genc19chr22](https://cloud.githubusercontent.com/assets/2781386/21854710/c440cf0e-d7e9-11e6-8f29-5fd55944cb99.png)
 shown.

**Comment by cmdcolin** [comment]
You probably want `"showLabels": false` instead of `"showLabels": "false"`

When it's quoted, it ends up being interpreted as true! Sort of similar to how numbers also don't need quoting in json

**Comment by bslaff** [comment]
That did it! Thanks. Also realized I had displayMode in the wrong place. Fixing this gave me more control.

**Comment by cmdcolin** [comment]
Cool :)

You might want to be aware of this list of potential issues with gff3 tabix currently in place https://github.com/GMOD/jbrowse/issues/780

If you find any more issues feel free to add to that list

**Comment by bslaff** [comment]
Thanks, will do!

**Comment by cmdcolin** [comment]
Since the tabix bed/gff is on master, maybe close in favor of #86

Summary of issue thread.

* tabix gff works, has caveats to be aware of #780
* tabix bed works fine, can even subclass it to make custom bed-like formats
* there is rudimentary gtf support from the "Open track" menu, but not from flatfile-to-json.pl. converting to gff is likely better for most cases in jbrowse
