### ISSUE TITLE
"Too many links" problem with flatfile-to-json.pl

### ISSUE THREAD

**Issue by abretaud** [GMOD/jbrowse#340]
Hello,

I am using jbrowse (1.10.2) for a draft assembly of a genome. It contains more than 45000 scaffolds.

I get an error when trying to load a gff file with matches on every scaffolds: "Too many links at [...]src/perl5/JsonFileStorage.pm line 65".

I try to load it with a command that looks like this:
bin/flatfile-to-json.pl --gff /example/my/matches.gff

Looking in the data/tracks/mytrack/ directory, I see that there are 32000 directories, 1 for each scaffold. The error come from the file system that doesn't support creating more than 32000 directories.

The same kind of problem as been solved for sequence storage: #139 
It would be very useful to have a fix for this problem as it prevents me from adding a track that could be quite useful.

**Comment by cmdcolin** [comment]
Just for reference, Tabix GFF could be used as a workaround here

**Comment by ilaydabozan** [comment]
Hi,

I'm trying to load 12 genomes and they are highly fragmented 200k+ contigs each. When I ran bin/prepare-refseqs.pl on the second one it took a lot of time and consumed all the RAM on the third one it consumed all the memory in the VM. I got this similar error;

No space left on device at /home/ubuntu/jbrowse2/bin/../src/perl5/Bio/JBrowse/Cmd/FormatSequences.pm line 595.

Now there is no memory left in the VM. 

Is there a work around this and better practice to put 12 genomes as such on JBrowse?

**Comment by cmdcolin** [comment]
You might consider using indexed file formats such as GFF3Tabix and IndexedFasta

**Comment by cmdcolin** [comment]
Note that the error No space left on device is literally, that you have no disk space left though, and may be unrelated to the "Too many links" error

**Comment by cmdcolin** [comment]
flatfile-to-json could have some problems with that number of contigs, but only if a large proportion of the contigs had annotations on it

**Comment by cmdcolin** [comment]
So, again, alternative is to manually use GFF3Tabix

**Comment by ilaydabozan** [comment]
Thank you for the suggestions but I'm having this problem while trying to upload the reference genome so I have fasta files. I believe running prepare-refseqs.pl on the contigs.fa created so many little folders and files under it, it filled up the entire disk which is very unexpected. 
But I believe GFF3Tabix is for annotation files. What should I do with reference sequences in fasta format?

**Comment by cmdcolin** [comment]
You can use indexed fasta, this should be efficient. You'll need samtools, then just run

samtools faidx yourfile.fa

This generates yourfile.fa.fai

Then run

bin/prepare-refseqs.pl --indexed_fasta yourfile.fa 

This will copy yourfile.fa and yourfile.fa.fai to the data directory

You can also use bgzip+indexed fasta if you want some good compression is a concern but indexed fasta is generally fine

bgzip fasta uses

bgzip -i yourfile.fa
samtools faidx yourfile.fa.gz
bin/prepare-refseqs.pl --bgzip_fasta yourfile.fa.gz
