### ISSUE TITLE
layerX/layerY warnings in safari

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#342]
On 09/13/2013 02:49 PM, Jim Hu wrote:

> I'm also seeing
> 
>   44event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.
> 
> in Safari's error console when I scroll horizontally.

**Comment by cmdcolin** [comment]
haven't seen this in a long time. might not still be an issue? maybe reopen if it reoccurs
