### ISSUE TITLE
dijit dialog scrolling bug, chrome 31/osx 10.9

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#386]
From #318 comments:

> HTML variants tracks I've got a small bug when I arrive at the end of
> the popup (when scrolling down with my trackpad): it goes back to the
> top as a cycle.

What browser and version do you see this on?

> Version 31.0.1650.57 and OSX 10.9

**Comment by cmdcolin** [comment]
this is actually way less bad in recent chrome versions than it used to be. safari is still affected, but I think it is reasonable to just close and forget

(recall: symptom is that scrolling through a view dialog box makes it jump back up to the top)
