### ISSUE TITLE
Bug? 'Delete track' for local tracks closes all not just selected.

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#428]
Hi Robert,

To reproduce use File Open to open the following in one go:

MySample.bam
MySample.bam.bai
MySample.bw (as separate XY plot)

(immediate open)

The select 'Delete track' on the BAM track.
All locally opened tracks are removed from display but BW track remains in faceted track selector.

I'm would expect that the BW track should still be displayed, or is this intentional behaviour?

Regards,
Keiran

**Comment by cmdcolin** [comment]
I've never seen this one get reproduced :) maybe we can close unless seen again
