### ISSUE TITLE
Store/SeqFeature/VCFTabix/Parser.js parseHeader function not always receiving enough bytes for a complete header

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#438]
This came up when trying to access the genotypes and sample names from a large VCF (bgzip compressed and tabix indexed) that is 6.6 Gb uncompressed with ### variant features. It also has a highly fragmented genome assembly with close to 13000 scaffolds, and GATK includes each one in the header in lines beginning with "##contig=".

I've found that the last few lines of the full header is not parsed in this example file, including the #CHROM prefixed line containing sample names. Tests with VCF altered as follows all parse the complete header:
1) truncated file with full header and only 9 variant features
2) truncated file with header modified to remove the ##contig lines
3) full file with header modified to remove the ##contig lines

I suspect that the Store/SeqFeature/VCFTabix.js getVCFHeader function is not fetching enough data to access the full header in the original large file. maxFetch is getting set to only 65535, due to thisB.indexedData.index.firstDataLine.block returning zero. Not sure why that is either.

One way to handle this (assuming I can't properly set thisB.indexedData.index.firstDataLine.block instead) is to fetch more data and continue parsing if the last line parsed in Store/SeqFeature/VCFTabix/Parser.js parseHeader still started with a # character. This function already skips lines that don't match this character at the start, so we'd just be ensuring that the entire header is parsed.

**Comment by zhjilin** [comment]
I got a similar problem last Friday when I put longer custom headers into tabix index BED files due to 2^16 -1 limitation. I solved it by increasing 'maxFetch'. 
I am using trackList.json to control my access, since I could not get a proper visualization with local track method.

**Comment by cmdcolin** [comment]
@zhjilin I was actually going to comment on your note in #670 that you might run into something like this. I think all the lines that are starting with a "#" will end up in the header, so you could end up with a really large header....Perhaps increasing header size maxFetch is a workaround but maybe there are other workarounds too? I think you might not want to increase header size too much at least

**Comment by zhjilin** [comment]
Thanks @cmdcolin ! You are right.  I don't want a heavy header either, luckily I don't have so many lines for now(may get more in the future). One alternative is to use Tabix GFF3 (I don't like this, which ends up with a big GFF3 file). 
I will submit my BEDTabix soon after I made it compatible with simple BED (3columns) file.
