### ISSUE TITLE
CanvasFeatures has strange histogram

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#474]
I first pointed this out in the HighDPI thread (#456) but this affects older versions of jbrowse too

![strange-histogram](https://cloud.githubusercontent.com/assets/6511937/2923634/5bb822a0-d71c-11e3-9e56-db3feede1171.png)

I loaded the same track into JBrowse twice with the same command, only differing on whether they have CanvasFeatures enabled

```
bin/flatfile-to-json.pl --gff ~/Downloads/Mus_musculus.GRCm38.75.gff --trackLabel "Mus_musculus.GRCm38.75.gff" --nclChunk 10000
bin/flatfile-to-json.pl --gff ~/Downloads/Mus_musculus.GRCm38.75.gff --trackType CanvasFeatures --trackLabel "Mus_musculus.GRCm38.75.gff (CanvasFeatures)" --nclChunk 10000
```

Here's a link to the data file I used (actually modified to gff from #453) http://www.divshare.com/download/25522772-b35

Here's a closer zoom of the histograms

![jbrowse-1-13112232-47647916 2014-05-08 21-07-23](https://cloud.githubusercontent.com/assets/6511937/2923737/cbb80884-d71e-11e3-9a14-aefac4e429e8.png)

**Comment by rbuels** [comment]
Closing for now, reopen if this turns out to still be an issue.
