### ISSUE TITLE
Left Click Configuration

### ISSUE THREAD

**Issue by DavidMuller** [GMOD/jbrowse#480]
Hello,

I'm having difficulty with left click configuration.  I inserted some left click customization verbatim from the <a href="http://gmod.org/wiki/BrowseDev/Using_a_Database_With_JBrowse#Click_Configuration_Options">JBrowse Configuration page</a> to the yeast "Protein-Coding genes" track provided with JBrowse 1.11.4, as in:
"onClick" :         {
           "iconClass" : "dijitIconDatabase",
           "action" : "iframeDialog",
           "url" : "http://www.ncbi.nlm.nih.gov/gquery/?term={name}",
           "label" : "Search for {name} at NCBI",
           "title" : "function(track,feature,div) { return 'Searching for '+feature.get('name')+' at NCBI'; }"
        }

When I click on a gene, a pop-up does appear searching NCBI with the name of the gene I've clicked on.  However, a mouse hover over the feature reads only as: "Search for {name} at NCBI."   Any idea what could be causing this?

Thanks for your help! 

-David

**Comment by cmdcolin** [comment]
There are examples of this in the volvox browser config in case anyone lands on this issue
