### ISSUE TITLE
URL Controlled Highlighting

### ISSUE THREAD

**Issue by DavidMuller** [GMOD/jbrowse#482]
Is it possible to highlight multiple regions in JBrowse via URL query parameters?  

The (<a href="http://gmod.org/wiki/BrowseDev/Using_a_Database_With_JBrowse#Controlling_JBrowse_with_the_URL_Query_String">JBrowse Configuration Guide's</a>, only example involves highlighting one region, and I haven't been able to get it manipulate the arguments in such a way as to produce more than one highlight.

**Comment by cmdcolin** [comment]
Sort of realized that it might be really cool to have a multihighlight or bookmark type tool.

**Comment by enuggetry** [comment]
How should they persist?  URL?
I kinda think these kinds of things could be empowered by a back-end agent.  It could be pretty robust.

**Comment by cmdcolin** [comment]
Yes it would be pretty great if it could get the highlighted regions from apollo or some other backend
