### ISSUE TITLE
Carry local tracks between tabs

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#484]
I'm not sure if this is possible within the scoping of JS but thought I'd ask.

When you right-click on a read in the alignments2 track you have the option to 'Open mate/next location in new tab'.  If you have opened tracks in the original view the new tab doesn't contain these, which is annoying if you selected the option in the locally loaded track.

**Comment by rbuels** [comment]
@keiranmraine is this still an issue?  This sounds like a bug, the list of open tracks is supposed to be stored in localstorage or a cookie, so new windows will have the same list of open tracks.

**Comment by rbuels** [comment]
Oooh is this for local-file tracks?  There is no way to carry those between tabs because of the security restrictions in browsers.

**Comment by rbuels** [comment]
@keiranmraine ping? Is this local-file tracks?  Can this be closed?

**Comment by keiranmraine** [comment]
@rbuels , yes, this was specific to loading additional track locally.  Closing
