### ISSUE TITLE
Track Pulldown Menu Obscuring Individual Feature Data

### ISSUE THREAD

**Issue by halfwayBraindead** [GMOD/jbrowse#490]
Under a sufficiently long track title, the track pulldown menu in JBrowse will semi-opaquely obscure large swaths of individual track features, like so in the following screenshot:

<a href="http://i.imgur.com/sVDlH13.png" target="_blank">Long Track Name's Pulldown Menu Obscuring its Features</a>

This can be extremely disruptive for end-users' browsing experience, so would it be possible to adjust the track layout format in JBrowse such that the track pulldown menu is placed <strong>above</strong> the individual track features?

**Comment by cmdcolin** [comment]
The global config trackLabels: no-block should address this

**Comment by cmdcolin** [comment]
Maybe close for now :)
