### ISSUE TITLE
Allow multiple names stores

### ISSUE THREAD

**Issue by benwbooth** [GMOD/jbrowse#499]
I've written a REST-enabled JBrowse backend which uses the REST names API for name lookups. However, now I need to add some static JBrowse tracks to my browser. I can add the tracks as an extra include directive in my jbrowse.conf file, but I want the tracks to be searchable. It would be nice if I could specify another names backend that JBrowse could use to search for names. So instead of giving a single names entry, I could give a list of names backends, and JBrowse would search each names database in order until it finds a match.

**Comment by cmdcolin** [comment]
Latest version now allows name stores to be initialized via plugins, so if a plugin wanted to search both hash store and another one that is certainly possible. Maybe close for now in that case!
