### ISSUE TITLE
  Feature request for add-bw-track.pl

### ISSUE THREAD

**Issue by childers** [GMOD/jbrowse#510]
Typo in help: the usage text refers to the program as "add_bw_track.pl", where is should be "add-bw-track.pl"

There are options I manually set that are usable, but not recognized as command line set parameters. I would like these parameters as optional command line options.
"clip_marker_color"
"height"
"bg_color"

**Comment by cmdcolin** [comment]
Here's a basic idea for adding the functionality

31,34d30
< my $height;
< my $clip_marker_color;
< my $bg_color;
< 
48,50d43
<            "clip_marker_color|M=s" => \$clip_marker_color,
<            "bg_color|B=s" => \$bg_color,
<            "height|H=s" => \$height,
118,120d110
< 	$bw_entry->{clip_marker_color} = $clip_marker_color;
< 	$bw_entry->{height} = $height;
< 	$bw_entry->{bg_color} = $bg_color;
188,190d177
< 	[ --clip_marker_color <color_for_clip_marker> ]    \
< 	[ --height <track_height> ]                        \
< 	[ --bg_color <background_color> ]                  \
