### ISSUE TITLE
Gridlines absent when no features are present

### ISSUE THREAD

**Issue by laceysanderson** [GMOD/jbrowse#514]
I have a JBrowse where the reference was loaded with the --noseq option for a FASTA file. When you navigate to a reference sequence for which there are no features in any track, none of the gridlines appear. See: http://knowpulse2.usask.ca/jbrowse/Lentil/index.html?loc=Lc0.7_contig168083638%3A11..90&tracks=Redberry454Contigs&highlight=

This made we worry my JBrowse was broken until I found a scaffold which did have features and was especially worrisome/problematic when I only had the reference loaded and no other tracks. Here's an example from the same JBrowse but where there are features: http://knowpulse2.usask.ca/jbrowse/Lentil/index.html?loc=Lc0.7_scaffold62358-1%3A16421..20822&tracks=Redberry454Contigs&highlight=

Also the JBrowse seems to take an really long time to load which I haven't noticed in other instances. I'm uncertain as to whether this is due to the --noseq option or the number of reference sequences.

~Lacey

**Comment by cmdcolin** [comment]
I think the fact that no features are present is a red herring, it seems more to have to do with specific zoom levels causing problems.


    diff --git a/src/JBrowse/View/Track/GridLines.js b/src/JBrowse/View/Track/GridLines.js
    index bc50fd3..95b1a7b 100644
    --- a/src/JBrowse/View/Track/GridLines.js
    +++ b/src/JBrowse/View/Track/GridLines.js
    @@ -44,8 +44,10 @@ return dojo.declare( BlockBased,
                 !( base_span % 10 ) ? 10 :
                 !( base_span % 5  ) ? 5  :
                 !( base_span % 2  ) ? 2  :
    +            !( base_span % 1  ) ? 5  :
                                       0;
             var major_count = base_span == 20 ? 2 : base_span > 0 ? 1 : 0;
  
             var new_gridline = function( glclass, position ) {
