### ISSUE TITLE
Names folder issue after update

### ISSUE THREAD

**Issue by bartg01** [GMOD/jbrowse#517]
First of all, thanks to all developers for the great work done with JBrowse project!

Recently, I updated the JBrowse version from 1.9.7 to 1.11.5, almost everything goes right. But since the update, each time I open the browser a message is shown: "Error reading from name store.". Then, I tried to reload the name indexes using generate-name.pl, and unfortunately the script gives a warning message: "WARNING: No feature names found for indexing, only reference sequence names will be indexed."

I have read an issue about "new" tracks.conf files and generate-name.pl script... Could the problem be related with these tracks.conf files? Should I change my config file to this new format?

Thanks you very much, looking forward for your response.

**Comment by cmdcolin** [comment]
A fair number of people seem to arrive at this page probably due to the message "Error reading from name store"

this error can happen for a variety of reasons, however, probably not due to the same reasons discussed here

Try posting a new issue if you see it again!
