### ISSUE TITLE
Overlap between track label and request data

### ISSUE THREAD

**Issue by gdroc** [GMOD/jbrowse#519]
Hi,
There is an overlap between the label of the track (i.e Gene or Gene models) and the corresponding glyph at the left of the screenshot. 
Does it possible to fix that?
Regards 

First example (in our website)
![capture d ecran 2014-10-13 a 14 41 54](https://cloud.githubusercontent.com/assets/154846/4613515/86138734-52d6-11e4-94b9-0dd4d5eb2611.png)

Second example refer to Solanum lycopersicum (tomato)  
![capture d ecran 2014-10-13 a 14 41 30](https://cloud.githubusercontent.com/assets/154846/4613517/88288524-52d6-11e4-8895-3351d3206ff4.png)

**Comment by cmdcolin** [comment]
Closed for duplicate
