### ISSUE TITLE
Paired end reads linkage in BAM and CRAM file

### ISSUE THREAD

**Issue by Kinztan** [GMOD/jbrowse#521]
Is there any function that can enable to visualize the paired end links between two pair ends. Just like the broad IGV did, it is quite important to visualize the linkage of pair end sequence to understand their mechanism. Is there any configuration I need to change for that?

**Comment by cmdcolin** [comment]
Some discussion that was sort of tangential was moved to here #560

**Comment by rbuels** [comment]
@scottcain you have some paired reads data that you have been working with at wormbase, could you maybe paste your configuration here?

**Comment by scottcain** [comment]
@rbuels, as much as I'd like for it to be generally applicable to BAM read pairs, the work I've done with pair ESTs is sufficiently different as to not be very helpful.  What I've done hinges on preprocessing the EST match GFF and creating a parent "experimental_feature" feature that has the two match features as children.  So it looks kind of like this:
```
experimental_feature
   match (for the 5' EST)
      match_part
      match_part
   match (for the 3' EST)
      match_part
      match_part
```
The only way I could see this working for BAM data would be if there were a process in JBrowse that would do the same sort of thing, but I have a hard time believing it would be anywhere near fast enough.

If it's helpful at all, the glyph I wrote is here:

https://github.com/WormBase/website-genome-browsers/blob/est_glyph/jbrowse/jbrowse/plugins/wormbase-glyphs/js/LinkedEST.js

**Comment by cmdcolin** [comment]
This is a code for connecting bam reads that adds two new glyphs, one using arcs and another with lines https://github.com/elsiklab/apollo_lsaa/tree/master/client/PairedReadViewer

It uses the bam coordinate position of the mate pairs to just draw lines "towards" it's mate

**Comment by keiranmraine** [comment]
@rbuels , WGS paired end data available here:

ftp://ngs.sanger.ac.uk/production/cancer/dockstore/cgpwgs/

Corresponding ref is Human GRCh37 (no chr prefix)

**Comment by rbuels** [comment]
Oh thanks so much for that! Good sample data is key.

**Comment by rbuels** [comment]
implementation sketch
* have a checkbox where you can turn on and off "connect paired reads", I guess it would default to on, but that could be configurable, cause this will have a significant performance hit
* do the rendering in two passes.  fetch all the data in one pass and make sure it's cached, then go through again and search the cache for each read's mate and aggregate them into parent/child features

**Comment by cmdcolin** [comment]
A cursory look at the igvjs code looks like it is a bit different from the block based rendering that jbrowse uses. It gets a large "alignmentContainer" that gets all alignments within the current view plus a bit outside the boundaries of the view too. Then, when you scroll sideways far enough, it will then reload the "alignmentContainer" with new reads, and redo pairings. This type of strategy is something that can probably be emulated with the JBrowse codebase but it would be sort of a different strategy than the block based style track/store that is used in most tracks.

**Comment by rbuels** [comment]
What if we do something similar to GFFTabix, where it redispatches requests
if paired is on?  Would be simplest to implement, and might not actually be
as slow as one might think, if the feature caching is working well.

**Comment by cmdcolin** [comment]
Nice idea. I'll see what that might entail...it sounds pretty reasonable

**Comment by cmdcolin** [comment]
At least one scenario that is difficult when just looking at a small block-by-block basis is if a BAM pair is on either side of a block, then the block will basically have no knowledge of it.

Example, this view works at a zoomed out level with several pairs going across the deletion, but if you zoom in, such that you are inside the deletion, it looks glitchy.

Here's the nice non glitchy screenshot though :)
![screenshot-localhost-2018 07 25-09-54-41](https://user-images.githubusercontent.com/6511937/43205477-72991672-8ff1-11e8-9c36-d11f58ae73f3.png)

**Comment by scottcain** [comment]
The alignmentContainer thing would be basically making the track one big glyph--that way everything knows about everything else in the view (and a little nearby, I imagine).  It wouldn't be too hard to implement; it would be similar to what I did to make the paired ESTs work (though I built the "super object" by preprocessing the GFF). It would certainly work, but would it be performant?

**Comment by scottcain** [comment]
Another thing that would be nice about the track being a single large glyph is that you'd be able to do things that are typically hard to do in a track, like sorting on arbitrary things: are they paired or not, are there splice junctions or not.  Could make for a really nice display, putting the "important" things at the top of the track.

**Comment by cmdcolin** [comment]
We reviewed example read pairing code from PairedReadViewer and looked at what our steps will probably be for obtaining solid functionality for this. Steps are probably as follows

step 1 refactor remotebinarystore with query aggregation
step 2 refactor  bam module with query agg with read pairing
step 3 add pairing
step 4 add redispatching for region around current view
step 5 pull in pairedreadviewer glyphs

**Comment by cmdcolin** [comment]
This was delivered in JBrowse 1.16.0!

Please give it a try and make new bugs if there are any issues or suggestions

**Comment by cmdcolin** [comment]
See docs here http://jbrowse.org/docs/paired_reads.html and blogpost  http://jbrowse.org/blog/2018/12/13/jbrowse-1-16-0.html

**Comment by malonge** [comment]
Hi there! Is this feature available on JBrowse2? It would be a very useful addition.

**Comment by cmdcolin** [comment]
@malonge we recently added "Arc view" and "Read cloud" view to jbrowse 2, which helps show paired reads as linked entities

Some info here https://jbrowse.org/jb2/blog/2022/12/15/v2.3.1-release/

It doesn't draw the pairs using the "stacked layout" like you'd normally see, but instead draws arcs (for the "Arc view") or lays them out stratified by "insert size" on the y-axis (for the "Read cloud")

We may add the normal "stacked" layout as a feature in the future, but hopefully this helps :)

## Some example links


- Showing both "Arc view" and "Read cloud" on the same set of paired end reads from simulated sample data https://jbrowse.org/code/jb2/v2.3.2/?config=test_data%2Fvolvox%2Fconfig.json&session=share-ms4H1EIfmi&password=iQuGf

- Showing "Arc view" connecting split long reads from our simulated sample data https://jbrowse.org/code/jb2/v2.3.2/?config=test_data%2Fvolvox%2Fconfig.json&session=share-3ywtm363HS&password=UY3u7

**Comment by malonge** [comment]
awesome thank you! looks like I need to update to a newer version of JBrowse2 (I am still using v2.0.1). Thanks!
