### ISSUE TITLE
Mismatched read bases rendered incorrectly

### ISSUE THREAD

**Issue by 09140930** [GMOD/jbrowse#523]
Hi - apologies in advance if this stems from a misunderstanding.

JBrowse 1.11.5.
I'm looking at 4 reads overlapping a position where a variation exists. The reference is "A", and the four observed bases are G/C/C/C/C. They are highlighted as being mismatches (which I expect), but are rendered as T/A/A/A/A, which makes no sense to me. Maybe I'm misunderstanding something?

The attached screenshot demonstrates what I mean. The popup refers to the bottom-most of the 4 visible reads.

I've checked the underlying BAM and have confirmed that the bases are indeed G/C/C/C/C.

Perhaps this is a bug?

![screen shot 2014-10-17 at 19 42 27](https://cloud.githubusercontent.com/assets/9286608/4684087/023db6dc-562d-11e4-9dd6-de925edef05a.png)

**Comment by cmdcolin** [comment]
I would like to add unit testing for this eventually
