### ISSUE TITLE
factor out parsers and stores as independent npm modules

### ISSUE THREAD

**Issue by wilzbach** [GMOD/jbrowse#529]
It would be great if JBrowse could publish their parsers (GFF,BAM,Wig,VCF,etc.) as separate modules to npm so that they can be easily reused by other JavaScript projects like BioJS or Bionode.

I would suggest this tiny roadmap
1. Create a list of interesting packages that can be reused
2. (Distribute the work and), convert the files to npm modules and publish them

For 1) we should also see whether there are other already existing JS projects.
I know of these two parsers, but I haven't tested one of them.

https://github.com/anilthanki/biojs-io-wig
http://registry.biojs.net/client/#/detail/biojs-io-sam 

I just start the list for 1)
- GFF3
- GTF
- VCF
- BAM
- BigWig
  (please modify this list)

@bmpvieira @homonecloco @saketkc

**Comment by rbuels** [comment]
@wilzbach this is in progress, https://www.npmjs.com/package/@gmod/gff is the first, which is consumed by JBrowse 1.14.0

the BAM/CRAM code will be next.

**Comment by nathandunn** [comment]
👍

**Comment by rbuels** [comment]
Closing this issue in favor of more specific issues for each backend that gets migrated.  They are all going into the @gmod organization on npm.

some of the specific issues that fall under this:
* #1178 
* #1152 
* #1096 
* #1155
