### ISSUE TITLE
Publish JBrowse to the BioJS registry

### ISSUE THREAD

**Issue by wilzbach** [GMOD/jbrowse#530]
The BioJS registry is a listing of biological javasscript applications (visualizations, parsers, ...).
Publishing JBrowse would (a) give the JBrowse project more public visibility, (b) would make it easier for biologist to embed JBrowse in their website and (c) (in the future) way easier to combine the JBrowse application with other BioJS components.

Why is it easier to embed? Because for the registry a component provides >= 1 visualization example on how to use this specific component and these examples have to define all their dependencies and thus can be modified in JSBin (edit button).

If JBrowse is easy to embedd the only obstacle would be to publish JBrowse (as it uses AMD) to npm.
I don't think that this should be a big problem as there is a bunch of projects to allow the AMD syntax in node (e.g. [amd](https://github.com/dominictarr/amd) or [node-amd-require]https://www.npmjs.org/package/node-amd-require).

**Comment by cmdcolin** [comment]
@gmod/jbrowse on npm might be satisfactory for this, it seems to satisfies some of the requirements of this. Maybe we can close for now :)
