### ISSUE TITLE
Parsing GFF3 files..

### ISSUE THREAD

**Issue by wkpalan** [GMOD/jbrowse#537]
I have tried parsing some GFF3 files which are downloaded from Gramene. The flatfile-to-json.pl script cannot parse through the file correctly. Each, feature in the file become it's own entity without collapsing to for genes/transcripts/mRNA. I played around and found that the cause of this is that the file has the attribute "Parent" in full caps as "PARENT". Would it be possible to allow identification of all the attributes regardless of upper or lower case in the GFF3 file?

We can always convert the upper case to lowercase, but need to maintain some direct links for the files. 

For Example
<pre>
Pt      ensembl gene    6392    12986   .       +       .       ID=gene:GRMZM5G856777;biotype=protein_coding;description=Photosystem II CP43 chlorophyll apoprotein  [Source:UniProtKB/Swiss-Prot%3BAcc:P48187];external_name=PSBC;logic_name=genebuilder
Pt      ensembl transcript      3363    5604    .       -       .       ID=transcript:GRMZM5G811749_T01;PARENT=gene:GRMZM5G811749;biotype=protein_coding;description=est|oprotein;external_name=RPS16;logic_name=genebuilder
Pt      ensembl exon    3363    4708    .       -       .       NAME=GRMZM5G811749_E02;PARENT=transcript:GRMZM5G811749_T01;constitutive=1;ensembl_end_phase=-1;ensembl_phase=1;rank=2
Pt      .       three_prime_UTR 3363    4490    .       -       .       PARENT=GRMZM5G811749_T01
Pt      ensembl CDS     4491    4708    .       -       2       ID=CDS:GRMZM5G811749_P01;PARENT=transcript:GRMZM5G811749_T01
Pt      ensembl CDS     5565    5604    .       -       0       ID=CDS:GRMZM5G811749_P01;PARENT=transcript:GRMZM5G811749_T01
Pt      ensembl exon    5565    5604    .       -       .       NAME=GRMZM5G811749_E01;PARENT=transcript:GRMZM5G811749_T01;constitutive=1;ensembl_end_phase=1;ensembl_phase=0;rank=1
Pt      ensembl transcript      1674    3308    .       -       .       ID=transcript:GRMZM5G836994_T01;PARENT=gene:GRMZM5G836994;biotype=protein_coding;description=protein;external_name=MATK;logic_name=genebuilder
Pt      ensembl CDS     1674    3308    .       -       0       ID=CDS:GRMZM5G836994_P01;PARENT=transcript:GRMZM5G836994_T01
Pt      ensembl exon    1674    3308    .       -       .       NAME=GRMZM5G836994_E01;PARENT=transcript:GRMZM5G836994_T01;constitutive=1;ensembl_end_phase=0;ensembl_phase=-1;rank=1
Pt      ensembl transcript      6392    12986   .       +       .       ID=transcript:GRMZM5G856777_T01;PARENT=gene:GRMZM5G856777;biotype=protein_coding;description=est|mrna|protein;external_name=PSBC;logic_name=genebuilder

</pre>

**Comment by cmdcolin** [comment]
Seems that this should be a nofix. If there's any disagreement feel free to reopen
