### ISSUE TITLE
Too many links at /home/www/jbrowse/JBrowse-1.11.5/bin/../src/perl5/JsonFileStorage.pm line 64.

### ISSUE THREAD

**Issue by ge11232002** [GMOD/jbrowse#539]
I am using JBrowse 1.11.5. When I tried to load a GFF file with more than 80000 contigs, it failed with the error above. The maximal number of contigs I can load is 31999.
Is there any workaround?

**Comment by cmdcolin** [comment]
Closed for duplicate
