### ISSUE TITLE
Add support for compressed BAI files

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#542]
Hi,

There is some discussion on the samtools mailing list about setting your nginx server to automatically compress BAI files and then have the receiving tool decompress them when storing locally.  This can reduce the time it takes to add a new bam track quite considerably for wholegenome sequence where these files can reach 20-30 MB.

This think this can also be applied to *.tbi index files (assuming not already compressed).

Regards,
Keiran

**Comment by cmdcolin** [comment]
do you have a link for this particular discussion?  here is another discussion that takes a different approach

http://www.hammerlab.org/2015/01/23/faster-pileup-loading-with-bai-indices/

**Comment by keiranmraine** [comment]
I think this approach from BioDalliance is an excellent alternative, especially as there is then no need to cache 20-30 MB of index for every bam track.

If JBrowse could be configured to fall back to native bai if the bai.json isn't found it would be very flexible.

**Comment by cmdcolin** [comment]
One alternative that was discussed here is actually breaking up the bam file http://gmod.827538.n3.nabble.com/Gmod-ajax-Speed-up-VCF-loads-td4053337.html

**Comment by rbuels** [comment]
So if we added code to the BAI loading to detect whether the BAI is compressed, and decompress it, that would probably take care of this, right?

**Comment by keiranmraine** [comment]
@rbuels as per #926, BAM is going to be deprecated completely in favour of csi (which is compressed).

**Comment by rbuels** [comment]
@keiranmraine it kind of sounds like having .csi support pretty much obviates this, do you think we can close it?

**Comment by keiranmraine** [comment]
@rbuels I agree
