### ISSUE TITLE
helping for implementing a new function

### ISSUE THREAD

**Issue by zym618** [GMOD/jbrowse#543]
I want to implement a function.
For example,  i search the sequence from 500 to 50000 in ctgA.
![qq 20141203113512](https://cloud.githubusercontent.com/assets/9545816/5275531/c1a300d6-7ae0-11e4-92ce-b62576422307.jpg)
then i click a new button(which can be placed on the right side of the "high light" button), the browser pop up a new page。
I can get the data of the sequence(*.fa) and the others(*.bw) from 500 to 50000 in ctgA
and do some further analysis such as drawing a histogram.
I don't know where to start.
the structure of the Jbrowse files seems too complex for me.
hoping for someone to give me some advice.
thank u.

**Comment by cmdcolin** [comment]
If there are any more questions feel free to re-open !
