### ISSUE TITLE
Change to click behavior of tracks when displayMode is set to "collapsed"

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#544]
Hi,

We've noticed that feature tracks set to displayMode "collapsed" retain any mouse click events. The trouble with this situation is that features are overlapping in this displayMode. Any click event that registers is merely the one associated with the feature rendered with the highest Z-level, and it is also unclear from a dense track which feature is represented.

My proposed solution is to remove all normal click events when in the "collapsed" state. This was easy to do on a test v1.11.5 dev build, but adding to _attachMouseOverEvents() in View/Track/CanvasFeatures.js where it already removes mouseover and mouseout events. This small change handles the transition from "collapsed" to "normal" or "compact" very well so far.

I would also like to attach a new click event to trigger a switch to "compact" displayMode (analogous to how the UCSC browser associates any click on a "dense" track to an expansion to "packed" state). I'm not sure how best to do this, though.  The simplest approach would be be to add this to _attachMouseOverEvents() for "collapsed" displayMode as well, but the lines that follow only attach a normally expected event if none exists. Am I on the right track with this?

Comments and suggestions appreciated!

**Comment by nauer** [comment]
Hi Colin,
I have a similar track with non overlapping fragments. Is it now possible to turn on the mouseover events in the trackList.json for collapsed tracks or is it completely turned off?

**Comment by cmdcolin** [comment]
Hey @nauer , currently it is completely turned off in collapsed mode the moment. I had tested code for optionally enabling it but I can't find it right now (my screenshot shows the intended behavior though: it is collapsed but still has mouseover labels). It is not too complicated so if I get a chance I'll follow up

**Comment by nauer** [comment]
Maybe you can point me to the accountable code then I could make a try. For this kind of data only the collapsed mode make sense. But without a legend and the mouseover tag it is hard to understand the shown data.

**Comment by rdhayes** [comment]
Yes, thanks for bringing this back up. Colin, I'd like to build on your
code changes to meet the other goal of this ticket, changing the
"collapsed" click events to cause only the track to expand to normal
spacing, also optional with a parameter controlling its use. That's all a
bit more tricky, I think.

Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by cmdcolin** [comment]
See #870 for this one @rdhayes, could help!
