### ISSUE TITLE
Unable to load data/seq/refSeq.json

### ISSUE THREAD

**Issue by karlapollyanna** [GMOD/jbrowse#547]
Hey folks, 

I got a problem after all procedures to configure JBrowse 1.11.5: my Reference was unable to be loaded.
I check all my files: 

1. GFF is ok, and I already validated it on http://genometools.org/cgi-bin/gff3validator.cgi
2. I downloaded once more my reference in https://www.vectorbase.org/organisms/lutzomyia-longipalpis (Scaffolds). 
3. I thought that diff between name of Scaffold could be a problem. So I changed it.

However, as I am new in programming, I did not check all codes to try figure out. 
Does anyone know how can I fixe it?

Tks in advance.

Karla Oliveira

**Comment by cmdcolin** [comment]
I'll close this for now, feel free to reopen if there are any more problems
