### ISSUE TITLE
If a track is deleted from the list of local tracks, the number of local tracks is not decreased.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#548]
From https://github.com/GMOD/Apollo/issues/100

To reproduce:  remove a track from the main screen
Found:  Track is removed from available tracks but the count remains the same. 
Expect:  If a track is removed, the count should be decremented by 1.

![](https://cloud.githubusercontent.com/assets/751274/5272196/6c3c5298-7a2f-11e4-9447-07c50cc75efa.jpg)

**Comment by rbuels** [comment]
@nathandunn can you confirm that this issue is still present?

**Comment by nathandunn** [comment]
@rbuels   Seems to work now.
