### ISSUE TITLE
'visibleChanged' event's payload doesn't conform to expectations

### ISSUE THREAD

**Issue by yeban** [GMOD/jbrowse#550]
Regarding `/jbrowse/v1/n/tracks/visibleChanged` event sent out from `GenomeView.updateTrackList` [L2366](https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/GenomeView.js#L2366).

If I subscribe to `/jbrowse/v1/n/tracks/visibleChanged` somewhere, I would expect callback's argument to be an array of visible track names, but the argument instead is an array of visible track names contained in yet another array.

```
this.browser.subscribe('/jbrowse/v1/n/tracks/visibleChanged'
, function (visibleTrackNames) {
    console.log(visibleTrackNames);
    console.log(visibleTrackNames[0]);
});
```

I wonder if L2366 shouldn't be just:

```
this.browser.publish( '/jbrowse/v1/n/tracks/visibleChanged', this.visibleTrackNames());
```

**Comment by cmdcolin** [comment]
As minor as this is i think we may not want to change it.

I think wrapping things in the array is a relic of the dojo.publish api (see 
see http://dojotoolkit.org/reference-guide/1.10/dojo/topic.html#dojo-topic). If you grep for "publish" in the codebase youll find that wrapping in an array is true of almost all publish events.

While it may be correct to change it in this case, it is a public API so we should probably leave it to the next iteration.

**Comment by yeban** [comment]
Makes sense to not change it before 2.0.

**Comment by cmdcolin** [comment]
I think this was decided not to change then :)
