### ISSUE TITLE
Unable to fetch ...bam

### ISSUE THREAD

**Issue by mjafin** [GMOD/jbrowse#552]
Hi there,
Thanks much for JBrowse! I'm trying to visualise bam files but am hitting an error:
```
Unable to fetch http://ec2-54-86-183-240.compute-1.amazonaws.com/JBrowse-1.11.5/data/data/10-497-T-ready.bam
```
The file exists and I've placed the following lines in ``/etc/httpd/conf/httpd.conf``:
```
<IfModule mod_headers.c>
    Header onsuccess set Access-Control-Allow-Origin *
    Header onsuccess set Access-Control-Allow-Headers X-Requested-With,Range
</IfModule>
```
 It looks like JBrowse also generated a ``.htaccess`` file on its own. 

Any further tips for where to look at for possible errors? Installation seemed to go fine without errors.

Here's a link to the view
http://ec2-54-86-183-240.compute-1.amazonaws.com/JBrowse-1.11.5/index.html?loc=chr12%3A25398256..25398311&tracks=DNA%2Cmy-bam-track&highlight=

Any help much appreciated,
Thanks,
Miika

**Comment by nathandunn** [comment]
Is there any way for you to verify that your file is not corrupt?  Here are the errors I am getting when loading.  Your file is clearly available.    Could it be a different file type (?bai?).



Nathan

**Comment by mjafin** [comment]
Hi Nathan,
Thanks for the prompt reply! I'm slicing the bam file using samtools just fine, so can't see it being corrupt. Did you intend to paste something above? It's not showing up in my browser.

**Comment by nathandunn** [comment]
yeah, sorry:  
![screen shot 2015-01-06 at 11 21 54 am](https://cloud.githubusercontent.com/assets/751274/5649098/3b6b8a14-9648-11e4-8155-82a0437b06dc.png)

**Comment by nathandunn** [comment]
The Invalid BGZF block header would indicate that its not of the correct binary format.  The code is pretty straight-forward in Util.js 

   var ba = new Uint8Array( data, ptr[0], 18 );

            // check the bgzf block magic
            if( !( ba[0] == 31 && ba[1] == 139 ) ) {
                console.error( 'invalid BGZF block header, skipping', ba );
                break;
            }

or in BAM.js

         if( readInt(uncba, 0) != BAM_MAGIC)
                        throw new Error('Not a BAM file');

I would take a small snippet and see if you can't load it up . .  I'll try to check your bamfile with my version of samtools.

**Comment by cmdcolin** [comment]
I didn't see that error come up as nathan had it originally because i was looking in the network tab instead of the console, but now i think that's correct, but its possible that is related to this: http://gmod.org/wiki/JBrowse_Configuration_Guide#Apache_Configuration_Note

**Comment by nathandunn** [comment]
That looks like it is likely the culprit.  

Just need to add this to the httpd.conf then?:   

 AddType application/octet-stream .bam .bami


Nathan

**Comment by mjafin** [comment]
That did it, thanks guys! Totally missed that bit about Apache..
