### ISSUE TITLE
Add phylogenetic tree to select tracks

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#554]
I am doing pan-genome data analysis.
Can Jbrowse add the feature of track selection with the form of phylogenetic tree?
Every track and every branch has a check box to select data.
Thank you!

**Comment by cmdcolin** [comment]
That sounds like a cool feature. I guess a more basic feature that jbrowse has is the hierarchical track selector. You can have nested sub-categories with this track selector by specifying "/" in the "category" attribute. For example, the sample data in JBrowse has tracks that say "metadata.category = Quantitative / XY Plot".  If you need a more custom look and feel, you can build your own track list module in the "plugin" system though.

![screenshot-jbrowse org 2015-01-23 15-38-04](https://cloud.githubusercontent.com/assets/6511937/5883237/16ddd1a4-a316-11e4-8e03-42982fc20988.png)

**Comment by verne91** [comment]
Hi, colin
Tks for your response.
I am new to JS. Can you provide some tutorials for developing plugin or some suggestions for learning JS.
Thank you!

**Comment by cmdcolin** [comment]
I would say the key thing for understanding the JBrowse codebase is understanding AMD and dojo.declare. for example the section on Writing JBrowse plugins has a section on this

http://gmod.org/wiki/JBrowse_Configuration_Guide#Writing_JBrowse_Plugins

I added some annotation to the code to help differentiate the AMD and the dojo.declare

![plugin_format](https://cloud.githubusercontent.com/assets/6511937/5888902/b2086d50-a3d5-11e4-913e-68c6a564e2b1.PNG)

**Comment by verne91** [comment]
Thanks a lot.

**Comment by selewis** [comment]
One possibility would be to incorporate the tree widget from biojs into
Apollo. (see https://github.com/daviddao/biojs-vis-tree). This is something
I've been interested in doing, along with a number of others. Most of the
work then would be on making the connection between the two components,
rather than needing to develop the tree from scratch.

-S
