### ISSUE TITLE
Note attribute visualized as Description

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/jbrowse#555]
Hi there,

We've been uploading some Web Apollo gff3 output into JBrowse as read-only tracks. Many of the annotations have multiple 'Note' attributes. When creating a new track via the flatfile-to-jbrowse.pl script, we've noticed that the first Note attribute is visualized as a description in JBrowse, whereas the remaining notes are visualized as notes: 

![notes](https://cloud.githubusercontent.com/assets/5487172/5857590/fc24d548-a21a-11e4-93cc-5493fd05a256.png)

This is the corresponding gff3 line for the mRNA: 

Scaffold1630    ManualCuration  mRNA    177426  186813  .       +       .       ID=OFAS025255-RB;Parent=OFAS025255;Name=Ofas-Gustatory receptor 91-RA -partial;symbol=Ofas-Gr91-RA;Note=Annotation type: Add a new gene model not existing in gene set,Data source for annotation: Oncopeltus paralogue,Note to curator: final small exon of 15-30 aa with conserved motif is missing;date_last_modified=2014-07-31;owner=kpanfilio

URL:
https://apollo.nal.usda.gov/oncfas/jbrowse/?loc=Scaffold1630%3A179649..187410&tracks=DNA%2CAnnotations%2COGS_v1.1&highlight=

Is this a (admittedly rather minor) bug, or is there a setting in the flatfile-to-json.pl script that can modify this behavior?

**Comment by cmdcolin** [comment]
Thanks for the report. This is sort of a weird issue and I also noticed it recently when a feature has multiple aliases.

You could try the following patch which might produce the desired behavior for your file, let me know if that helps

    diff --git a/src/perl5/Bio/JBrowse/FeatureStream.pm b/src/perl5/Bio/JBrowse/FeatureStream.pm
    index 2621fe8..f2a75d5 100644
    --- a/src/perl5/Bio/JBrowse/FeatureStream.pm
    +++ b/src/perl5/Bio/JBrowse/FeatureStream.pm
    @@ -136,7 +136,7 @@ sub endIndex          { 2 }
  
     my %must_flatten =
        map { $_ => 1 }
    -   qw( name id start end score strand description note );
    +   qw( name id start end score strand description );
     # given a hashref like {  tagname => [ value1, value2 ], ... }
     # flatten it to numbered tagnames like { tagname => value1, tagname2 => value2 }
     sub _flatten_multivalues {


Maybe there can be additional discussion as to whether this flattening step is even necessary

**Comment by cmdcolin** [comment]
Does that help your issue? I suppose the other thing is that Note is renamed to Description. If you need to change it manually, you can use "fmtDetailField_Description": "function() { return 'Note'; }"

**Comment by mpoelchau** [comment]
Hi Colin,

Sorry for dropping the ball on this. I tried your 1st fix on our staging site, but it didn’t change how the Notes were rendered (even after clearing cache/trying multiple browsers/restarting the instance). Do I need to rebuild the underlying json file for that track for the change to take effect, or is it the description field that’s causing the hangup?

And on that note, in your 2nd fix (change Description to Note), in which file should I change fmtDetailField_Description?

Thanks!

Monica
--
Monica Poelchau, Ph.D.
National Agricultural Library
10301 Baltimore Ave, Beltsville, MD 20705
monica.poelchau@ars.usda.gov

**Comment by cmdcolin** [comment]
No worries. The first fix would require reloading your tracks. The change affects the way the json is outputted.

The second fix is something you can add to particular tracks in the trackList.json.

**Comment by mpoelchau** [comment]
Thanks for clarifying! With your first fix, I get this:
![step1](https://cloud.githubusercontent.com/assets/5487172/5937880/0e325ed4-a6c3-11e4-99ff-1dda69ecfd61.png)
Here's the corresponding gff3 line for the mRNA:

Scaffold2       ManualCuration  mRNA    764008  787176  .       +       .       ID=OFAS025228-RA;Parent=OFAS025228;Name=Poly(ADP-ribose) glycohydrolase-RA;symbol=Parg;description=Poly(ADP-ribose) glycohydrolase;Note=Annotation type: Modify an existing gene model,Note to curator: Incorrect intron boundaries but well supported by RNA-seq data;date_last_modified=2014-05-4;Dbxref=FlyBase:FBgn0023216;owner=darmisen

So, the 'Note' attributes get pulled into the JBrowse 'Primary Data' section as separate Descriptions, and the 'description' attribute is displayed in the 'Attributes' section as a Description, as well. 

If I add the 2nd fix that you propose, then both 'Description' fields are changed to 'Note' fields.

So, fix1 does solve the 'flattening' problem, but it's still odd that JBrowse conflates the 'Note' and 'description' attributes into one, and where it puts them. It would make a bit more sense to me if the actual description was listed in the 'Primary Data' section, and the notes in the 'Attributes' section. Again, not a huge deal, but it would be nice if there were a fix for this at some point... 

Thanks!

Monica

**Comment by cmdcolin** [comment]
You can set style.description="description" to explicitly load the description field there (the default is to use note first, i.e. "note,description") but unfortunately, this causes the note field not to be displayed at all in the popup.

**Comment by cmdcolin** [comment]
xref http://gmod.827538.n3.nabble.com/Display-GFF-quot-Note-quot-attribute-but-not-in-the-quot-Description-quot-field-td4057463.html

**Comment by cmdcolin** [comment]
This should be mitigated by #885, showNoteInAttributes:true in config?

**Comment by rbuels** [comment]
closing this, feel free to reopen if it's still an issue
