### ISSUE TITLE
Selecting large gene with many transcripts delays browser::should open subfeatures on demand isntead

### ISSUE THREAD

**Issue by kshefchek** [GMOD/jbrowse#559]
I'm having an issue with Jbrowse when using firefox 35.0.1.  When going here:
http://icebox.lbl.gov/WebApolloHuman/jbrowse/?loc=BRCA1
and select the gene, I get this message:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
Script: http://icebox.lbl.gov/WebApolloHuman/jbrowse/src/dojo/dojo.js:194

**Comment by cmdcolin** [comment]
I mentioned this to @nathandunn  but I think it's just loading a lot of data here

>It looks like it is just trying to load too much data at once into the dialog box, but it does open eventually at least on my machine

>You could try to set maxFeatureSizeForUnderlyingRefSeq in the jbrowse config files to prevent it loading so much data

>That will tell jbrowse not to load sequence data for dialog boxes when features over a certain size (default 250kb)

We'll follow up

**Comment by nathandunn** [comment]
@cmdcolin   I set the max to 2.5M.  It does *eventually* come back.  I get the same result for either track.    Would be nice if it would load on-demand instead of pausing to load all of the data.

**Comment by cmdcolin** [comment]
The default is 250kb so that is raising it, however, even when it is set to 0, the dialog box can still take a long time.

I would probably need more time to look at a profiling tool to see what is causing that, but setting maxFeatureSizeForUnderlyingRefSeq to 0 should at least save a couple seconds

**Comment by nathandunn** [comment]
@cmdcolin   This does  help some.   I guess what I'd like to see instead is for it to open features / subfeatures on-demand (preferable) or in a logical order.   Seeing every CDS when its hard to tell from the interface which one is which makes things difficult.   However if I clicked on a particular transcript / CDS I could have it highlight or focus . . that would be great.  

Not an easy solution, but I think it makes sense to do at some point.

**Comment by selewis** [comment]
I believe the solution we came to was to go ahead and load all the
transcripts, but delay loading of the metadata which is what the big
time-sink is. That is, first pass just load what is minimally needed for
the graphics (the intervals) and defer anything else.

-S

**Comment by rbuels** [comment]
> go ahead and load all the
transcripts, but delay loading of the metadata which is what the big
time-sink is

Was this ever implemented?  And does anybody have an up-to-date link showing this problem?

**Comment by cmdcolin** [comment]
This was implemented as a config called subfeatureDetailLevel  (#861) but its a little unintuitive for most users

**Comment by cmdcolin** [comment]
And by users I mean admins setting up a browser

**Comment by rbuels** [comment]
Yeah, I'd like to avoid having the browser hang under any circumstance.  If it's too big, it should throw a descriptive error, maybe even crash the whole session, but never hang.  Basically, I always think of it in terms of: is there potential for somebody to get completely stuck by this, to the point of them having to email the mailing list? If so, we need to see what we can do to smooth it over.

**Comment by rbuels** [comment]
The original link for this issue seems to be gone now, does anybody have a link that demonstrates the problem?

**Comment by cmdcolin** [comment]
Pretty much any gene that is pretty long and has many transcripts will take a long time to popup the View details popup

Wormbase has some examples perhaps, for example wormbase gene (etr-1) has a ton of subfeatures and can take awhile to enable the popup

http://www.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=II%3A146175..186314&tracks=Curated_Genes&highlight=

Possible solutions

a) heuristic for dynamically putting subfeatureDetailLevel on
b) make a more intelligent popup that doesn't have lots of textboxes (maybe just one textbox with the sequence for the subfeatures highlighted)
