### ISSUE TITLE
proposed change to menubar.css

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#561]
Hi,

I'd like to propose a change to menubar.css to better handle menu item and image alignment when Jbrowse is updated to include new images. The current file makes use of "vertical-align: middle;" default settings throughout.

It's a fairly straightforward update that I can commit to master ASAP, but I wanted to discuss first, in the event that it has any downstream effect to WebApollo.

1) addition of "vertical-align: top;" to the ".menuBar *" section
2) addition of "vertical-align:middle;" to the ".share .icon", ".menubar .config .icon", and ".menuBar > .dataset_select .dijitSelectLabel" sections

A live demo is available now at:
http://phytozome.jgi.doe.gov/jbrowse/index.html?data=genomes%2FAthaliana
The addition of the Phytozome logo on the righthand side via a JBrowse plugin is what prompted this css change.

Also, I've attached some before and after images showing the minor rendering adjustment with and without the change applied to the basic menubar from v1.11.5.

Before:
![stock_menubar](https://cloud.githubusercontent.com/assets/474584/6087801/a9786ab2-ae04-11e4-8690-5bf3c8ed91aa.png)

After:
![revised_menubar](https://cloud.githubusercontent.com/assets/474584/6087802/ac96eef8-ae04-11e4-8051-4159de5224cd.png)

**Comment by cmdcolin** [comment]
Looks good to me :+1:

**Comment by selewis** [comment]
+1
