### ISSUE TITLE
flatfile-to-json.pl  category option

### ISSUE THREAD

**Issue by holmrenser** [GMOD/jbrowse#565]
It might be nice to be able to add a 'category' option to the flatfile-to-json.pl script to directly add a file to a given category.

**Comment by cmdcolin** [comment]
That would probably be a pretty good default option to have. However, in general, arbitrary options can be added to the command line using the --config option too. For example, you could have bin/flatfile-to-json.pl --config '{ "category": "my category" }'

**Comment by holmrenser** [comment]
I did not know this was the way to do it, thanks!


On 02 Mar 2015, at 19:54, Colin Diesh <notifications@github.com<mailto:notifications@github.com>> wrote:


That would probably be a pretty good default option to have. However, in general, arbitrary options can be added to the command line using the --config option too. For example, you could have bin/flatfile-to-json.pl --config '{ "category": "my category" }'

**Comment by cmdcolin** [comment]
Yep, the flatfile-to-json is pretty flexible in that regard. Not all of the command line scripts have the --config option though (i.e. add-bam-track,add-be-track) so more consistency needs to be made.

**Comment by cmdcolin** [comment]
I'll close this for now since we have an easy workaround :)
