### ISSUE TITLE
1.11.6 release package has sortHierarchical=false set by default

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#566]
The 1.11.6 release package was released with sortHierarchical=false even though the release tag didn't have this set

github release tag https://github.com/GMOD/jbrowse/blob/master/jbrowse.conf
release package http://jbrowse.org/code/JBrowse-1.11.6/jbrowse.conf

**Comment by cmdcolin** [comment]
This can't necessarily be fixed in the code, we should just be careful to avoid releasing developers  configuration files.

There are already several worksafes in place, but eventually, maybe git reset --hard origin/master would be needed to make sure config files are synced with server

**Comment by cmdcolin** [comment]
Closed for now (note...does not affect webapollo since webapollo does not use the release package but rather the github clone itself)

**Comment by nathandunn** [comment]
@cmdcolin   This is a good use-case for moving exclusively to npm (bower/grunt/etc.) for generic installation.
