### ISSUE TITLE
Using &loc= parameter can open two instances of the same track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#567]
Open this link in two tabs
http://jbrowse.org/code/JBrowse-1.11.6/?data=sample_data/json/volvox&loc=EDEN

The first time you open it, it will show the track "Protein-coding genes" centered on EDEN
The second time you open it, it will show the same track duplicated and it also has bad formatting

![screenshot-jbrowse org 2015-02-27 15-22-02](https://cloud.githubusercontent.com/assets/6511937/6421448/b49ad0a6-be94-11e4-8c5e-7e5b5211d34e.png)

Interestingly this problem doesn't affect most HTMLFeatures tracks in the volvox sample but I first observed this problem in a recent version of WebApollo that uses HTMLFeatures tracks

This problem also affects lots of other JBrowse versions including back to the 1.10 branch but I haven't evaluated the entire scope

Another version example http://jbrowse.org/code/JBrowse-1.11.0/?data=sample_data/json/volvox&loc=EDEN

**Comment by fossilfriend** [comment]
I'm having the same problem on my site; it occurs when the value for the loc parameter specifies a named feature such as a gene or SNP (as opposed to just a physical location, e.g., chr1:10-20) and the track used to generate the name is also specified as a default track.

**Comment by cmdcolin** [comment]
@fossilfriend  interesting, that is actually a good clue for why it happens (e.g. when a feature is located in the name store, it automatically opens the track that the feature was on, so if that track was already open, then it gets opened twice)
