### ISSUE TITLE
config ignored for all but last file when opening multiple local files

### ISSUE THREAD

**Issue by lpryszcz** [GMOD/jbrowse#569]
Hi, I've noticed that configuration (including altered name and display type) is ignored for all but last file when multiple files are opened at once. This happens for .bigWig and .bam files - I didn't tested other formats. I'm using JBrowse 1.11.6. 

![configuration]
(http://imageshack.com/a/img538/305/tblttW.png)

![view]
(http://imageshack.com/a/img661/9103/Qd7h3S.png)

**Comment by cmdcolin** [comment]
It looks like the bug goes back to the 1.10 branch too. Looks like a confirmed bug

**Comment by cmdcolin** [comment]
Added a little bugfix for this :)! Improper use of a variable outside the event handling closure
