### ISSUE TITLE
Add multiple entries in addStores

### ISSUE THREAD

**Issue by abdoukadri** [GMOD/jbrowse#572]
Hi all, 
addTracks can handle multiple entries for example:
addTracks=[{"label":"genes","type":"JBrowse/View/Track/CanvasFeatures","store":"url"},{"label":"genes1","type":"JBrowse/View/Track/CanvasFeatures","store":"url1"}]

But I could find an example how JBrowse handles multiple entries in addstores. I'd tried but with no luck for example:
addStores:[{"url":{"type":"JBrowse/Store/SeqFeature/GFF3","urlTemplate":"http://host/genes.gff"}},{"url1":{"type":"JBrowse/Store/SeqFeature/GFF3","urlTemplate":"http://host/genes1.gff"}}]

Could you please guide me through this if it is possible?

Cheers!!!!

**Comment by cmdcolin** [comment]
Here's an example with multiple tracks loaded


    addStores={"url1":{"type":"JBrowse/Store/SeqFeature/BAM","urlTemplate":"http://hostvolvox-sorted.bam"},"url":{"type":"JBrowse/Store/SeqFeature/GFF3","urlTemplate":"http://host/volvox.gff3"}}
        &addTracks=[{"label":"Genes","type":"JBrowse/View/Track/CanvasFeatures","store":"url"},{"label":"BAM file","type":"JBrowse/View/Track/Alignments2","store":"url1"}]

**Comment by cmdcolin** [comment]
If there are any new issues feel free to re-open :+1:
