### ISSUE TITLE
typing a specific coordinates is sometimes offset by a few bp

### ISSUE THREAD

**Issue by nmenda** [GMOD/jbrowse#577]
this behavior seems random and might be linked to the browser trying to fit the zoomed region in the given window size.
The browser alters a bit the typed coordinates.

I've played with different locations on the SGN Jbrowse 
http://solgenomics.net/jbrowse/

and also on the example jbrowse on jbrowse.org and I see the same behavior in both.

**Comment by cmdcolin** [comment]
This probably isn't necessarily a new problem. I don't know the exact background of the problem but this thread covered some similar things https://github.com/GMOD/jbrowse/issues/341

**Comment by cmdcolin** [comment]
I would say unless there is a compelling reason / use case where it causes problems, this could maybe be closed. If you need precise coordinates for exporting, I would use the "highlight" button and then the "Save track data" allows exporting the highlighted region

**Comment by cmdcolin** [comment]
maybe close for now
