### ISSUE TITLE
don't organize tracks according to file names, but according to data source

### ISSUE THREAD

**Issue by selewis** [GMOD/jbrowse#579]
An RNA seq run generates a single raw data file. This one file is analyzed twice, once for coverage (used for heat map display and wiggle track) and once to align the reads.

From a user's perspective (i.e. the biologist who has ultimate authority for requirements) wants to see one track per experiment, with alternate view options. Zoomed out, either heat map or wiggle or collapsed alignments (calculated synthetic transcripts). Zoomed in either full alignments or synthetic RNA transcripts.

**Comment by cmdcolin** [comment]
I think at least part of this is available. It is mentioned in a tiny section called "configuring summary histograms". http://gmod.org/wiki/JBrowse_Configuration_Guide#Configuring_Summary_Histograms

The track shown here uses that function http://jbrowse.org/code/JBrowse-1.11.6/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A1..50001&tracks=volvox-sorted_bam&highlight=
