### ISSUE TITLE
Retire pre-rendered image track features

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#587]
It has been proposed to entirely retire the portions of the code base associated with the pre-rendered image track features which includes wig-to-json.pl and draw-basepair-track.pl and associated javascript modules.

**Comment by enuggetry** [comment]
Per Colin:  the only tiny caveat with these features is that there is a small browser compatibility gap that is enabled by the scripts like wig-to-json

Specifically, ie9 doesn't work with the dynamic bigwig downloads or the dynamic bam downloads, but ie10 does, so that is the only place where those image rendering scripts have any real purpose.

nevertheless jbrowse doesn't work on ie8 at all, so there is not like a super big concern for the super old browsers. latest firefox,chrome,safari are all pretty well tested though

**Comment by scottcain** [comment]
While I don't use pre-rendered images, I could imagine a case where I'd like to use GBrowse or BioGraphics to generate an image and then have JBrowse display it (perhaps because there isn't support for a glyph or other things that GBrowse can do that JBrowse can't).  I have no idea if anybody is doing this in real life.

**Comment by selewis** [comment]
What's the % of users who might still be using ie8 or ie9? If it is low,
then I don't think we need to worry about doing more than letting them know
they need to update their browser.

I can appreciate Seth's comment on the general use of pre-rendered images
(e.g. perhaps we could show in-situ expression images of a particular
isoform). That said, for the specific case of individual bases it is
entirely the wrong approach. It is one of the reasons (I believe) that
keeps us from doing reverse complement, but there are other nice ui
features that this approach has keep us from implemented. For drawing base
pairs it -has- to be replaced.

-S

**Comment by nathandunn** [comment]
IE is 5-10% and less than 5% is <IE10.  So is that ~ 0.025%?  I think we can safely ignore <IE10. 

Nathan

**Comment by ihh** [comment]
If the tradeoff is (a) requiring the presence of a full GNU build system (C++ compiler, make, etc) during setup for all admins so we can build wig2png vs (b) requiring a browser update for the <5% of clients who are using IE so we can rely on dynamic BAM/BigWig downloads, I am comfortable going with (b).

As for Scott's point, can we keep the JBrowse/View/FixedImage.js parent class, while pruning the JBrowse/View/FixedImage/Wiggle.js derived class? The FixedImage superclass seems useful for all sorts of things, for example displaying banner ads or cat gifs along the genome (joke) (kinda) as well as potentially rendering legacy GBrowse tracks (though no-one's actually doing that now, and the work it'd take to do it would be more productively spent on adding new functionality in JavaScript IMO; pre-rendering using GBrowse is how we were doing it back in 2007...)

**Comment by cjfields** [comment]
Maybe have a deprecation cycle for GBrowse support in this case? We're basically moving completely to JBrowse for everything locally when requested, and don't envision using GBrowse functionality within JBrowse to reduce technical debt (though others at MODs with more technical investment might want to chime in as their investment in GBrowse is likely higher).

**Comment by enuggetry** [comment]
Scrub the sample data on the next release, too.

**Comment by cmdcolin** [comment]
setup.sh has been enabled in a way to disables the legacy image and bam-to-json modes of operation now so that could cover this issue I think. many thanks to @keiranmraine  for that :)

**Comment by cmdcolin** [comment]
maybe discussion about complete removal of these modules can be a new issue. I think making it not installed by default solves a lot of the headaches!
