### ISSUE TITLE
how to use "Addtracks" in URL Query String

### ISSUE THREAD

**Issue by zhangyumin** [GMOD/jbrowse#590]
i would like to display my bigwig and bed format data in temporary by using url query string.
 i try "addTracks" for lots of times.
the label name shows in the track sidebar but nothing shows when i click it.
need help for the right way to use addtracks.

**Comment by cmdcolin** [comment]
There is a recommendation on the configuration guide to combine addStores with addTracks like this 




       addStores={"url":{"type":"JBrowse/Store/SeqFeature/GFF3","urlTemplate":"http://host/genes.gff"}}
        &addTracks=[{"label":"genes","type":"JBrowse/View/Track/CanvasFeatures","store":"url"}]

http://gmod.org/wiki/JBrowse_Configuration_Guide#addStores

It's possible that this could be simplified, but I haven't done any testing

**Comment by cmdcolin** [comment]
Here's an example with multiple tracks loaded


    addStores={"url1":{"type":"JBrowse/Store/SeqFeature/BAM","urlTemplate":"http://hostvolvox-sorted.bam"},"url":{"type":"JBrowse/Store/SeqFeature/GFF3","urlTemplate":"http://host/volvox.gff3"}}
        &addTracks=[{"label":"Genes","type":"JBrowse/View/Track/CanvasFeatures","store":"url"},{"label":"BAM file","type":"JBrowse/View/Track/Alignments2","store":"url1"}]

**Comment by cmdcolin** [comment]
If there are any new issues feel free to re-open :+1:
