### ISSUE TITLE
CanvasFeature labels don't follow along like HTMLFeatures do

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#592]
HTML Features:

![screenshot from 2015-05-21 12 45 13](https://cloud.githubusercontent.com/assets/458683/7755107/69239c02-ffb7-11e4-8771-33b02d9fa514.png)

Canvas Features:

![screenshot from 2015-05-21 12 45 02](https://cloud.githubusercontent.com/assets/458683/7755108/6926a9e2-ffb7-11e4-8735-25b5df7a749e.png)

**Comment by cmdcolin** [comment]
Duplicate of https://github.com/GMOD/jbrowse/issues/390 ?

**Comment by erasche** [comment]
Yes, absolutely. I searched on "Canvas" instead of "canvasfeature" and missed it. Ugh, github.
