### ISSUE TITLE
CanvasFeatures seem to HtmlFeatures version first.

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#593]
E.g. https://cpt.tamu.edu/dot/jb/JBrowse-1.11.6/?loc=Merlin%3A1041..1728&tracks=89b4b9280761aacde16640100508bde7%2CDNA%2C1432226279&highlight=

When that loads (for me, in two browsers on linux) the first time the track loads, it defaults to the old HTMLFeatures view of it. Unselecting + Reselecting the "blast-canvas-test" track causes it to load as a Canvas feature.

**Comment by cmdcolin** [comment]
Your track is duplicated with the same label in your config file, and the label is actually an internal ID so it is getting confused. 


      {
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : "JBrowse/View/Track/CanvasFeatures",
         "glyph": "JBrowse/View/FeatureGlyph/Segments",
         "type" : "JBrowse/View/Track/CanvasFeatures",
         "label" : "1432226279",
         "key" : "blast-canvas-test",
         "compress" : 0,
         "maxHeight" : 18000,
         "urlTemplate" : "tracks/1432226279/{refseq}/trackData.json",
         "style" : {
            "label" : "description",
            "color": "function(feature, variableName, glyphObject, track) { var score = feature._parent.get('score'); var opacity = 0; if(score == 0.0) { opacity = 1; } else{ opacity = (20 - Math.log10(score)) / 180; } return 'rgba(109, 166, 166, ' + opacity + ')'; }",
            "description" : "Hit_titles"
         }
      },
      {
         "type" : "FeatureTrack",
         "label" : "1432226279",
         "urlTemplate" : "tracks/1432226279/{refseq}/trackData.json",
         "trackType" : "JBrowse/View/Track/CanvasFeatures",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "maxHeight" : 18000,
         "key" : "blast-1432226279",
         "style" : {
            "className" : "match",
            "label" : "description",
            "description" : "Hit_titles",
            "color" : "function() { return 'red'; }"
         },
         "compress" : 0
      }

**Comment by erasche** [comment]
Ahhh. That explains that.
