### ISSUE TITLE
Display dataset_id parameter text in menu bar if dataset_id and datasets are both set, but dataset_id is not in datasets list

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#595]
We would like to make a few genomes available that will be kept out of the configured list of datasets, but still coexisting with many other fully public datasets on the same server. These are preliminary data that will be shared to small groups internally via a direct URL only (Apache user authentication handling access control). 

In 1.11.6 Browser.js initView() code, when both this.config.dataset_id and this.config.datasets are configured, the menu bar always displays the drop-down menu of configured datasets. In my test case, the dataset_id will never be included in this.config.datasets, so I get the drop-down menu and no obvious indication otherwise of what dataset is actually being displayed (outside of the URL text).

My proposed modification introduces a test for whether or not dataset_id can be found as a key in the datasets JSON hash, when both config parameters are set. If a match is found, the drop-down menu displays as usual. If there is no match, the dataset_id parameter text itself is displayed instead. There is a small edit to menubar.css to include a new class for this div to control rendering, too.

Lack of dataset_id parameter in config still fallback to display of the JBrowse logo in this section of the menu bar.

I can commit these changes to main or set up a pull request, whichever is preferred at this point. I thought about implementing this in plugin code, but that would entail completely overriding initiView(), which could be a maintenance headache.

**Comment by cmdcolin** [comment]
The alternative that you might be able to do is to actually define your dataset inside of your data directory. This overwrites any other datasets in the list and just leaves it as being the only one in the list apparently.

Then, it doesn't show up in the normal list of datasets, and it stays sort of on it's own.

I.e. if I have this in my tracks.conf file (not the global config)


    dataset_id=testing
    [datasets.testing]
    name = Blah blah blah

Then that is just the one item that shows up in the dropdown box when you navigate to your data directory

**Comment by rdhayes** [comment]
I tried that syntax out, but it's not overriding the datasets configuration in the main jbrowse_conf.json config.

**Comment by cmdcolin** [comment]
Hmm. Well it seems to override it if the datasets that are specified in jbrowse.conf

The "config" merging schemes are sort of complex so I don't have a good explanation for that difference but if you define the datasets in jbrowse.conf instead of jbrowse_conf.json, then datasets defined in trackList.json or tracks.conf seem to override.

**Comment by rdhayes** [comment]
Odd, but I was considering that switch to jbrowse.conf anyway. I'll try that out if it means I can get this functionality without code and CSS changes.

**Comment by rdhayes** [comment]
Hi, the switch to jbrowse.conf worked, so I'm going to close this ticket with no commits to the code base. Colin's suggestion of overriding the global [datasets] list at the tracks.conf level worked well instead.

**Comment by cmdcolin** [comment]
Sounds good. Feel free to reopen :+1:
