### ISSUE TITLE
Renaming the file menu

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse#597]
It was pointed out to me today that users can be confused by the "file" menu present in GBrowse, JBrowse and WebApollo, since you can tell people to access the "file menu" and to most people in the world, that means the web browser's file menu, not the genome browser's file menu that is in the web page.  This is further complicated by the additional overloading the of the word "browser" which sometimes means web browser but sometimes means genome browser software running inside the web browser.  One step toward easing this confusion would be to rename the file menu to something else.  Lincoln suggested "data", which I think makes a fair amount of sense given what is in that menu for JBrowse and WebApollo (I'm less happy with it for GBrowse, but that is less of an issue at the moment).

**Comment by nathandunn** [comment]
I think that having a duplicate UI paradigm (dual file-type menu) is problematic to begin-with.   

I’m not sure what a good alternate paradigm might be.  Looking at the way google docs works, it does this duplication as well.   

Tabs or modal dialogs might be good instead. 


Maybe another simpler suggestion, rename “file” to “evidence tracks” or “tracks”.  

However, I think it bears some additional discussion. 

Nathan

**Comment by scottcain** [comment]
I don't like the "tracks" label for the file menu, since to me that would imply it's where I would go to select tracks even though there are more obvious places to go do that.  I understand why you'd want to call it that, as it is the place to go to perform operations on tracks (loading new data, searching for stuff, combining data in tracks to make new tracks).

**Comment by rbuels** [comment]
Well 2.5 years later, it's 'tracks' now.  Closing for now, feel free to reopen.
