### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse#598]
It would be really nice if JBrowse/WebApollo had a "full screen" mode, where a user could do something (press a button or the like) and the web browser UI stuff would go away and JBrowse/WebApollo would take up the entire screen (much like YouTube running in full screen mode).  Any idea how difficult that would be to implement?

This suggestion came from Todd Harris and Lincoln Stein at WormBase.

**Comment by nathandunn** [comment]
How would this be different then a full-screen mode on the mac (command-shift-f)?  	  

Nathan

**Comment by scottcain** [comment]
I think it would be very similar, except platform independent, and you could get out of it by hitting escape, which I don't think you can do with cmd-shift-F (that is, you have to hit that key combo to exit and escape won't do the same thing).

**Comment by nathandunn** [comment]
Looks like there are some ways to do it (third link down):

http://stackoverflow.com/questions/1125084/how-to-make-in-javascript-full-screen-windows-stretching-all-over-the-screen <http://stackoverflow.com/questions/1125084/how-to-make-in-javascript-full-screen-windows-stretching-all-over-the-screen>


Nathan

**Comment by scottcain** [comment]
This plugin does the trick nicely:

https://github.com/awilkey/fullscreen-jbrowse
