### ISSUE TITLE
I-beam cursor in Edit Track Configuration, wrong cursor

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#600]
In the Edit Track Configuration dialog box, the i-beam cursor should switch back to an arrow cursor when it leaves the text editable region of the textbox.  It doesn't.  The i-beam remains throughout the client area of the browser until it is closed.
![mwsnap 2015-06-04 16_29_48](https://cloud.githubusercontent.com/assets/10053377/7996654/8c2c29fa-0ad7-11e5-8d52-9c47353f8ccc.png)

Cosmetic

Observed on Chrome v 43.
Not verified on Safari nor Firefox.

**Comment by enuggetry** [comment]
This may be a fluke.  After closing chrome and reopening, I don't see it happening.

**Comment by cmdcolin** [comment]
Maybe close if not happening anymore?
