### ISSUE TITLE
Main Genome View page up/down scroll function doesn't function

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#601]
Normally, when clicking the region above/below the scroll drag bar will function as page up/down.  This does not function in the Genome Viewer, whereas everywhere else in the app, the scrollbars seem to function normally.
![mwsnap 2015-06-04 16_58_48](https://cloud.githubusercontent.com/assets/10053377/7996954/2881ed64-0adb-11e5-9927-add8040004b6.png)

GUI Functional
Observed in Firefox and Chrome.

**Comment by cmdcolin** [comment]
That particular scrollbar is pretty much all custom and handled programmatically, so it could probably be improved in this way

**Comment by cmdcolin** [comment]
I guess what I mean to say is that it is probably not a "bug" in this sense.

**Comment by enuggetry** [comment]
That's what I figured.  Just worth a mention that by convention it's not working they way it probably should.

**Comment by harshuopi** [comment]
Hi, @enuggetry and @cmdcolin .

I just added the feature through which we can scroll by clicking on the scroll bar.

Pull request #707. What do you guys think? :)

**Comment by cmdcolin** [comment]
@harshuopi nice work! I think if someone can get around to testing this, then it would definitely be a good feature to pull in!

**Comment by cmdcolin** [comment]
@harshuopi Can you also break the two features on #707 into separate pull requests ?

**Comment by harshuopi** [comment]
Done. #709

**Comment by cmdcolin** [comment]
Should be fixed now!
