### ISSUE TITLE
URL input is written into web page.

### ISSUE THREAD

**Issue by GrainGenes** [GMOD/jbrowse#602]
I am developing the use of Jbrowse in GrainGenes and T thinking about how to dynamically generate some of JSON files for serving Jbrowse. I wanted to test that it was possible to insert a ? into the requested URL. 
http://jbrowse.org/code/JBrowse-1.11.6/?data=?%3Ca%20href=%27http://yahoo.com%27%3EYahoo%3C/a%3E shows a link. This can be extended into XSS.
This loads an error page, since rather than requesting a json file, it requests a folder. Further, the error code does not filter htm tags and displays a link. 

Thanks,
Sayer

**Comment by cmdcolin** [comment]
Good catch

I think this is an example of a "non persistent" XSS, which is not the super bad kind of XSS, but should still be fixed. The super bad ("persistent") case is where it stays on the page even if they don't click a specially crafted link.

see http://en.wikipedia.org/wiki/Cross-site_scripting#Reflected_.28non-persistent.29

A similar thing was noted here https://github.com/GMOD/jbrowse/pull/570 but this makes it more obvious.

**Comment by vivekkrish** [comment]
@GrainGenes , InterMine has developed functionality to serve out JBrowse compatible configs + data from the warehouse, in accordance with the JBrowse REST specifications.
See docs: 
http://intermine.readthedocs.org/en/latest/webapp/third-party-tools/jbrowse/
https://intermine.readthedocs.org/en/selinium/web-services/how-tos/set-up-jbrowse/

An example, view all [FlyMine](http://www.flymine.org) data in JBrowse: http://jbrowse.org/code/JBrowse-1.12.0/?data=http://www.flymine.org/query/service/jbrowse/config/7227

Is this the sort of capability you are thinking about implementing?

Even if the URL developed by you, that is capable of serving JBrowse compatible data had "?" in it, with some clever Apache mod_rewrite functionality, you could normalize (or clean) out the URLs and have them be REST-like.

Does that sound reasonable, or am I way off base in interpreting your issue?

**Comment by cmdcolin** [comment]
@vivekkrish I think the issue is the XSS

The cross domain data thing like FlyMine is awesome but it is also technically a touchy issue too

For example, http://jbrowse.org/code/JBrowse-1.11.6/?data=http://genomes.missouri.edu/cdiesh/data&tracks=Genes

**Comment by cmdcolin** [comment]
Maybe there's another thing that GrainGenes was also looking for in terms offunctionality that I didn't see in this post (e.g the ? in url)?

**Comment by rbuels** [comment]
Just need to html-entity encode error messages in the error page.
