### ISSUE TITLE
4-arrow cursor - Window not draggable

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#603]
The 4-arrow cursor suggests the red region (the viewable window of the ref seq) is a draggable region; but, that's not the case.  It actually functions more like a zoom.
![mwsnap 2015-06-08 12_01_40](https://cloud.githubusercontent.com/assets/10053377/8042932/75f90402-0dd7-11e5-9b0a-a33b61d21b4b.png)

This is just a convention issue.

Suggestion: it would be nice to be able to drag the window region as a means of a more precise "long" jump across the reference sequence.

Observed in Chrome v 43.

**Comment by cmdcolin** [comment]
Is this still a problem?

**Comment by enuggetry** [comment]
This does not appear to be a problem, at present.
