### ISSUE TITLE
Colours hardly visible

### ISSUE THREAD

**Issue by colindaven** [GMOD/jbrowse#605]
Hi,

thanks for the excellent work on Jbrowse. We have been running JBrowse for some time and one thing the users always comment on is that the default light grey is far too light to make out against a white background. Therefore I always make the following changes to the 

track_styles.css

Is there any chance at least the dark grey  "background-color: #2F4F4F;" might be used as default instead of the default light greys ?

Thanks!
Colin

old

background-color: #dadada;
background-color: #eee;

new
      background-color: #2F4F4F;

old
img/plus-chevron3.png
new
img/plus-chevron2.png

old
dark_20x3.png
new
dark_20x2.png

old
opacity: 0.2
new
opacity: 0.9

**Comment by cmdcolin** [comment]
Looks like PR fixed this :)
