### ISSUE TITLE
"Highlight this feature" Function in Internet Explorer 11 Breaks Genome Browser Pane

### ISSUE THREAD

**Issue by halfwayBraindead** [GMOD/jbrowse#606]
As the title of this ticket suggests, the "Highlight this feature" function in JBrowse (even on version 1.11.6 available on the public demonstration instance) seems to "break" (e.g. more-so of a "white-out") the entire genome browser pane of JBrowse.

The genome browsing pane isn't truly "broken", as simply panning around the displayed genomic area with the mouse re-displays the highlighted region correctly, but the fact that the highlight function "whites-out" the genome browser in the first place [until users move the display] is a significant user-experience blocker.

**Comment by cmdcolin** [comment]
Does the same thing happen on the jbrowse.org sample browser? I couldn't reproduce that even on ie11

**Comment by halfwayBraindead** [comment]
Tested the public JBrowse instance again on IE version 11.0.9600.17914 today, and the error does not seem to be reproducible now. Previously, we tested multiple IE 11 machines that encountered this same issue, but perhaps a recent IE update resolved the underlying problems?

Closing this ticket; apologies for any associated headache(s)!

**Comment by cmdcolin** [comment]
ah no worries :) feel free to reopen if it happens again
