### ISSUE TITLE
Faceted Track Selector with hyperlink 

### ISSUE THREAD

**Issue by mrigayamehrajha** [GMOD/jbrowse#607]
Is any option for hyperlink into faceted track selector for displayed column. Where I can modify for the hyperlink

**Comment by cmdcolin** [comment]
You can add html directly to your trackMetadata.csv that is used for the faceted data, or you can just add the metadata for the hyperlink individually to your tracks too, e.g.


... in trackList.json form... 

    "metadata": {
        "hyperlink": "<a href=http://google.com>http://google.com</a>"
    } 


Then just add "hyperlink" to the "displayColumns" part of the faceted selector

Feel free to close if that helps
