### ISSUE TITLE
Chrome Canary 45 has glitchy side scrolling

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#608]
In Chrome 45.0.2435.5 any kind of side scrolling in jbrowse ends up being very glitchy at base level

Chrome 43.0.2357.124 appears to be fine

![x2](https://cloud.githubusercontent.com/assets/6511937/8263790/f2663cec-16a3-11e5-81d2-adc6b98b6748.png)

This glitchyness also happens in WebApollo too. It also affects jbrowse (at least versions) 1.11.0 - 1.11.6 so it's not new in jbrowse

You can see the actual track data, track labels, and other things are misaligned

Also, this is maybe a separate issue, but the touchscroll in Firefox Nightly has similar problems but not as extreme.

Unknown cause!

**Comment by cmdcolin** [comment]
Seems to be a non-issue in 45.0.2438.0 (or it could have also been something else weird about my environment.)

Closing for now!

**Comment by cmdcolin** [comment]
This definitely still happens, probably closed it too fast, but it is unclear what the cause is. If anyone else can confirm it that would be great

**Comment by enuggetry** [comment]
Haven't tried 45 yet.  Will give it a go when I get a chance.

**Comment by cmdcolin** [comment]
This is one of those weird bugs that might have just been unstable

Haven't seen it for last two weeks.

I guess close for now!
