### ISSUE TITLE
Improve clarity of search fields tracks / features

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#611]
Difficulty for users to determine how to search.  The box on the left is for tracks but users may think this is a simple keyword search of the browser itself.  The search box in the upper center has a dropdown box for chromosomes. This implies to the user that he or she can only search by position on a designated chromosome. There is no indication that a user can submit a gene symbol, ID or keyword.  We are unable to customize the headings or labels here to provide examples or explanations.

A major source of both misunderstanding and misuse in JBrowse stems from the search bar in its left-hand column for hierarchical datasets—the track selector:
![screenshot_thu_jun_18_15 26 20](https://cloud.githubusercontent.com/assets/10053377/8369215/120a2e48-1b6b-11e5-8a02-221173c5f73c.png)
To a naïve and ignorant user, this search field can be easily confused for the field that searches through the features’ index—to which even members of our development staff have found themselves confused by in the past. Instead of presenting the greyed-out “filter by text” string in the track filter field by default, this functionality could be better communicated as, “filter available tracks by text”, which better reflects the parent title of this column, “Available Tracks”.

Another major source of concerns regarding potential usability stems from the genome coordinate field, which JBrowse also uses for searching through its datasets’ indexed features:
![screenshot_thu_jun_18_15 30 12](https://cloud.githubusercontent.com/assets/10053377/8369198/02e73474-1b6b-11e5-88e4-a91e22316c69.png)
It is not entirely intuitive, at first, that a user needs to clear the genome coordinate field in order to enter a feature term, such as a gene symbol, to be autocompleted by the JBrowse dataset index.  Perhaps worse yet, a user could easily mistake the current chromosome [or scaffold] for the exclusive search location of their entered search query term, whereas JBrowse actually attempts a search over its whole dataset index. These facts are not made intuitively clear from the current JBrowse UI.

Ideally, JBrowse could significantly better itself by housing the feature search field within an entirely separate area of its UI, so as to be evidently clear to users and to also enable placement of additional function buttons, such as a button that clears the current search field (currently, users have to either triple-click with a mouse and then delete the search contents, or use keyboard shortcuts within the field, or highlight and delete the existing genome coordinates—all of which is undesirable for the end-user experience).

By divorcing the feature search field from the current genome navigation [and feature search] field, users could keep track of their current genome location while searching for a feature, a presumablydesirable functionality for JBrowse.

Submitted by:
Mary Shimoyama

**Comment by enuggetry** [comment]
I did some work, as can be seen in this sandbox:
http://jbrowse.org/code/sandbox-112/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A7493..8218&tracks=DNA%2CTranscript%2Cmalformed_alignments%2CEST&highlight=

**Comment by enuggetry** [comment]
I think this is definitely an improvement.  Here are some thoughts and suggestions:

·         I would switch the locations of the two fields so that the one that gives the location of the region you are looking at is front and center and the search is off to the side.

·         I would suggest changing the visual format of the navigation field (the one that gives the location of the region you are looking at) so that it doesn't look like a search box, e.g. remove the outline, change the font, and/or make the background transparent so it doesn't look like an editable box (although it is nice that you can select the string that's displayed in the navigation field and copy it).

·         I personally don't see the need for the chromosome dropdown—I think it's more confusing than helpful.  You don't have to select a chromosome, but you can.  If you have that set to the wrong chromosome and enter, for example, a gene symbol it will still go to the correct region for that gene, but the naïve user might think they have to know what chromosome the gene is on and enter it to get the results they want.  You can select one chromosome there and enter the complete coordinates for the region you want using a different chromosome (e.g. select chromosome 1 in the dropdown and enter Chr2:116049798..174068641 in the search box) and it will go to the chromosome in the search box and ignore the dropdown (and quite honestly, ignoring the dropdown is also what I always do, but an inexperienced user wouldn't know that they could just ignore it).

·         Trying to think as a naïve user who wouldn't necessarily know to use two dots to separate the start and stop, I tried using the chromosome dropdown to select the chromosome and put in coordinates using a dash rather than two dots.  It took me a bit to figure out what it's doing with that.  I selected chromosome ctgA and entered 1134-3500 in the search box and it shows ctgA:1107..1160 (55 b) if I have it displaying full screen and ctgA:1115..1153 (40 b) if the window is smaller.  I take it that it's showing the number of nucleotides it can fit on the screen centered around the first number inputted (1134)?  How hard would it be to make the tool smart enough to convert the dash into two dots if a user entered the position using a dash?

·         Tool tips would be great—maybe something like "Enter a chromosomal position, symbol or ID to search" for the search box and "Region displayed:  ctgA:1320..3280 (1.96 Kb), Search term:  hgb" for the navigation field.  (These are obviously not necessary for the experienced user but could be very helpful for naïve users.)

Thanks,
Jennifer

**Comment by colindaven** [comment]
I personally do see a clear need for the chromosome dropdown. I use it very frequently to switch between chromosomes - otherwise you need to type. Furthermore you can see if particular chromosomes are included in the genome build, or indeed extra scaffolds or mitochondrion. 

Furthermore many assemblies have different chromosome names 1, chr1, Chr1, 01, etc which are not apparent to naive users, or even experienced ones if many assemblies are used.

Please don't remove the dropdown ! 

Asides from this, many of my users navigate to a spot using links to named features, not chromosomal coordinates. 

Cheers,
Colin

**Comment by enuggetry** [comment]
I agree.

**Comment by enuggetry** [comment]
Resulting changes:

Clarify track search placeholder text
![screenshot_wed_jul_01_22 01 13](https://cloud.githubusercontent.com/assets/10053377/8470227/d2e121a0-203c-11e5-8107-27a70a219534.png)

Clarify feature search
![screenshot_wed_jul_01_22 00 47](https://cloud.githubusercontent.com/assets/10053377/8470225/c967b742-203c-11e5-93dc-cec12151cc37.png)
