### ISSUE TITLE
HTMLFeatures tracks and CanvasFeatures tracks are somewhat exclusive to themselves

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#613]
The feature-set and capabilities of “HTMLFeatures” tracks and “CanvasFeatures” tracks in JBrowse are somewhat exclusive to themselves.

a.      HTMLFeatures tracks possess the capability to “roll” a given feature’s name along with the user as they pan along an organism’s genome—this is extremely helpful for investigating long features. Additionally, the HTMLFeatures tracks interpret HTML tags within a feature’s name. On the downside, HTMLFeatures tracks display “fragmented” summary histograms, where the small whitespace between individual histogram bars can be visually jarring. Additionally, the histogram scale of HTMLFeatures tracks is not rendered on top of the actual histogram bars, making it very difficult to read when using a darker color for the histograms’ background. Finally, when JBrowse [automatically] collapses features together at large resolutions (such as viewing hundreds of megabases), HTMLFeatures tracks do not possess a “mouse-over” capability to inspect an individual feature from the collapsed pile, making feature identification very difficult.

b.      CanvasFeatures tracks display continuous histograms that appear to be rendered behind or underneath the histogram scale [which is also colored darker in black], allowing for easier reading of histograms—this is noticeably improved from the HTMLFeatures tracks. Additionally, CanvasFeatures tracks support shading and a mouse-over view of individual features when inspecting a collapsed feature pile at large resolutions, making individual feature identification easier. Unfortunately, CanvasFeatures tracks do not interpret HTML tags from feature names, displaying the literal text instead, and they also do not support “rolling” of feature names along a long feature’s length, making the browsing of tracks such as QTLs very tedious.

Submitted by Mary Shimoyama

**Comment by halfwayBraindead** [comment]
A particularly frustrating aspect in the "HTMLFeatures vs. CanvasFeatures" discussion in JBrowse stems from how HTMLFeatures tracks allow for individual feature labels to "scroll" along with the genome browser, which is excellent for very long features (like QTLs), and these feature labels also scroll "intelligently" with actual track labels, so the track labels do not obscure individual feature labels!

It is an *excellent* feature of JBrowse HTMLFeatures tracks, yet CanvasFeatures tracks support no rudimentary implementation of the same method and/or function. CanvasFeatures were introduced as the future HTML5-supported track trackType for JBrowse, yet they still developmentally "lag behind" advanced features currently available in HTMLFeatures tracks.

**Comment by rbuels** [comment]
I split this giant omnibus issue into two more granular issues that can be more effectively addressed in the flow of development.

#961 #962
