### ISSUE TITLE
Implement a way to hide track labels

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#614]
The JBrowse UI renders a track’s label in the genome browsing pane on top of its actual features. This may seem innocuous at first, but when browsing track names that are rather long, the label also extends in length, to the point where it may obscure [almost] all track features in the genome browser pane. This is a blocker issue in certain cases, and it has been previously reported on the JBrowse GitHub issue tracker. Currently, this issue remains unresolved.

Submitted by Mary Shimoyama

**Comment by enuggetry** [comment]
I implemented an EYE icon on the toolbar to toggle the track labels.
http://jbrowse.org/code/sandbox-112/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A7493..8218&tracks=DNA%2CTranscript%2Cmalformed_alignments%2CEST&highlight=

Apollo also has a mechanism.
Need to look into how resolve potential overlap of the two mechanisms when Apollo is present.

**Comment by cmdcolin** [comment]
I like it

The track labels still re-appear if you scroll around a little bit which was a little weird, but maybe that is intended?


In our code, our "updateLabels" function is sort of like this


    updateLabels: function() {
        if(!this._showLabels) {
            query('.track-label').style('visibility','hidden');
        }
        else {
            query('.track-label').style('visibility','visible');
        }
        this.browser.view.updateScroll();
    },


We decided to use visibility:hidden instead of display:none because display:none takes the track label out of "flow" and makes the "rolling feature labels" bad


Also, we had to make a change in our draggableHTMLfeatures to support the rolling feature labels without the track labels there (we override updateFeatureLabelPosition here https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L1303)

**Comment by enuggetry** [comment]
Yeah, the they reappear when there's any kind of movement or resizing.
This is partly a side effect of the way the original code positions for
those actions.  But, I was shooting for the label to stay for 1 second
before rehiding.  I thought this could be a reminder that those track
labels/menus were still there.   However, the delay code introduced
additional anomalies that were harder to deal with.  So, I left it as a
reasonable compromise to what I was trying to achieve.  I may try to tweak
it to delay properly.  The trick I believe is that while the effect is in
mid-animation, a move has to abort the anim in progress, otherwise, the
anim proceeds after getting repositioned.  Then, the menus end up hiding
only half-way.

What remains is how we should integrate with Apollo.   When, Apollo is
installed, which version do you want to use?
To trigger, there is a function that you call in browser.js called
showTrackLabels(cmd), where cmd is "show", "hide", "hide-if","toggle".
"hide-if" rehides if it was originally hidden.
Alternatively, Apollo can hide that "eye" button.

I haven't checked in yet.

**Comment by cmdcolin** [comment]
We use a github clone of jbrowse checked out with the 1.11.6-release tag in webapollo builds


>What remains is how we should integrate with Apollo. 

Apollo could just remove our own implementation if it becomes a core jbrowse feature, or just not use it if we are using updated versions of jbrowse. It was only added recently to apollo, and we are glad to see it being added in jbrowse i think

**Comment by nathandunn** [comment]
Also if you look at the ucsc  browser .. They do the same thing but with a hide able left hand side column for labels. I think it might be worth thinking about something like that and then adding info drop down that way as well in a similar animated style.  Just some ideas.  I think what you have is still a nice improvement and agree with what @cmdcolin said.

**Comment by enuggetry** [comment]
Introduced "eye" button to hide/show track labels.
![screenshot_wed_jul_01_22 07 27](https://cloud.githubusercontent.com/assets/10053377/8470301/ad21b730-203d-11e5-9cfd-6e6b3b495991.png)

**Comment by halfwayBraindead** [comment]
I like the motivation behind what's been done thus far, but I've still got a nagging concern about this: doesn't the "eye" functionality somewhat defeat the purpose behind having track labels in the first place?

If a user wants to take a screenshot of their current view in JBrowse, say for a journal publication and/or article, then why would they omit track labels from the display? It doesn't seem very practical.

As the original request suggested, wouldn't it be better to simply render the track label entirely *above* the actual track features, as GBrowse does? Is this too difficult to achieve in the JBrowse UI?

[Here](http://jbrowse.org/code/sandbox-112/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A16451..28390&tracks=DNA%2CGenes%2CCDS%2CTranscript&highlight=) is an example of track labels completely obscuring track feature glyphs and labels in the JBrowse sandbox.

**Comment by enuggetry** [comment]
It's a good point, @halfwayBraindead.  We'd probably have to provide extra horiz spacing between tracks to accommodate.

**Comment by Matthias-HDE** [comment]
Hi guys,

That's a nice thing here, indeed I also feel sometimes that labels get on
the way of what we want to see.
What about a fixed width label box ending with '...'. In the form or what
exists now, but displaying the full label only when hovering over ?
+ a configuration entry per tracks / per instance that will be like:
"fixed_label_width" : True/False

About having it not on the data but just above the track, it's not fully
satisfying, since the limited vertical space on a screen is precious for
covisualisation... More configuration ? "label_on_track" : T/F, haha ;)

Cheers,

Matthias
​.​

**Comment by enuggetry** [comment]
Thank Matthias,
I was thinking along the same lines. 
I think we are serving multiple purposes, here.  For some who are using the tool for analysis and editing, as with Apollo, the labels sort of get in the way; whereas, others use it for illustrative purposes and need them there all the time.  So, making more flexible config options is a good idea.
