### ISSUE TITLE
go to the result immediately when clicking a search result in name completion dropdown

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#616]
I noted the dropdown items in the search box cannot be selected.  Therefore, although the autocomplete provides some hints as to what is found, but you still have to type then whole feature name out.

![screenshot_wed_jun_24_09 20 31](https://cloud.githubusercontent.com/assets/10053377/8369576/db0643b8-1b70-11e5-8f78-c014eab08d64.png)

Conventionally, if an item is clicked, it should replace the search box content, or something.

I think it should be an easy fix, but wondering if there is any reasoning behind it.

**Comment by cmdcolin** [comment]
I think you can click them? What platform can you not click them?

**Comment by enuggetry** [comment]
you can click them, but you still have to click "go".  That's what I meant.

**Comment by rbuels** [comment]
Oh, so you should just go there when you click them.  That's a good idea.
