### ISSUE TITLE
generate-names.pl hangs for Apollo human sample data

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#617]
It generates 000.json.log 0ff.json.log, then hangs.

**Comment by cmdcolin** [comment]
@nathandunn can you confirm this?

**Comment by cmdcolin** [comment]
The instance on http://icebox.lbl.gov/WebApolloHuman/ looks like it has generate names correctly run. Maybe it was fixed? @nathandunn

**Comment by cmdcolin** [comment]
Does this still happen? Last I remembered I think it worked. Maybe close for now?
