### ISSUE TITLE
Jbrowse does not start

### ISSUE THREAD

**Issue by Sergiu354** [GMOD/jbrowse#619]
Ordered: trackList.json, refSeqs.json, tracks.conf. And Jbrowse does not start, showing a blank page

**Comment by colindaven** [comment]
I think you'll need to provide more details to get an answer, your comment is very cryptic!

Have you run setup.sh properly ?
Do you have all dependencies etc ?

**Comment by Sergiu354** [comment]
I have not started "setup.sh" , I just added it to the project, and configured it in Scala
Here is an example configuration:

TrackList(tracks = List(Track("mygene_track",
      "Genes",
      "JBrowse/View/Track/HTMLFeatures",
      "JBrowse/Store/SeqFeature/REST",
      "http://my.site.com/rest/api/base",
      List(Query("tyrannosaurus", Some("gene")))
    ), Track("my_sequence_track",
      "DNA",
      "JBrowse/View/Track/Sequence",
      "JBrowse/Store/SeqFeature/REST",
      "http://my.site.com/rest/api/base",
      List(Query("tyrannosaurus", sequence = Some(true))))))


TracksConf(
      "JBrowse/Store/SeqFeature/BigWig",
      "../../my-bigwig-file.bw",
      "Quantitative",
      "JBrowse/View/Track/Wiggle/XYPlot",
      "Coverage plot of NGS alignments from XYZ"
    )

when I run the server and go to localhost, it starts the main page blank.
Here is an example of what I see:
http://s17.postimg.org/mw5n8pdwf/Screenshot_from_2015_07_07_12_42_44.png

**Comment by enuggetry** [comment]
What is console reporting?

**Comment by Sergiu354** [comment]
The console reporting: http://s28.postimg.org/le2ew3sz1/Screenshot_from_2015_07_07_22_04_30.png
But I did not find on the site ( http://gmod.org/wiki/JBrowse_Configuration_Guide ), how to prescribe "root.json". I read on forums that's not necessarily prescribe "root.json"

**Comment by cmdcolin** [comment]
The root.json isn't a bad sign, as on the JBrowse config guide it just describes that it means it didn't find your default name store from generate names

Did you modify the index.html at all?

**Comment by Sergiu354** [comment]
I have not modified the index.html
problem is in index.html?

**Comment by cmdcolin** [comment]
Not necessarily. Actually, I just noticed that you mentioned refSeqs.json. Does this get loaded correctly?

JBrowse will not load (i.e. it will be a completely blank screen) until refSeqs.json is loaded

**Comment by Sergiu354** [comment]
I wrote certanily:
case class RefSeqs(         // class refSeqs both on site (github.com/GMOD/jbrowse...)
                    name:String,
                    start:Int,
                    end:Int
                    )

def getRefSeqs={                //defined function refSeqs
    RefSeqs("chr1",0,12345678)
  }

path("data" / "seq" / "refSeqs.json") {      //and directory
...}   

It's all what I wrote after this guide, to "refSeqs.json".

**Comment by cmdcolin** [comment]
I would definitely double check that this refSeqs.json file is downloaded correctly and in the right format. I don't really know what this scala code is saying but I would just double check in your chrome dev tools network tab that it is downloaded at the very least!

Cool app

**Comment by cmdcolin** [comment]
If you have any more details on this feel free to update but since this is likely not a jbrowse bug itself, I would suggest closing!
