### ISSUE TITLE
Starts of features (wrongly?) incremented by one. Version 1.11.6.

### ISSUE THREAD

**Issue by Strep** [GMOD/jbrowse#623]
I use flatfile-to-json.pl to read in a bed file containing CDSs of a bacterial genome.
An example bed file line is below:
Sven	3997049	3999394	SVEN_3677	0	+	3997049	3999394	0,255,0

Clicking on this feature in JBrowse the pop-up box shows nucleotide sequence of the region 
Sven:3997050..3999394 (+ strand)
which, instead of starting with ATG... start with TG...

Similarly, for a feature on the reverse strand.
Bed file has:
Sven	3995590	3996270	SVEN_3676	0	-	3995590	3996270	0,0,255
JBrowse shows:
Sven:3995591..3996270 (- strand)
In this case the last nucleotide of the stop codon is missing.

If nucleotide positions in the bed file are considered to be zero based then both ends should be shifted by one. I am attaching two screenshots for illustration. 

![jbrowse2](https://cloud.githubusercontent.com/assets/4579637/8803711/511f4be0-2fc0-11e5-8b5b-265389fd247d.png)
![jbrowse1](https://cloud.githubusercontent.com/assets/4579637/8803710/511a6152-2fc0-11e5-88db-50dc924b8178.png)

Being very new to JBrowse, I might be doing something silly. But I have tested this several times before deciding to submit this issue. I was able to artificially "fix" the problem by decrementing the starts by one in the bed file. But shifting only one end of features seems such a wrong thing to do. I hope one of you is able to replicate my problem or suggest what I might be doing wrong.

I would be happy to provide more information / data etc. if required.

Thanks

Govind Chandra
Department of Microbiology
John Innes Centre
Norwich NR4 7UH.
UK.

**Comment by vivekkrish** [comment]
Hello Govind,

This is due to the idiosyncrasy of the bed format (http://genome.ucsc.edu/FAQ/FAQformat.html#format1), where the first base in the chromosome is numbered 0, as opposed to GFF3 where the first base is numbered 1. i.e. bed format is 0-based and gff format is 1-based.

When JBrowse loads bed files, it converts from the 0-based to 1-based system, which is why you see that the start coordinates are off-by-one.

In both numbering systems, the end coordinate will always be the same.

Hope this helps!

Thank you.
Vivek

**Comment by Strep** [comment]
Thanks Vivek,

I don't have a problem with the conversion to 0-based numbering. What I was having trouble with is the fact that only the starts had to be corrected. I just had another look at the BED format documentation and it says:

>    chromEnd - The ending position of the feature in the chromosome or scaffold. The chromEnd
>   base   is not included in the display of the feature.

The bit that I was not taking into account is this:  The chromEnd base is *not* included in the display of the feature.

You are right, it is idiosyncratic. I might want to stick to the GFF3 format for this reason. I will have to figure out whether, in the GFF3 format, the ending coordinate is part of the feature or, like bed, lies just outside the feature. May be you can tell me.

Thanks again and best wishes

Govind

**Comment by vivekkrish** [comment]
Hi Govind,

In the description provided on the UCSC website about the bed format (0-based), the clause which says the `chromEnd` the end base in not included in the display of the feature, is specific to how the UCSC genome browser draws features.

On the other hand, JBrowse strictly follows the 1-based coordinate system (used by GFF).
According to the GFF3 spec (http://www.sequenceontology.org/gff3.shtml), here is how the coordinates are defined:
```
Columns 4 & 5: "start" and "end"
The start and end coordinates of the feature are given in positive 1-based integer coordinates, relative to the landmark given in column one. Start is always less than or equal to end. For features that cross the origin of a circular feature (e.g. most bacterial genomes, plasmids, and some viral genomes), the requirement for start to be less than or equal to end is satisfied by making end = the position of the end + the length of the landmark feature.

For zero-length features, such as insertion sites, start equals end and the implied site is to the right of the indicated base in the direction of the landmark.
```

So even after adding 1 to the start coordinate while loading the bed file, JBrowse should still be able to correctly locate and correctly show the start codon.

@cmdcolin , would you be able to chime in on this discussion about the specifics of how JBrowse handles the coordinate systems?

Thank you.
Vivek
