### ISSUE TITLE
dataroot in jbrowse.conf

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#625]
As the disk space of my web server is small, I have to move the data folder to another disk and set the permission of "777". Then I try to modify the dataroot in jbrowse.conf with both absolute path and relative path.
But I still got the message:
Could not load reference sequence definitions. RequestError: Unable to load data/seq/refSeqs.json status: 404

**Comment by enuggetry** [comment]
If you put an arbitrary file in your alternate data root, like test.html,
can you access it?

**Comment by colindaven** [comment]
Hi,

we have been using Jbrowse for years, and use a local mount of a NAS folder within the jbrowse directory.

Webserver
/opt/whatever/jbrowse

NAS Folder linked _within_ the jbrowse directory
/opt/whatever/jbrowse/myNAS

myNAS then contains jbrowse_data

This works well. 

cheers,
Colin


Date: Wed, 22 Jul 2015 11:48:31 -0700

**Comment by cmdcolin** [comment]
@colindaven do your then set dataRoot=myNAS?

Just curious. 

@colindaven is right here though, you would probably just want to symlink your external drive into your jbrowse folder, because dataRoot can't be a filesystem path (it is a URL path)

**Comment by colindaven** [comment]
Hi @cmdcolin 

I don't use the dataRoot as yet -never change a running system.

**Comment by cmdcolin** [comment]
@colindaven sounds good :)

I just wanted to see about how your linking was done. It sounds like you also have a symlink though, so I think @verne91 would probably just want to symlink the external drive into the jbrowse folder as well. The dataRoot is just a method to make jbrowse load a different data folder by default


I.e.

normally jbrowse just loads data from


http://localhost/jbrowse/data


If you changed dataRoot=otherdata, it might load the data from

http://localhost/jbrowse/otherdata

**Comment by cmdcolin** [comment]
I opened up a new issue regarding dataRoot but this issue is probably more related to a web server setup than a jbrowse specific thing. So, closing for now, but feel free to reopen if there are more issues!
