### ISSUE TITLE
bigwig file from wig-to-bigwig seems not working

### ISSUE THREAD

**Issue by graphanalytics** [GMOD/jbrowse#630]
Hi, I am testing JBrowse for use with our web app. I tried the latest download of the wig-to-bigwig exe, to convert some wig file to be visualized in jbrowse as a bigwig, but seems to be not working... Any help would be appreciated. If it is the issue with wig-to-bigwig tool, are there any other alternatives for this ?

Thanks,
Vijay

<img width="1394" alt="wigtobigwig" src="https://cloud.githubusercontent.com/assets/12382571/9159008/7eef4966-3eee-11e5-9262-f23533b81661.png">

The original wig file is here..
https://gist.github.com/graphanalytics/1c83c8b1c751a23c323d

**Comment by cmdcolin** [comment]
I think the issue is that you have this in your wig file "chrom=chrHPV18" but I think it should be "chrom=HPV18" (i.e. the names should match the reference sequence that you are seeing in the browser, which, in your screenshot is HPV18)

**Comment by graphanalytics** [comment]
Thanks for the suggestion. I fixed the "chrom=HPV18" in the wig, reran the wig-to-bigwig with the fixed wig file, but see the same in the browser ...:-(

**Comment by cmdcolin** [comment]
I think you are probably pretty close. You should also make your chrome.sizes file (passed to wigToBigWig) use the same name as the browser too. I did this and it worked pretty well

    wigToBigWig brca.wig.txt chrom.sizes out.bw
    mv out.bw data/out.bw
    bin/add-bw-track.pl --bw_url out.bw --label out.bw --in data29/trackList.json
    bin/add-bw-track.pl --bw_url out.bw --label out.bw_xyplot --in data29/trackList.json --plot



![xyplot](https://cloud.githubusercontent.com/assets/6511937/9175297/8ccce4f6-3f4a-11e5-8c83-750e3b42e03b.png)

**Comment by graphanalytics** [comment]
Thanks again, Colin. It is encouraging to see that screenshot. I did generate the .bw with the chrome.sizes file fixed, but looks like i am not setting the tracks or my urls properly. I guess the data directory is in the root jbrowse folder, but i am not sure where you had the data29 folder that has the trackList.jason location, for the screenshot that you made ?

**Comment by cmdcolin** [comment]
Sorry about the data29 instances. That is just because I normally have many data folders for jbrowse that I do testing on. Normally, your jbrowse scripts will just output to the data folder, and then this will be loaded automatically when you go to http://localhost/jbrowse/ or similar (you can load the different data folders with http://localhost/jbrowse/?data=data29 or similar)

I think if you just use the data folder, then you can just load http://localhost/jbrowse and it would be fine, but if you create a new data folder for testing, feel free to try the other method

**Comment by graphanalytics** [comment]
No worries, Colin. Turns out, i did not properly set the track list. Your example line of code to set the track list helped me figure this out. Its all working great, thanks to you.

Cheers,
Vijay
![brca](https://cloud.githubusercontent.com/assets/12382571/9178876/faf52b16-3f66-11e5-9690-3eaf95d31b16.png)

**Comment by cmdcolin** [comment]
Sure feel free to reopen or file a new issue if you have any other problems
