### ISSUE TITLE
Unable to display selectableFacets and metadata error.

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#632]
I add five columns for selectableFacets in jbrowse_conf.json, but only two displayed in my JBrowse.
In addition, a column in the metadata displayed same with another column, but they are different in the {dataroot}/trackList.json.

**Comment by cmdcolin** [comment]
Can you post samples of the data files?

**Comment by verne91** [comment]
jbrowse_conf.json is below.

{
"trackSelector":{
        "type": "Faceted",
        "displayColumns": [
                "code",
                "name",
                "A_type",
                "B_type",
                "B_subgroup",
                "country",
                "region",
                "seq_depth",
                "map_depth",
                "map_cov"
        ],
        "selectableFacets": ["A_type","B_type","B_subgroup","country","region"]
}
}

Only "country" and "region" can display in the jbrowse.

**Comment by cmdcolin** [comment]
Just curious, do you have metadata embedded in the trackList.json or are you using an external trackMetadata.csv file

If you have those files that could help too :)

**Comment by verne91** [comment]
The metadata was embedded in the trackList.json.

And I find the bugs.
The first letter of column names in the selectableFacets can't be capital and "name" can 't be the column name.

**Comment by cmdcolin** [comment]
Awesome! This can be added to the documentation ! I had actually seen this recently so I am very glad you solved this :)
