### ISSUE TITLE
Generate spliced mRNA sequence in "Gene details view"

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#633]
Suppose a gene with exon-intron structures like this:
![a](https://cloud.githubusercontent.com/assets/1146090/9538416/bc34e092-4d76-11e5-8c0c-d9279f7e3872.JPG)

If you click on this gene, you can view and download the genomic sequence, "mRNA sequence" and each exon sequence in a "gene details view" pop-up window. In this situation, the viewed "mRNA sequence" is unspliced. In fact, it is exactly the same with genomic sequence. If users want to obtain the spliced mRNA sequences, the only method is to manually connect exons one by one, which seems inconvenience.

I'll be very glad if we can obtain spliced mRNA sequence automatically in the "Gene details view"!

**Comment by colindaven** [comment]
You can use a JBrowse plugin for this:
https://github.com/tsaari88/FeatureSequence

**Comment by billzt** [comment]
Yes, this could be deal with https://github.com/tsaari88/FeatureSequence
