### ISSUE TITLE
Serving JBrowse assets from a different directory

### ISSUE THREAD

**Issue by girlwithglasses** [GMOD/jbrowse#636]
As a factor of the way the server is set up and how I am using JBrowse, I have to specify a separate URL for serving assets (css, JS, plugins, etc.). For the most part, I can solve this by setting `config.baseUrl` to `http://my.server.com/jbrowse_assets`. I have also moved all the css files into their own directory (much tidier) and altered a couple of relative paths and added symlinks for `src` and `img`. This setup works for most files, but the following files still get served from `http://my.server.com/jbrowse/` instead of `.../jbrowse_assets/`:

`/img/JBrowseLogo_small.png`
`/img/Empty.png`
`/plugins/RegexSequenceSearch/css/main.css`

I couldn't find any documentation of whether `baseUrl` should be used for this purpose, but it seems to work, apart from these three cases. 

1) Is there a recommended way to use a separate directory for serving JBrowse assets?

2) Is there something anomalous in the path resolution that is causing these three files not to use `baseUrl`?

**Comment by cmdcolin** [comment]
Interesting issue. Looks like baseUrl is an undocumented option (?) but it probably should be documented and maybe could even be fixed in this case !

**Comment by cmdcolin** [comment]
Is this changing the "baseUrl" from the script line dojo.js in index.html?

**Comment by girlwithglasses** [comment]
Yes, and also in the config section further down the page. I generate the page from a template based on `index.html`, but with the `baseUrl` and `dataRoot` set by the app. The relevant bits of code:

    <script type="text/javascript" src="[% jbrowse_assets %]src/dojo/dojo.js"
      data-dojo-config="async: 1, baseUrl: '[% jbrowse_assets %]src'"></script>
    <script type="text/javascript" src="[% jbrowse_assets %]src/JBrowse/init.js"></script>
    <script type="text/javascript">
        window.onerror=function(msg){
        [... snip a load of identical code here ...]
                   var config = {
                       containerID: "GenomeBrowser",
                       baseUrl: "[% jbrowse_assets %]",
                       dataRoot: "[% data_dir %]",
                       queryParams: queryParams,
        [... etc.]

**Comment by enuggetry** [comment]
"I think" you may have to "hack" resolveUrl() in Browser.js to fix the PNG
references.

One "cleaner" way to do this w/o modifying Browser.js is to create a plugin
that hacks the function.

I have a simple example here, a plugin that hacks the showTracks() function
to modify it's behavior.

https://github.com/GMOD/jbrowse/tree/Eric_work_f1/plugins/CategoryUrl

You might hack it to return something like (applying some special case
logic):
   return "http://myurl.com/" + url;

As for /plugins/RegexSequenceSearch/css/main.css,  it's probably a similar
problem.    Try fooling with "location" parameter of the plugin config in
tracklist.json.
http://gmod.org/wiki/JBrowse_Configuration_Guide#Using_Plugins
(you'd probably have to move the entire plugin module to your asset server)

**Comment by girlwithglasses** [comment]
Probably not relevant, but I have just noticed that Empty.png and JBrowseLogo_small.png are the only two files in `images` that have the first letter capitalised...

**Comment by enuggetry** [comment]
It does appear the two files (and plugins, BTW) seem to use the
browser.resolveUrl(), (plus, there's some other code in the faceted track
selector uses it too).
It's just a guess.
Other areas use Util.resolveUrl() and many image files are referenced in
css which would use paths relative the the css files.

**Comment by girlwithglasses** [comment]
It looks like there might be some redundancy between `browserRoot` and `baseUrl` -- the comments in the change log and the usage in the code suggest they serve similar purposes. It doesn't look like the tests in ConfigManager.spec.js cover URL resolution or dealing with `browserRoot` or `baseUrl`. I don't know enough about how JBrowse is structured, where and when the config params are integrated, what the application flow is, etc., to know how this should be fixed. :-\

**Comment by cmdcolin** [comment]
Looks like there was a similar bug a little while back. Mentioned using the browserRoot variable https://github.com/gmod/jbrowse/issues/258

**Comment by girlwithglasses** [comment]
I've fixed this in my local version by editing dojo.js; the corresponding edit in `Browser.js` is:

    resolveUrl: function( url ) {
        // use browserRoot OR baseUrl
        var browserRoot = this.config.browserRoot || this.config.baseUrl || "";
        if( browserRoot && browserRoot.charAt( browserRoot.length - 1 ) != '/' )
            browserRoot += '/';
        return Util.resolveUrl( browserRoot, url );
    },

**Comment by cmdcolin** [comment]
just curious, since your patch just adds baseUrl to this list, did setting browserRoot not work?

**Comment by girlwithglasses** [comment]
I didn't actually try using `browserRoot` since `baseUrl` appears to be representing the same thing, and I originally used `baseUrl` because I was getting an error about it being undefined (which I now realise was from the way I had my template set up).

Is there some documentation somewhere about where JBrowse gets its config data from and in what order it reads the various config files and variables?

**Comment by cmdcolin** [comment]
The config system is pretty interesting. The config system allows multiple config files to be "included" and merged together, and also, multiple config formats are supported (the json format and conf format both coexist). This is sort of how I see it is setup by default:

![](https://cloud.githubusercontent.com/assets/6511937/10300084/e673cf9e-6bb7-11e5-8111-6463e341bfa6.png)

As you have seen, you can actually just pass in config variables via the index.html since the constructor for Browser.js is used as the initial "seed" of the config. Then Browser.js adds some additional variables from "defaultConfig", which instructs it to fetch jbrowse.conf and jbrowse_conf.json, and then jbrowse.conf instructs the browser to fetch trackList.json and tracks.conf, etc


If you have any ideas for clarifying documentation the wiki is always open! I'd be curious since we kind of have similar concerns on apollo but we somehow are encapsulating jbrowse without the static asset approach

**Comment by girlwithglasses** [comment]
Thank you for the explanation and diagram! When I start doing some more serious fiddling with JBrowse, I'll add some documentation to the wiki.

**Comment by cmdcolin** [comment]
That sounds good. Also, this is random but instead of editing dojo.js, I would recommend creating a custom build (see README.md) or using the JBrowse-1.11.6-dev.zip. I imagine if you had to edit the dojo.js then it is the compressed version of the javascript which is painful to edit :)

Anyways feel free to reopen

**Comment by girlwithglasses** [comment]
At some point I will do some better testing, add inline documentation, and then submit a pull request about this. In the future...
