### ISSUE TITLE
Speed up CSS loading and SASS / LESS

### ISSUE THREAD

**Issue by ialarmedalien** [GMOD/jbrowse#638]
`genome.css` currently uses `@import` to pull in other css files. It would be much better to have a single css file containing all the css instead of multiple files. There would not be the overhead of the extra HTTP requests, and the page could also render more quickly as you would not have to wait for all the `@import`ed files to download.

One solution to this issue might be to move to using a CSS preprocessor like LESS or [SASS](http://sass-lang.com), and create a single genome.css file as part of the JBrowse build process (it's fairly trivial to convert the existing files). You can also add CSS minification and [auto prefixing](https://css-tricks.com/autoprefixer/) on to the CSS compilation pretty easily. I would be happy to get this set up and submit a pull request; the only thing would be to choose a preprocessor language to use. I prefer SASS as it's more flexible, but I noticed that dijit themes are available as LESS, so maybe that would be more appropriate.

If there are plans to move to bower for dependency management, it'd be good to add [normalize.css](https://necolas.github.io/normalize.css/) to ensure a more uniform browser experience.

**Comment by nathandunn** [comment]
I think that this is a great idea. @cmdcolin  did something like this for the Apollo JS libraries and we do something similar (asset compilation).

**Comment by enuggetry** [comment]
Sass is used in JBrowse 2 branch.  Good idea.

**Comment by girlwithglasses** [comment]
I see there's a gulpfile branch of JBrowse -- I'll add a minimal gulpfile with CSS compilation in it, which can be combined with that gulpfile for building and asset compilation. Is there anything to stop a move to using bower, other than just putting together the list of dependencies, adding some documentation on setting it up, and actually setting it up?

**Comment by nathandunn** [comment]
:+1:

**Comment by cmdcolin** [comment]
The gulpfile is a little experimental but could be a launching point :)

The main limitation with the gulpfile is that it doesn't perform the JS minimization step. In the end, dojo has to run it's own build tool so it isn't super ideal for integrating with gulp framework of piping things through the system.

The bower thing though would be great to have though. The https://github.com/GMOD/jbrowse/tree/yeban-bowerise branch is probably the latest on this front.

**Comment by girlwithglasses** [comment]
@yeban Is the bower file in your yeban-bowerise branch of JBrowse up to date?

**Comment by cmdcolin** [comment]
I've tested out the yeban-bowerise branch and it should work! I'd say the only thing holding back merging it is some inertia....i think a "next gen" build system would be great though.

**Comment by girlwithglasses** [comment]
Thanks Colin! What about the dojo build step that you mentioned above? I guess I can do the CSS stuff and then someone else can add in the dojo bit.

**Comment by cmdcolin** [comment]
Hmm. I dunno how to put it. I guess the dojo build system does a lot of work, so some things that you might do in gulp aren't really useful because it is already done by the dojo build system

Since the dojo build system does a lot of the things that gulp is designed for, it sort of makes gulp not as useful

Maybe the CSS asset compilation could be added to the dojo build step
https://dojotoolkit.org/documentation/tutorials/1.9/build/


Either that or some smaller gulp file for css asset compilation could be added to the makefile
Or, some fully next gen system might be possible. The makefile is actually pretty good though...maybe it does more work than necessary but the automation is pretty nice

Have you ever run the makefile ?

**Comment by nathandunn** [comment]
I think that backporting the Sass build procedures @enuggetry  mentioned might be a first-step.  Support for bower / gulp, etc. would be great.

**Comment by cmdcolin** [comment]
Should be fixed by webpack sass loading on dev :)
