### ISSUE TITLE
Tracks from ENCODE data

### ISSUE THREAD

**Issue by graphanalytics** [GMOD/jbrowse#640]
If it is possible, wonder what options are available to add tracks based on the encode data that is available at goldenPath download site (http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/). 

Adding annotation tracks like knownGene, refGene seems to be straight forward with ucsc-to-json.pl, but not with loading the encode data.

Any thoughts ?

Thanks,
Vijay

**Comment by cmdcolin** [comment]
As far as I know, they basically just put a link for the bigwig file inside their .txt.gz file for the encode tracks! It would be nice if perhaps ucsc-to-json.pl could handle that too, but it isn't too hard to just unzip those .txt.gz and add a bw track manually too :)

**Comment by cmdcolin** [comment]
If there's interest in the "autoloading" of those tracks, feel free to add a request
