### ISSUE TITLE
.htaccess file not included in release package for JBrowse 1.11.6 (and possibly earlier)

### ISSUE THREAD

**Issue by justinccdev** [GMOD/jbrowse#643]
At least on the package for JBrowse 1.11.6, it looks the .htaccess file added in 572b922 is not there.  Perhaps a build script is ignoring/stripping out all dot files in the root directory (other .htaccess files in example directories are there)?

**Comment by enuggetry** [comment]
It's not strictly required for either case, but I suspect it was left there for example.

**Comment by rbuels** [comment]
Is this still an issue with later JBrowse builds, or can it be closed?

**Comment by justinccdev** [comment]
I say close it.

**Comment by cmdcolin** [comment]
Closed it is :)
