### ISSUE TITLE
Minifying JBrowse

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#644]
Howdy all,

I'd like to figure out how to minify JBrowse for our deployments. For various reasons our deployment means we have a large number of complete copies of JBrowse and it's not currently faesible to reduce these to a single site-wide JBrowse, so when rsyncing I see lots of this:

```
063/dataset_63086_files/JBrowse-1.11.6/src/nls/pt-pt/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/pt/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/pt/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/ro/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/ro/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/ru/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/ru/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/sk/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/sk/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/sl/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/sl/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/sv/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/sv/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/th/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/th/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/tr/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/tr/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/zh-tw/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/zh-tw/colors.js
063/dataset_63086_files/JBrowse-1.11.6/src/nls/zh/
063/dataset_63086_files/JBrowse-1.11.6/src/nls/zh/colors.js
```

We simply aren't going to ever need those localizations. If there's either a way for us to specify a single/few l10ns, or if we could minified to a single javascript file for nls/clndr/jbrowse/etc

## What I've tried:

- setting `optimize: 'shrinksafe'` in `src/JBrowse/JBrowse.profile.js`
- setting `optimize: 'closure'` in `src/JBrowse/JBrowse.profile.js`

both of which resulted in errors on the `make -f build/Makefile release-min` step:

```console
<snip>
...
/home/hxr/work/cpt-jbrowse/JBrowse-dev-dev/src/lazyload/test/node_modules/express/node_modules/connect/lib/middleware/static.js:46: ERROR - Parse error. missing ( before function parameters.
exports = module.exports = function static(root, options){
                                           ^
/home/hxr/work/cpt-jbrowse/JBrowse-dev-dev/src/lazyload/test/node_modules/express/node_modules/qs/support/should/test/should.test.js:59: ERROR - Parse error. missing name after . operator
    true.should.not.be.false;
                             ^

/home/hxr/work/cpt-jbrowse/JBrowse-dev-dev/src/lazyload/test/node_modules/express/node_modules/qs/support/should/test/should.test.js:60: ERROR - Parse error. missing name after . operator
    (0).should.not.be.false;
                            ^

<snip, various warnings/errors above>
/home/hxr/work/cpt-jbrowse/JBrowse-dev-dev/src/JBrowse/View/TrackList/Faceted.js:
/home/hxr/work/cpt-jbrowse/JBrowse-dev-dev/src/JBrowse/View/TrackList/Faceted.js:13066: WARNING - If this if/for/while really shouldnt have a body, use {}
                        for(var node = evt.target; node && !node.dijitDateValue; node = node.parentNode);
                        ^

/home/hxr/work/cpt-jbrowse/JBrowse-dev-dev/src/JBrowse/View/TrackList/Faceted.js:13183: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
        new Date("X"); // workaround for #11279, new Date("") == NaN
                ^

0 error(s), 2 warning(s)
Done (compile time:0.819s)


Process finished normally
        errors: 1
        warnings: 48
        build time: 47.551 seconds
```

Thoughts? Suggestions on debugging?

**Comment by cmdcolin** [comment]
JBrowse already does minifying in the release step. If you see the JBrowse.profile.js, you'll see that most of the code is compiled into the "dojo/dojo" layer, which means 99% of the code is packed into src/dojo/dojo.js in the JBrowse release package (i.e. JBrowse-1.11.6.zip or equivalent). There are also a couple of other "layers" that are only included on demand, but most of the code is packaged into this "dojo/dojo" layer

So in essence, it is already minimized, but you could possible strip away even more unneeded files. What I mean by  that is even despite minimization, some files are still packaged that are unneeded, but the biggest gain in the release package is compressing the large dojo codebase.

**Comment by erasche** [comment]
@cmdcolin okay, my reading seemed to indicate what you said, that the dojo stuff was compiled and compressed down. We're using the `release-min` target's results and still seeing 23Mb unpacked releases (4 is sample_data which we already remove) and we'd like to get those down further. 

Is there an easy way to hook into an compile all of the CSS rules (we don't need 13 separate files for that)?

Is there any risk to wiping out all of the subdirectories under `nls/` folders if we don't care about i18n/l10n, or will dojo(?) carry on nicely without them? Sorry, I'm extremely unfamiliar with dojo.

**Comment by cmdcolin** [comment]
I would look into creating a "localized build"

http://dojotoolkit.org/reference-guide/1.10/build/localizationExample.html

I haven't gotten it to work but it might help

**Comment by erasche** [comment]
Thanks @cmdcolin I'll have a look into that and see if I can make any headway with that.

**Comment by nathandunn** [comment]
If you could let us know what you fine, I have a feeling other users would be interested in a minimal / optimal deploy option.

**Comment by erasche** [comment]
Absolutely!

**Comment by enuggetry** [comment]
Don't know much right now, but I'll be doing a release next month and I'll be happy to take a deep dive into it, then.  So, I'm very curious about what you learn.

**Comment by cmdcolin** [comment]
I think given that JBrowse is already minified and built, and that the ultra minimal build is kind of a special case, maybe the issue can be closed :)? I guess if there are updates maybe they can be added later as a PR for the build system

**Comment by erasche** [comment]
@cmdcolin this is fine. I still wish that dojo didn't behave how it did with i18n stuff, but I suppose the rest cannot be avoided.

**Comment by nathandunn** [comment]
@erasche   I think its a matter of updating the build minification script.  I know that @enuggetry  is taking this into the realm of nodejs, so hopefully this can be rewritten then to exclude those.  There is a ton of doc for [doing the build](https://dojotoolkit.org/documentation/tutorials/1.10/build/) as I'm sure you're aware of, so I'm sure its very possible to do this without the i18n.   I'm also not sure if its related to this:  https://bugs.dojotoolkit.org/ticket/15260
