### ISSUE TITLE
Gradient Features Optional for NeatHTMLFeature plugin

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#650]
Make Gradient Features configurable and optional for NeatHTMLFeatures plugin.
Currently, when NeatHTMLFeatures is applied, features are rendered like this:
![ice_screenshot_20151104-150016](https://cloud.githubusercontent.com/assets/10053377/10954867/e1a01946-8304-11e5-9d09-e3fdf62e5b4c.png)

**Comment by nathandunn** [comment]
:+1:

**Comment by nathandunn** [comment]
My dream is that we can use the gradient to convey information about the genomic structure and/or its associated data (not sure what that would be).  Worst-case it could be configured to indicate strand (imagine that in the RNASeq data!).   Anyway, just some thoughts, I think the original case is fine.

**Comment by keiranmraine** [comment]
+1
We used colour gradients in read colours to show the MAPQ from the alignment under GBrowse, our scientist would definatly use this under JBrowse

**Comment by enuggetry** [comment]
I should have put a little more reference and description in the ticket.  (so, I added it)

Let's discuss some more.  I'd like to sketch out your ideas and config options.

**Comment by cmdcolin** [comment]
I think the gradient for what @keiranmraine refers to would be sort of like this (screenshot of consed)

http://1ofdmq2n8tc36m6i46scovo2e.wpengine.netdna-cdn.com/wp-content/uploads/2013/11/consedView.gif


This would actually be very cool, but I don't think the default glyph for Alignments2 handles that. A new glyph that is designed specially for this case might be able to though

**Comment by enuggetry** [comment]
That's cool.  So, cells background color are conditionally driven by data. Looks like fun.  Need to learn more.

**Comment by enuggetry** [comment]
This is a different type of enhancement all together.  Should probably be a different ticket.

**Comment by cmdcolin** [comment]
Probably true !

**Comment by keiranmraine** [comment]
Hi @cmdcolin, actually that's far more complicated than we use.  That shows per-base-quality (and would be very resource costly).  MAPQ applies to the read as a whole:

![screen shot 2015-11-05 at 10 46 34](https://cloud.githubusercontent.com/assets/3740323/10966294/8a9f690c-83aa-11e5-9e6b-842570ca9a84.png)

This allowed us to define a colour gradient using numeric fields of the SAM record (via simple callback) for the fill colour and also define the line colour to indicate specific aligner auxiliary tags.

Here is the same region in our JBrowse instance, using the read colouring scheme for DNA (see #443 and #473).  There didn't appear to be a way to do the gradient at that point:

![screen shot 2015-11-05 at 10 48 18](https://cloud.githubusercontent.com/assets/3740323/10966336/db04b956-83aa-11e5-8488-88865e55ac6f.png)

**Comment by cmdcolin** [comment]
I think you can define a style->color callback to change your color by score.

The per base requires a custom glyph though.

Anyways, I'll try and make a new issue

**Comment by nathandunn** [comment]
I was talking more about getting rid of the in-cell gradient (dark on the sides to light in the middle).   I think what @keiranmraine  showed is a great example of using the color density to represent another dimension.   Very nice.

**Comment by nathandunn** [comment]
Fied in #718.

**Comment by keiranmraine** [comment]
Although this is closed I thought I'd give a little update and ask a small question.

I've been working to use a combination of:
 * `color` to indicate strand (red/blue)
 * `color` 'lightness' to indicate quality of mapping (from MAPQ field)
 * `borderColor` to indicate pair information:
    * corretly mapped pair - no border (I believe falls back to `color`)
    * mate unmapped - purple
    * mate different chr - red
    * mate same chr (not proper) - green

As you can see it is working but the boarder is too fine:

<img width="1057" alt="screen shot 2016-08-18 at 21 10 21" src="https://cloud.githubusercontent.com/assets/3740323/17789291/7ac06fe2-6589-11e6-8969-fb417df9a190.png">

__My question is, can I increase the size of the boarder?__

Code for above callbacks:

color:
```js
function(f) {
  var mq = f.get('mq');
  var lightness = 75 - (mq/3);
  var saturation = 55;
  var hue = 0;
  if(f.get('strand') != 1) {
    hue = 240;
  }
  return 'hsl('+hue+','+saturation+'%%,'+lightness+'%%)';
}
```

boarderColor:
```js
function(f) {
  var bc;
  if(f.get('multi_segment_all_correctly_aligned')) {
    return bc;
  }
  if(f.get('multi_segment_next_segment_unmapped')) {
    return 'purple';
  }
  if(f.get('seq_id') != f.get('next_seq_id')) {
    return 'red';
  }
  return 'green';
}
```

**Comment by cmdcolin** [comment]
@keiranmraine looks like theres a (undocumented) style.borderWidth parameter in the canvasfeatures glyphs

**Comment by cmdcolin** [comment]
note that I also created some things here that look at mapping qualities https://github.com/cmdcolin/qualityglyphs

it doesn't try to combine too much info as maybe that is sort of "visually busy"

**Comment by keiranmraine** [comment]
Thanks style.borderWidth 2 solves the problem.

<img width="499" alt="screen shot 2016-08-18 at 21 42 49" src="https://cloud.githubusercontent.com/assets/3740323/17790044/c0c5b04e-658c-11e6-9135-8d63536645cf.png">
