### ISSUE TITLE
Documentation lacking on codonTable

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#653]
The release notice for 1.11.6 mentioned the addition of a codon table configuration option. http://jbrowse.org/blog/

However, the only code references are here: https://github.com/GMOD/jbrowse/search?utf8=%E2%9C%93&q=codontable and weren't enough to elucidate how to use this parameter, and it isn't mentioned in the wiki.

If anyone could tell me how to use this feature I'd be happy to update the gmod wiki + docs if there are appropriate places in the JBrowse code to do so. We use coding table 11, so this would be very useful for us.

**Comment by vivekkrish** [comment]
Hi @erasche , I believe in your situation the transl_table=11 (for Bacteria) is not different from the standard transl_table=1 (see reference: [transl_table=11])

However, if you were using a table which had 1 or more differences from the standard table (for example: [transl_table=2] which has 4 differences), you would define it in your own configuration file using a variable named `codonTable`, which gets mixed-in with the `defaultCodonTable` here: [JBrowse/View/Track/Sequence.js#L40]

Hope this helps!

Thank you.
Vivek

[transl_table=11]: http://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/index.cgi?chapter=tgencodes#SG11
[transl_table=2]: http://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/index.cgi?chapter=tgencodes#SG2
[JBrowse/View/Track/Sequence.js#L40]: https://github.com/GMOD/jbrowse/blob/2130b4593c60a2d827be897bc9d3e4301dd3cc5d/src/JBrowse/View/Track/Sequence.js#L40

**Comment by cmdcolin** [comment]
Briefly mentioned on wiki too http://gmod.org/wiki/JBrowse_Configuration_Guide#Sequence_track :)

**Comment by erasche** [comment]
@vivekkrish there are three additional start codons. `AT[TCA]` :)

@cmdcolin aha! That was the snippet I was missing. I think I searched for coding and translation and somehow missed it. Sorry for the spurious issue.
