### ISSUE TITLE
location box should support passing in of custom JSON on an arbitrary label

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#654]
The current location box supports a single scaffold and min/max coordinates.  

In Apollo we are going to be combining multiple folded (around exons and individual) scaffolds at once, in arbitrary orders.  See: https://github.com/GMOD/Apollo/issues/672

We need to support JSON creating arbitrary JSON labels or the ability to interpret.  

The JSON will be of the format:

```
{"padding":50, "projection":"Exon", "referenceTrack":"Official Gene Set v3.2", "sequenceList":[{"name":"Group15.19":features:[{"name":"GB-4012131-RA"}]},{"name":"Group2.19"},{"name":"Group9.10"}]}
```

Personally, I would create a `label` field in the JSON (easy to add) that JBrowse could just pull out and display.  This way its up to the up-stream client to worry about how it labels stuff, not jbrowse.

1.11.8 (or custom build is okay)

FYI @cmdcolin  and @enuggetry

**Comment by enuggetry** [comment]
Sorry, forgot to mention: this will probably not work without this particular build or later because of #652 feature.
https://github.com/GMOD/jbrowse/commit/6617ffb2be31b31607ec449996b9579094a13367

**Comment by cmdcolin** [comment]
This is actually sort of a random idea, but it might be kind of related.....basically I was thinking it would be cool if the "refseq names" could actually undergo arbitrary transformations

Reason being, the identifiers for chromosomes names is a real mess sometimes in bioinformatics sometimes.

You can have GFF which have chromosome identifiers (NC_1232341.1) in the column 1, whereas the fasta you loaded just has chr1,chr2,chr3, or the reverse situation where your fasta had the NC_1231241.2 IDs, and your GFF has chr1,chr2,chr3

the only solution that we have is to actually modify the source file before loading, but it would be cool if those things could be transformed on the fly by user defined functions...

**Comment by nathandunn** [comment]
This works, though I don't think its in the master branch.
