### ISSUE TITLE
How to minimize the height of each track?

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#656]
Hi everyone,
I want to minimize the default height of the tracks to visualize more tracks in one screen.
How could I achieve this implementation?

![image](https://cloud.githubusercontent.com/assets/3148255/11204588/689a81ee-8d3b-11e5-8557-edba17202c93.png)

**Comment by keiranmraine** [comment]
Hi,

Not sure how complex your data is, but have you considered putting them all into a single bgzip/tabix bed file (and resulting track) with labels displayed?

Regards,

Keiran Raine
Principal Bioinformatician
Cancer Genome Project
Wellcome Trust Sanger Institute

kr2@sanger.ac.uk
Tel:+44 (0)1223 834244 Ext: 7703
Office: H104

On 17 Nov 2015, at 06:59, Sun Chen <notifications@github.com> wrote:

> Hi everyone,
> I want to minimize the default height of the tracks to visualize more tracks in one screen.
> How could I achieve this implementation?
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by cmdcolin** [comment]
There is also a config variable called view→trackPadding that is by default 20px

Can set it smaller for this use case perhaps (i.e. add view.trackPadding=0 in jbrowse.conf or similar), or a combined track as @keiranmraine suggests might help

Note that you can't set a "track specific" trackPadding. The padding is applied to all tracks

**Comment by verne91** [comment]
Hi, @keiranmraine 
I have lots of different bed files with different labels.
How could I specify the labels if I put them into a single file?

Hi @cmdcolin , thank you for your suggestion and it is effective for my trouble.
But could I minimize the height of track label further?

**Comment by keiranmraine** [comment]
Hi, I've not done it myself but on testing to give you an example I've found JBrowse doesn't support bed.  You can however use gff3 (apparently tabix gff3 isn't supported either):

http://www.sequenceontology.org/gff3.shtml

```
##gff-version 3.2.1
8	.	.	66000000	66000500	20	+	.	ID=3;Name=C
8	.	.	66600000	66615461	30	.	.	ID=4;Name=D
8	.	.	66872480	66872500	5	+	.	ID=1;Name=A
8	.	.	66874000	66874600	10	-	.	ID=2;Name=B
```

![screen shot 2015-11-18 at 06 36 36](https://cloud.githubusercontent.com/assets/3740323/11234324/c9b211d0-8dbe-11e5-84b0-acfb31ceed27.png)

Hope this helps.

**Comment by verne91** [comment]
Hi @keiranmraine ,

Thank you for your recommendation.
However, my data is intensive among tracks and all the tracks would not display at same time.
This method may not suit for me.
