### ISSUE TITLE
Reference sequence requested multiple times with static chuncked store

### ISSUE THREAD

**Issue by einhverfr** [GMOD/jbrowse#658]
Using the JBrowse/Store/Sequence/StaticChunked store for reference sequence information, I noticed it requests the whole file for every chunk requested. 

Given that the whole file is requested, would it not make more sense to have it request the file once and then chunk it as it does?

Would be interested and willing to provide either a fix to the current store or a new store that behaves like this.

**Comment by cmdcolin** [comment]
Looks like #641 also mentions this just FYI. If you can add discussions to that issue that would be great :)

**Comment by einhverfr** [comment]
Added a comment there.  Given the use case I am looking at (fetching contigs as reference sequences from a relational database and then sending out as a web service) it would make most sense to get the reference sequence once.  Would you be interested in a separate (for now) version which memoizes this call?

**Comment by einhverfr** [comment]
I could patch SequenceChunks.js instead but I could imagine cases where the redundancy between the browser cache and caching in Javascript might cause problems so was thinking of having a separate one instead.

**Comment by einhverfr** [comment]
See PR #661

**Comment by einhverfr** [comment]
My previous pull request did not work as expected currently, so I am removing it for now.  I am having issues with the refseqs store not being found in those cases.

My comments on caching will go on the other ticket.  I will note it is *not* necessarily true that most results are served out fo the browser cache (I got a chance to test on 3 different browsers).

**Comment by cmdcolin** [comment]
Some work on this done in #855

**Comment by cmdcolin** [comment]
Maybe close this as dup of #641
