### ISSUE TITLE
Trouble with Tabix Index access by Firefox

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#667]
In case this might have been buried in what turned out to be an unrelated email thread, I have encountered some sort of browser-dependent issue with access the tabix index file for VCF tracks.

I have two development servers ("old" and "new"), whose main difference is that the "new" has zlib.so.1.2.3 and "old" has zlib.so.1.2.3.4.

VCF tracks are working in Chrome 46.0.2490.86 (64-bit) on MAC OSX 10.9.5 and also the latest Safari. Firefox 42.0 fails to load the track with an error message that varies from dataset to dataset:
"Error: invalid stored block lengths"
"Error: too many length or distance symbols" etc. (example stack trace from the Browser Console at the end of this message)

It appears as if the response object is empty in the call to get() in JBrowse/Store/RemoteBinaryFile.js. Even in Chrome, with a breakpoint at line 272, there is an Exception buried in the "response" variable's __proto__ byteLength attribute:

    byteLength: [Exception: TypeError: Method ArrayBuffer.prototype.byteLength called on incompatible receiver #<ArrayBuffer>
     at ArrayBuffer.get byteLength (native)
     at ArrayBuffer.remoteFunction (<anonymous>:3:14) at Object.InjectedScript.callFunctionOn (<anonymous>:721:66)
     at null.<anonymous> (https://phytozome-dev.jgi.doe.gov/JBrowse-dev/src/JBrowse/Store/RemoteBinaryFile.js:273:21)
     at XMLHttpRequest.<anonymous> (https://phytozome-dev.jgi.doe.gov/JBrowse-dev/src/dojo/_base/lang.js:375:55)

Example Firefox Browser console message:

Error: invalid stored block lengths .cache["jszlib/inflate"]/</<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:1678:279
.cache["JBrowse/Model/BGZip/BGZBlob"]/</e<.unbgzf@https://phytozome-next.jgi.doe.gov/jbrowse/src/JBrowse/Store/SeqFeature/VCFTabix.js:9:145
.cache["JBrowse/Model/BGZip/BGZBlob"]/</e<._wrap/<@https://phytozome-next.jgi.doe.gov/jbrowse/src/JBrowse/Store/SeqFeature/VCFTabix.js:8:134
.cache["JBrowse/Store/RemoteBinaryFile"]/</<.get/</<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:979:461
.cache["JBrowse/Store/RemoteBinaryFile"]/</<._assembleChunks@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:981:256
.cache["JBrowse/Store/RemoteBinaryFile"]/</<.get/<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:979:1
.cache["dojo/_base/lang"]/</f.hitch/<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:121:420
.cache["JBrowse/Store/RemoteBinaryFile"]/</<._fetchChunks/</<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:975:393
.cache["JBrowse/Store/LRUCache"]/</<._attemptFill/</<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:986:148
.cache["dojo/_base/array"]/</f.forEach@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:151:382
.cache["JBrowse/Store/LRUCache"]/</<._attemptFill/<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:986:110
.cache["dojo/_base/lang"]/</f._hitchArgs/<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:121:99
.cache["JBrowse/Store/RemoteBinaryFile"]/</<._fetch/j@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:977:192
.cache["JBrowse/Store/RemoteBinaryFile"]/</<._fetch/e.onreadystatechange<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:978:230
.cache["dojo/_base/lang"]/</f.hitch/<@https://phytozome-next.jgi.doe.gov/jbrowse/src/dojo/dojo.js:121:420
 Error: invalid stored block lengths

**Comment by cmdcolin** [comment]
is it happening on any files that you know used to work? or just new files? any sample data available or links up?

**Comment by cmdcolin** [comment]
thanks for making the github issue btw

**Comment by rdhayes** [comment]
Thanks for looking into it! FYI, I have to unexpectedly go out of town and
I'm not sure how much I can work on this over the next week or so.

The problem in Firefox is all VCF tracks, including existing ones that are
working on phytozome.jgi.doe.gov. Firefox is loading VCF tracks just fine
from that public site. The problem came up when testing new servers
(Scientific Linux versus Debian on the old servers).

I am pretty sure that our dev server is behind a firewall, but try this
URL:
https://phytozome-dev.jgi.doe.gov/jbrowse/index.html?data=genomes%2FCreinhardtii%2F&loc=chromosome_10%3A1657251..1723450&tracks=Transcripts%2CAlt_Transcripts%2Ctpc00508_SNVsandIndels&highlight=

I looked at apache log files. From the access log when loading successfully
with Chrome:
127.0.0.1 - - [03/Dec/2015:11:09:10 -0800] "GET
/jbrowse/genomes/Creinhardtii//vcf/Creinhardtii_281_smallVariants_tpc00508-SupplementalDS2_forJbrowse.vcf.gz.tbi
HTTP/1.1" 200 56834 "
https://phytozome-dev.jgi.doe.gov/jbrowse/index.html?data=genomes%2FCreinhardtii%2F&loc=chromosome_10%3A2310436..3120411&tracks=Transcripts%2CAlt_Transcripts&highlight="
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/47.0.2526.73 Safari/537.36"

and unsuccessfully from Firefox:
127.0.0.1 - - [03/Dec/2015:11:13:06 -0800] "GET
/jbrowse/genomes/Creinhardtii//vcf/Creinhardtii_281_smallVariants_tpc00508-SupplementalDS2_forJbrowse.vcf.gz.tbi
HTTP/1.1" 200 56834 "
https://phytozome-dev.jgi.doe.gov/jbrowse/index.html?data=genomes%2FCreinhardtii%2F&loc=chromosome_10%3A2335071..3145046&tracks=&highlight="
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:42.0) Gecko/20100101
Firefox/42.0"

No message in the error log to indicate why that 200 status request isn't
generating a response in Firefox.

I see leading slashes in those URLs and that doesn't match my config:
tbiUrlTemplate =
vcf/Creinhardtii_281_smallVariants_tpc00508-SupplementalDS2_forJbrowse.vcf.gz.tbi



Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by rdhayes** [comment]
I looked into request/response header differences in Firebug when I get success from the old server and failure on the new. Apache versions are slightly different.

Request headers are structurally the same:
GET /jbrowse/genomes/Creinhardtii//vcf/Creinhardtii_281_smallVariants_tpc00508-SupplementalDS2_forJbrowse.vcf.gz.tbi HTTP/1.1
Host: phytozome-olddev.jgi.doe.gov
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:42.0) Gecko/20100101 Firefox/42.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://phytozome-olddev.jgi.doe.gov/jbrowse/index.html?data=genomes%2FCreinhardtii%2F&loc=chromosome_10%3A1657738..1722301&tracks=Transcripts%2CAlt_Transcripts&highlight=
Cookie: __utma=249693981.718172500.1330039201.1446160881.1447796684.24; _ga=GA1.2.718172500.1330039201; __utmz=249693981.1446160881.23.4.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)
Connection: keep-alive

Working Response header:
HTTP/1.1 200 OK
Date: Thu, 03 Dec 2015 22:56:28 GMT
Server: Apache/2.2.25 (Unix)
Last-Modified: Wed, 02 Dec 2015 00:43:53 GMT
Etag: "360ab86-de02-525df91877984"
Accept-Ranges: bytes
Content-Length: 56834
Vary: User-Agent
Content-Type: application/x-gzip
Keep-Alive: timeout=15, max=48
Connection: Keep-Alive

Failing Response header:
HTTP/1.1 200 OK
Date: Thu, 03 Dec 2015 23:06:24 GMT
Server: Apache/2.2.15 (Scientific Linux)
Last-Modified: Wed, 02 Dec 2015 00:43:53 GMT
Etag: "360ab86-de02-525df91877984"
Accept-Ranges: bytes
Vary: User-Agent,Accept-Encoding
Content-Type: application/x-gzip
Content-Encoding: gzip
Keep-Alive: timeout=15, max=69
Connection: Keep-Alive
Transfer-Encoding: chunked

No "Content-Length" in the failed response header, but Firebug is reporting a smaller file size in the cache (Data Size 51784 versus full length 56834)

I have tried adding 
Cache-Control: no-cache
to the header, as there is at least a few references online to lack of this settings causing 200 OK responses for GET requests to have zero-length content in Firefox. No change.
I similarly tried enabling
Access-Control-Allow-Origin "*"
in case CORS was at fault, but this is content all from the same webserver and domain. No change from that either.

**Comment by cmdcolin** [comment]
I couldn't access that server (behind firewall)




Nevertheless i think your issue is very similar to the issue presented by this thread http://gmod.827538.n3.nabble.com/Gmod-ajax-SNP-vcf-error-td4049533.html#a4049690

The reason it works in chrome is due to chrome actually making a patch that allows for bad response headers from the server to be interpreted correctly


basically you DO NOT want "Content-Encoding: gzip" turned on in your messages

i forget how to turn it off but I'd start there

**Comment by cmdcolin** [comment]
also, you'll note in that thread, i thought it was so weird that Chrome allows this where other browsers fail, so I actually found the chrome patch that allowed it


https://chromium.googlesource.com/chromium/src/+log/42.0.2311.0..43.0.2357.0?pretty=fuller&n=10000


    [net] Remove logic for fixing up Gzip encoding type for downloads.

    Some servers incorrectly send 'Content-Encoding: gzip' for responses
    that should be downloaded as gzipped files. UMA indicates that the
    number of servers that exhibit this incorrect behavior is vanishingly
    small. Hence the network stack  will no longer perform this encoding
    fixup.

    What an embedder of the network stack does with a response often depends
    on the response headers and the capabilities of the embedder. The
    current implementation was based on an inaccurate prediction of the
    inteded disposition of the response. In addition to the inaccuracy, the
    implementation was also becoming a maintenance burden.

    With this change, resources downloaded with the incorrect
    Content-Encoding will be saved uncompressed.

    BUG=318217

    Review URL: https://codereview.chromium.org/1008873006

    Cr-Commit-Position: refs/heads/master@{#321890}

**Comment by rdhayes** [comment]
Our says admins think it might be a mod_ssl bug. I'll pass this along to
them.

**Comment by rdhayes** [comment]
One simple addition to our mod_headers config did the trick. I'm still not sure why "Content-Encoding gzip" was applied to *.tbi files prior to this change.

The "Compressing data on the server" section of the wiki documentation says to use:
<IfModule mod_headers.c>
   <FilesMatch "(\.jsonz|\.txtz)">
     Header onsuccess set Content-Encoding gzip
   </FilesMatch>
 </IfModule>

When I change to the following (addition of \.gz to the FilesMatch test is my only edit), Firefox will render correctly:
<IfModule mod_headers.c>
   <FilesMatch "(\.jsonz|\.txtz|\.gz)">
     Header onsuccess set Content-Encoding gzip
   </FilesMatch>
 </IfModule>

**Comment by cmdcolin** [comment]
I'm not sure that this is accurate to set this flag this way, because I think then it implies that the client should decompress it


For example, if I set that on a test server, then I get lots of errors.


![error](https://cloud.githubusercontent.com/assets/6511937/11826959/4be4b4c4-a34e-11e5-9708-1d0687e3f28c.png)


If indeed the change that you made was causing it to work, then maybe you are getting "double gzipped"

**Comment by rdhayes** [comment]
I do need to revisit this apache config in general. I have mod_deflate configured but no mod_gzip enabled.

**Comment by rdhayes** [comment]
Colin, you are correct. That change to mod_header config was now breaking display in Chrome! (RangeError: Offset is outside the bounds of the DataView). I believe I finally have this fixed by backing out that change to mod_header config and removing my mod_deflate config. We don't use mod_gzip, but I had incorrectly assumed that config was necessary to use jsonz and txtz compressed JSON files.

Another approach was to remove .gz from the tabix index file name. The fact that this fixed display in Chrome was the big hint that my mod_deflate config was not working as I expected.

**Comment by rdhayes** [comment]
The tabix file name change to remove .gz turned out to be required for display in Firefox.

My new config is mod_deflate disabled and I also anchored the mod_header config to match file extensions:
\<IfModule mod_headers.c\>
   \<FilesMatch "(\.jsonz|\.txtz)$"\>
     Header onsuccess set Content-Encoding gzip
   \</FilesMatch\>
   Header append Vary User-Agent
\</IfModule\>

**Comment by cmdcolin** [comment]
Good to hear...I suppose if you have no more issues then feel free to close. Also check out #670 ... potentially having tabix gff support!

**Comment by rdhayes** [comment]
The hack where I remove any mention of ".gz" from the tabix index file name is working for me in Apache 2.2.15. I still need to test an update to a newer apache, but I consider this done.
