### ISSUE TITLE
PhantomJS screenshots lead to blank image

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#669]
According to http://gmod.org/wiki/JBrowse_Configuration_Guide , screenshots could be built by  PhantomJS. However, it produce nearly blank images (PhantomJS 2.0+JBrowse1.11.6). PhantomJS works normal in other websites. I don't know which problem occurs here. Any good suggestions?

**Comment by cmdcolin** [comment]
Are you able to take a screenshot of the browser on jbrowse.org?

Also, make sure to set a reasonable timeout for the rasterize.js script

The default value is only 200 milliseconds which may not be enough for jbrowse to load yet

**Comment by billzt** [comment]
@cmdcolin Thank you! After change timeout  from 200 to 1000, it works well.

**Comment by cmdcolin** [comment]
Glad that helps. Let us know if there ends up being other issues, phantomjs or otherwise, that you run into!
