### ISSUE TITLE
Add &loc=featureId discussion to docs

### ISSUE THREAD

**Issue by colindaven** [GMOD/jbrowse#671]
Hi all,

I like to use this functionality to link _in_ to a named and indexed JBrowse feature.

That is, you use a feature as part of the URL and JBrowse jumps right to it - smart!

http://myserver/Jbrowse/index.html?data=genome&loc=myFeatureID

Could this (or is this) documented in the configuration guide ?  I couldn't find this ?

http://gmod.org/wiki/JBrowse_Configuration_Guide
 
Or should I do it (if I can make an account).

Regards,
Colin

**Comment by vivekkrish** [comment]
Hi @colindaven - We use this parameter too to link into our JBrowse!

Regarding the documentation, I did notice that there is some information about this URL parameter here: http://gmod.org/wiki/JBrowse_Configuration_Guide#loc

---
**feature name/ID**
If a string or a mix of string and numbers are entered as an input, JBrowser treats the input as a feature name/ID of a gene. If the ID exists in the database RefSeq, JBrowser displays an arbitrary region of the feature from the the position 0, starting position of the gene, to a certain end point.
```
  example) ctgA
```
---

This text already mentions that input to loc is treated as a feature name. As you suggested, the documentation could be updated to mention that fact that this is tied to the JBrowse names index, and provide some example of Gene identifer in addition to a Reference sequence ID. Thoughts?

Thanks!

**Comment by cmdcolin** [comment]
I believe this is in the docs as vivekkrish said! Maybe an example link there could help or something though. Maybe closed now though :)
