### ISSUE TITLE
JBrowse/Analytics

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#674]
I'm releasing and publicising a version of JBrowse that's built into [Galaxy](https://galaxyproject.org). Would the JBrowse team like me to patch dojo.js locally to segment users for your analytics? E.g. add a "galaxy=true" parameter to the tracking pixel's URL?

More information can be found in the [PR](https://github.com/galaxyproject/tools-iuc/pull/507) for the curious.

**Comment by enuggetry** [comment]
This is slick!  Nice job!
Yes, separate tracking would be nice.

**Comment by erasche** [comment]
Ok, thanks!
