### ISSUE TITLE
VCFTabix.js incorrectly converts to interbase

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#675]
We noticed that our VCF tracks are converting to interbase coordinates, but the VCF spec says that this format as 1-based. (https://samtools.github.io/hts-specs/VCFv4.2.pdf, page 4).

For example, we have a VCF line with POS 93241 that is drawn starting at position 93240. However, the default popup lists this as having start 93241 correctly.

I haven't tested 1.12.0 yet, but in 1.11.6, I see the declare function in src/JBrowse/Store/SeqFeature/VCFTabix.js convert to interbase in line 35.

I think that was originally done because the default popup code (src/JBrowse/View/Track/_VariantDetailMixin.js) calls the common _renderCoreDetails() method in  src/JBrowse/View/Track/_FeatureDetailMixin.js. Line 96 calls the Util.assembleLocString() common method that must be shared with GFF3 features. Line 356 of src/JBrowse/Util.js adds 1 back to start for display.

Is VCF the only non-interbase format that JBrowse uses? It seems that we need a flag parameter added to Util.assembleLocString() to signify that we are not in interbase coordinates.

**Comment by cmdcolin** [comment]
I'm just curious, here is a sample data point at position 3000 in the VCF

http://jbrowse.org/code/JBrowse-1.11.6/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A2975..3027&tracks=DNA%2Cvolvox_vcf_test&highlight=

Does yours appear differently?

**Comment by rdhayes** [comment]
Huh.

I think I was misinterpreting a quirk of the JBrowse ruler flag not displaying the correct coordinate. See this example for SNP ss.37384513, rendered at position Chr01:138383 correctly:
http://phytozome.jgi.doe.gov/jbrowse/index.html?data=genomes%2FPtrichocarpa&loc=Chr01%3A138340..138439&tracks=Transcripts%2CAlt_Transcripts%2Cnatgen2014_variation&highlight=
(see position in screenshot attached)
![poplar_snp](https://cloud.githubusercontent.com/assets/474584/12129756/854e8cb8-b3ba-11e5-8442-1e3e3f4d8447.png)

VCF is not interbase, so I was also led astray by src/JBrowse/Store/SeqFeature/VCFTabix.js converting to interbase coordinates. Why is that done? To share rendering code with CanvasFeatures?

**Comment by cmdcolin** [comment]
If I remember correctly (i have to do some homework on this for webapollo) internal data representation is 0-based and display is 1-based(?) The GFF storeclass parser does same thing, as it is 1-based too. There is a weird ecosystem of coordinates in file formats, but hopefully everything gets rendered correctly. Feel free to reopen if any more issues :)
