### ISSUE TITLE
sequence search track keeps "Loading" in 1.12.0

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#676]
JBrowse 1.12.0, Firefox 43.0.3, Using "Add sequence search track":

![a](https://cloud.githubusercontent.com/assets/1146090/12131372/f717271e-b44c-11e5-8408-560ba5e5e466.PNG)

Click "Search", the track keeps "Loading". The results can't appear
![b](https://cloud.githubusercontent.com/assets/1146090/12131388/11d321d4-b44d-11e5-95f4-72cefdc6b511.PNG)

**Comment by enuggetry** [comment]
Indeed it is broke.  Thanks.

**Comment by billzt** [comment]
OMG! Any chance to fix? @enuggetry @rbuels @cmdcolin @dkasenberg @skinner

**Comment by enuggetry** [comment]
The workaround for now is to disable the NeatCanvasFeatures plugin in the trackList.json config file.

**Comment by billzt** [comment]
The problem is fixed according to @enuggetry 's suggestion. However NeatCanvasFeatures is really beautiful, it is too cruel to remove it. I hope JBrowse could fix the bug as soon as possible.

**Comment by ihh** [comment]
We're working on it...

**Comment by enuggetry** [comment]
Fixed.

**Comment by enuggetry** [comment]
The fix was released in 1.12.1
