### ISSUE TITLE
Invisible of track names in track list

### ISSUE THREAD

**Issue by pwwang** [GMOD/jbrowse#678]
It suddenly happens in Chrome (Chromium Version 42.0.2311.152)
Not encountered in other browsers yet.

It is fine at the beginning, but suddenly the fonts disappear. 
I even force the font color black, but without luck.

![jb](https://cloud.githubusercontent.com/assets/1188067/12257809/7e41a93e-b944-11e5-92d8-1d3ca60e2ea1.PNG)

**Comment by cmdcolin** [comment]
Just curious, is this still happening? Does it also happen on other jbrowse instances like the volvox sample browser?

**Comment by pwwang** [comment]
@cmdcolin Yes, It is still happening, no matter what jbrowse instance it's running.

**Comment by enuggetry** [comment]
can you share a public instance that exhibits the problem?

**Comment by cmdcolin** [comment]
I doubt it's just the fact that the CSS is preventing it from showing up in "stock JBrowse"

There are several things that govern what name is used to display in the trackList. Normally it is key. If no key is present in trackList it is label.

If it is still an issue, please post the trackList.json!
