### ISSUE TITLE
Nav buttons are covered by Faceted track selector tab

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#680]
Minor UI issue, but can view here
http://jbrowse.org/code/JBrowse-1.12.0/?data=sample_data/json/modencode

**Comment by enuggetry** [comment]
Yes, indeed.
Here's a better link
http://jbrowse.org/code/JBrowse-1.12.0/?data=sample_data/json/modencode.

**Comment by harshuopi** [comment]
Hello, everyone.

[http://imgur.com/87qTUET](url)
Will this work?

**Comment by cmdcolin** [comment]
@harshuopi I might try and avoid moving it downwards that much, as it could cover up the tracks

I actually really like how the lotus genome browser does it, with the nav buttons in the center https://lotus.au.dk/genome/?loc=chr1%3A18987031..18987712&tracks=DNA%2C20140314_Lj30%2C20150909_LORE1%2C20121123_RepeatMasker%2C20151108_ljv3genome_n_gaps%2C20121122_Augustus&highlight=

**Comment by enuggetry** [comment]
Funny.  I thought I moved the tools to the right a bit in 1.12.0.  But, I
guess not.
I think we just need to give it a little left margin rather than moving the
tab vertically.
In 1.11.6, it was centered.

**Comment by cmdcolin** [comment]
Fixed in master
