### ISSUE TITLE
Bug shows when loading the bam files

### ISSUE THREAD

**Issue by luluchow88** [GMOD/jbrowse#681]
When I loaded the bam file using the jbrowse 1.12.0,there always showed error like"Error:Not a bam file",no matter from the Volvox example or my own data.Why?

**Comment by cmdcolin** [comment]
The most common reason for that error is probably from the Apache configuration. This shows some ways that you might be able to fix it

http://gmod.org/wiki/JBrowse_Configuration_Guide#Apache_Configuration_Note

If you think that might apply or if that doesn't fix it let us know

**Comment by cmdcolin** [comment]
Not sure if you have fixed the issue yet but if you have any more problems or details on your setup, feel free to re-open!

**Comment by luluchow88** [comment]
I have tried to change the apache configuration in your way,but it doesn't work.
