### ISSUE TITLE
track label menu for *Variants tracks

### ISSUE THREAD

**Issue by sdavey** [GMOD/jbrowse#685]
I'm not getting the drop down menu at the right end of the track label for HTMLVariants and CanvasVariants tracks. The button to click on for the menu is displayed on mouse over, but clicking on it does nothing. I tried tracing through some of the promise code and while it appears that the menu may be partially constructed, it is not finally attached to the button.

**Comment by cmdcolin** [comment]
One thing with HTMLVariants and CanvasVariants tracks is that they try to make augmented track label menus with "filters" added onto them, so maybe there is a filter in your VCF file that is causing it to crash. Actually, are you serving variants via a REST API?

**Comment by sdavey** [comment]
yes, I this is a REST track. I don't think we're returning filters with our data. Here's a sample line:
alt: "A"
end: 3250017
id: "1533"
info: "NS=1;DP=32"
name: "snp G > A"
ref: "G"
score: 38
start: 3250017
type: "snpGtoA"

**Comment by cmdcolin** [comment]
Interesting! I think the REST API actually might need some fixes to make that track menu work.

The default "JBrowse/Store/SeqFeature/REST" class has code like this:


    // STUB method to satisfy requirements when setting the REST track to a VCF type
    getVCFHeader: function( query, filterFunctionCallback, errorCallback ) {
        return new Deferred(function() { /* console.log("REST store getVCFHeader"); */ });
    },

I think to make it work, you'd have to fill out that method somewhat, maybe replace that function with your code or make a subclass which overrides that function!

**Comment by sdavey** [comment]
sounds good. thanks for the info and the suggestions!

**Comment by cmdcolin** [comment]
Just an idea but you might be able to call "filterFunctionCallback" with a blank object or something to just remedy the error for now. I am not setup with rest api for testing

**Comment by sdavey** [comment]
basing our class on HTMLFeatures instead of HTMLVariants seems to have solved the problem.
