### ISSUE TITLE
CanvasFeatures Gene glyph sometimes does not layout features correctly

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#686]
https://github.com/GMOD/Apollo/issues/825 on Apollo reported this bug displaying gene glyphs (in which a single feature was "broken" across blocks) under CanvasFeatures

I am attaching the GFF used (formatted with tabs)

[test.gff](https://github.com/GMOD/jbrowse/files/128169/test.gff.txt)

Screenshot

![](https://cloud.githubusercontent.com/assets/458683/12623149/66dc4a50-c4ee-11e5-9f47-684834e06bfe.png)

**Comment by cmdcolin** [comment]
Note: @erasche I also experimented with adding a "Name" field to column 9 for that mRNA and it ended up sort of fixing it. That could be a clue.

**Comment by cmdcolin** [comment]
![screenshot-localhost 2016-02-12 09-14-28 png resize](https://cloud.githubusercontent.com/assets/6511937/13011170/1ecdebfe-d16b-11e5-893c-0b40b793b719.png)

**Comment by erasche** [comment]
@cmdcolin ooooh. That looks like something I can implement locally to fix this. Thanks!

**Comment by cmdcolin** [comment]
In the code, it shows how this issue might have come about "// sort the children by name"

Potential fix:



```
diff --git a/src/JBrowse/View/FeatureGlyph/Gene.js b/src/JBrowse/View/FeatureGlyph/Gene.js
index 5c37a21..50e1cef 100644
--- a/src/JBrowse/View/FeatureGlyph/Gene.js
+++ b/src/JBrowse/View/FeatureGlyph/Gene.js
@@ -57,8 +57,8 @@ _getFeatureRectangle: function( viewArgs, feature ) {
         glyph: this
     };
     if( subfeatures && subfeatures.length ) {
-        // sort the children by name
-        subfeatures.sort( function( a, b ) { return (a.get('name') || '').localeCompare( b.get('name')||'' ); } );
+        // sort the children by name or id
+        subfeatures.sort( function( a, b ) { return (a.get('name') || a.get('id') || '').localeCompare( b.get('name') || b.get('id') || '' ); } );
```
