### ISSUE TITLE
new publish/subscribe request

### ISSUE THREAD

**Issue by sdavey** [GMOD/jbrowse#689]
could you please add
this.browser.publish( '/jbrowse/v1/v/tracks/updateStaticElements', coords );
to the function updateStaticElements in BlockBased.js?

we're adding some static elements to some of our tracks and need to know when the track is scrolled so we can update them.

Or is there a more appropriate place to publish a track scroll event?

**Comment by cmdcolin** [comment]
If you are making a custom track type, then your track type will automatically inherit BlockBased functions, so then you can trigger that function manually by just calling "this.updateStaticElements()" wherever that is relevant. Would that work?

**Comment by sdavey** [comment]
yep, I can make that work. thanks.

**Comment by cmdcolin** [comment]
Cool :) feel free to re-open if there are issues
