### ISSUE TITLE
classMenu and hideGenomeOption

### ISSUE THREAD

**Issue by bhofmei** [GMOD/jbrowse#690]
I can't seem to get the "classMenu" and "hideGenomeOptions" to work properly. I've put the following in my ``jbrowse.conf`` but I still see the default 1.12.0 menu bar.
![image](https://cloud.githubusercontent.com/assets/16089658/13149412/6dd4de7e-d62f-11e5-9076-4f8efb9381c5.png)

    [GENERAL]
    hideGenomeOption = true
    classMenu = true

**Comment by cmdcolin** [comment]
Looks like the jbrowse configuration guide spelled these wrong. It is classicMenu instead of classMenu and also it is hideGenomeOptions instead of hideGenomeOption!

**Comment by bhofmei** [comment]
Awesome! Those spelling mistakes got it to work. Thank you!!!!!
