### ISSUE TITLE
histograms and REST

### ISSUE THREAD

**Issue by sdavey** [GMOD/jbrowse#691]
did something change regarding histograms on alignment tracks and REST storeClasses? Our alignment tracks are based on Alignments2 and work with older versions of JBrowse. In 1.12 and the dev versions we're now seeing histograms where every value is off the chart (red top) and the ruler scale is 0..1. Looking at the network traffic I see that JBrowse is calling our features endpoint but shouldn't it be calling regionFeatureDensities? I also see that there is a new parameter, basesPerSpan. Is that documented somewhere?

thanks, sean

**Comment by rbuels** [comment]
@sdavey is this still an issue?  Going through the backlog and trying to pick up and organize all the things that have been dropped over the years.

**Comment by zenlunatics** [comment]
I can't remember, it's been two years (-: go ahead and close it.

**Comment by sdavey** [comment]
whoops, that was me. just with a different login. Sean
