### ISSUE TITLE
Bug shows when loading the bam files:"Not a BAM file".

### ISSUE THREAD

**Issue by luluchow88** [GMOD/jbrowse#692]
When I loaded the bam file using the jbrowse 1.12.0,there always showed error like"Error:Not a bam file",no matter from the Volvox example or my own data.Why?
I have tried to change the apache configuration in this way:
http://gmod.org/wiki/JBrowse_Configuration_Guide#Apache_Configuration_Note,
but it doesn't work.

**Comment by cmdcolin** [comment]
Hi there,
Configuring apache is sometimes tricky. If you can share your exact configuration, or at least the relevant sections, that might help

Also don't forget to restart the apache server after the configuration is updated :)

**Comment by luluchow88** [comment]
I have deleted "LoadModule mime_magic_module modules/mod_mime_magic.so" in the "/etc/httpd/conf/httpd.conf" file to deactivate mime_magic module and then restart httpd service.

在2016-02-23 00:55:26，周露zhoulu@sibs.ac.cn写道：

Hi there,
Configuring apache is sometimes tricky. If you can share your exact configuration, or at least the relevant sections, that might help

Also don't forget to restart the apache server after the configuration is updated :)

**Comment by luluchow88** [comment]
I have deleted "LoadModule mime_magic_module modules/mod_mime_magic.so" in the "/etc/httpd/conf/httpd.conf" file to deactivate mime_magic module and then restart httpd service.

**Comment by luluchow88** [comment]
I also find that both in JBrowse-1.11.6 and JBrowse-1.12.0 exist such problem,but in JBrowse-1.11.4 don't.

**Comment by cmdcolin** [comment]
>I also find that both in JBrowse-1.11.6 and JBrowse-1.12.0 exist such problem,but in JBrowse-1.11.4 don't.

I can't think of any reason why that version difference would exist. Could you try clearing browser cache and rechecking the 1.11.6/1.12.0? Have you also tested with different browsers and seen any issues?

**Comment by luluchow88** [comment]
Thank you for your reminding,this problem was solved.

**Comment by cmdcolin** [comment]
Awesome, glad that helps! closed for now
