### ISSUE TITLE
[bam_header_read] EOF marker is absent. The input is probably truncated

### ISSUE THREAD

**Issue by man4ish** [GMOD/jbrowse#693]
Hi,

I am configuring jbrowse step by step using following commands.
**
Step1.**

sudo perl bin/prepare-refseqs.pl --fasta  /home/metabolomics/snipa/data/genome.fa

**Step2.**
After that i am converting bam to json format using following command.

perl bin/bam-to-json.pl --bam /home/metabolomics/snipa/data/SRR2098262.bam --trackLabel hg but i am getting follwoing error message.
**
[bam_header_read] EOF marker is absent. The input is probably truncated**

How can i fix such issue?

Regards

**Comment by nathandunn** [comment]
Is there a way you can validate your bam file or at least regenerate it? 

Nathan

**Comment by cmdcolin** [comment]
I imagine this is fixed now? In any case, I would recommend using add-bam-track.pl instead of bam-to-json.pl. It is normally unnecessary to convert BAM to json now. We might want to consdier deprecating it :)

**Comment by man4ish** [comment]
yes this is fixed thanks.
