### ISSUE TITLE
Reference sequence not available for remote sequences

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#698]
I haven't tested this/no deeper knowledge about why this is happening, but I was looking at one of the links in #602 and noticed the following:

![selection_602](https://cloud.githubusercontent.com/assets/458683/13369757/d3e781cc-dcf0-11e5-8fda-476397e41306.png)

**Comment by cmdcolin** [comment]
The most likely reason for this is useAsRefSeqStore isn't enabled on the REST API/it is not labeled with the name refseqs type sequence track. The refseq on the popups will only display if it finds that "official" refseq track


Not super well documented but this is the line of code for that
https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/ConfigAdaptor/JB_json_v1.js#L236

**Comment by erasche** [comment]
fyi @vivekkrish
