### ISSUE TITLE
No track output when loading using ucsc files.

### ISSUE THREAD

**Issue by man4ish** [GMOD/jbrowse#699]
Hi,

I have UCSC files and converted into bed format by picking 

Chr start stop as three columns and put other columns. 

**gene.bed**

chr1    23444  34556  +    434   NM000091   

I used sudo perl bin/flatfiletojson.pl  --bed gene.bed --trackLable gene

It runs successfully but there is no output track. 

**bam file**
Same i did for bam file

sudo perl bin/bamtojson.pl  --bam sample.bam --trackLable hg   

perl   bin/generate_names.pl 

But there is no track for it. How can i fix such issue? I also changed permisson for data folder.

sudo chmod 777 data still there is no output.
 

Regards

**Comment by cmdcolin** [comment]
I would double check that the "RefSeq" or chromosome names match in the genome browser and in your data files


For example, on the genome browser, if it is just "1" for the chromosome name, but it is "chr1" in your data file, then the features won't show up

Hope that helps

**Comment by man4ish** [comment]
i changed it still same pblm.

**gene.deb file**

1	14695	35736
1	228291	228654
1	234205	234559
1	321689	331663
1	334155	368597
1	558653	569756
1	621095	805472
1	808832	809729
1	857387	879533
1	880073	894620
1	896721	900571
1	902099	909955
1	911551	916409
1	924260	935353
1	936193	949858
1	955552	967190
1	969935	990361


**refseq.fa**

>1
CTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGATGCTGTGGTCTT
CATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCAAGCTGAGCAC
TGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGGGCCATTGTTCAT
CTTCTGGCCCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGGAAAGATT
GGAGGAAAGATGAGTGAGAGCATCAACTTCTCTCACAACCTAGGCCAGTAAGTAGTGCTT
GTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTAC

**Comment by cmdcolin** [comment]
That should be sufficient. I would try clearing cache on your browser and if that doesn't help you can share your data directory with us if it isn't too large.

Also, I would recommend following the tutorial, it has some good tips on getting started. See http://jbrowse.org/code/JBrowse-1.12.0/docs/tutorial

**Comment by man4ish** [comment]
i removed cache but still it does not work for me. May i know how can i share my directory? It is on  my personal laptop.

**Comment by man4ish** [comment]
I have shared my data folder. Pls help me.

**Comment by man4ish** [comment]
Below is link for data folder.

https://www.dropbox.com/s/ej5xmy57cjc05pd/data.tar.gz?dl=0

**Comment by cmdcolin** [comment]
I just downloaded this folder and put it into jbrowse and it worked! I am not sure what the problem might be on your end


![screenshot-localhost 2016-03-01 17-01-45](https://cloud.githubusercontent.com/assets/6511937/13445845/61d423d8-dfd4-11e5-950c-c226d5169c63.png)

**Comment by man4ish** [comment]
Is it possible because of permission?

Location : /var/www/jbrowse/JBrowse-1.12.0/data

-rwxrwxrwx  1 manish manish    0 فبر 17 19:22 tracks.conf
drwxrwxrwx 27 manish manish 4096 فبر 17 19:22 seq
drwxrwxrwx  2 manish manish 4096 فبر 18 19:33 names
drwxrwxrwx  3 manish manish 4096 مار  1 18:51 tracks
-rwxrwxrwx  1 manish manish  782 مار  1 18:51 trackList.json

But in above files it seems to be ok.

**Comment by cmdcolin** [comment]
I doubt it. What exactly do you see on your screen? Post a screenshot?

Can you check in your javascript console too and see if there are errors?

**Comment by cmdcolin** [comment]
I imagine this is fixed now? Reopen if not

**Comment by man4ish** [comment]
Yes this is fixed. Thanks for the help.
