### ISSUE TITLE
GFF3 flatfile + CanvasFeatures not rendering anything but a thin line; other possible bugs

### ISSUE THREAD

**Issue by clb1000** [GMOD/jbrowse#701]
Hello JBrowse,
        I have spent two days trying to load a GFF3 flatfile and have it rendered as CanvasFeatures glyphs. All that gets rendered is a thin black line+arrowhead that corresponds to the "gene" feature. Nothing is rendered for the "mRNA" or "exon" features.  I am using JBrowse 1.12.0 and the Firebox browser. The JBrowse test browsers (e.g. Volvox, Yeast)  work just fine for me (i.e. I can see all of the different glyph types for all of the different track types). I have tried modifying my data/trackLists.json file extensively based on the examples in the Volvox and Yeast examples and based on other configuration examples from GMOD wiki, but nothing other than the thin black line ever results.  Any help getting this working would be appreciated.
                             Thank you,
                             Christian

Here is my GFF3 file:

> ##gff-version 3
> ##sequence-region chr8 1 145138636
> chr8    CGDB    gene    63238   232344  0       -       .       ID=ig1;Name=CGDB1;gene=RPL23AP53
> chr8    CGDB    mRNA    63238   71811   0       -       .       ID=CGDB1.7.20.14;Parent=ig1;
> chr8    CGDB    exon    71793   71811   0       -       .       Parent=CGDB1.7.20.14;
> chr8    CGDB    exon    70426   71331   0       -       .       Parent=CGDB1.7.20.14;
> chr8    CGDB    exon    63238   64175   0       -       .       Parent=CGDB1.7.20.14;

I load the flatfile with the command:
`bin/flatfile-to-json.pl --gff CGDB.gff3 --trackLabel TEST -key TEST --trackType CanvasFeatures`
(NOTE: I have tried *many* other commandlines variations, that included --clientConfig data, different styles, etc)

The resulting contents of the file .../JBrowse-1.12.0/data/trackList.json:
>{
>  "tracks" : [
>     {
>         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
>         "type" : "SequenceTrack",
>         "urlTemplate" : "seq/hg38.fa",
>         "category" : "Reference sequence",
>         "urlTemplateFAI" : "seq/hg38.fa.fai",
 >        "label" : "DNA",
 >        "key" : "Reference sequence"
 >     },
 >    {
 >       "compress" : 0,
 >        "trackType" : "CanvasFeatures",
 >       "storeClass" : "JBrowse/Store/SeqFeature/NCList",
  >       "style" : {
 >           "className" : "feature"
 >        },
 >        "urlTemplate" : "tracks/TEST2/{refseq}/trackData.json",
 >        "label" : "TEST",
 >        "key" : "TEST",
 >       "type" : "CanvasFeatures"
 >    }
 > ],
 >  "formatVersion" : 1
>}

BONUS: OTHER POSSIBLE  BUGS:
1) The file docs/featureglyphs.html tries to import genome.css with 
`<link rel="stylesheet" type="text/css" href="../genome.css"></link>`,
but genome.css lives in css/, so this line should be
`<link rel="stylesheet" type="text/css" href="../css/genome.css"></link>`

2) The feature glyph types "transcript-exon" and "transcript-UTR" no longer have glyph definitions, so can no longer be rendered.

(I think these last two bugs should only apply to HTMLFeatures (correct?), but I ran across them in my efforts to resolve my problem so I thought I'd report them.)

**Comment by cmdcolin** [comment]
The default CanvasFeatures glyph expects there to be CDS subfeatures, or a combination of exon+CDS in the GFF, but exons by themselves, as you said, will just show up as a straight line

This can be fixed though if you specify the subParts in the trackList.json

     "subParts": "exon"

Add that to the track. This is a pretty subtle distinction, but I hope that helps!  The config guide for canvasfeatures should probably have a note for this specifically for this to help out

http://gmod.org/wiki/JBrowse_Configuration_Guide#CanvasFeatures_Configuration_Options

**Comment by clb1000** [comment]
Hi Colin,
      The use of "subParts" worked for displaying the exons.
                     Thank you,
                     Christian
