### ISSUE TITLE
JBrowse comparative genomics view

### ISSUE THREAD

**Issue by andreyto** [GMOD/jbrowse#702]
What would be the best way to add a comparative view to JBrowse? I mean something like the Sybil ([PMC3259440](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3259440/)) screenshot attached below. My own primary application would be to microbial strains. The user would have a menu to select one genome as reference and one gene on it as the center. The other genomes then get centered on the pre-computed orthologs of this gene and flipped if necessary. Although the orthology can be pre-computed on hundreds of genomes, I doubt that anyone would look at more than 10 at a time. This can be also applied to arbitrary syntenic ranges, but let us consider here only genes for simplicity.

Sybil is an excellent software in terms of features. I, however, would like something that is easier to populate with data and faster. I have written a tool back in 2013 to [build a JBrowse visualization as an output Galaxy dataset](https://github.com/JCVI-Cloud/VICVB) and to view it inside Galaxy's main frame, and appreciated the advantages of serverless setup.

I expect that removing a "single reference" assumption from JBrowse would be too disruptive. I see two alternative work-arounds, which can be implemented as plugins:
- Show each genome as a separate JBrowse instance. Use dojo publish/subscribe to catch scroll/zoom of the current reference genome and sync the views of the other genomes. Can two instances co-exist on one page? What are the performance considerations compared to the next alternative below?
- Show each genome as a track in a single JBrowse instance, with the coordinates of features projected onto the reference genome. For each non-reference genome, it would amount to maybe flipping and then shifting the coordinates by a constant value in order to put the currently selected orthologous gene into the center of the view. Can this be implemented as a custom Store that pulls data from some standard Store like tabix and then performs the transformation?

I do not have any definitive idea on how to best implement the shaded trapezoids connecting the orthologs. Maybe overlay a transparent [TNT Board](https://github.com/tntvis/tnt.board), draw the connectors and get them moving in sync with the JBrowse tracks?

I would appreciate any pointers. Or maybe you are already close to releasing something like that?

Thanks,

Andrey

![image](https://cloud.githubusercontent.com/assets/136912/13444132/85d5dab2-dfd2-11e5-9ee3-40e43b027e5a.png)

**Comment by erasche** [comment]
I'm just commenting on the galaxy stuff as I'm a galaxy dev/tool dev, but @andreyto that's reall neat! I wish I'd known about that, I ended up implementing it separately over the past year.  https://github.com/galaxyproject/tools-iuc/tree/master/tools/jbrowse it's more general and the output dataset contains a complete JBrowse instance. 

Anyway, my org (center for phage tech) is likewise incredibly invested in synteny maps. When I last poked around for JBrowse/synteny this link was shared with me www.biodalliance.org/dev/test-comparative.html which might be of interest to y'all as well.

**Comment by andreyto** [comment]
@erasche, yes, I saw your new Galaxy tool recently, good job! I, too, found the Biodalliance repo for your link above [https://github.com/dasmoth/dalliance-synteny-demo](https://github.com/dasmoth/dalliance-synteny-demo). This was the one the gave me the idea of linking multiple browser instances mentioned in my ticket. The repo has not been touched for a couple of years. I also saw some 2010 JBrowse Hackathone with a comparative genomic effort that apparently did not go anywhere. There are surprisingly few actively developed visualization tools for comparative genomics, considering how much stuff gets sequenced. Hopefully, the JBrowse team will have a renewed interest in this topic.

**Comment by erasche** [comment]
@andreyto yeah, jbrowse_syn seems pretty dead at this point. 

Oh, nice, I hadn't found the repo, I'm considering deploying their browser just for our comparative stuff, but a JBrowse solution would be nicer since we use it everywhere else. 

If you need help/support/testing/etc for a JBrowse synteny browser, I'd be glad to pitch in. 

> There are surprisingly few actively developed visualization tools for comparative genomics, considering how much stuff gets sequenced

We virus people care about this topic more than most others. :)

**Comment by ihh** [comment]
Ooh, that Biodalliance synteny viewer is nice isn't it?

We definitely want to do synteny views. There is some refactoring to get out of the way first. Specifically @enuggetry is working on getting multiple JBrowse instances running on the same page with arbitrary layout. Synteny is downstream of that...

I consider myself a virus person too but I am not sure I would claim that virus people care more about synteny than others ;)

**Comment by Runsheng** [comment]
Well, glad to know synteny viewers for jbrowse after jbrowse_syn. I am still using gbrowse only because gbrowse_syn works well...

**Comment by srobb1** [comment]
Just wanted to comment that I would definitely use a jbrowse synteny browser. This would be super helpful for a few of the organisms I host in our institute's genome database system.

**Comment by cmdcolin** [comment]
@srobb1 We're currently underway for developing JBrowse 2. It is designed in mind with displaying multiple views on the same screen, which is highly amenable to things like synteny. It already does some sort of interesting things and can connect features from two different linear genomes with shaded polygons and things of that nature. If you're interested, I can add some more info.

There are alternatives also available for JBrowse 1 too. The plasmodb group has created a JBrowse 1 synteny plugin that's quite impressive. They have some special data processing I think to get the data into this format but it is very cool and has a demo here https://tritrypdb.org/a/jbrowse/index.html?data=%2Fa%2Fservice%2Fjbrowse%2Ftracks%2Fdefault&loc=Tb927_01_v5.1%3A425890..638823&tracks=Syntenic%20Sequences%20and%20Genes%20(Shaded%20by%20Orthology)&highlight=

Here's a screenshot

![tritrypdb org_a_jbrowse_index html_data=%2Fa%2Fservice%2Fjbrowse%2Ftracks%2Fdefault loc=Tb927_01_v5 1%3A425890 583346 tracks=Syntenic%20Sequences%20and%20Genes%20(Shaded%20by%20Orthology) highlight=](https://user-images.githubusercontent.com/6511937/66522281-0d092d80-eabb-11e9-865a-31a51355dcae.png)

They have a link on github here too https://github.com/jbrestel/CanvasSubtracks

**Comment by srobb1** [comment]
@cmdcolin  Excellent! I am certainly interested in learning more! 

Is that screenshot from plasmodb? I might have to try that out. 

What is the tentative timeline on JBrowse 2?

Thank you for the information

**Comment by cmdcolin** [comment]
The screenshot is from https://tritrypdb.org/tritrypdb/ on their "synteny" jbrowse track, i think they are related to plasmodb.

We are aiming to get something like a preview of jbrowse 2 that users at the end of november or so, and then we will invite some feedback! We could keep you posted

**Comment by cmdcolin** [comment]
Hi all
I wanted to just give some previews of some work on jbrowse 2 with rendering some synteny datasets

Here are a couple of demos

Grape vs Peach

https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/synteny_demo/index.html?config=test_data%2Fconfig_synteny_grape_peach.json&session=eJzVVNtum0AQ_ZVon10KGAzyW5wolyaNrNpK20RRtIExbLMXtLu-yfK_ZxZs4qKmsvpWiQeYmZ1z9pxhNkRSAWRILjWt4GRhTsZAs_LkHIQiPbJkuS3JMEhjv0dyTZegvzehfhr1yILB0pDh44awHHv8Orv59KV6CPGgXVeu6y2TQPVkLS3I9T1WY6oEmoO-AlaUlgyjQQel3Cd8B8lMxen67k8csVWm5IwVc00tU5IMN3-DpTIrlUa2xIKxzzm19HPhGnqV6-bt8z1imKg4nB5X7zXVeEywPMeXodVz2KICmmavE-CQWaWnDa-SgaY6K1lGuQMq1fJaYqHTETm_muZ0j3D8uG_EnVFuMMLwLtjRTlVRcMjbeMeCu5Uvop-3gep6cAlSCdhpoWYzA3a8Qs2DfhSEXhpHcRJEYRqjHS_VGLRLhmnfS9J--6StId-gQMXNhVbi1BgQL3zvUbWzRsMCtDkgWutxwDQUP8TZZD2-eWc6ooZlU1dH3ucgcHPQMbpBeS5AgiHbpzpvteJmN5xB6HeniuVwtitqKbngVT2Ne93rMq4MjObWOqQmfISXgkkm5mLEVfa6YxH6297ustfJSgSRGTwcaUs4iALPT8IwidI0iINBfGBLnPhemPjt0z_Clnpyj7FlvbQ3yQUfqX-xpUb5D2x5cuTadVaANW55HB6dHrZ2yVqcjytasa4-Kjk_gKtXF-e0qp3Y4LaYMY7_9xRWKC0hGDBgDIr6lUpawDuDTriFnfwe32IHXBZsAeedW2JCgJyPqFttj41HEgm6uXHp7Rv7UREj


Human vs Mouse vs Rat

https://s3.amazonaws.com/jbrowse.org/code/JBrowse-2.0.0-synteny-demo-alpha.0/index.html?config=test_data/config_synteny_integration_test.json

They both use different approaches in synteny. The human mouse rat uses "reciprocal best liftover" pipeline from UCSC, and actually uses liftover data loaded as tracks

The grape vs peach demo uses MCScan data which shows gene-to-gene synteny and the synteny is rendered in the middle.

We will be trying to present at PSB 2020 and PAG 2020 some of these and other features of JBrowse 2. If anyone is interested in more let me know. We are still in beta but early users encouraged to let us know. We have a sign up form here for our "early access program" http://jbrowse.org/eap but if you have specific interests let us know

**Comment by FatihSarigol** [comment]
hi,
for visualizing a multiple species comparative synteny study online, I am in search for a browser tool. 
is it already possible to do something similar to those two via early access to JBrowse2 and host the dataset right away?
thanks

**Comment by cmdcolin** [comment]
@FatihSaragol we could try to get you setup but to be clear it is early beta stage software. It has some exciting results but it is under construction in various ways. If you are interested though please let me know via email and I can try to help

**Comment by rbuels** [comment]
JBrowse 2 has this feature, so I'll close this long-standing issue now. :-)
