### ISSUE TITLE
Current repo's JBrowse not working

### ISSUE THREAD

**Issue by sakshamsaxena** [GMOD/jbrowse#710]
I was using the stable release (1.12.1) downloaded from the website till now, and cloned the repo last night to run the latest code. The setup went fine, but when I hit it up on localhost, I saw a blank page. Not even the volvox data was displayed on its link. Console showed a lot of 404s. Subsequently checked if those files were there or not, and apparently they weren't. dijit, etc folders were empty. 
I'm sure about the steps I've taken, and sure about running the server and scripts etc. So I'm guessing some recent changes led to this? Saw a lot of ```set -e``` in setup.sh but the log seemed normal, but I don't think the shell exited at any point at all. Must be some perl issue in my opinion.

**Comment by cmdcolin** [comment]
When you clone the repo, you have to use "git clone --recursive" to initialize the submodules (dijit, etc are submodules)


You can also run "git submodule update --init --recursive" on your existing clone to do that. Check out "Setting up a development environment" on the README for details

**Comment by sakshamsaxena** [comment]
Ah! Silly of me. Thanks !
