### ISSUE TITLE
Error reading from name store.

### ISSUE THREAD

**Issue by man4ish** [GMOD/jbrowse#712]
Hi,

I am getting pop up window erroe message when i start the browser. 

**Error reading from name store.**

![screenshot from 2016-03-07 15 45 22](https://cloud.githubusercontent.com/assets/6385968/13570002/8d2366d2-e47c-11e5-82ed-3e79bdab84f4.png)

Following is tranks.conf file. 

[{
   "tracks" : [
      {
         "chunkSize" : 20000,
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
         "type" : "SequenceTrack",
         "label" : "DNA",
         "category" : "Reference sequence",
         "key" : "Reference sequence"
      },
      {
         "style" : {
            "className" : "feature"
         },
         "key" : "GeneId",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : null,
         "urlTemplate" : "tracks/GeneId/{refseq}/trackData.json",
         "compress" : 0,
         "type" : "FeatureTrack",
         "label" : "GeneId"
      },
      {
         "style" : {
            "className" : "feature"
         },
         "key" : "RefGene",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : null,
         "urlTemplate" : "tracks/RefGene/{refseq}/trackData.json",
         "compress" : 0,
         "type" : "FeatureTrack",
         "label" : "RefGene"
      },
      {
         "style" : {
            "className" : "feature"
         },
         "key" : "DGV",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : null,
         "urlTemplate" : "tracks/DGV/{refseq}/trackData.json",
         "compress" : 0,
         "type" : "FeatureTrack",
         "label" : "DGV"
      },
      {
         "style" : {
            "className" : "feature"
         },
         "key" : "snp138",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : null,
         "urlTemplate" : "tracks/snp138/{refseq}/trackData.json",
         "compress" : 0,
         "type" : "FeatureTrack",
         "label" : "snp138"
      },
   ],
   "names" : {
      "url" : "names/",
      "type" : "Hash"
   },
   "formatVersion" : 1
}
](url)

How can i fix such issue?

**Comment by cmdcolin** [comment]
This error basically indicates a problem when generate-names.pl was run. You can try to re-run generate-names.pl on your data directory. In some cases, running "generate-names.pl --hashBits 16" can fix it too.

**Comment by man4ish** [comment]
I ran with following command but still same error.

sudo perl bin/generate-names.pl --hashBits 16
WARNING: No feature names found for indexing, only reference sequence names will be indexed.

**Comment by cmdcolin** [comment]
@man4ish I would recommend not using sudo. You should fix your permissions on your data directory "chown -R manish:manish data" or similar, and then run these commands without sudo. You can also see in your http error log if the files are being given permission denied.

**Comment by man4ish** [comment]
I changed permission also 

[-rwxrwxrwx  1 manish manish       7003  18 14:10 setup.sh
drwxrwxrwx  4 manish manish       4096  18 14:10 sample_data
-rwxrwxrwx  1 manish manish       3803  18 14:10 README.md
drwxrwxrwx  8 manish manish       4096  18 14:10 plugins
-rwxrwxrwx  1 manish manish        253  18 14:10 package.json
-rwxrwxrwx  1 manish manish       2962  18 14:10 Makefile.PL
-rwxrwxrwx  1 manish manish      33634  18 14:10 LICENSE
-rwxrwxrwx  1 manish manish        299  18 14:10 jbrowse_conf.json
-rwxrwxrwx  1 manish manish       2893  18 14:10 jbrowse.conf
-rwxrwxrwx  1 manish manish         97  18 14:10 INSTALL
-rwxrwxrwx  1 manish manish       4823  18 14:10 index.html
drwxrwxrwx  2 manish manish       4096  18 14:10 img
drwxrwxrwx  5 manish manish       4096  18 14:10 docs
drwxrwxrwx  2 manish manish       4096  18 14:10 css
-rwxrwxrwx  1 manish manish       2145  18 14:10 compat_121.html
drwxrwxrwx  2 manish manish       4096  18 14:10 browser
-rwxrwxrwx  1 manish manish     112142  18 14:10 release-notes.txt
drwxrwxrwx 10 manish manish       4096  14:13 src
drwxrwxrwx  5 manish manish       4096   7 22:42 extlib
drwxrwxrwx  6 manish manish       4096   7 22:48 samtools-0.1.20
drwxrwxrwx  8 manish manish       4096   7 22:49 blib
-rwxrwxrwx  1 manish manish      60808   8 00:16 Makefile
-rwxrwxrwx  1 manish manish       2582   8 00:16 MYMETA.json
-rwxrwxrwx  1 manish manish       1504   8 00:16 MYMETA.yml
-rwxrwxrwx  1 manish manish          0   8 00:17 pm_to_blib
-rwxrwxrwx  1 manish manish      32139  11 20:17 setup.log
drwxrwxrwx  2 manish manish       4096  14 19:41 bin
-rwxrwxrwx  1 manish manish 3147288982  17 19:09 genome.fa
drwxrwxrwx  5 manish manish       4096   7 23:04 data](url)

**Command for generating name:**

 perl bin/generate-names.pl --hashBits 16

But still same error

**Comment by man4ish** [comment]
Is there anything that i need to change?

**Comment by nathandunn** [comment]
Just grasping at things:
1 - what are the permissions for the name-store in JBrowse (vs the other served documents)? . . unlikely to be the error, but an easy fix if so
2 - are you seeing any errors reported in your apache log or the console?

**Comment by man4ish** [comment]
Following is permisson for names store.

[-rwxrwxrwx  1 manish manish    0  17 19:22 tracks.conf
drwxrwxrwx 27 manish manish 4096  17 19:22 seq
drwxrwxrwx  3 manish manish 4096  1 18:51 tracks
-rwxrwxrwx  1 manish manish  782   7 23:25 trackList.json
drwxrwxr-x  2 manish manish 4096   7 23:25 names](url)



I just checked in console.

[](not well-formed jbrowse.conf:1:2
no element found tracks.conf:1:1
Use of getAttributeNode() is deprecated. Use getAttribute() instead. dojo.js:171:494
Object { message: "Unable to load http://localhost/jbr…", stack: ".cache["dojo/errors/create"]/</</d@…", response: Object, status: 404, responseText: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD…", xhr: XMLHttpRequest } dojo.js:360:282

Object { message: "Unable to load http://localhost/jbr…", stack: ".cache["dojo/errors/create"]/</</d@…", response: Object, status: 404, responseText: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD…", xhr: XMLHttpRequest })

**Comment by man4ish** [comment]
Pls help me in fixing in this issue as i am stuck in my project.

**Comment by cmdcolin** [comment]
If you want, you can just remove this from trackList.json

"names" : {
"url" : "names/",
"type" : "Hash"
},

And the error will go away

The search functionality won't be enabled, but there are not any features being indexed apparently, so in that case it does not change anything

**Comment by man4ish** [comment]
This solves the problem but not sure later hash-name is needed or not?

**Comment by cmdcolin** [comment]
It won't cause any problems really without it enabled.

If you want to enable searching, you can re-run generate-names.pl, and hopefully have better luck. Feel free to re-open the issue when then happens!
