### ISSUE TITLE
How to hide Available Tracks panel

### ISSUE THREAD

**Issue by hqyone** [GMOD/jbrowse#715]
Hi 

How can I hide "Available Tracks" panel by default, just like the one in http://jbrowse.org/?

Thanks

Leo

**Comment by awilkey** [comment]
If you don't want the "Available Tracks" to show there are two simple options.
The first is appending `&tracklist=0` to the URL string. 

The second would be to add:
`show_tracklist = 0`
to the general section of jbrowse.conf (to default for the entire browser), or trackList.json/tracks.conf for a specific genome.
 
In this case, you can view the panel again by appending `&tracklist=1` to the URL string.

**Comment by hqyone** [comment]
Hi Andrew

Got it!
Thank so much!

Leo

**Comment by hqyone** [comment]
Hi Andrew

Is there any way to set the width of "Avaliable Tracks" panel.

Thanks

Leo

**Comment by mhammoud** [comment]
If you hover on the margins of the available tracks panel, you should see your cursor change to the "pull" cursor. You can stretch the width from the right-margin of the active tracks panel.

Hope that helps!

**Comment by cmdcolin** [comment]
Customizable width might be a nice feature, it is by default 25% of screen which works OK on some displays but not on others.
