### ISSUE TITLE
'KeyboardEvent.keyLocation' is deprecated message in chrome

### ISSUE THREAD

**Issue by bhofmei** [GMOD/jbrowse#716]
I think this is an issue with dojo not JBrowse, but thought it's worth bringing to your attention since it's almost April 2016.

When using JBrowse, the first keyboard event throws this warning: `'KeyboardEvent.keyLocation' is deprecated and will be removed in M50, around April 2016. Please use 'KeyboardEvent.location' instead. See https://www.chromestatus.com/features/4997403308457984 for more details.`

I'm using Chrome with JBrowse 1.12.0 but I would get this warning with JBrowse 1.11.6 as well. I don't get the warning with Firefox or Safari.

**Comment by enuggetry** [comment]
In JBrowse 1.12.1 we updated dojo to 1.8.10.  The warning still comes up.
Maybe it was a chromium issue?:  https://codereview.chromium.org/1529623002
Will have to give dojo 1.10 a try.

**Comment by cmdcolin** [comment]
I'm not seeing the message anymore :) Probably just fully deprecated and stopped warning, but I imagine the library on the backend used this as a fallback or something.
