### ISSUE TITLE
"reference sequence not available" in "view details" when using indexed fasta

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#719]
My reference sequences are loaded by indexed fasta:
```
      {
         "urlTemplateFAI" : "seq/genome_Garb_JBrowse.fa.fai",
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "urlTemplate" : "seq/genome_Garb_JBrowse.fa",
         "label" : "DNA",
         "type" : "SequenceTrack",
         "category" : "Reference sequence",
         "key" : "Reference sequence"
      },
```

My GFF file is loaded in a normal way:
```
      {
         "style" : {
            "className" : "feature"
         },
         "key" : "Protein Coding Gene",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : "CanvasFeatures",
         "urlTemplate" : "tracks/protein_coding_gene/{refseq}/trackData.jsonz",
         "compress" : 1,
         "category" : "Feature Annotation",
         "label" : "protein_coding_gene",
         "type" : "CanvasFeatures"
      },
```

In the "view detail" diaglog, it says:
`Region sequence: reference sequence not available`

![b](https://cloud.githubusercontent.com/assets/1146090/14132208/d1c0f894-f675-11e5-89ad-f4fe16594e77.png)

Why?

**Comment by cmdcolin** [comment]
I think you can add "useAsRefSeqStore": true to the config for the sequence track to fix this particular issue, but it might be a bug where the prepare-refseqs.pl for indexed fasta didn't output that properly. Will need to check and fix that if true

**Comment by billzt** [comment]
Thank you. After add `"useAsRefSeqStore": true`, the bug is fixed.
