### ISSUE TITLE
Issue with display of frameshifted features

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#720]
We have features which exhibit programmed ribosomal slippage events and have frameshifts (-1, -2, maybe more?).

## Background

Per [SO](http://sequenceontology.org/gff3.shtml), our GFF3 looks like:

```
chrX  . gene               XXXX   YYYY  .  +  . ID=gene01;name=my_gene
chrX  . mRNA               XXXX   YYYY  .  +  . ID=tran01;Parent=gene01;Ontology_term=SO:1000069
chrX  . exon               XXXX   YYYY  .  +  . Parent=tran01
chrX  . CDS                XXXX   YYYY  0  +  . ID=cds01;Parent=tran01
chrX  . CDS                YYYY-1 ZZZZ  1  +  . ID=cds01;Parent=tran01
```

however this does not display very well in JBrowse. Does anyone have suggestions on how I might make it display more cleanly? What parts of JBrowse should I modify? etc.

## Example Data

Here's a concrete example of our GFF3:

```
##gff-version 3
##sequence-region Merlin 1 172788
Merlin  GeneMark.hmm    gene    10      20      .       +       .       ID=Merlin_1;seqid=Merlin
Merlin  GeneMark.hmm    mRNA    10      20      .       +       .       ID=Merlin_1_mRNA;Parent=Merlin_1
Merlin  GeneMark.hmm    exon    10      20      .       +       .       Parent=Merlin_1_mRNA
Merlin  GeneMark.hmm    CDS     10      20      1000    +       0       ID=Merlin_1_CDS ;Parent=Merlin_1_mRNA
Merlin  GeneMark.hmm    CDS     19      30      500     +       1       ID=Merlin_1_CDS ;Parent=Merlin_1_mRNA
```

## Result

And here's how it looks under Canvas:
![utvalg_678](https://cloud.githubusercontent.com/assets/458683/14159767/4ea8bc24-f6c7-11e5-9bd3-335b00273c3e.png)

and HTML:
![utvalg_679](https://cloud.githubusercontent.com/assets/458683/14159769/50710174-f6c7-11e5-8cd7-fa80dfae5790.png)

## Identified Problems

- Neither Canvas nor HTML actually extend any part of the feature to base 30, both stop at 25 or earlier (odd!)
- The display of the feature does not make it clear that there is a frameshift. I would expect the second CDS to be in a different vertical position to represent how it's in a different reading frame, maybe with a joining line of some sort

## Resolution

Any pointers on how I might fix the display here?

**Comment by cmdcolin** [comment]
I may have overlooked something on this thread, but the thing about the subfeatures having coordinates outside the display of the parent gene was the most obvious one. Generally jbrowse doesn't really like this.


However...there is a configuration variable for CanvasFeatures called maxFeatureGlyphExpansion that can help fix this on the canvas tracks, but I would consider whether you want to keep having subfeatures outside the boundaries of the gene

**Comment by erasche** [comment]
@cmdcolin I'm just following the GFF3 specification :( I wanted to be "technically correct" according to their description of frameshifted features but it's understandable JBrowse wouldn't accept this really odd syntax.

I can extend the gene + mRNA features to contain both CDSs which removes the problem of displaying up to base 30, but they remain overlapped, so if you have any pointers for how I might force them to be vertically separated and adding an indication of the ribosomal slippage event, it would be appreciated.

**Comment by cmdcolin** [comment]
You could potentially just load the CDS features only with --type CDS on your gff. Then being separate theyll appear on different y-coords. The volvox sample browser has some examples of "bare CDS" features which I think is relevant for some situations like this. Otherwise you could try making a custom "glyph" class, or extend the existing one to support this :) If interested, and the original issues with your screenshot are explained i'd probably close this for now
