### ISSUE TITLE
Rendering bug if GFF file only includes "gene"

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#722]
JBrowse 1.12.1, using flatfile-to-json.pl to load a GFF file with only "gene" feature (I only need gene region, do not need sub-features):

```
D07	EVM	gene	1327875	1330999	.	+	.	ID=Gh_D07G0120;Name=TBL16;Description=Protein trichome birefringence-like 16 ;
```

The render is very strange, no boxes, but multiple names in even wrong position:
![a](https://cloud.githubusercontent.com/assets/1146090/14202240/7672eeb0-f829-11e5-9ce2-6fad9d99ddc9.PNG)

However, if I change `gene` to some other words, (e.g. OTHER), it works well.
```
D07	EVM	OTHER	1327875	1330999	.	+	.	ID=Gh_D07G0120;Name=TBL16;Description=Protein trichome birefringence-like 16 ;
```

![b](https://cloud.githubusercontent.com/assets/1146090/14202292/b4c428f0-f829-11e5-95b7-d38bcde93476.PNG)

Why?

**Comment by nathandunn** [comment]
What is the command you use to run your flatfile-to-json.pl command? 

Nathan

**Comment by billzt** [comment]
@nathandunn 
```
flatfile-to-json.pl --gff gene.gff --out dir --tracklabel gene --trackType CanvasFeatures --compress
```

**Comment by cmdcolin** [comment]
One workaround could be adding a glyph callback to tell it to not use the default Gene glyph for the genes without subfeatures

     "glyph": "function(feature) { return feature.get('subfeatures') ? 'JBrowse/View/FeatureGlyph/Gene': 'JBrowse/View/FeatureGlyph/Box'; }"

**Comment by cmdcolin** [comment]
I think given the workaround for the issue, it might make sense to just close this :)

If interested feel free to add comments
