### ISSUE TITLE
Error when displaying Chromatin States track

### ISSUE THREAD

**Issue by vegardiv** [GMOD/jbrowse#726]
Getting this error on Araport's website when displaying all 9 Chromatin State tracks:
![chromatin states error](https://cloud.githubusercontent.com/assets/18325790/14346586/317b38ec-fcb3-11e5-8062-53e5d8b25a3c.PNG)

The error appeared after infrastructure upgrade and maintenance was performed on april 5.

**Comment by vegardiv** [comment]
The infrastructure upgrade and maintenance is supposedly done, but this problem remains. Why close the issue?

This only happens when displaying chromatin states and vista plots.

**Comment by vivekkrish** [comment]
Hi @vegardiv , The current repository [GMOD/jbrowse](https://github.com/GMOD/jbrowse) is the parent repo from which the [Araport/jbrowse](https://github.com/Arabidopsis-Information-Portal/jbrowse) has been built. In the future, please report issues in the Araport fork of JBrowse.

Thank you for reporting the issue with the Araport chromatin states tracks. We are aware of it and are working to resolve the problem with our underlying API mediation layer.

Thank you for your patience! Please check back at https://www.araport.org later today for updates on the status.

Vivek @ Araport
