### ISSUE TITLE
Issue with the timeout for global stats estimation

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#727]
I think because of pull request #663, which added a "timeout" for the store calculation, we now have a weird situation where the histograms can show up semi-randomly for the volvox sample

For example, given repeated refreshes of the localhost jbrowse environment on the volvox sample data, the coverage plot on the BAM track seems to show up semi-randomly and instead displays the full list of reads (on Firefox, the stats estimation almost never completes on time, making the large number of reads display always)

![screenshot-localhost 2016-04-07 13-34-06](https://cloud.githubusercontent.com/assets/6511937/14362524/85da4f1a-fcc5-11e5-860a-78bd351e9bfa.png)
![screenshot-localhost 2016-04-07 13-32-39](https://cloud.githubusercontent.com/assets/6511937/14362523/85d9511e-fcc5-11e5-848d-6dff90505be4.png)
Figures: shows the same region just displayed after refreshing twice. I'd expect the histogram to always show up at this zoom level, but the reads get displayed instead

If I add console logging to the GlobalStatsEstimationMixin, then it commonly outputs something like this

    1458ms
    Store statistics timed out: volvox-sorted.bam

That says that since it took more than 500ms to load the stats, then it timed out, which makes it show the raw reads instead of the histogram

It was a little confusing to see this happen, and I think in general, it would be better if this timeout was more configurable.

**Comment by cmdcolin** [comment]
Note that I also think that https://github.com/GMOD/jbrowse/issues/540 is sort of related, and I think that perhaps this helps solve that (it prevents stats estimation from running wild) so it's good that way, but I am wondering if it could be made a little better

**Comment by cmdcolin** [comment]
Pointed to wrong PR number in original post https://github.com/GMOD/jbrowse/pull/663

**Comment by enuggetry** [comment]
Nice catch.  Let's leave the timeout log there in any case.

**Comment by enuggetry** [comment]
should we set the default threshold higher?

**Comment by cmdcolin** [comment]
Increasing the default threshold would help I think. Maybe like 3-5 seconds (configuration is always a nice way to allow different scenarios too)

With regards to #540, another possibility is instead of throwing a hard error during stats estimation (https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Store/SeqFeature/GlobalStatsEstimationMixin.js#L45-L48) about the chunkSizeLimit (which makes track unviewable) then instead do what the timeout does and return a blank stats estimation.
