### ISSUE TITLE
Unable to initialize a custom Name search from a plugin

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse#731]
There is a little issue if you try to create a "name store" from a plugin which is that the "loadNames" milestone comes before the "initPlugins" milestone functions, so a plugin can't implement a custom search.

If you swap the milestone functions it works fine though, hence the PR :)

**Comment by cmdcolin** [comment]
I can't really imagine any effect of switching up the order of the functions here. The code for the Name store seems to imply that it is allowed to be overridden by a plugin, and it was already switched up to put the loadCSS after the initPlugins so that plugins have their own css

It seems to work pretty well too for querying myvariant.info

![screenshot-localhost 2016-04-22 12-23-59](https://cloud.githubusercontent.com/assets/6511937/14749528/8213e08c-0885-11e6-91d1-24a350d0513c.png)

**Comment by enuggetry** [comment]
Looks good.  Thanks.
