### ISSUE TITLE
generate-names.pl stops when 0 is encountered in name field

### ISSUE THREAD

**Issue by uitde007** [GMOD/jbrowse#734]
Hi,
It seems the generate-names.pl script stops generating names when it encounters a 0 as a name field.
In my case, no names were generated after this occurrence: "Alias=OPC-8-0 CoA ligase1,OPC,8,0,CoA". After I removed the ",0," the script executed fine.

**Comment by enuggetry** [comment]
Thanks for reporting this.

**Comment by cmdcolin** [comment]
Not sure if I can reproduce this. I added that Alias string onto a feature on the volvox data and it seemed to load fine and was indexed by generate-names.pl too.

I am kind of wondering if the alias that is written there is in it's intended format in the first place too, maybe it should be url encoded? "Alias=OPC-8-0 CoA ligase1,OPC%2C8%2C0%2CCoA"

**Comment by cmdcolin** [comment]
Maybe this can be closed. Seems to be unreproducible. Feel free to add a test case if it comes up
