### ISSUE TITLE
Custom JBrowse feature glyphs do not work with NeatHTMLFeatures

### ISSUE THREAD

**Issue by thomasvangurp** [GMOD/jbrowse#735]
I've used the "hourglass hgred" features as a subclass to annotate conserved domains in proteins:
![deena_bioinformatics_test_jbrowse_uti_cns_0005289_447339__447721](https://cloud.githubusercontent.com/assets/1284722/14952423/96f00a20-1060-11e6-9a07-c310444b1ff2.jpg)
However, when activating the NeatHTMLFeatures plugin the hourglass tags disappear.
![deena_bioinformatics_test_jbrowse_uti_cns_0005289_447339__447721](https://cloud.githubusercontent.com/assets/1284722/14952473/d1a17154-1060-11e6-98ab-6eddf923e653.jpg)

 Any idea how to fix this? Would it be possible to exclude certain tracks from using the NeatHTMLFeatures plugin?

**Comment by nathandunn** [comment]
I had two thoughts about this:
1. this plugin could be a subclassed track
2. we allow more configuration of the plugin to exclude certain options

I can take a look at the second one.

**Comment by nathandunn** [comment]
3. configure at the track of the plugin level

**Comment by enuggetry** [comment]
I suspect it's probably the gradient function that is causing this.
Thiere is an option to turn off gradients, with gradientFeatures=0.  Then, gradients can be turned ON per track.  This is spelled out in the last half of the readme file.
https://github.com/GMOD/jbrowse/blob/master/plugins/NeatHTMLFeatures/README.md

**Comment by enuggetry** [comment]
What I said there, wasn't quite true, but now it is true.
Introns remain ON all the time, now.
gradientFeatures=0 disable gradient features only.

as of this:
https://github.com/GMOD/jbrowse/commit/85c048a4663378a2e48524a30225799849bcefc3

**Comment by nathandunn** [comment]
I added a related PR: https://github.com/GMOD/jbrowse/pull/737

allows turning off the linear gradient, but is otherwise unchanged.

**Comment by cmdcolin** [comment]
I made some experiments at making neatfeatures a subclassed track type here, something I think @nathandunn referred to above https://github.com/GMOD/jbrowse/tree/track_type_neatfeatures

**Comment by rbuels** [comment]
Since NeatHTMLFeatures is also no longer on by default, this seems like it's probably not a big issue anymore. Closing for now, please reopen if this is still a problem.
