### ISSUE TITLE
Two sets of body tags in index.html

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse#736]
While I suppose this is a relatively minor issue, I imagine it could have varying interpretations by different browsers.  In the current index.html, there are two each of </head>, <body> and </body> tags, which means it is certainly not a valid html document.

**Comment by cmdcolin** [comment]
Yep! Put a fix up here. Probably added around the time of the electron app.

**Comment by enuggetry** [comment]
Thanks.
