### ISSUE TITLE
ssl support for the internal analytics

### ISSUE THREAD

**Issue by childers** [GMOD/jbrowse#739]
Hey all, 
I've gotten a mandate to remove all mixed content errors, and the last one I have is the internal analytics. @cmdcolin noted in the past (https://github.com/GMOD/jbrowse/issues/589) that the code is minified and not really modifiable by us. Can you guys update the internal analytics to support https?

**Comment by nathandunn** [comment]
@childers  We use something similar in Apollo.  Updated insertion script should try to match the protocol you are using.   I think that the Urchin.js file attempts to do something similar.

**Comment by cmdcolin** [comment]
I think #660 fixed this on the jbrowse side? If you are using versions of jbrowse older than 1.12, then you can add the suppressUsageStatistics config to avoid the issue 

http://gmod.org/wiki/JBrowse_Configuration_Guide#Anonymous_Usage_Statistics

On the Apollo side, synchronizing with JBrowse 1.12.2 or similar will be able to fix this

**Comment by nathandunn** [comment]
You would set that here:  https://github.com/GMOD/Apollo/blob/master/build.xml#L116

**Comment by childers** [comment]
That's great. We just got word that all government sites need to conform by the end of the year, and different agencies are adopting different timetables.  For example, ours is much sooner (05/31). We can't roll out Apollo2 before then, and so my plan is to go with the analytics suppression route for the interim. @nathandunn I think I got into trouble with that before.  Will this work on the 1.0.4 release?

**Comment by nathandunn** [comment]
@childers  Only one way to find out ;)     

It should work, but I would double-check the version in jbrowse afterwards just to make sure.

**Comment by childers** [comment]
Oh, I should know if it works pretty fast. We've got some patches for visualizing some data types that will make it obvious if the update sticks.  Thanks for the advice!

**Comment by cmdcolin** [comment]
Seems like this has been addressed as analytics go over https now :)!

**Comment by childers** [comment]
Yay!!
