### ISSUE TITLE
Add Wiggle/XYscatter - like Wiggle/XYPlot

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#740]
Has anyone implemented a variation on XYPlot where only the value is rendered rather than the vertical bar?

At present the best I can do is:

![screen shot 2016-05-09 at 13 42 28](https://cloud.githubusercontent.com/assets/3740323/15113397/e854aa52-15eb-11e6-9f61-1acf760af167.png)

But what I need (i.e. scientist prefers) is the like that available in IGV:

![screen shot 2016-05-09 at 13 41 42](https://cloud.githubusercontent.com/assets/3740323/15113405/f6a17342-15eb-11e6-8c5b-1d6fabb2e709.png)

Thanks,
Keiran

**Comment by nathandunn** [comment]
@keiranmraine  I don't know if anyone has done that, but I think you would do it by modifying this:

https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/WiggleBase.js#L631

I think you can (almost) make the height a consistent pixel height and the "top" will be the height (or canvasHeight-height).    I'm not sure if it would be easier to do upstream, either:  https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/Wiggle/XYPlot.js#L111

You may also be able to set the internal color style as well (potentially an easier solution):

http://gmod.org/wiki/JBrowse_Configuration_Guide#Example_BigWig-based_Wiggle_XY-Plot_Track_Configuration

**Comment by keiranmraine** [comment]
It doesn't look like fill is a modifiable option, the colour of the vertical truncation indicator is, but...

> https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/WiggleBase.js#L631

Thanks for this, I'll give it a try modifying this to set 'height' to a fixed 1-2 px and follow up with the same pixel ratio checks as width has.

If it works I'll see if I expose it as a fill/no-fill config option.

**Comment by keiranmraine** [comment]
Well that went well:

https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/WiggleBase.js#L631

````
630a631,633
> 	if(this.config.dots == true) {
> 		height=1;
> 	}
````

![screen shot 2016-05-13 at 16 01 08](https://cloud.githubusercontent.com/assets/3740323/15252037/0d226dac-1924-11e6-8364-f1514757139b.png)

![screen shot 2016-05-13 at 16 01 29](https://cloud.githubusercontent.com/assets/3740323/15252047/16e16f78-1924-11e6-889d-95688d8e1a3c.png)

![screen shot 2016-05-13 at 16 01 40](https://cloud.githubusercontent.com/assets/3740323/15252052/1b8d8692-1924-11e6-9982-d5548bc10a6a.png)

**Comment by enuggetry** [comment]
+1

**Comment by keiranmraine** [comment]
I suspect this won't work for negative values, just looking and I think the change actually needs to be applied in Wiggle/XYPlot.js as the value to be set to 1, needs to swap between 'top' and 'height':

https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/Wiggle/XYPlot.js#L107-L127

**Comment by keiranmraine** [comment]
See pull req #741 for solution which works for positive and negative values.

**Comment by cmdcolin** [comment]
Should be added to master now!
