### ISSUE TITLE
Update bower packages to latest versions

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#742]
in bower all package names should be lower-case in order to better (or at all) allow caching.

Will have to change the import names possibly to make this happen.

**Comment by cmdcolin** [comment]
I think the packages that are not cached by bower are the ones that do not have proper github tags with semantic versioning.

The biggest packages like dojo, dijit, dojox all have this though, so they are cached nicely.

**Comment by cmdcolin** [comment]
Another thing that could be done though is to sync with the latest FileSaver, jDataView, etc. in bower. They have built in AMD builds so the forks are mostly unnecessary. In the jDataView case, the DataView API changed

**Comment by cmdcolin** [comment]
I mention that because then it is bower install --save file-saver and bower install --save jdataview which are lower case and have proper version tags

**Comment by nathandunn** [comment]
That is what I was imagining.  If there are more up to date / better-supported libraries we should use those.

**Comment by cmdcolin** [comment]
Right. The jDataView api changed significantly though so it is sort of a pain to update that one.

**Comment by cmdcolin** [comment]
The mentions the replace_bower_with_npm branch #873 lots of updated versions (dojo 1.9.8->1.12.2 update, jdataview update, dgrid update, filesaver update, etc)

**Comment by nathandunn** [comment]
This will probably go away with #873.

**Comment by cmdcolin** [comment]
Maybe close in favor of #873 then :)
