### ISSUE TITLE
NeatHTMLFeatures fails to draw intron clearly when zoomed in

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#743]
On zoom, we may need to redraw and add/or additional angle to the intron being drawn.

**Comment by nathandunn** [comment]
![screen shot 2016-05-17 at 10 21 18 am](https://cloud.githubusercontent.com/assets/751274/15332252/bad30a68-1c19-11e6-9260-c36b36a6aab2.png)

**Comment by nathandunn** [comment]
Originally reported as part of: https://github.com/GMOD/Apollo/issues/970

**Comment by nathandunn** [comment]
Tried to addes here: Tried to address here: #754 but had further issues when zoomed out.

**Comment by nathandunn** [comment]
In straight JBrowse, it draws features when zoomed in !?! and they disappear some other times:

<img width="501" alt="screen shot 2016-11-08 at 3 39 39 pm" src="https://cloud.githubusercontent.com/assets/751274/20122030/a7450250-a5c9-11e6-8127-17e0c1103d52.png">
<img width="636" alt="screen shot 2016-11-08 at 3 39 29 pm" src="https://cloud.githubusercontent.com/assets/751274/20122031/a7464638-a5c9-11e6-8564-4b414923d85a.png">
<img width="307" alt="screen shot 2016-11-08 at 3 39 25 pm" src="https://cloud.githubusercontent.com/assets/751274/20122032/a7471c8e-a5c9-11e6-9c45-42aed6b41ee2.png">

**Comment by enuggetry** [comment]
do you mean, when zoomed in, it doesn't draw the introns if it is at the
edge?.
I noticed that just now, since you mentioned it. But I'm not sure I fully
understood your problem.
The problem that I noticed is that introns are drawn between two
subfeatures, but if those subfeatures don't exist beyond the "Block
Regions" ends, then I think it would have a problem.  Just postulating,
here.

**Comment by nathandunn** [comment]
I updated [my comment above](https://github.com/GMOD/jbrowse/issues/743#issuecomment-259294690).  In Apollo-land they just disappear.   They disappear in 3 cases:

1 - you are zoomed in too far into an intron with an exon on both sides
2 - you are zoomed in too far on an exon, but the intron on the right of the exon (for a positive strand) does not appear
3 - same as 2, but a negative strand and to the left of an exon. 

For JBrowse sometimes it disappears and sometimes it is the solid bar (when zoomed in).  

What you should see:
http://jbrowse.org/code/JBrowse-1.12.1/?loc=ctgA%3A14161..23440&tracks=DNA%2CClones&data=sample_data%2Fjson%2Fvolvox&highlight=&tracklist=1&nav=1&overview=1

Disappeared here:

http://jbrowse.org/code/JBrowse-1.12.1/?loc=ctgA%3A17871..19726&tracks=DNA%2CClones&data=sample_data%2Fjson%2Fvolvox&highlight=&tracklist=1&nav=1&overview=1

Normal here:

http://jbrowse.org/code/JBrowse-1.12.1/?loc=ctgA%3A11901..16540&tracks=DNA%2CClones&data=sample_data%2Fjson%2Fvolvox&highlight=&tracklist=1&nav=1&overview=1

Zoom in and you see a solid bar:

http://jbrowse.org/code/JBrowse-1.12.1/?loc=ctgA%3A13293..15148&tracks=DNA%2CClones&data=sample_data%2Fjson%2Fvolvox&highlight=&tracklist=1&nav=1&overview=1

**Comment by enuggetry** [comment]
Try this one and see if it covers all your cases.
[HTMLFeatures.zip](https://github.com/GMOD/jbrowse/files/658623/HTMLFeatures.zip)

**Comment by nathandunn** [comment]
Thanks.  I’ll take a look. 

Nathan
