### ISSUE TITLE
"font-size" property applied to HTML root element affects non-JBrowse elements

### ISSUE THREAD

**Issue by mbomhoff** [GMOD/jbrowse#744]
Classes applied to the HTML root element are causing all elements on page to be resized (such as the CoGe page header) whether or not they are part of JBrowse.  Is it possible to restrict these classes to the JBrowse container element?  See "font-size: 12px" in debugger screenshot.  Thanks for your consideration!

![screen shot 2016-05-19 at 4 36 58 pm](https://cloud.githubusercontent.com/assets/2916502/15412857/1313722c-1de0-11e6-9cbe-81817ff04886.png)

**Comment by cmdcolin** [comment]
The current pull request #844 has a couple of methods to fix that :)

It tries to contain a lot of jbrowse styles better. There were actually two places where font-family was being assigned globally, and I think the pr tries to contain that better now

Feel free to test but there are caveats  like dialog boxes not getting styled right on that branch still

**Comment by mbomhoff** [comment]
Awesome, thanks!
