### ISSUE TITLE
How to disable using cookies in JBrowse

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#746]
I've found that when open JBrowse, it would "remember" last tracks I selected. I didn't want so. How to configure to disable using cookies in JBrowse **in server-side configure**?

**Comment by cmdcolin** [comment]
There is a variable called cookieSizeLimit, perhaps you can set that to zero in the config file

**Comment by cmdcolin** [comment]
Just curious were you seeing "strange" behavior with this? Like where tracks that you may have looked at, but then closed, were then being re-opened when you refreshed the browser?

I saw something like this but wasn't really sure why. It kept happening that several tracks that I was sure that I had closed kept re-opening

**Comment by cmdcolin** [comment]
I am not seeing any other strange behavior that I had mentioned. Anyways, the cookieSizeLimit is a jbrowse config that can be configured to be 0 if you want no cookies to be stored.

Just add cookieSizeLimit=0 to jbrowse.conf :)
