### ISSUE TITLE
Extend Wiggle/XYPlot to support multiple inputs

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#747]
Now we are able to turn off the fill (#740), it would be hugely beneficial if we could draw multiple bigwig datasets on a single XYPlot track.

I realise the biggest problem here would be determining the scaling from multiple datasources but a first implementation requiring fixed min/max would be a good start.

I'm proposing that the existing track definition could be extended to accept string or array for various attributes, the ones that stand out being:

* urlTemplate
* style
    * pos_color
    * neg_color
    * clip_marker_color

e.g.
```js
{
  "label"         : "copynumber",
  "key"           : "CN-Major_minor",
  "storeClass"    : "JBrowse/Store/SeqFeature/BigWig",
  "urlTemplate"   : [ "../tests/data/CN-Major.bigwig",
                      "../tests/data/CN-Minor.bigwig"],
  "type"          : "JBrowse/View/Track/Wiggle/XYPlot",
  "min_score"     : -10,
  "max_score"     : 10,
  "style": {
    "pos_color"         : ["#FFA600", "#000099"],
    "neg_color"         : ["#005EFF", "#CCCCFF"],
    "clip_marker_color" : ["red", "red"],
    "height"            : 100
  },
  "noFill": true
}
```

Can someone familiar with the architecture of the code tell me if this is possible?  If you can give me some pointers which bits of code would need investigation I can have a go.

**Comment by cmdcolin** [comment]
I made a plugin that does something like this. It is able to solve the problem of scaling from multiple datasources issue pretty well I think. It does so by using a custom "store class". It might be possible to make the tracktype to "orchestrate" grabbing multiple bigwigs without writing a custom store, but the custom store makes it pretty easy. The plugin doesn't have 100% functionality of the regular bigwig track mouseovers but maybe that can be fixed https://github.com/cmdcolin/multibigwig

**Comment by keiranmraine** [comment]
Ah, that looks like it may cover what I need. Will give it a go when I get a chance.

**Comment by keiranmraine** [comment]
I'll add the xy scatter style plot to it like in #741, closing this
