### ISSUE TITLE
Error when displaying BigWig files 

### ISSUE THREAD

**Issue by shervas** [GMOD/jbrowse#748]
I am using jbrowse version 1.12.0 to display quantitative data at different zoom scales. Data is in BigWig format. 

I have different estimates at many zoom scales, with windows ranging from 1Kb to 100Kb. There is no problem when trying to visualize 50Kb and 100Kb windows data, however, when I load either 10Kb or 1Kb data, an error appears. The diagnostic message says: #_Error: jDataView length or (byteOffset+length) value is out of bounds_

![screenshot from 2016-05-25 15 36 53](https://cloud.githubusercontent.com/assets/19146296/15541833/8c1d8aa6-228e-11e6-9f57-67eabf5c10a4.png)

I tried many things, but it seems to be an internal problem in BigWig.js or XYplot.js which I don't know how to solve. 
If necessary, I can provide a copy of the reference sequence I am using and a couple of those files which are causing the error.

Any help would be very appreciated! 
Cheers,

Sergi

**Comment by enuggetry** [comment]
Hi Sergi,
Please do share your files and configs.

**Comment by shervas** [comment]
Configs for 2 tracks (50Kb and 10Kb):

_{
   "key" : "RAL_Pi-INDEL_50Kb",
   "type" : "JBrowse/View/Track/Wiggle/XYPlot",
   "urlTemplate" : "../datatest/indels/RAL_Pi-INDEL_50Kb.bw",
   "label" : "RAL_Pi-INDEL_50Kb",
   "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
   "style": {"pos_color":"#A5C0CC", "neg_color":"#CEF0FF"},
   "metadata": {"population":"RAL", "measure":"Pi-INDEL", "continent":"America", "window":"50Kb"}
},
{
   "key" : "RAL_Pi-INDEL_10Kb",
   "type" : "JBrowse/View/Track/Wiggle/XYPlot",
   "urlTemplate" : "../datatest/indels/RAL_Pi-INDEL_10Kb.bw",
   "label" : "RAL_Pi-INDEL_10Kb",
   "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
   "style": {"pos_color":"#A5C0CC", "neg_color":"#CEF0FF"},
   "metadata": {"population":"RAL", "measure":"Pi-INDEL", "continent":"America", "window":"10Kb"}
}_

In the zip file there are the Wig and BigWig files (50Kb & 10Kb) and the wigToBigWig program together with the chrom.sizes file used to create bw files from wig.

[wig_bw.zip](https://github.com/GMOD/jbrowse/files/283692/wig_bw.zip)

Sergi

**Comment by enuggetry** [comment]
Can you provide the refseq too?  thanks.

**Comment by shervas** [comment]
Of course! 

One zip file for each chromosome I am using (as the max size for a single zip attached file is 10Mb).

[ref2L.zip](https://github.com/GMOD/jbrowse/files/286041/ref2L.zip)
[ref2R.zip](https://github.com/GMOD/jbrowse/files/286042/ref2R.zip)
[ref3L.zip](https://github.com/GMOD/jbrowse/files/286043/ref3L.zip)
[ref3R.zip](https://github.com/GMOD/jbrowse/files/286044/ref3R.zip)
[refX.zip](https://github.com/GMOD/jbrowse/files/286045/refX.zip)

Sergi

**Comment by enuggetry** [comment]
I can't seem to reproduce the problem.  Using your config, exactly.
![ice_screenshot_20160527-174923](https://cloud.githubusercontent.com/assets/10053377/15624080/6b4b0f46-2433-11e6-8602-273877f99268.png)

I'm using JBrowse 1.12.1, though. (but, I don't think it should make a difference).

**Comment by shervas** [comment]
Wow... I will reinstall jbrowse, updating to the newest version and try again... Any idea about what can be causing the problem in my browser? I will let you know if the problem magically disappears when reinstalling the software.

Sergi

**Comment by shervas** [comment]
I guess it is a problem of my own browser or java configuration, as I replicated this in another machine and it also works fine... I will have to investigate further, but if you have any idea about what could be causing this error, please let me know.

**Comment by cmdcolin** [comment]
@shervas What internet browser and version are you using?

**Comment by shervas** [comment]
I am using mozilla firefox version 46.0.1.
My Ubuntu system is 14.04 LTS.
I could display the data using exactly the same browser configuration, but on an Ubuntu 16.04 machine. It has also mozilla firefox version 46.0.1.

**Comment by cmdcolin** [comment]
I would doubt that there is anything different between those two. Are you accessing the same jbrowse instance from both machines or are there two different jbrowse installations on each machine?

**Comment by shervas** [comment]
What I did was to copy the entire JBrowse folder to the other machine, place it in /var/www/html and re-run the whole thing (from setup.sh to the complete jbrowse instance). It worked fine and I could visualize all tracks. Then I did the same in another machine which is pretty similar to the first one I was using (same OS and mainly the same software installed) and it didn't work again... 

Maybe there is something I did install in both machines which causes this error, as the machine which worked fine was formatted and Ubuntu was reinstalled just before trying to load jbrowse... Is it possible that something is interfering with jbrowse?

Thanks for replying!

Sergi

**Comment by shervas** [comment]
Solved!! I close the issue.

**Comment by LuisSoares** [comment]
I shervas, I seem to have the same problem you had when trying to load the bigwig file, in principle there is nothing wrong with the file since I can add it as a local file and it loads fine, however the file in the server gives the same error (and from the traffic it seems that jbrowse is actually downloading the entire file in an attempt to display  it). Can you share how you solved your problem?

**Comment by cmdcolin** [comment]
@LuisSoares If it is downloading the entire file, your webserver might not be accepting "Range" HTTP headers. which web server are you using?

**Comment by LuisSoares** [comment]
Thanks for the help cmdcolin! I think you are absolutely right, I was using a simple python flask app to serve the index.html file, I think I will probably have to serve the track files with a different route and extract the range header.

**Comment by shervas** [comment]
Hi Luis, I was actually doing a very stupid mistake. I was trying to load the index.html file to the browser, and had this error. When I wrote the complete path (first using localhost, then with my server's IP) instead of loading the index.html to the browser it worked fine. Hope it helps you!
