### ISSUE TITLE
JBrowse.org latest demos do not seem to be loading?

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#749]
http://jbrowse.org/code/JBrowse-1.12.1/

I get an `Unable to load data/seq/refSeqs.json status: 404`. I'm testing without any adblockers, is this occurring for anyone else?

**Comment by nathandunn** [comment]
@erasche  Also seeing the same thing.

**Comment by cmdcolin** [comment]
This isn't really an error. Anyone who runs jbrowse will see this screen when they run setup.sh properly.

It basically means: "you haven't setup your data directory yet, click on the volvox link for the demo"

Maybe it should just say that :)

**Comment by erasche** [comment]
@cmdcolin you're absolutely right. I could have sworn I followed that link from somewhere. If only I could remember where... sigh. Thanks.
