### ISSUE TITLE
1.12.1 - Faceted track selector widget covers navbar slide left arrow

### ISSUE THREAD

**Issue by Matthias-HDE** [GMOD/jbrowse#751]
Hi guys,

Noticed that in the new maintenance release 1.12.1 the faceted track selector widget covers part of the navigation bar. 
![screen shot 2016-06-01 at 09 52 12](https://cloud.githubusercontent.com/assets/8438493/15702239/277b6df6-27df-11e6-982c-8a56baacd4f8.png)

In previous releases, navigation bar items were centered.

Cheers,

Matthias

**Comment by shervas** [comment]
Hi Matthias,

I fixed this by changing the dojo.js file.To center the navigation bar you have to replace
{id:"navbox",style:{"text-align":"**left**"}} by {id:"navbox",style:{"text-align":"**center**"}}

Hope this helps! 

Sergi

**Comment by cmdcolin** [comment]
Github issues https://github.com/GMOD/jbrowse/pull/723 and
https://github.com/GMOD/jbrowse/pull/680 documented this

The fix shervas provides is appropriate !


-Colin

**Comment by cmdcolin** [comment]
The bug is fixed on the master branch via #723, pending release :)
