### ISSUE TITLE
Dataset selector: UI issue

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#753]
There are a couple of issues with the new new config

1. It's not clear to new users that 'genomes' is a menu.
2. Can the text be overridden in config?

**Comment by vivekkrish** [comment]
Hi @keiranmraine, I believe there is a way to revert the menu to the old style "Track, View, Help", if that is what you prefer. You can see the configuration option documented in the 1.12.0 Release notes (https://jbrowse.org/jbrowse-1-12-0/, under the "Minor Improvements" section) or the JBrowse Config Guide on the Wiki (http://gmod.org/wiki/JBrowse_Configuration_Guide#General_configuration_options).

HTH!

**Comment by vivekkrish** [comment]
And, unfortunately, it looks like the text is currently not overridable in the config. It has to be changed in Browser.js.

**Comment by keiranmraine** [comment]
Hi, I don't want to revert, more a comment on usability.

**Comment by vivekkrish** [comment]
OK, nevermind my original comment then.

To improve the functionality at Araport, we have altered the new menu to pick the name of the "first" occurring dataset and display it in place of the string "Genome" (see [src/JBrowse/Browser.js#L1032-L1052](https://github.com/Arabidopsis-Information-Portal/jbrowse/blob/stable/src/JBrowse/Browser.js#L1032-L1052)). In our case, we generally tend to have only one/primary dataset.

Also, we only show the dataset name if we are injecting a *favicon + link back to our Araport project home* into the menu bar, done using a combination of config in [jbrowse_conf.json](https://github.com/Arabidopsis-Information-Portal/jbrowse/blob/stable/jbrowse_conf.json#L18-L22) plus code changes in [src/JBrowse/Browser.js](https://github.com/Arabidopsis-Information-Portal/jbrowse/blob/stable/src/JBrowse/Browser.js#L991-L999).

**Comment by keiranmraine** [comment]
@vivekkrish , thanks for the suggestions but I see the problem with it not being obvious as a drop-down menu as a _**usability flaw**_ that needs to be fixed.

The ability to have 'genomes' optionally replaced would be considered **_an enhancement_** with either:
* A config defined value, e.g. species+genome
    * Even if you only have one dataset/reference it's good to be clear which one it is.
* The first 'N' characters of the selected dataset name as a nice to have enhancement.

**Comment by keiranmraine** [comment]
Closing as picked up by #761
