### ISSUE TITLE
"Genome" should show the currently selected genome by default

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#761]
"Genome" should show the currently selected genome by default or somewhere on the screen so that a user is always aware of their context.

**Comment by nathandunn** [comment]
Something like this had existed, but it might have been part of our Apollo plugin.

**Comment by nathandunn** [comment]
Brought up as part of https://github.com/GMOD/Apollo/issues/1109 . . but I think that this is the right behavior for JBrowse in general.

**Comment by erasche** [comment]
Noticed this the other day. Pretty unpleasant inside jbrowse inside Galaxy, as you lose the context available from the URL.

**Comment by nathandunn** [comment]
You use the classicMenu option:

http://gmod.org/wiki/JBrowse_Configuration_Guide#General_configuration_options
