### ISSUE TITLE
wiggle track score flags overlapped by other tracks

### ISSUE THREAD

**Issue by sdavey** [GMOD/jbrowse#762]
if you are viewing the scores while mousing over a track based on WiggleBase and there are a lot (10 or more) of scores for a particular place, the flag is drawn below the border and data for the next track down.
<img width="610" alt="screen shot 2016-06-08 at 4 00 48 pm" src="https://cloud.githubusercontent.com/assets/11775142/15913980/38c8226c-2d92-11e6-857a-2ec7cee4d213.png">
This happens because the flag is drawn with position:fixed which makes z-index local to the current stacking context. I think the code will need to be rewritten with position:absolute, possibly outside the track itself.

**Comment by rbuels** [comment]
Is that a JBrowse multi-wiggle plugin you're using there?  This seems like an issue with that plugin.

**Comment by rbuels** [comment]
@cmdcolin do you recognize that screenshot?

**Comment by cmdcolin** [comment]
I believe it's a custom "multiwiggle" track developed at CoGe

**Comment by cmdcolin** [comment]
Maybe located here https://github.com/LyonsLab/CoGe_plugin/blob/master/js/View/Track/Wiggle/XYPlot.js

**Comment by rbuels** [comment]
closing, since looks like an issue with CoGe_plugin.  perhaps report it over there?
