### ISSUE TITLE
REST tracks need to be updatable

### ISSUE THREAD

**Issue by sdavey** [GMOD/jbrowse#763]
an issue has arisen where the data associated with one of our REST based tracks can be modified after it has been shown, so we'd like to be able to trigger a reload of the data for the track. I tried to hide/show and also delete/new, but the data seems to be cached. Is there already a way to have JBrowse refetch the data for a track? Or, if not, can one be added?

**Comment by vivekkrish** [comment]
Hi @sdavey ,
If you look at this section of code, [JBrowse/Store/SeqFeature/REST.js#L81-L87](https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Store/SeqFeature/REST.js#L81-L87), you will notice a config option called `noCache`, which is set to `false` by default. Adjusting this might help with your situation. However, this means that the REST retrieved track data will never be cached.

Regarding the other config option, `feature_range_cache`, [this snippet of release notes](https://github.com/GMOD/jbrowse/blob/23fbf1be1a2a3cd7204740a494a694dc4a424560/release-notes.txt#L832-L835) from v1.8.0 describes its function.

Hope this helps!

Thank you.

**Comment by sdavey** [comment]
Hi Vivek,
thanks! setting hiding the track, setting noCache to true, showing the track and then setting noCache back to false does the trick.
sean

**Comment by sdavey** [comment]
oops, I spoke too soon. There is still caching going on, even with noCache set to true. Here's the code that I eventually got to work:

				store.browser.publish('/jbrowse/v1/v/tracks/hide', [config]);
				var cache = store._getCache();
				cache._prune(cache.maxSize);
				store.config.noCache = true;
				store.config.feature_range_cache = false;
				store.browser.publish('/jbrowse/v1/v/tracks/show', [config]);
				store.config.noCache = false;
				store.config.feature_range_cache = true;
