### ISSUE TITLE
add a button or menu item to reset view to default tracks

### ISSUE THREAD

**Issue by kkarra** [GMOD/jbrowse#764]
Currently the only way I know to get back to 'default tracks' is clear cache in browser. If there is no other easier way to do this, I would like to request to add this as a feature in 'My Tracks' section in track selector.
Thanks

**Comment by rbuels** [comment]
Perhaps we could add an item to the "View" dropdown menu called "Reset to defaults" that would bring the view's location back to the default, select only the default tracks, and order the tracks in the default order?
