### ISSUE TITLE
In 'view details', jbrowse only deplayed the name of fasta file, but without the sequence

### ISSUE THREAD

**Issue by meihl** [GMOD/jbrowse#765]
My genome sequence is loaded like this:
      {
         "urlTemplateFAI" : "seq/all.fa.fai",
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "urlTemplate" : "seq/all.fa",
         "label" : "msu_genome",
         "type" : "SequenceTrack",
         "category" : "A.Reference Genome Sequence",
         "key" : "MSU_Rice_Genome_Annotation_Project_Release_7"
      },
GFF3 file is loaded like this:
{
         "style" : {
            "className" : "feature2",
            "color" : "#DF255A"
         },
         "key" : "Gene Structure details",
         "useAsRefSeqStore" : true,
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : "CanvasFeatures",
         "urlTemplate" : "tracks/msu_gene_model/{refseq}/trackData.json",
         "compress" : 0,
         "category" : "B.Gene Annotation",
         "type" : "CanvasFeatures",
         "label" : "msu_gene_model"
      },
In the "view detail" diaglog, but it only displayed the name or ID of the fasta, but no sequence:
![image](https://cloud.githubusercontent.com/assets/6195322/16073920/b193e5ae-331a-11e6-8227-97ddcb08e19d.png)

I have already added "useAsRefSeqStore": true to the config, but there still is no sequence, why?
I am really appreciated for your help. Thank you very much!

**Comment by cmdcolin** [comment]
You can put the attribute "useAsRefSeqStore" : true on the fasta track instead of the GFF track to fix this :)

**Comment by meihl** [comment]
Oh, yes! It really works. Thank you very much!
