### ISSUE TITLE
classicMenu should not revert the File / Track name

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#766]
classicMenu should not revert the File / Track name.  

I definitely appreciate being able to revert to the classic Menu for organisms.   However, I can't find a good use-case for keeping "File" the same instead of moving to "Track".  

Related to: https://github.com/GMOD/Apollo/issues/1133

Any thoughts @enuggetry  @ihh  @cmdcolin  ?

**Comment by cmdcolin** [comment]
I think that the classicMenu option should basically look like the pre-1.12 menu, so I'd prefer not changing that:)

Maybe the thing that might be desired is to re-enable putting the organism name/dataset selector on the menu bar (or somewhere) in the default implementation.

**Comment by keiranmraine** [comment]
👍  for being able to display selected dataset.

**Comment by rbuels** [comment]
Hmm, after looking at it further, I think `classicMenu` should mean classic menu, i.e. keep the menu the same as it was before 1.12.0, which is what the switch currently does. Closing.
