### ISSUE TITLE
Put selected genome name on the right of the menu in the bar.

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#767]
Ref: #766 

Since the genome name needs a home, I propose it be placed to the right of the menu within the menu bar, since we have a little space there.

**Comment by cmdcolin** [comment]
This one would be great to solve. I guess I kind of feel like the classicMenu layout is an ideal layout for most jbrowse installations (i.e. the <1.11 branch menu)

We have the classicMenu option to enable 1.11 style menus which includes the genome name on the menu bar if the dataset selector is configured. Potentially could make it even easier and enable it without dataset selector configured.
