### ISSUE TITLE
List plugins in the About Box

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#768]
Currently plugins spit out a console message.  I propose listing the plugins in the about box.

**Comment by erasche** [comment]
:+1:

**Comment by colindaven** [comment]
Good idea, especially as plugins are multiplying fast

**Comment by cmdcolin** [comment]
I had made a simple demo of that here https://github.com/GMOD/jbrowse/tree/list_plugins_about_box

could make a PR :)

**Comment by enuggetry** [comment]
sure.  thanks!

**Comment by cmdcolin** [comment]
Should be fixed by #848 :)
