### ISSUE TITLE
Highlight with negative start value prevent JBrowse loading.

### ISSUE THREAD

**Issue by h2akim** [GMOD/jbrowse#769]
I have tested this problem when highlight using highlight from middle to start. Difficulty to precisely set the highlight to 0 would force user to highlight all the way before 0 coordinate (negative value).

Returning back to the URL with highlight parameter including start coordinate with negative value prevent JBrowse from loading at all.

http://jbrowse.org/code/JBrowse-1.12.1/?loc=ctgA%3A1..22607&tracks=DNA%2CTranscript%2Cvolvox-sorted-vcf%2Cvolvox-sorted_bam%2Cvolvox_microarray_bw_xyplot%2Cvolvox_microarray_bw_density&data=sample_data%2Fjson%2Fvolvox&highlight=ctgA%3A-1140..1241

Suggestion: Force the highlight to reset to 0 when highlight start is below 0 value. I've tried to fix on the source, currently no luck. 

Thanks :)

**Comment by cmdcolin** [comment]
I think this patch can fix it. It just fixes the regex that is used to parse the location 

```
diff --git a/src/JBrowse/Util.js b/src/JBrowse/Util.js
index fd1841b..3e5133c 100644
--- a/src/JBrowse/Util.js
+++ b/src/JBrowse/Util.js
@@ -296,7 +296,7 @@ Util = {
             locstring = tokens[1];
         }
 
-        tokens = locstring.match( /^\s*([\d,]+)\s*\.\.+\s*([\d,]+)/ );
+        tokens = locstring.match( /^\s*([-\d,]+)\s*\.\.+\s*([-\d,]+)/ );
         if( tokens ) { // range of two numbers?
             location.start = parseCoord( tokens[1] )-1;

```

**Comment by cmdcolin** [comment]
Either a patch like that could be used or just something more general that catches the case where the regex fails

**Comment by h2akim** [comment]
Seems now JBrowse force negative number to re-set to 1. I close the issue.

**Comment by cmdcolin** [comment]
@h2akim I think it's a real bug

It affects the &highlight= but it doesn't affect &loc=

See following link

http://jbrowse.org/code/JBrowse-1.12.1/?data=sample_data/json/volvox&highlight=ctgA:-1:100
