### ISSUE TITLE
could not load reference sequence defenitions. RequestError: Unable to load data/seq/refseqs.jason status: 404.

### ISSUE THREAD

**Issue by viv3kanand** [GMOD/jbrowse#770]
I tried to load a Grch38 version genome file in Jbrowse as mentioned in the tutorials, and this error pops up.
"could not load reference sequence defenitions. RequestError: Unable to load data/seq/refseqs.jason status: 404."
![jbrowse](https://cloud.githubusercontent.com/assets/7590787/16297857/3ca0ff20-3950-11e6-911b-c636cfa4d622.jpg)

**Comment by cmdcolin** [comment]
There is a FAQ entry regarding this here!

http://gmod.org/wiki/JBrowse_FAQ#I_see_a_message_that_says_.22Congratulations.2C_JBrowse_is_on_the_web.22_but_I_don.27t_see_my_genome


Let me know if that helps

**Comment by viv3kanand** [comment]
The sample data of Volvox works perfectly for me. The 'data' directory is inside the 'bin' directory where the perl scripts are. Is that possibiliy a problem behind this issue?

**Comment by viv3kanand** [comment]
It worked. I moved the 'data' directory to root directory. Thank you for the help.

**Comment by cmdcolin** [comment]
cool! we'll close for now then :)
