### ISSUE TITLE
Chado config unsecure

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#773]
http://gmod.org/wiki/JBrowse_Configuration_Guide#Using_JBrowse_with_Existing_Databases

The Chado adapter could perhaps be moved to the back end to secure the auth credentials.

**Comment by erasche** [comment]
Is that provided to the client? I could have sworn when I used that last it was only on the backend.

**Comment by enuggetry** [comment]
oops, sorry, thought it was a tracklist.json config.
