### ISSUE TITLE
How to make the Available Tracks and Select Tracks co-exist?

### ISSUE THREAD

**Issue by meihl** [GMOD/jbrowse#775]
The normal Jbrowse display is like this:
![image](https://cloud.githubusercontent.com/assets/6195322/16480596/97e7c830-3ed9-11e6-8696-8ac513a84ee2.png)
But after I set the faceted track selector in jbrowse.conf, Jbrowse is displaying like this:
![image](https://cloud.githubusercontent.com/assets/6195322/16480664/fe34b7c4-3ed9-11e6-93a9-f1674e618238.png)
The normal Jbrowse available tracks is disappeared, but only the select tracks.
My jbrowse.conf is modified as below:
[trackSelector]
type = Faceted
displayColumns=label
displayColumns+=key
[trackSelector.renameFacets]
submission = Submission ID
developmental-stage = Conditions
There must be errors in my setting. Could some help me? I really appreciate your response. Thank you!

**Comment by cmdcolin** [comment]
Are you saying that there are tracks that have disappeared once you use the faceted track selector?

**Comment by cmdcolin** [comment]
Or if you want to have both the faceted and the heirarchical track selectors enabled at the same time, then you might consider this plugin called ComboTrackSelector https://github.com/Arabidopsis-Information-Portal/jbrowse/tree/stable/plugins/ComboTrackSelector

@vivekkrish did a presentation on it http://www.slideshare.net/vivekkrish/jbrowse-within-the-arabidopsis-information-portal

**Comment by meihl** [comment]
Yes, I want to the faceted and the hierarchical track selectors enabled at the same time. I have tried to install plugin called ComboTrackSelector, but unfortunately I failed for there was no detail information about the Plugin. Still, I really appreciate your response. Thank you very much!

**Comment by vivekkrish** [comment]
Hi @meihl , We have updated the ComboTrackSelector repo with a README file explaining how the plugin can be configured to work with JBrowse. Please see: https://github.com/Arabidopsis-Information-Portal/ComboTrackSelector

Comments/suggestions welcome!

Thank you.

**Comment by meihl** [comment]
Hi @vivekkrish. I have seen that. I really appreciat your guide. Thanks a lot!

**Comment by cmdcolin** [comment]
Hopefully that plugin helps. I suppose convo can be continued there if there are further issues
