### ISSUE TITLE
Left click behavior do not work

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#784]
Hi,

When I configure the gff track, the "onClick" option do not work.

"onClick": {
                "action": "newWindow", 
                "url": "function(track,feature,div) { return 'http://www.ncbi.nlm.nih.gov/gquery/?term='+this.feature.get('name'); }", 
                "label": "Search for gene in database"
            }

When I click on gene, it seems that this.feature.get('name') returns nothing.

Thank you for your help!

**Comment by cmdcolin** [comment]
Do the genes themselves might not have a "Name" field in your gff? You could just try this.feature.get('id') too

**Comment by verne91** [comment]
@cmdcolin 
My gff file don't have a "Name" field, but have a "ID" field. 

chr01   irgsp1_rep      gene    2983    10815   .       +       .       ID=Os01g0100100

However, After I tried this.feature.get('ID'), it still seems the click do not work.
And the config file of this track missed "url" within "onClick".

"onClick": {
    "action": "newWindow",
    "label": "Search for gene in database"
  },

**Comment by verne91** [comment]
When I change the "ID" to "id", it works.
Thank you!

**Comment by cmdcolin** [comment]
Good to hear.

Here is some "documentation" about the feature.get functions in case that helps! http://gmod.org/wiki/JBrowse_FAQ#How_do_I_access_data_about_my_features_in_my_callback_or_plugin
