### ISSUE TITLE
add hooks to hide / replace sequence drop-down

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#786]
I'd like to be able to not show this, or configure it so that its more useful.   Right now I'm doing this in a plugin, but if fires after its already been displayed. 

<img width="690" alt="screen shot 2016-07-13 at 10 40 42 am" src="https://cloud.githubusercontent.com/assets/751274/16813436/4a96bf98-48e6-11e6-946a-19c0f6467266.png">

**Comment by enuggetry** [comment]
In what way could it be more useful?

**Comment by nathandunn** [comment]
From my email to you: 

> In the case of the drop-down of sequences, I think having a way to change that (including remove it) would be great.   Its great for a last visited, but there is no way to easily filter that list or make the largest scaffolds appear first (or use some other sorting / filtering mechanism).   A lot could be done there even for regular JBrowse users (though we definitely need this for Apollo.

**Comment by nathandunn** [comment]
To clarify only a set small set of chromosomes the drop down is great, but many of our users have several hundred scaffolds, most of them fragments.   Would be awesome to retool that with favorites, recently visited or a combo box to allow searching and viewing the entire set at once.

**Comment by nathandunn** [comment]
Done in 4a0ae4f9ad63cf8746c19c1cba9ee73b3c8482e2
