### ISSUE TITLE
Clear all tracks with one click?

### ISSUE THREAD

**Issue by KelvinLu1024** [GMOD/jbrowse#790]
How can I add a button in the toolbar of JBrowse which removes all selected tracks when clicked?

**Comment by cmdcolin** [comment]
The hierarchical track selector (i.e. the default one) can enable a function similar to this with the help of this plugin

https://github.com/bhofmei/jbplugin-hierarchicalcheckbox

The faceted track selector has the ability to select and de-select multiple tracks with shift-click by default, so it can do this without modification.

Would those be able to solve the problem?

**Comment by colindaven** [comment]
Hi,
thanks for this, this plugin is helpful.
Colin

**Comment by billzt** [comment]
https://github.com/bhofmei/jbplugin-hierarchicalcheckbox works well

**Comment by cmdcolin** [comment]
is there still interest in this? it seems sort of niche so maybe close for now
