### ISSUE TITLE
wig-to-json --bgcolor option not working

### ISSUE THREAD

**Issue by LuisSoares** [GMOD/jbrowse#791]
I'm using JBrowse-1.12.1 and by reasons I cannot avoid I cannot use the direct access to bigwig files implementation, so I am relying on the old wig-to-json.pl script to create the image tracks, my problem is that while the --fgcolor option works fine, using --bgcolor is not working, the script doesn't fail but the images are generated without background color.

**Comment by cmdcolin** [comment]
I'd suggest using the direct access to bigwig if at all possible. For example, if the reason for not using it regards not being able to do HTTP Range request handling, there might be some workaround (previous discussion https://github.com/GMOD/jbrowse/issues/748#issuecomment-232731616)

It does look like the bgcolor option might not really do anything though
