### ISSUE TITLE
dijit widgets

### ISSUE THREAD

**Issue by bhofmei** [GMOD/jbrowse#796]
I've been creating plugins for JBrowse and taking advantage of dojo and dijit. There seems to be quite a few of the dijit elements missing from JBrowse's build of dojo. Can more be added in future versions? Specifically, I want to use more layout features, like AccordianContainer and BorderContainer. I also wanted to use a HorizontalSlider, which is missing.
I've thought about including the source code directly with the plugin, but seems silly since so much code would be duplicated.

**Comment by cmdcolin** [comment]
There are some notes about handling this situation here http://gmod.org/wiki/JBrowse_Configuration_Guide#Plugin_build_notes

JBrowse "release" builds will prune away unneeded libraries, which is what you are probably seeing

To fix it, you can create a build of your plugin which will automatically package those libraries packaged into your plugin only. Basically, the easiest way to do that is to clone jbrowse from github, then run " make -f build/Makefile release-notest" with your plugin in the plugins folder. Then the resulting "build" will contain your plugin with the extra dojo libraries packaged inside it.

**Comment by bhofmei** [comment]
Awesome thanks!
