### ISSUE TITLE
Documentation:  Read coloring

### ISSUE THREAD

**Issue by jorvis** [GMOD/jbrowse#797]
Could someone please add (or point me to) any documentation explaining the various colorings of the read glyphs within BAM file displays?  For example, what is the significance of black reads?

**Comment by cmdcolin** [comment]
Here is some documentation http://gmod.org/wiki/JBrowse_Configuration_Guide#Alignments2_coloring_schemes


There isn't really the equivalent of a "legend" though you can add custom content to the "About this track" dialogs http://gmod.org/wiki/JBrowse_FAQ#How_do_I_add_a_legend_to_the_track_in_the_.22About_this_track.22_dialog.3F

**Comment by cmdcolin** [comment]
If no other issues maybe this can be closed :)

**Comment by cmdcolin** [comment]
Note that it matches the default colors in IGV too
