### ISSUE TITLE
Will 1.12.2 be released properly?

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#799]
1.12.2 is marked as pre-release and not on jbrowse.org.  Is there a reason to not use this version outside of Apollo?

**Comment by nathandunn** [comment]
It should be fine outside of Apollo.   We just wanted to make sure that, for Apollo purposes, we had a consistent version to test against.  This version has been well-tested for Apollo, but I'm not sure what additional steps JBrowse does for an official release.

**Comment by nathandunn** [comment]
I think they are going to do a 1.12.3 but @enuggetry  can confirm.

**Comment by keiranmraine** [comment]
That would be great there's lots of pending pull requests with good functionality.  I ask as I'm doing a ground up re-build of our server and configuration and it would be good to get the new features.

Could you tell me if should I worry about warnings like this when building (I'm trying to test bgzip fasta using master):

```
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojox/mobile/TimePicker; plugin: dojox/mobile/_PickerChooser
warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: dojo-bidi?dojox/mobile/bidi/ToolBarButton; reference module id: dojox/mobile/ToolBarButton
```

**Comment by nathandunn** [comment]
I am no expert here, but I think you can probably ignore them:

https://bugs.dojotoolkit.org/ticket/15903
