### ISSUE TITLE
help setting scoreType for BigWig tracks

### ISSUE THREAD

**Issue by childers** [GMOD/jbrowse#801]
Where do you set scoreType in the configuration?  Adding it to the style section does nothing and adding it to the base causes nothing to appear (yikes!) whihc makes me wonder if I am doing something badly wrong.  I was looking for it in the configuration guide, did find a reference to it, but my implementation is not working.

I am testing Apollo 2.0.4 which (I think) defaults to JBrowse 1.12.1 based on release-notes.txt.

Any advice would be greatly appreciated!

Here is a sample stanza from my trackList.json file that results in a blank track.  Removing the line causes the bigwig to display a maxValue type score.
```shell
      {  
         "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
         "urlTemplate" : "bigwig/Edan07162013.scaffolds_GC.bigwig",
         "style" : {
            "neg_color" : "rgba(255,255,0,50)",
            "pos_color" : "rgba(0,0,255,50)"
         },
         "label" : "GC Content",
         "type" : "JBrowse/View/Track/Wiggle/Density",
         "bicolor_pivot" : "0.5",
         "category" : "0. Reference Assembly",
         "key" : "GC Content",
         "scoreType":"avgValue",
         "autoscale" : "local"
      }
```

**Comment by cmdcolin** [comment]
you have it set in the right place but it should be `avgScore` instead of `avgValue`. after that I think the algorithm that @hotdogee made should be applied

**Comment by childers** [comment]
Sorry, my typo.. It should be:
```         "scoreType":"avgScore",```
It was updated since the release notes.

**Comment by childers** [comment]
@cmdcolin You're right, it is correct in the configuration guide, but was named differently in the release notes, website and github issues that came before it.

**Comment by cmdcolin** [comment]
interesting. thanks for catching :)

**Comment by childers** [comment]
I know it took a while, but I am so glad this got rolled into the main codebase!  Thanks again for pulling it in.
