### ISSUE TITLE
IndexedFasta doesn't set useAsRefSeqStore

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#804]
It appears that using the IndexedFasta store doesn't make the sequence available for access with:

```js
thisB.browser.getStore('refseqs', function(refSeqStore) {});
```

Setting the following option in the track config solves it but I'm assuming this should default automatically:

```js
{  ...,
  "useAsRefSeqStore" : "true"
}
```

**Comment by cmdcolin** [comment]
The prepare-refseqs.pl on master branch should have this fixed, updated here

https://github.com/GMOD/jbrowse/commit/7a6af9f37d9dcb591a834174248f5f4e4140c1be


also reported here https://github.com/GMOD/jbrowse/issues/719

**Comment by billzt** [comment]
Well, this is because JBrowse hasn't released a new version for a long time~

**Comment by nathandunn** [comment]
You can use the [1.12.2-apollo](https://github.com/GMOD/jbrowse/releases/tag/1.12.2-apollo) release which should have that fix in it or master.   We have quite a few users using it that haven't reported any issues, but I doubt they are flexing everything that JBrowse does.  Most likely master should be fine (if not, report it).

**Comment by keiranmraine** [comment]
I was working from master, but the config stanza I have has `urlTemplateFAI`, not `faiUrlTemplate`.  Probably due to getting it to work on the old configuration before it was modified as indicated by @cmdcolin

**Comment by keiranmraine** [comment]
Hmm, this works:

```js
      {
         "label" : "DNA",
         "urlTemplateFAI" : "seq/human_37.fa.fai",
         "showTranslation" : false,
         "showReverseStrand" : false,
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "type" : "SequenceTrack",
         "key" : "Reference sequence",
         "category" : "Reference sequence",
         "urlTemplate" : "seq/human_37.fa",
         "useAsRefSeqStore" : "true"
      },
```

This doesn't:
```js
      {
         "label" : "DNA",
         "faiUrlTemplate" : "seq/human_37.fa.fai",
         "showTranslation" : false,
         "showReverseStrand" : false,
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "type" : "SequenceTrack",
         "key" : "Reference sequence",
         "category" : "Reference sequence",
         "urlTemplate" : "seq/human_37.fa"
      }
```

What am I missing (and I've double checked I'm on master)?

**Comment by cmdcolin** [comment]
The below one does not have useAsRefSeqStore set. If you use the prepare-refseqs.pl on master I believe it would have outputted this property

**Comment by cmdcolin** [comment]
Should be fixed on master
