### ISSUE TITLE
ignore dnd/drop when copy is true

### ISSUE THREAD

**Issue by sdavey** [GMOD/jbrowse#806]
in src/JBrowse/GenomeView.js there is a subscription to dnd/drop currently on line 230. Could you please add

if (copy) return;

to the beginning of the function? We would like to use the drag and drop of tracks for a new purpose other than rearranging tracks. To do this we're checking for "copy" which is set when the Command/Ctrl key is held down before the drop. The current JBrowse function rearranges the tracks regardless of the value of copy. If you could please add the check and return then the tracks wouldn't be rearranged for our new use of drag and drop.

thanks,
  sean

**Comment by enuggetry** [comment]
I'll give it a try before next release.

**Comment by cmdcolin** [comment]
The line number may have been changed since this posting. Would it go before or after updateTrackList?

**Comment by cmdcolin** [comment]
Might use the "git diff" format to suggest patches as these provide context for the patch :)

**Comment by rbuels** [comment]
Is this still needed? Closing for now, reopen if this is still an issue.
