### ISSUE TITLE
How to remove the FASTA Box from Details View?

### ISSUE THREAD

**Issue by Rhinogradentia** [GMOD/jbrowse#808]
Hi There!

because I just wan't to show some homologous region I want to remove the Fasta/Sequence View from the "View Details" Menu. I've already tried following:

"fmtDetailValue_fastaView": "function(fastaView) { return null;}"
"fmtDetailValue_feature_sequence": "function(feature_sequence) { return null;}"
"fmtDetailValue_feature_sequence0": "function(feature_sequence0) { return null;}"
"fmtDetailValue_fasta": "function(fasta) { return null;}"

But nothing worked out. Maybe someone could help me with this? That would be really great!
Best Regards,
Nadine

**Comment by cmdcolin** [comment]
You might be able to set maxFeatureSizeForUnderlyingRefSeq to zero for the track in the config. It should work but will basically display a little box saying the sequence isn't being loaded. It might be nice if the fmt functions did that though
![screenshot_20160914-111242](https://cloud.githubusercontent.com/assets/6511937/18517974/3cb9a73e-7a6c-11e6-8b34-e9092d91821d.png)

**Comment by Rhinogradentia** [comment]
That was very helpful - Thank you!

This is good for now, but it would be great if the details view could be configurated a little bit more, in the sense that parts of it could be turned on and off. 

Best Regards,

Nadine

**Comment by cmdcolin** [comment]
Agree. Maybe we can close for now yhough. There are a couple other open issues with similar customizations requested
