### ISSUE TITLE
Feature not displayed in full length at certain zoom

### ISSUE THREAD

**Issue by Rhinogradentia** [GMOD/jbrowse#809]
I've stumbled upon a display problem with a CanvasFeatures track regarding the displayed length of a feature. The feature is contained in a summary track and as a single track. The single track is displayed correctly at any zoom level, but the summary track cuts the feature at a certain point - not the same zoom level for every feature though. It appears that only entries from a certain length and higher are affected, shorter ones do not show any problem. The features which are affected are UTRs. The direction arrow can't be seen as well.

I've attached some cases as screen shots to visualize the problem:
Example 1:
![zoomout2](https://cloud.githubusercontent.com/assets/12270382/18506827/feb5009e-7a6d-11e6-953e-77998aaaca75.png)
![zoomin2](https://cloud.githubusercontent.com/assets/12270382/18506830/026cc2a8-7a6e-11e6-876e-e7ab11fe22b7.png)

Example 2:
![zoomout3](https://cloud.githubusercontent.com/assets/12270382/18506839/06fbbc8e-7a6e-11e6-8be8-88cd01af1fcb.png)
![zoomin3](https://cloud.githubusercontent.com/assets/12270382/18506842/0a194120-7a6e-11e6-83aa-0dbbd45b7384.png)

The entry in trackList.json is like this:

{
         "trackType" : "JBrowse/View/Track/CanvasFeatures",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "type" : "JBrowse/View/Track/CanvasFeatures",
         "key" : "CBS7435 Gene & regul. Elements",
         "fmtDetailField_Subfeature" : "function(subfeature){return null;}",
         "label" : "cbs7435_gene_2",
         "compress" : 0,
         "urlTemplate" : "tracks/cbs7435_gene_2/{refseq}/trackData.json",
         "fmtDetailValue_Dbxref" : {_[some content here]_}
         "category" : "2. Features/1. Coding Features",
         "fmtDetailValue_Name" : "function(name){ _[some content here]_}"
      },

I've also tried it with different browsers to exclude this as a source of the problem.

Would be great I this could be corrected at some point.
Best Regards,
Nadine

**Comment by cmdcolin** [comment]
If you have a snippet of the gff file in that area it might help

**Comment by Rhinogradentia** [comment]
For example 1 the gff is like this:

```
cbs7435_chr4	GenBank	gene	238899	240890	.	+	.	ID=PP7435_Chr4-0130;Name=PP7435_Chr4-0130;Note=AOX1;Gene=AOX1;locus_tag=PP7435_Chr4-0130;protein_sequence=MAIPEEFDILVLGGGSSGSCIAGRLANLDHSLKVGLIEAGENNLNNPWVYLPGIYPRNMKLDSKTASFYTSNPSPHLNGRRAIVPCANVLGGGSSINFMMYTRGSASDYDDFQAEGWKTKDLLPLMKKTETYQRACNNPDIHGFEGPIKVSFGNYTYPVCQDFLRASESQGIPYVDDLEDLVTAHGAEHWLKWINRDTGRRSDSAHAFVHSTMRNHDNLYLICNTKVDKIIVEDGRAAAVRTVPSKPLNPKKPSHKIYRARKQIVLSCGTISSPLVLQRSGFGDPIKLRAAGVKPLVNLPGVGRNFQDHYCFFSPYRIKPQYESFDDFVRGDAEIQKRVFDQWYANGTGPLATNGIEAGVKIRPTPEELSQMDESFQEGYREYFEDKPDKPVMHYSIIAGFFGDHTKIPPGKYMTMFHFLEYPFSRGSIHITSPDPYAAPDFDPGFMNDERDMAPMVWAYKKSRETARRMDHFAGEVTSHHPLFPYSSEARALEMDLETSNAYGGPLNLSAGLAHGSWTQPLKKPTAKNEGHVTSNQVELHPDIEYDEEDDKAIENYIREHTETTWHCLGTCSIGPREGSKIVKWGGVLDHRSNVYGVKGLKVGDLSVCPDNVGCNTYTTALLIGEKTATLVGEDLGYSGEALDMTVPQFKLGTYEKTGLARF*
cbs7435_chr4	GenBank	mRNA	238899	240890	.	+	.	ID=PP7435_Chr4-0130.t01;Name=PP7435_Chr4-0130.t01;Parent=PP7435_Chr4-0130;locus_tag=PP7435_Chr4-0130;Note=AOX1
cbs7435_chr4	GenBank	CDS	238899	240890	.	+	0	ID=PP7435_Chr4-0130.p01;Name=PP7435_Chr4-0130.p01;Parent=PP7435_Chr4-0130.t01;gene=AOX1;Note=AOX1;Dbxref=GI:328353908,GOA:F2QY27,InterPro:IPR000172,InterPro:IPR007867,InterPro:IPR012132;codon_start=1;eC_number=1.1.3.13;protein_id=CCA40305.1;product=Alcohol oxidase variant 1;translation=length.663;function=oxidation of methanol into formaldehyde and H2O2;locus_tag=PP7435_Chr4-0130;protein_sequence=MAIPEEFDILVLGGGSSGSCIAGRLANLDHSLKVGLIEAGENNLNNPWVYLPGIYPRNMKLDSKTASFYTSNPSPHLNGRRAIVPCANVLGGGSSINFMMYTRGSASDYDDFQAEGWKTKDLLPLMKKTETYQRACNNPDIHGFEGPIKVSFGNYTYPVCQDFLRASESQGIPYVDDLEDLVTAHGAEHWLKWINRDTGRRSDSAHAFVHSTMRNHDNLYLICNTKVDKIIVEDGRAAAVRTVPSKPLNPKKPSHKIYRARKQIVLSCGTISSPLVLQRSGFGDPIKLRAAGVKPLVNLPGVGRNFQDHYCFFSPYRIKPQYESFDDFVRGDAEIQKRVFDQWYANGTGPLATNGIEAGVKIRPTPEELSQMDESFQEGYREYFEDKPDKPVMHYSIIAGFFGDHTKIPPGKYMTMFHFLEYPFSRGSIHITSPDPYAAPDFDPGFMNDERDMAPMVWAYKKSRETARRMDHFAGEVTSHHPLFPYSSEARALEMDLETSNAYGGPLNLSAGLAHGSWTQPLKKPTAKNEGHVTSNQVELHPDIEYDEEDDKAIENYIREHTETTWHCLGTCSIGPREGSKIVKWGGVLDHRSNVYGVKGLKVGDLSVCPDNVGCNTYTTALLIGEKTATLVGEDLGYSGEALDMTVPQFKLGTYEKTGLARF*
cbs7435_chr4	GenBank	exon	238899	240890	.	+	.	Parent=PP7435_Chr4-0130.t01;locus_tag=PP7435_Chr4-0130
cbs7435_chr4	Cufflinks	three_prime_UTR	240891	240967	.	+	.	Parent=PP7435_Chr4-0130;Name=PP7435_Chr4-0130_3-UTR;Note=PP7435_Chr4-0130_3-UTR;length=77
```

The gff for Example 2 is like this:

```
cbs7435_chr4	Cufflinks	five_prime_UTR	245544	245586	.	+	.	Parent=PP7435_Chr4-0135;Name=PP7435_Chr4-0135_5-UTR;Note=PP7435_Chr4-0135_5-UTR;length=43
cbs7435_chr4	GenBank	gene	245587	247932	.	+	.	ID=PP7435_Chr4-0135;Name=PP7435_Chr4-0135;Note=NTH1;Gene=NTH1;locus_tag=PP7435_Chr4-0135;protein_sequence=MQDGNAIERPHSVAVDVPDGLQQPHHTRTFSTGSNSGFIDPFSEPSQYYGPATDIARASTRSKIGRTRTLSAVENRFNRPMVHEDDAFSKVHLQRRGSNDTLVNRRFFISDIDETLRDLLKNEDSDSNCQITIEDTGPKVLRVGTANSNGYRQTDIRGTYMLSNLLQELTIAKRFGRNQMVLDEARLNENPVKRLRRLISHSFWKNLTRQVGSGNVAEIAQDTKIDTPDGRIPRIYVPHDDPEQYEFYLEIARKNEAVGGARLDVRYLNEVIDPEYVKSINGTPGLLALATHKVPDGQGGITLEGYPYVVPGGRFNELYGWDSYMMALGLLKDGMLDLARGMVENFIYEIRHYGMILNANRSYYLGRSQPPFLTDFGIMVYEAMVEHAHQNEEDTEKSLQDAEYFLRRTFCAAICEYKTVWCCEPRLDKTTGLSCYHPQGVGIPPETESTHFTTLLTPYAKKHGVSIEEFYELYNNHTIVEPELDEYFLHDRAVRESGHDTSYRLEGICASLATVDLNALLYKYEVDIAKIIKEHFNDELVTENSVEHSAEWTKRAELRKERMDKYLWNEEEGIYFDYNLKLKKQHRYESVTTFWPMWAGCSSQEQAQLMVDKSLSKFEEFGGLVAGTLASRGRVGLERPSRQWDYPYGWAPQQILAWVGLDKYGFRGHTKRLCYRWLYLMTKAFVDYNGIVVEKYDVTTGTSPHKVDAEYGNQGADFKGVATEGFGWVNASFILGLTYLDVQGIRAIGAVTSPDVFFRKLKPWERASYGLRPCNEIVKSN*
cbs7435_chr4	GenBank	mRNA	245587	247932	.	+	.	ID=PP7435_Chr4-0135.t01;Name=PP7435_Chr4-0135.t01;Parent=PP7435_Chr4-0135;locus_tag=PP7435_Chr4-0135;Note=NTH1
cbs7435_chr4	GenBank	CDS	245587	247932	.	+	0	ID=PP7435_Chr4-0135.p01;Name=PP7435_Chr4-0135.p01;Parent=PP7435_Chr4-0135.t01;gene=NTH1;Note=NTH1;Dbxref=GI:328353913,GOA:F2QY32,InterPro:IPR001661,InterPro:IPR008928,InterPro:IPR011120,InterPro:IPR018232,UniProtKB/TrEMBL:F2QY32;codon_start=1;eC_number=3.2.1.28;inference=protein motif:KOG:Neutral trehalase;protein_id=CCA40310.1;product=alpha%2Calpha-trehalase;translation=length.781;locus_tag=PP7435_Chr4-0135;protein_sequence=MQDGNAIERPHSVAVDVPDGLQQPHHTRTFSTGSNSGFIDPFSEPSQYYGPATDIARASTRSKIGRTRTLSAVENRFNRPMVHEDDAFSKVHLQRRGSNDTLVNRRFFISDIDETLRDLLKNEDSDSNCQITIEDTGPKVLRVGTANSNGYRQTDIRGTYMLSNLLQELTIAKRFGRNQMVLDEARLNENPVKRLRRLISHSFWKNLTRQVGSGNVAEIAQDTKIDTPDGRIPRIYVPHDDPEQYEFYLEIARKNEAVGGARLDVRYLNEVIDPEYVKSINGTPGLLALATHKVPDGQGGITLEGYPYVVPGGRFNELYGWDSYMMALGLLKDGMLDLARGMVENFIYEIRHYGMILNANRSYYLGRSQPPFLTDFGIMVYEAMVEHAHQNEEDTEKSLQDAEYFLRRTFCAAICEYKTVWCCEPRLDKTTGLSCYHPQGVGIPPETESTHFTTLLTPYAKKHGVSIEEFYELYNNHTIVEPELDEYFLHDRAVRESGHDTSYRLEGICASLATVDLNALLYKYEVDIAKIIKEHFNDELVTENSVEHSAEWTKRAELRKERMDKYLWNEEEGIYFDYNLKLKKQHRYESVTTFWPMWAGCSSQEQAQLMVDKSLSKFEEFGGLVAGTLASRGRVGLERPSRQWDYPYGWAPQQILAWVGLDKYGFRGHTKRLCYRWLYLMTKAFVDYNGIVVEKYDVTTGTSPHKVDAEYGNQGADFKGVATEGFGWVNASFILGLTYLDVQGIRAIGAVTSPDVFFRKLKPWERASYGLRPCNEIVKSN*
cbs7435_chr4	GenBank	exon	245587	247932	.	+	.	Parent=PP7435_Chr4-0135.t01;locus_tag=PP7435_Chr4-0135
cbs7435_chr4	Cufflinks	three_prime_UTR	247933	247978	.	+	.	Parent=PP7435_Chr4-0135;Name=PP7435_Chr4-0135_3-UTR;Note=PP7435_Chr4-0135_3-UTR;length=46
```

**Comment by rdhayes** [comment]
Hello,

I think I see a parent-child relationship issue here. The UTR features have
the gene feature as parent, but I think need to be children of mRNA instead
(placing UTR at the same level as CDS and exon features).

Example 2 also has the five_prime_UTR defined before the gene and mRNA
parent features, which can be a problem for some parsers. That said, I
believe the Bio::GFF3::LowLevel module used by JBrowse to convert GFF3 to
JSON handles this condition properly.

Best regards,

Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by cmdcolin** [comment]
Maybe what @rdhayes suggested but also the UTR coordinates are outside the bounds of the parent feature which is probably the main reason for the observed glitch at different zoom levels. If you really want to not change the source gff you can increase maxFeatureGlyphExpansion so that it draws subfeatures that are outside the bounds of the parent feature but it's probably better to fix the source gff.

**Comment by Rhinogradentia** [comment]
Thank you for your help. To increase maxFeatureGlyphExpansion did help! I can't change the source gff, because the coordinates of the UTR are supposed to be outside the parent feature this far. 
What I will try as well is to change the parent-child-relation to the mRNA. Thank you for mentioning that. I wasn't aware that this is not correct this way.
Best Regards,
Nadine

**Comment by cmdcolin** [comment]
Cool! Feel free to reopen if there are other issues
