### ISSUE TITLE
Generate inaccurate PDF with PhantomJS

### ISSUE THREAD

**Issue by verne91** [GMOD/jbrowse#811]
Hi everyone,

When I pass a url which contains many tracks to PhantomJS in order to get the screenshot, the PDF just displays the end of the page. It seems that PhantomJS simulates the motion of adding tracks.

**Comment by cmdcolin** [comment]
I think that this probably isn't a jbrowse problem. PhantomJS is fully scriptable so it could just be told to scroll back up to the top programmatically. Alternatively, you can take a very tall screenshot with phantomJS to capture whole area (this is actually very fun) and then crop the output. The pageres program I think does this type of autocropping well but doesn't do pdf.

Fun screenshot of very tall jbrowse screenshot from phantomJS http://imgur.com/a/7lXx4 (5mb image)

**Comment by cmdcolin** [comment]
maybe close for now

**Comment by keiranmraine** [comment]
Also see: https://github.com/cancerit/cgpJBrowseToolkit/blob/master/README.md#jbrowse_rasterizejs
