### ISSUE TITLE
what does "Reverse complement view" mean and what 's the usage of it

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#812]
in JBrowse's menu: View->Reverse complement view, check on it, the current position automatically changed to `[length(chr)-pos]`. what's the usage of this option? I didn't find any manual help about it.

**Comment by cmdcolin** [comment]
That is a feature added by https://github.com/elsiklab/projectionplugin

Not core jbrowse.  :)

Feel free to add discussion there if interested, but it is largely experimental as a jbrowse plugin
