### ISSUE TITLE
Display complete CDS in details as single subfeature

### ISSUE THREAD

**Issue by Rhinogradentia** [GMOD/jbrowse#816]
The CDS in the details-view is displayed in a splitted way if more than one is available. It would be great if the coding sequence would be displayed as one single subfeature. Maybe this could be combined with this feature request?  
https://github.com/GMOD/jbrowse/issues/320 

Best Regards,
Nadine

**Comment by colindaven** [comment]
There is a plugin which does this very nicely. 

https://github.com/tsaari88/FeatureSequence

Regards,
Colin

**Comment by Rhinogradentia** [comment]
Thats great - thank you. I will give it a try.
Best Regards
Nadine
