### ISSUE TITLE
apache deflate setting conflicts with IndexedFasta

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#818]
By deault, apache does not turn on deflate setting, the IndexedFasta works well:

```
      {
         "urlTemplateFAI" : "seq/genome_Grai_JBrowse.fa.fai",
         "key" : "Reference sequence",
         "useAsRefSeqStore" : true,
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "urlTemplate" : "seq/genome_Grai_JBrowse.fa",
         "label" : "DNA",
         "type" : "SequenceTrack",
         "category" : "Reference sequence"
      },
```

![qq 20161016135628](https://cloud.githubusercontent.com/assets/1146090/19415629/783fda4e-93a8-11e6-8962-464831e62254.png)

In the browse console, the reference.genome.fa is downloaded in a **206** state (partail content)

However, when I turn on apache deflate in the whole server (including JBrowse and my other websites):

```
<IfModule mod_deflate.c>
        SetOutputFilter DEFLATE
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE text/javascript
        AddOutputFilterByType DEFLATE application/xhtml+xml
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/atom_xml
        AddOutputFilterByType DEFLATE application/x-javascript
        AddOutputFilterByType DEFLATE application/x-httpd-php
        AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>
<IfModule setenvif.c>
        SetEnvIf Request_URI "(\.jsonz|\.txtz)" no-gzip dont-vary
</IfModule>
<IfModule mod_headers.c>
        <FilesMatch "(\.jsonz|\.txtz)">
                Header onsuccess set Content-Encoding gzip
        </FilesMatch>
</IfModule>
```

Problem occurs! When I view the reference sequence tracks, it keeps showing "loading". My server machine makes loud noises and I find a `httpd` process is running in background. In the browser console, I found the browser try to download the whole reference genome file! (~1Gb) .The reference.genome.fa is downloaded in a **200** state 
![qq 20161016135539](https://cloud.githubusercontent.com/assets/1146090/19415649/5275b4ea-93a9-11e6-9b88-451d3a04e9da.png)

What's wrong with my apache deflate setting?

**Comment by cmdcolin** [comment]
I'd probably not use deflate combined with range requests and probably disable it, maybe at least the text/plain. Deflate settings are also not really something discussed in the jbrowse user guide either so I might suggest closing

I imagine that combining range request and gzip encoding is probably difficult not just for the Apache server settings but also the http headers

https://lists.w3.org/Archives/Public/ietf-http-wg/2014JanMar/1179.html

**Comment by billzt** [comment]
Well, jbrowse user guide discussed gzip http://gmod.org/wiki/JBrowse_Configuration_Guide#Compressing_data_on_the_server

**Comment by cmdcolin** [comment]
I think this is probably a specific server issue or maybe a documentation issue but not really an issue with jbrowse code so maybe suggest closing!

Of course, with .2bit support added you'll have good compression over the wire in an easier format than using this :)
