### ISSUE TITLE
Tracks not showing on uploading bam files

### ISSUE THREAD

**Issue by pasudyan** [GMOD/jbrowse#819]
Hello, 

I am new to JBrowse so this issue may be trivial. I am using JBrowse for my bam files. Upon uploading both the bam and bai files, I can see nothing on my track except its title. I have sorted by leftmost coordinate and index my bam file and I know that my bam file is not corrupt (at least I am told so.) Am I missing anything here? I am just following the tutorial on how to download and upload my files onto JBrowse. 

Any help would be appreciated. 

Thank you.

**Comment by cmdcolin** [comment]
Most commonly this would be due to mismatched chromosome names

http://gmod.org/wiki/JBrowse_FAQ#After_I_load_my_track_it_appears_in_the_tracklist.2C_but_the_track_appears_empty

Have you looked into this possibility?

**Comment by pasudyan** [comment]
No, I have not. Do you know of a good way to do this?

**Comment by cmdcolin** [comment]
I saw your edit. Is the issue fixed then? You might consider running "samtools view -H yourfile.bam" to output only the header and then you can see the chromosome names. you can also lookup how to use "samtools reheader" to update the bam chromosome names (otherwise you can reload the reference genome FASTA with names matching the bam)

**Comment by pasudyan** [comment]
Thank you so much for the response. 
I was told that the reference file used is a different one to that default of the jBrowse. I am thinking of using the appropriate reference genome. Do I just upload the fasta file along with the bam files?

**Comment by cmdcolin** [comment]
I think this was fixed. Other discussion on mailing list for continued convo    http://gmod.827538.n3.nabble.com/Gmod-ajax-problem-with-JBrowse-td4056003.html
