### ISSUE TITLE
bigWig file displays negative values

### ISSUE THREAD

**Issue by benoistlaurent** [GMOD/jbrowse#826]
I converted a wig file to bigWig using wigToBigWig:

```bash
wigToBigWig sRNASeq_mock_avRPM_strand-.wig chrom.sizes out.bw
```

The source wig file contains only positive values, as confirmed by any genome browser such as IGV.

But when I load it into JBrowse (see configuration below), I see negative values.

JBrowse configuration:

```ini
[ tracks . sRNASeq_mock_avRPM_strand- xyplot ]
storeClass = JBrowse/Store/BigWig
urlTemplate = raw/cv11/sRNASeq_mock_avRPM_strand-.bw
style.bg_color = #ccc
category = Quantitative / XY Plot
type = JBrowse/View/Track/Wiggle/XYPlot
key = BigWig XY - sRNASeq_mock_avRPM - strand-
logScaleOption = true
```

<img width="1878" alt="screen shot 2016-11-02 at 12 08 07" src="https://cloud.githubusercontent.com/assets/234145/19926481/0e30d108-a0f5-11e6-9f1e-80366ad5ffbe.png">

Any help would be very much appreciated.
Ben
[sRNASeq_mock_avRPM_strand-.zip](https://github.com/GMOD/jbrowse/files/566350/sRNASeq_mock_avRPM_strand-.zip)

**Comment by benoistlaurent** [comment]
Note that I tried to create the bigwig from the wig on the exact same machine as the one my server is running on (which was not the case).

The new file is looks totally identical to the old one (differences evaluated with cmp and md5sum).

However, the new bigwig appears correctly (with positive values) in the browser.

**Comment by nathandunn** [comment]
What happens when you convert it back?

**Comment by benoistlaurent** [comment]
When I convert it back, I've got something weird actually.
The new wig file has a header line which is repeated every 1025 lines.
Appart from that, the values are exactly the same.

**Comment by nathandunn** [comment]
No idea.  Might want to post it to the list in case its just a misconfiguration.

**Comment by cmdcolin** [comment]
is this still a problem? if the files are exactly the same via md5 then there can't be anything different, so it must be cache or configuration differences

**Comment by cmdcolin** [comment]
i noted you had some sample data and it's fairly clear from it that the values are indeed positive. the only scenario i can imagine negative values being plotted from a positive bigwig is if the values are between 0-1 and the log score is enabled.

**Comment by cmdcolin** [comment]
don't look like that is the case here, though. I'd suggest close for now :) feel free to reopen if it happens again
