### ISSUE TITLE
clarify build instructions to reflect nodejs / npm dependencies

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#828]
Related to https://github.com/GMOD/Apollo/issues/1317

Basically you need to make sure you are using the newest npm / node.js.   The default on ubuntu14  (and probably 16) is horribly old.

**Comment by enuggetry** [comment]
do we know the minimal requirements?

**Comment by nathandunn** [comment]
I put it at NPM 2 per https://github.com/GMOD/Apollo/pull/1321/files#diff-31f2385ba9cc65dba7ccb9aa5c5b7600  and https://github.com/GMOD/Apollo/pull/1321/files#diff-614f5c7f5ec0a8f955f030135ec52edcL27

**Comment by cmdcolin** [comment]
At least with #886 you can use even ancient versions of npm, even ubuntu where they have the stupid thing where it is named nodejs instead of node without modification :)
