### ISSUE TITLE
FASTA upload does not work 

### ISSUE THREAD

**Issue by kkarra** [GMOD/jbrowse#831]
In public latest version 1.12.1 
Tried this with different fasta files in chrome Version 54.0.2840.98 (64-bit)

**Comment by cmdcolin** [comment]
It does seem this is pretty buggy. It says "No sequence available" when zooming in and tracklist is not cleared

**Comment by cmdcolin** [comment]
This should be largely fixed on master branch but could use someone to review

At least one bug with this feature 1.12.1 was aided by this commit

https://github.com/GMOD/jbrowse/commit/9b917f34146a2542be4e5a23bc3dcfba6352d44e

**Comment by cmdcolin** [comment]
Should be fixed in $release.next. Feel free to reopen or new issue if not
