### ISSUE TITLE
jbrowse crashed when chunk size too big

### ISSUE THREAD

**Issue by vanney9** [GMOD/jbrowse#832]
i want to use JBrowse to show a vcf file on chromosome 22.  This vcf file size is about 200M.  And JBrowse crashed. 

Here is my conf file
````
[ tracks . vcf ]
key = VCF - volvox-sorted variants
storeClass = JBrowse/Store/SeqFeature/VCFTabix
urlTemplate = vcf/22.vcf.gz
type = JBrowse/View/Track/HTMLVariants
metadata.category = VCF
chunkSizeLimit = 50000000
````
When i change the chunkSizeLimit to 10,000,000, The JBrowse shows 
````
ERROR: Too much data. ChunkSize 17,301,683 bytes exceeds chunkSizeLimit of 10,000,000
````

How can I fix this problem to show big size vcf file?

Thanks

**Comment by colindaven** [comment]
Change chunkSizeLimit to 20000000 ?

Maybe filter your VCF ?

Are you zoomed in to a very small region ? Chome seems to still be the most performant browser for displaying big data in JBrowse.

**Comment by cmdcolin** [comment]
One possibility in this case is that the "stats estimation" causes this bug to occur. The "stats estimation" procedure can cause chunkSizeErrors because it samples a VCF file from a region to see how many features there are, and doubles the size of that region to see if it can find enough features to estimate stats.

In sparse files, this can lead to many doublings and then eventually too much data gets downloaded all of a sudden

The fix, which is actually on the master branch, is to just timeout stats estimation.

You could try a master branch version of jbrowse to see if your problem is fixed. Xref https://github.com/GMOD/jbrowse/pull/663 and https://github.com/GMOD/jbrowse/pull/730

**Comment by vanney9** [comment]
@cmdcolin Thanks for your response. I have downloaded the master branch, and I have changed the storeTimeout to 60s. But the chrome crashed again. Here is my tracks.conf 
````
[ tracks . vcf ]
style.height = 7
key = VCF - volvox-sorted variants
storeClass = JBrowse/Store/SeqFeature/VCFTabix
urlTemplate = vcf/22.vcf.gz
type = JBrowse/View/Track/HTMLVariants
metadata.category = VCF
chunkSizeLimit = 20000000
storeTimeout = 60000
````

The browser is loading VCF data for about 30s, and then it crashed
![2016-11-29 10 42 05](https://cloud.githubusercontent.com/assets/8433575/20694598/5854aeda-b621-11e6-8511-30e4ab1e1956.png)
![2016-11-29 10 48 32](https://cloud.githubusercontent.com/assets/8433575/20694616/720aeb14-b621-11e6-807b-8069497b3501.png)

## Data source ##
I downloaded the sequence file [chr22.fa.gz](http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz) from [UCSC](http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/) ,
and downloaded the vcf file : [vcf.gz](ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz) [vcf.gz.tbi](ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz.tbi)  from [1000 Genomes](http://www.internationalgenome.org/data-portal/population/GBR)

You have mentioned that it may caused by `stats estimation`. And can I config to not use this function, and just fetch the data in the small region?

**Comment by vanney9** [comment]
I think I have figured it out. 
I changed the `storeTimeout = 6` to ensure it is small enough. 
![2016-11-29 8 27 12](https://cloud.githubusercontent.com/assets/8433575/20709794/48140902-b672-11e6-9877-137541338a65.png)
### So the function `statsFromInterval` only execute once.  But now it can not collect enough feature data to do the estimation ###
And the browser shows the vcf data after making this change.
![2016-11-29 8 30 12](https://cloud.githubusercontent.com/assets/8433575/20709883/ad7a5d50-b672-11e6-9ac1-f586f7608de1.png)

**Comment by cmdcolin** [comment]
Looks good!

**Comment by cmdcolin** [comment]
Close since the workaround found :)
