### ISSUE TITLE
Does not work with default macOS server

### ISSUE THREAD

**Issue by aishmitk** [GMOD/jbrowse#836]
Hi I'm fairly new to all this, but when I was trying to install JBrowse on the default web server that can be opened up with macOS by following this link:
https://discussions.apple.com/docs/DOC-3083

With this server I it would not be able to load anything other than the index.html page. However when I used MAMP, the problem magically fixed itself. Perhaps editing the README.md file might solve a few issues for less tech-savvy people like myself :P 

Great work with the browser by the way!

**Comment by nathandunn** [comment]
Thanks for the comment (I can't take credit for the browser, but I agree).  

You should be able to edit the README.md within github and it will generate a Pull Request which we can review and integrate.    We also have docker instances that do the same thing, but having more "good" ways to do stuff is always useful.

**Comment by cmdcolin** [comment]
JBrowse should be fine with an apache server like the one discussed in that guide. If there is some specific error then maybe post that error message? It is likely a problem with the server setup rather than JBrowse itself

**Comment by aishmitk** [comment]
Yeah there's nothing wrong with JBrowse, I was just warning others from refraining form the use of the web server that macOS uses, as it causes issues with the set up.

**Comment by cmdcolin** [comment]
If I do the following steps

1) sudo apachectl start
2) put jbrowse in /Library/WebServer/Documents
3) run setup.sh in the jbrowse folder

Then it is accessible from http://localhost/jbrowse works on macOS sierra, including volvox data :)

I don't believe any other additional steps were involved, maybe installing xcode beforehand.

I think that setup guide was just a little overcomplicated

**Comment by aishmitk** [comment]
Ahh okay I was using El Capitan but I doubt it makes a big difference.
Anyhow, it seems to work so cheers!
