### ISSUE TITLE
neat feature artifact with unspliced features

### ISSUE THREAD

**Issue by childers** [GMOD/jbrowse#837]
This is using apollo2.0.6-SNAPSHOT

I've been getting some strange artifacts with the introns, and have a workaround for some by setting renderClassName to gray-center-30pct.  However, on unspliced features I see what looks like the renderClass gray-line-30pct offset.  I'm seeing this on HTMLDraggableFeatures and BLASTDraggableFeatures (which inherit from HTMLFeatures)

Can you reproduce this? I am pretty sure this is not a client side caching issue.

![apollo2 0 6-intronlessgenes](https://cloud.githubusercontent.com/assets/421248/21730097/20cf407e-d41c-11e6-9949-7b8f092d7208.png)

**Comment by nathandunn** [comment]
Confirmed on volvox:

![screen shot 2017-01-06 at 1 05 38 pm](https://cloud.githubusercontent.com/assets/751274/21732950/e9964536-d410-11e6-8823-ea9d86458f7b.png)

http://localhost/jbrowse/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A23243..26652&tracks=DNA%2CClones%2CEST%2CExampleFeatures%2CMotifs%2Cmalformed_alignments%2CNameTest&highlight=

Its just drawing the rest of the block.

**Comment by nathandunn** [comment]
Slightly simpler: 

http://localhost/jbrowse/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A24389..27798&tracks=DNA%2CMotifs&highlight=

![screen shot 2017-01-06 at 1 10 12 pm](https://cloud.githubusercontent.com/assets/751274/21733089/86beadd0-d411-11e6-9f0e-09b51b141d95.png)

**Comment by nathandunn** [comment]
@childers  This works in the pure JBrowse case, but still doesn't quite fix https://github.com/GMOD/Apollo/issues/1417 . . I think due to formatting issues.  Not quite sure.

**Comment by childers** [comment]
@nathandunn Awesome, thank you! I've got my eye on the Apollo issue too.  Thanks!

**Comment by nathandunn** [comment]
If you could confirm the JBrowse one, that would be awesome, as well.   Should be in master now (though you’ll still see the problem in Apollo).
