### ISSUE TITLE
some alignments in bam not render?

### ISSUE THREAD

**Issue by vanney9** [GMOD/jbrowse#841]
Hi, I have a question that JBrowse did not render some bam alignments.
For example:
I select the region chr6:34765178..34765338 and JBrowse show **3 alignments** as below:
![2017-01-10 10 32 18](https://cloud.githubusercontent.com/assets/8433575/21791750/10b4e7a0-d720-11e6-83fa-975e98de6b4d.png)

And when I use samtools to view the alignments in the same region, it shows **5 alignments**  as below:
![2017-01-10 10 34 30](https://cloud.githubusercontent.com/assets/8433575/21791791/5fb54c0a-d720-11e6-9d85-d38563b56b9e.png)

And the second and last alignment was not shown at JBrowse. The second alignment is the same as the first alignment, but it`s flag is 1024 (0x400). The last alignment has the same end position as the third, but it is shorter than the third, and the flag is 1040 (0x410)

And is there a reason not show these alignments ? Or is there a place to set to show all the alignment?

Thanks.

**Comment by cmdcolin** [comment]
These reads have the "read is PCR or optical duplicate" flag enabled (i.e. the bitmask 1024 means it is a duplicate). See https://broadinstitute.github.io/picard/explain-flags.html

Reads with this flag are by default hidden in jbrowse. You can enable them in the UI (see screenshot) or by  editing your trackList.json to have `"hideDuplicateReads": false` on your track  (by default it is true)

![screenshot-jbrowse org-2017-01-09-22-24-40](https://cloud.githubusercontent.com/assets/6511937/21792882/d1f31f92-d6ba-11e6-87dc-dafa1f719696.png)

**Comment by vanney9** [comment]
yeah, I got it now. Thanks

**Comment by cmdcolin** [comment]
super!
