### ISSUE TITLE
missing node.dll

### ISSUE THREAD

**Issue by aalmosa1** [GMOD/jbrowse#849]
I tried to install JBrowser on W 7 64 bit, and i get this message node.dll is missing, please your help is greatly appreciate it.

**Comment by nathandunn** [comment]
Do you have node + npm installed?

**Comment by nathandunn** [comment]
http://blog.teamtreehouse.com/install-node-js-npm-windows

I think you want npm 2+

**Comment by aalmosa1** [comment]
No I don’t , can you please tell from where I have to install them, or if you kindly send me the link .

Thanks,
Ahmad

**Comment by cmdcolin** [comment]
This probably refers to the electron app JBrowseDesktop-1.12.1-desktop-win.zip

I think the error about node.dll not being found would happen if you move JBrowseDesktop.exe to a different folder after unzipping the file.

Therefore, just unzip the zip file, don't move JBrowseDesktop.exe anywhere, and it should be fine. You don't need to install nodejs separately

**Comment by nathandunn** [comment]
Oh thanks. I was just going to say, you probably either need to use the windows electron app or install via docker:

However, you're going to have a lot of trouble installing this on windows directly.  You could try the windows desktop app:  

http://jbrowse.org/blog/

or docker:

https://hub.docker.com/r/gmod/jbrowse/

**Comment by aalmosa1** [comment]
I tried all the trouble shooting you sent me, I followed all your suggestions, I am still unable to run the file, I install the node.js also doesn’t help me, it seem there is a lot of trouble install this program directly on Windows.

**Comment by cmdcolin** [comment]
If you can further describe your setup steps, it would help

* Show the directory listing of the unzipped folder? screenshot of the folder is fine.
* Confirm that node.dll is in the directory of the unzipped folder?
* If node.dll is not in the zip folder that you unzipped, maybe you have anti-virus that automatically removed it, and you could disable the anti-virus or unquanantine the file to make it work?

**Comment by aalmosa1** [comment]
I installed the Node.dll first, then I download the JBrowse-1.12.1 then I run the jbroswer desktop, then I got the error message?
I don’t mind to connect remotely to my desktop and take a look , I can establish gotomeeting session if you like?

Thanks,
Ahmad

**Comment by cmdcolin** [comment]
Sorry I don't think I can do remote desktop right now. Maybe later if you still have issues with it!

**Comment by aalmosa1** [comment]
Ok, thank you for offering your help!

**Comment by aalmosa1** [comment]
Sorry to bother you, do you have time right now?

**Comment by nathandunn** [comment]
You might want to try the docker solution on windows first or install a server on virtualbox. 

https://docs.docker.com/docker-for-windows/ <https://docs.docker.com/docker-for-windows/>

https://hub.docker.com/r/gmod/jbrowse/ <https://hub.docker.com/r/gmod/jbrowse/>

Nahan

**Comment by cmdcolin** [comment]
It's my opinion that JBrowseDesktop is a specific solution, more akin to running something like IGV, so it is different from installing jbrowse normally or via docker. of course, you have to decide whether that type of use case is what you want. if it's not even what you want then you may not want JBrowseDesktop

In any case, feel free to send me email me colin.diesh@gmail.com to setup chat. I am willing to provide some support for it (as the desktop version specifically was sort of a monster of my making :))

**Comment by cmdcolin** [comment]
I didn't receive any reply for this so maybe close for now

**Comment by aalmosa1** [comment]
Yes please close.

Thanks,
Ahmad
