### ISSUE TITLE
bulk export using API

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#850]
Emulate "Save Track Data" behavior GFF3, bed, etc. in the API

<img width="496" alt="screen shot 2017-01-30 at 12 50 38 pm" src="https://cloud.githubusercontent.com/assets/751274/22441131/fdd1464e-e6ea-11e6-8d94-26d1e3c49fb4.png">

This would allow JBrowse to be used as a datastore:

http://localhost/jbrowse/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A28002..30338&tracks=Motifs&highlight=&export=GFF3&out=stream

New options would be:

 - export GFF3
 - out stream

FYI @enuggetry

**Comment by enuggetry** [comment]
Only thing is, it would be rather uncharacteristic of JBrowse to return GFF as a HTTP GET response, but should be doable.

**Comment by nathandunn** [comment]
JSON would be the best, but allowing a few different things is good.

**Comment by nathandunn** [comment]
This is fairly related as well:  https://github.com/GMOD/jbrowse/issues/265

**Comment by nathandunn** [comment]
I guess that is non-compiled access into the store.   Somewhat similar.

**Comment by cmdcolin** [comment]
Not sure if this is relevant, but I had a demo of something like this awhile ago here for accessing sequence data and using jbrowse code in a standalone page https://gist.github.com/cmdcolin/b0acb8696b7b7bd8927b


The general method can be extended to access an NCList track or any other track type like this, using the same code as the "Save track data" export that that dialog box provides https://gist.github.com/cmdcolin/d7c849083164510d4f0a93a280b0a92f

**Comment by nathandunn** [comment]
Thanks @cmdcolin .  I think this is very *apropos*.

**Comment by erasche** [comment]
Wow, that's awesome @cmdcolin, will have to re-use that for displaying gene models. Seems like magic.

![utvalg_108](https://cloud.githubusercontent.com/assets/458683/22483002/545daf8a-e7f3-11e6-8b1b-cbc5b3cf4b42.png)

**Comment by rbuels** [comment]
So would this be addressed if we factored out much of our data store code to be published separately as npm modules?

**Comment by nathandunn** [comment]
@rbuels  I think they are separate issues.  I think that the separate npm modules would be ideal.

**Comment by cmdcolin** [comment]
>This would allow JBrowse to be used as a datastore

I think the idea of "using JBrowse as a datastore" or thinking that JBrowse provides a "REST API" is going to basically just be confusing. JBrowse's javascript is evaluated client side, so you don't get a HTTP response with the parsed data that you want (as most REST APIs work), you get an HTTP response with JBrowse's index.html and javascript that are then evaluated as a page, which I guess the page could be some JSON, but that is not a REST API in any conventional terms.

I hope that makes sense. I might suggest close for now but if I am missing something let me know and then an reopen or clarify issue

**Comment by cmdcolin** [comment]
As for how NPM modularization is helping the situation, currently even those are just compiled into client side with webpack but certainly they could be used server side to create a REST API or compiled into something like the GenomFeaturesComponent

**Comment by nathandunn** [comment]
Agreed @cmdcolin .    I think using Apollo or JBServe are the appropriate ways to do this.

**Comment by ihh** [comment]
*JBConnect. But yes.
