### ISSUE TITLE
BigWig unable to fetch

### ISSUE THREAD

**Issue by yloemie** [GMOD/jbrowse#852]
Hi,
first thanks for your work,

I have troubles, I want to display 2 bw files but I have the error 'unable to fetch'.
The URL is correct and I have already loaded plenty of bw tracks with no problems.
My bigwig version is 4 as all previously loaded tracks.
I tested these 2 in IGV successfully so I am a bit disappointed. Did you already see a bug like that?

Thanks a lot.

**Comment by yloemie** [comment]
Update,
we saw that the tracks are visible with chrome or chromium. It works too with Firefox on a MacOS X but not on windows or ubuntu... So I suggest a javascript issue.

**Comment by cmdcolin** [comment]
In general there shouldn't be that much cross platform variance. can you open the javascript console to look for errors? If it says something like

    Failed to load resource: net::ERR_CONTENT_DECODING_FAILED

That means that your server is probably applying gzip headers incorrectly. This has caused similar "Unable to fetch" issues here https://github.com/GMOD/jbrowse/issues/825

If you go to the network tab in the chrome, then you can inspect the "response headers" to see if you have the problem. For example, for a proper bigwig response header it would say something like

```
Accept-Ranges:bytes
Content-Length:32768
Content-Range:bytes 0-32767/100245
Content-Type:text/plain; charset=UTF-8
Date:Fri, 17 Feb 2017 02:32:52 GMT
ETag:"5e2a7-18795-52cfb54f04840"
Last-Modified:Tue, 01 Mar 2016 11:47:37 GMT
Server:Apache/2.2.31 (Amazon)
Vary:User-Agent
```

An improper response would probably contain "Content-Encoding: gzip"

some browsers are actually adapted to ignore incorrect gzip headers which could explain your cross platform variance, but the problem here is actually out of jbrowse's control because the content is being decoded incorrectly before it even hits the jbrowse code (it is failing to pass through the browsers "decoding", which again, shouldn't be happening at all), so it's mostly a server configuration

**Comment by yloemie** [comment]
In chromium and chrome it works perfectly :

> Accept-Ranges:bytes
> Content-Length:32768
> Content-Range:bytes 0-32767/198731367
> Date:Fri, 17 Feb 2017 13:28:50 GMT
> ETag:"10ed800a-bd86667-548940bce9180"
> Last-Modified:Wed, 15 Feb 2017 16:19:34 GMT
> Server:Apache/2.2.22 (Ubuntu)

In firefox :

> "Unable to fetch http://localhost/JBrowse/data/Ad2_2_sorted.bw" "Unable to fetch http://localhost/JBrowse/data/Ad2_2_sorted.bw"  dojo.js:829:114
> 	.cache["JBrowse/View/Track/BlockBased"]/</<._handleError http://localhost/JBrowse/src/dojo/dojo.js:829:114
> 	.cache["JBrowse/View/Track/WiggleBase"]/</<._getBlockFeatures/< http://localhost/JBrowse/src/dojo/dojo.js:1457:123
> 	.cache["dojo/_base/lang"]/</b.hitch/< http://localhost/JBrowse/src/dojo/dojo.js:141:21
> 	.cache["dojo/Deferred"]/</c http://localhost/JBrowse/src/dojo/dojo.js:236:165
> 	.cache["dojo/Deferred"]/</d http://localhost/JBrowse/src/dojo/dojo.js:236:91
> 	.cache["dojo/Deferred"]/</k/this.reject http://localhost/JBrowse/src/dojo/dojo.js:238:353
> 	.cache["JBrowse/Store"]/</<._failAllDeferred http://localhost/JBrowse/src/dojo/dojo.js:1046:329
> 	.cache["dojo/_base/lang"]/</b.hitch/< http://localhost/JBrowse/src/dojo/dojo.js:140:465
> 	.cache["JBrowse/Store/RemoteBinaryFile"]/</<._fetchChunks/</< http://localhost/JBrowse/src/dojo/dojo.js:1003:262
> 	.cache["JBrowse/Store/LRUCache"]/</<._attemptFill/</< http://localhost/JBrowse/src/dojo/dojo.js:1013:290
> 	.cache["dojo/_base/array"]/</b.forEach http://localhost/JBrowse/src/dojo/dojo.js:163:221
> 	.cache["JBrowse/Store/LRUCache"]/</<._attemptFill/< http://localhost/JBrowse/src/dojo/dojo.js:1013:252
> 	.cache["dojo/_base/lang"]/</b._hitchArgs/< http://localhost/JBrowse/src/dojo/dojo.js:140:202
> 	.cache["JBrowse/Store/RemoteBinaryFile"]/</<._fetch/e.onreadystatechange< http://localhost/JBrowse/src/dojo/dojo.js:1006:133
> 	.cache["dojo/_base/lang"]/</b.hitch/< http://localhost/JBrowse/src/dojo/dojo.js:141:21

I don't know if it make sens for you, I am not really a web developer :)

**Comment by cmdcolin** [comment]
The error message is difficult to decipher here too

If you have the ability it would be helpful to download the package that says "development" e.g. JBrowse-1.12.1-dev.zip from here http://jbrowse.org/jbrowse-1-12-1/ and try that

You can just unzip the downloaded folder and copy your data directory from current jbrowse to it, no need to repeat setup.

Looking at the request headers in firefox would be great too

**Comment by cmdcolin** [comment]
Any updates on this? If you have a link to instance it might help.

**Comment by yloemie** [comment]
Hi,
No update, sorry, but it's because I don't really manage the web developer
tools from chrome or firefox, I will ask a friend and come back to you.

Thanks,

**Comment by cmdcolin** [comment]
Would be curious what the issue is but maybe close for now. If you have a link feel free to post and can reopen. Suspect an odd server side config, the "unable to fetch" problems are quite weird like that e.g. #825
