### ISSUE TITLE
flatfile-to-json.pl gff3 failure to parse strand of '?'

### ISSUE THREAD

**Issue by MikeAxtell** [GMOD/jbrowse#853]
Thanks for all the hard work on JBrowse, fantastic tool!

I noticed what might be a small bug .. flatfile-to-json.pl throws errors when parsing a gff3 file that has strand (the 7th column of gff3) set as '?'. However, '?' appears to be a valid entry per gff3 format, along with the more normally encountered +, -, and . (https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md), and some gff3 tracks for model organisms ship with ? set on some features. Easy to work around, but if a bug, could be fixed.

Example command and one line of error:
`./bin/flatfile-to-json.pl --gff ../Zea_mays.AGPv3.20_repeats.gff3 --trackLabel repeats --trackType CanvasFeatures --config '{"category" : "annotations", "displayMode" : "collapsed"}' --clientConfig '{"color" : "red"}'
Argument "?" isn't numeric in addition (+) at /data/www/html/zma-b3/jbrowse/bin/../src/perl5/Bio/JBrowse/FeatureStream.pm line 66, <$f> line 80531.`

Using JBrowse 1.12.1

**Comment by cmdcolin** [comment]
This is an interesting one, it would probably actually take a fair amount of work to incorporate ? as a proper strand into the entire jbrowse ecosystem because there are just so many places that assume either -, +, or . (no strand). Presumably jbrowse could just convert it to no strand but that would be equivalent of chaging it in source file too

**Comment by rbuels** [comment]
I looked into this, and currently JBrowse is just treating '?' the same as '.', which is "no strand". It's just throwing a warning about it during formatting.  I will get rid of the warning for now, reopen if we want to do further work on better representing unknown-strand features as distinct from no-strand features.
