### ISSUE TITLE
problem in setting fgcolor in JBrowse/View/Track/SNPCoverage

### ISSUE THREAD

**Issue by bostanict** [GMOD/jbrowse#857]
Hi all,

Might this to be very basic but I have problem setting the color for the coverage plot (density area under the curve). I could simply change the background color of the area but the coverage plot remains as gray all the time.

I tried to look for the style property that can do that but was not successful.
Can anyone tell me how I can do that or which parameter to set in style to work?
Thanks

**Comment by cmdcolin** [comment]
There was actually a recent thread about this here https://sourceforge.net/p/gmod/mailman/gmod-ajax/thread/CAP9qM-3S9haT0dEfhtcBXmwvYLpY6KqYs%2B-CS37prQki1%2BBjxg%40mail.gmail.com/#msg35608170

Message reproduced here with possible solution

```
It is sort of a "hidden setting", but you can actually change colors on the
SNPCoverage track using CSS

See css/sequence.css:

/* colors for bases must be specified as hex or rgb/hsl strings, no named
colors such as 'red' */
.base_n {
    background-color: #C6C6C6;
}
.base_a {
    background-color: #00BF00;
}
.base_c {
    background-color: #4747ff;
}
.base_t {
    background-color: #f00;
}
.base_g {
    background-color: #d5bb04;
}
.base_reference {
    background-color: #a33;
}
.base_deletion {
    background-color: #999;
}

.sequence.nocolor .base {
    background-color: #ddd;
}


If you change those, it will be reflected in your SNPCoverage track.

The .base_reference is the background grey of the SNPCoverage plot, and if
you actually add to the list and make .base_skip you can make the intron
grey change color.
```

**Comment by bostanict** [comment]
Dear @cmdcolin 

thanks alot ofr the insigh, I managed to chaneg the color but as I can say it is not possible to change the color for eahc specific track?  So this change will change the bg color for all the tracks in this format, but what if I want to set specific color for each track?

like expression coverage for blueberry as blue color and for the watermelon as red. Is this possible in any way?

thanks a lot~

**Comment by cmdcolin** [comment]
Actually that is probably the problem with the CSS approach in this case, it isn't really track specific.

It would probably be good to add some simple config variables like maybe "fg_color" that can be configured per-track. 

Just as an example of how that could be done with your current setup, you could add a new file called src/JBrowse/View/Track/SNPCoverageColors.js


```
define( ['dojo/_base/declare',
         'JBrowse/View/Track/SNPCoverage'
        ],
        function( declare, SNPCoverage) {

return declare( SNPCoverage,
{

    colorForBase: function(base) {
        return base == 'reference' ? (this.config.style.fg_color||'#bbb') : this.inherited(arguments);
    }
    

});
});
```
 This simple "subclass" can be dropped into the existing installation

Then make your track type "JBrowse/View/Track/SNPCoverageColors" in your track config and set style->fg_color to some color of interest too.

**Comment by bostanict** [comment]
Wow,
great... It worked though I did not understand the code :)

thanks alot @cmdcolin

**Comment by cmdcolin** [comment]
Maybe close for now, might develop a better solution that customizes colors outside of CSS sometime :) glad that helped though @bostanict
