### ISSUE TITLE
bigbed data backend

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#86]
Render feature tracks directly from a bigbed URL

**Comment by cmdcolin** [comment]
Great to hear :)

There is some progress on BigBed implementation, this PR is coming along https://github.com/GMOD/jbrowse/pull/944

I could try testing it out on those files (looks like these in particular 
 https://www.ebi.ac.uk/~anight/genome_annotation_tracks/saccharomyces_cerevisiae/UP000002311_559292_hub/sacCer3/)

**Comment by cmdcolin** [comment]
I think all these files work fine with the code now :)

![screenshot-localhost-2018 04 10-12-30-22](https://user-images.githubusercontent.com/6511937/38570111-071d95f0-3cbb-11e8-9625-4eaa5ef48af2.png)

**Comment by cmdcolin** [comment]
landed in 1.14 release :) open up new issues if theres any problem!

**Comment by benwbooth** [comment]
Is it possible to search for BigBed feature names using the search box? What if I've already defined a name lookup using the REST API? Will searching for BigBed feature names still work? Thanks!
