### ISSUE TITLE
How to solve the problem "error : not a BAM file"?

### ISSUE THREAD

**Issue by milkcookie** [GMOD/jbrowse#863]
Hi, all:
I hava a problem when I ues JBrowse,I have sorted and indexed the bam file,but it says:not a bamfile,I use bowtie2 to mapping the fastq file and samtools to generate the bam file, sort the bam file and index it it always says: not a BAM file,Ican't solove it,so I think you can help me to solve it.
my tracks.conf codes:
# make a section for the new track called tracks.(unique name)
[ tracks.my-bam-track ]

# settings for what data is shown in the track
storeClass     = JBrowse/Store/SeqFeature/BAM
urlTemplate    = ./bamfiles/L24.sorted.bam
baiUrlTemplat  = ./bamfiles/L24.sorted.bam.bai

# settings for how the track looks
category = NGS   #< category for this track
type = JBrowse/View/Track/Alignments2
key  = BAM alignments from sample XYZ

Thanks all
FAFU
milkcookie

**Comment by cmdcolin** [comment]
Normally this is due to some apache server configuration issues http://gmod.org/wiki/JBrowse_FAQ#How_do_I_fix_the_.22Not_a_BAM_file.22_issue.3F

Hope that helps!

**Comment by milkcookie** [comment]
Thank Cm:
I have add line: AddType application/octet-stream .bam .bami .bai,but it doesn't work,I know little about apache,I don't know how to deactivate the module mime_magic,is there other methods to solve this problem?thanks again @cmdcolin

**Comment by cmdcolin** [comment]
You can run try running `sudo a2dismod mime_magic` which will try and disable it. Then restart the apache server afterwards

**Comment by cmdcolin** [comment]
Glad it helps! Will close for now then
