### ISSUE TITLE
How to display multiple alignment format (MAF)

### ISSUE THREAD

**Issue by newuser1971** [GMOD/jbrowse#864]
I want to know how to display MAF as a track.

**Comment by cmdcolin** [comment]
You could try using this jbrowse plugin https://github.com/cmdcolin/mafviewer !

It is a little sophisticated to setup (it requires the maf to be pre-processed and using jbrowse master branch currently) but I'd be interested if it helps.

**Comment by cmdcolin** [comment]
Seems like there was maybe some confusion and it's not clear that MAF format was what was wanted, but if you want to try maf check out that plugin!
