### ISSUE TITLE
How to display reference, consensus and reads at the same time

### ISSUE THREAD

**Issue by newuser1971** [GMOD/jbrowse#865]

**Comment by nathandunn** [comment]
This might be better to pose a question to the jbrowse list at gmod-ajax <gmod-ajax@lists.sourceforge.net>

Archives are here:  https://lists.sourceforge.net/lists/listinfo/gmod-ajax

However, if its a bug, then please provide some more detail.

**Comment by cmdcolin** [comment]
maybe there is more context here https://github.com/igvteam/igv.js/issues/331

still a little confused about what the goal is, but maybe the SNPCoverage track just in the way that the consensus at a particular position can be seen http://jbrowse.org/wordpress/wp-content/uploads/2013/01/snpcoverage.png

**Comment by cmdcolin** [comment]
Any update on this? I thought that the snpcoverage was an ok solution but didn't get feedback :)

**Comment by cmdcolin** [comment]
Probably close with no response :) feel free to reopen if you thing this still needs addressing
