### ISSUE TITLE
Custom Sorting Reference Sequence

### ISSUE THREAD

**Issue by wkpalan** [GMOD/jbrowse#867]
It would be good to specify an order in which reference sequences are sorted when importing, and keep the same sort order. 

If this is not possible is there a way to build a custom sort function for sorting the reference sequences? I have 100+ refseqs and no easy way to sort them

**Comment by cmdcolin** [comment]
Technically there are a couple of sortings that can be added by default:

Sorting by name and length http://gmod.org/wiki/JBrowse_Configuration_Guide#Reference_Sequence_Display_Order

You can also, if it is really needed, have no sorting, and manually edit your refSeqs.json file to have the refseqs in the order that you want in case that is not working. There is no custom sort callback though

**Comment by cmdcolin** [comment]
I think if there are any issues with this feel free to post...otherwise maybe try the custom sorting of the refSeqs.json file manually :)
