### ISSUE TITLE
setting tracklabels=0 does not seem to hide tracks

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#868]
config is picked up okay, the then 

show_tracklabels seems to be ignored everywhere. 

Affects: https://github.com/alliance-genome/agr/issues/244

**Comment by nathandunn** [comment]
@enuggetry   You have any idea what happened to this one? 

Kind of obscures stuff.

**Comment by cmdcolin** [comment]
I don't think it was ever implemented even though that flag exists.

Maybe it could be added to hidetracklabels plugin though.

maybe could try this out https://github.com/GMOD/jbrowse/tree/hide_tracklabels

**Comment by keiranmraine** [comment]
I was just about to ask about this functionality in URL.  Specific use case is showing a genome overview in a wrapper page:

<img width="521" alt="screen shot 2017-03-22 at 05 15 27" src="https://cloud.githubusercontent.com/assets/3740323/24183178/ac97e552-0ebe-11e7-83b9-00233589d8a9.png">
