### ISSUE TITLE
Dataset selector issues

### ISSUE THREAD

**Issue by LuisSoares** [GMOD/jbrowse#879]
I don't know if somebody can help me but no matter what combination I try there is no way I can get the Dataset selector to work properly. Following the instructions I do get a initial webpage with links that open Jbrowse windows with the correct dataset, however once inside Jbrowse the Genomes drop down does not show any options so it is not possible to change the dataset. I know it is possible to have the other datasets appear in the dropdown (in the examples that are created when installing (volvox, yeast and modencode), this is the behavior, however I don't understand which conf file is the volvox dataset using in instalation example so as to show the differenct datasets in the dataset selector). Some help would be appreciated.

**Comment by enuggetry** [comment]
Actually, the sample datasets are hard-coded in Browser.js.
https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Browser.js#L2098

I'm not sure of the historical significance of this.  It seems to me it
would be more intuitive if it could be found in the sample config files.

**Comment by cmdcolin** [comment]
A general way to set this up for yourself can be done by adding small snippets to your tracks.conf and jbrowse.conf

For example in jbrowse.conf, add your dataset "declarations"

```
[datasets.hg38]
name = hg38
url = ?data=hg38
[datasets.hg19]
name = hg19
url = ?data=hg19
[datasets.danio]
name = zebrafish
url = ?data=danio
```

And then in your individual data directories, like in tracks.conf, make `dataset_id=danio` or whatever to the id part of your dataset declaration e.g. [dataset.danio] <-- danio is the ID in that case

```
[GENERAL]
dataset_id=danio
```

**Comment by cmdcolin** [comment]
There have been a couple of dataset selector related issues come up but I don't think there is necessarily a bug here. Maybe documentation improvement? The documentation basically just contains the same example I posted though

The concept of the hardcoded dataset selector is a little crazy but it only applies to the sample datasets. It could potentially be un-hardcoded too, but it would just want to avoid polluting any global config like jbrowse.conf
