### ISSUE TITLE
Faceted track selector in additional to hierarchical

### ISSUE THREAD

**Issue by erasche** [GMOD/jbrowse#883]
I'm currently working to add support for the faceted track selector in various parts of our pipeline, and I'm finding myself wanting to be able to *optionally* look at the faceted metadata in addition to using the hierarchical selector as my primary method of track selection / browsing.

Our track counts are generally in the 5-100 range, and those work great with hierarchical so I'd rather not switch completely.

Is this an option? Am I missing something obvious?

**Comment by cmdcolin** [comment]
Check out @vivekkrish s ComboTrackSelector :)

**Comment by erasche** [comment]
Perfect! Thanks @cmdcolin

**Comment by erasche** [comment]
xref https://github.com/GMOD/jbrowse-registry/pull/30
