### ISSUE TITLE
plugin NeatCanvasFeatures renders differently in 1.12.1 and 1.12.3

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#890]
Using exactly the same configuration, I found that plugin NeatCanvasFeatures renders differently in 1.12.1 and 1.12.3.

This is what I see in 1.12.1
![tim 20170504080812](https://cloud.githubusercontent.com/assets/1146090/25687264/90b5bb06-30a7-11e7-81a2-1ba9266d025b.png)

This is what I see in 1.12.3
![tim 20170504080804](https://cloud.githubusercontent.com/assets/1146090/25687268/952b141a-30a7-11e7-9388-068dd4580418.png)

And I think 1.12.3 is much ugly than 1.12.1

**Comment by nathandunn** [comment]
Did you set the linear gradient to true (bottom of page)?

https://github.com/GMOD/jbrowse/blob/master/plugins/NeatHTMLFeatures/README.md

Nathan

**Comment by billzt** [comment]
@nathandunn 
I add this to my `jbrowse.conf`. However it doesn't work. Only intron hats are OK. But no gradient 'tubular' look

```
[ plugins. NeatCanvasFeatures ]
location = plugins/NeatCanvasFeatures
neatFeatures = 1
linearGradient = 1
```

Is there anything wrong?

**Comment by enuggetry** [comment]
Yea, seems to be a bug there.

**Comment by nathandunn** [comment]
I think they were commented out at some point because they can not be configured to be turned off and our preference is to have them off. 

Do you have time to take a look at it @enuggtry? 

Nathan

**Comment by enuggetry** [comment]
So, the quick fix is to uncomment the code at:
https://github.com/GMOD/jbrowse/blob/master/plugins/NeatCanvasFeatures/js/main.js#L179

**Comment by nathandunn** [comment]
Hmm .. I tried that and it was erring out.  Of course I could have done something wrong. 

Nathan

**Comment by enuggetry** [comment]
I didn't see a problem.   That `else` statement should look like this:
```
        else {
            //if (feature.get('type')==="CDS") bgcolor = this.colorShift(bgcolor,0);

            // Create gradient

            var grd = context.createLinearGradient(left, top, left, top+height);

            // Add colors
            grd.addColorStop(0.000, bgcolor);
            grd.addColorStop(0.500,this.colorShift(bgcolor,2.5));
            grd.addColorStop(0.999, bgcolor);

            // Fill with linear 
            context.fillStyle = grd;  //bgcolor;
           
        }

```

**Comment by nathandunn** [comment]
Its fine, but it didn't actually do anything for me.   Not sure if it gets over-written later, or maybe something I did wrong.

**Comment by nathandunn** [comment]
@enuggetry  Did it work for you?

**Comment by cmdcolin** [comment]
As far as I can tell the gradient is back on by default. I guess close for now :)
