### ISSUE TITLE
How to use histograms for a GFFTabix track when zooming out to a large scale

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#891]
For loading GFF annotations, the previous `flatfile-to-json.pl` might automatically generate histograms data. However in GFFTabix track, if I zoom out to a large scale, there is not such histograms> Perhaps I should generate one by myself. Any good suggestions to generate this?

**Comment by cmdcolin** [comment]
Technically all CanvasFeatures tracks (and Alignments2 since it is derived from CanvasFeatures) can use a bigwig for histograms http://gmod.org/wiki/JBrowse_Configuration_Guide#Configuring_Summary_Histograms

**Comment by cmdcolin** [comment]
I think you can use bedtools genomecov to generate bedgraph, then bedgraph to bigwig :)

**Comment by cmdcolin** [comment]
unless other features are needed maybe close for now :)
