### ISSUE TITLE
defaultTracks in config as a comma list not parsed in 1.12.3

### ISSUE THREAD

**Issue by rdhayes** [GMOD/jbrowse#892]
Hi,

We have defaultTracks in trackList.json as a comma separated list:
    "defaultTracks" : "Transcripts,PASA_assembly,Blastx_protein,Blatx_Monocots",

With JBrowse v1.12.3, and a newly emptied browser and cookie store, when I attempt to load a genome with just the data parameter (which should trigger those defaults), I instead only receive the DNA track.

The new logic in Browser.js is the culprit from lines 190 to 202.

The first time through with a new page load and no cookie set triggered the 

>      else if (thisB.config.defaultTracks) {

block at line 192 is entered, but the type check

>      if (!thisB.config.defaultTracks instanceof Array) {

on line 197 fails and does not populate tracksToShow as intended. This leaves only the unconfigured default of "DNA"

This looks like it initially was introduced in commit b4152538a2d45a57ef4c3c0ced5f536b2a99bd94 to address GMOD/Apollo#1498
 
I'm not familiar with what would alter the config value to be an array rather than string, but this slightly different syntax restores correct use of defaultTracks in regular JBrowse 1.12.3 for me.

      if (thisB.config.defaultTracks instanceof Array) {
            tracksToShow = tracksToShow.concat(thisB.config.defaultTracks);
      }
      else {
            tracksToShow = tracksToShow.concat(thisB.config.defaultTracks.split(","));
      }

I'm happy to submit a pull request for this minor change if that looks good.

**Comment by cmdcolin** [comment]
Yep looks like the intended commit was probably to use  `if (!(thisB.config.defaultTracks instanceof Array))`  but the alternative fix you posted seems good too

**Comment by rdhayes** [comment]
Looking at this again, my fix always adds defaultTracks to the trackToShow list, but Eric's original intention seems to only concat() if not an array. I think my proposal might end up building an array like [ "track1", "track2, track3" ] for Apollo default tracksToShow, which would be obviously wrong.

@cmdcolin 's extra enclosing () fixes this for me in a dev build of v1.12.3 and is the proper patch.

@erasche what do you think?

Thanks!

**Comment by erasche** [comment]
argh, so sorry I introduced such a bug. yes, that looks like what I intended, that it should be converted only if an array.
