### ISSUE TITLE
the URL parameter &loc= doesn't work for VCF IDs

### ISSUE THREAD

**Issue by billzt** [GMOD/jbrowse#899]
After indexed by `generate-names.pl`, the URL parameter `&loc=` works well with gene IDs, but not work with VCF IDs. However the Name Searching and Autocompletion in the search box is totally OK. Therefore I garantee my name indexing is successful.

**Comment by cmdcolin** [comment]
The volvox sample data still works if you plugin variant IDs into the url bar with this approach so the functionality isn't gone per se http://jbrowse.org/code/JBrowse-1.12.3/?data=sample_data%2Fjson%2Fvolvox&loc=rs17881732

**Comment by billzt** [comment]
Well, it works again in my test data also. Sorry to interrupt. 😄

**Comment by AgnesBaud** [comment]
Hello,
I think I have a similar problem. I correctly indexed some IDs and Names with generate-names.pl, the name searching and autocompletion in the search box are OK. But I can't make the URL parameter &loc= work with these IDs and Names, it only works with the positions (chr:start..end)
I don't know if I missed something. Should I have enabled some functions somewhere ?

PS : I use Apollo-2.0.8, which corresponds to the JBrowse release 1.12.3 (I think), but I'm currently searching on the jbrowse part (I'm logout of Apollo)

Thank you in advance,
Agnès

**Comment by cmdcolin** [comment]
Do you have a link to your instance? It is a little hard to guess without knowing all the details, but it is curious that the search box would work and the URL bar would not.

**Comment by cmdcolin** [comment]
I was able to get a login and was able to specify a gene name in the &loc= string and it seemed like it worked. I sent you an email but let me know if there's anything else I should try
