### ISSUE TITLE
Allow user to specify label and mouseover

### ISSUE THREAD

**Issue by jbrowsetix** [GMOD/jbrowse#9]
The label is not always terribly informative. It would be nice to use a sub to provide data (as is done for link generation) to generate a label (possibly with a similar template system) and ideally also a mouseover.

[original LH ticket](http://jbrowse.lighthouseapp.com/projects/23792/tickets/80)

 This ticket has 0 attachment(s).

**Comment by rbuels** [comment]
With the increasing dominance of touchscreen devices, popup balloons are no longer much in demand. Closing this.
