### ISSUE TITLE
Parsing gVCF and symbolic alleles

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#902]
The VCF v4.3 spec details in section 5.5 the use of a "symbolic allele" `<*>` in `gVCF` files. Currently, JBrowse doesn't seem to correctly deal with VCF files containing these:

![image](https://user-images.githubusercontent.com/2037575/27340246-297354de-5619-11e7-852c-cee8fb9644ef.png)

**Comment by cmdcolin** [comment]
I think some of these issues are fixed by this pull request https://github.com/GMOD/jbrowse/pull/847


For example, the gVCF style depends on the "END" info field too which I think is aided by this

**Comment by cmdcolin** [comment]
This should be fixed since 1.13.1

Feel free to check out and open new issue if there is still unexpected behavior
