### ISSUE TITLE
Any support for multiple track selection?

### ISSUE THREAD

**Issue by seigfried** [GMOD/jbrowse#903]
Hello
In Jbrowse for Bigwig file uploads,
Is there any way I can select multiple wiggle tracks and change their min_score, max_score options together?
If I have 50 files it is tedious to change scale for every sample since it is not really convenient to use autoscale every single time

**Comment by cmdcolin** [comment]
I guess the fundamental question is sort of similar to this and probably doesn't have a ready-made fix yet to synchronize all 50 tracks https://github.com/GMOD/jbrowse/issues/254

An alternative solution could possibly use something like the plugin multibigwig also, which basically just makes all the 50 bigwig files load as a single track https://github.com/elsiklab/multibigwig

Multibigwig can apply max_score or autoscaling across all the bigwigs at once too. It will probably be a little slow with 50 bigwigs, but I think it could work
