### ISSUE TITLE
Extract Spliced Gene sequences (without  introns)

### ISSUE THREAD

**Issue by deepak31a** [GMOD/jbrowse#910]
HI.. I am using JBrowse platform for browsing genome of my organism. I have set tracks of Genome and Genes. I can see the gene features and able to see the sequences of genes (with CDS and Introns) and multiple CDS (within on gene). But I am not able to see the Spliced Gene sequences (All CDS sequences, without introns as one complete CDS of the gene). Could anyone please help me to achieve this. 
Thanks in advance,
best regards'
Deepak

**Comment by colindaven** [comment]
Hi,
you can use the FeatureSequence plugin for this:

https://gmod.github.io/jbrowse-registry/#!?page=2

Best wishes,
Colin
