### ISSUE TITLE
Feature density for in-memory adaptor

### ISSUE THREAD

**Issue by hkmoon** [GMOD/jbrowse#913]
Currently, I am using GTF, GFF in-memory adaptor which is really useful and very straightforward.
However, when I zoom-out, it does not give any histogram of the feature density.
Can I make histogram by changing some configuration? Or, is there no feature density transition for in-memory adaptor cases?

**Comment by cmdcolin** [comment]
There is code for histograms to be generated dynamically from feature data but I think what's missing for the in-memory is that it doesn't implement the stats calculations like getGlobalStats. Therefore the genome browser doesn't get any clues as to when to display the histograms. That's just a guess though

**Comment by hkmoon** [comment]
Thank you for the clarifying it. I thought it was due to the my configuration.
I suppose that the ```getRegionFeatureDensities``` function is a quite heavy operation especially on the big files unless the index files are provided.
