### ISSUE TITLE
The refSeqOrder is not customisable

### ISSUE THREAD

**Issue by liub1993** [GMOD/jbrowse#919]
In some case, the reference sequence name is not ordered in proper way, for example, the human chromosomes, named from
` '1', '2', '3', ..., '22', 'X', 'Y', 'MT'`,
but the browser would order the names like this: 
`'1', '10', '11', '12', ..., '2', '21', ...`
 when the configuration is set to order by name, and that's not well read for us.

**Comment by dsenalik** [comment]
I am proposing a different way to accomplish this goal in issue #925 by preserving the order from the input FASTA file

**Comment by rbuels** [comment]
working branch: https://github.com/GMOD/jbrowse/compare/refseqorder
