### ISSUE TITLE
travis build failing

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#922]
I was experimenting with using the matrix node version testing:
```
language: node_js
node_js:
    - "8"
    - "7"
    - "6"
    - "5"
```
since @nathandunn had verified the lower node version limit is "5". 

The change of language causes problems in the build: 
```
Can't locate DateTime.pm in @INC (you may need to install the DateTime module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .).
BEGIN failed--compilation aborted.
make: *** [release-normal] Error 2
```
even though the given perl module is apparently installed without error.

**Comment by enuggetry** [comment]
Explore this
https://stackoverflow.com/questions/32358197/travis-ci-install-perl-module-with-non-perl-language

**Comment by enuggetry** [comment]
I will circle back to this.

**Comment by nathandunn** [comment]
I used: 

```
node_js:
  - "iojs"
```

and it worked for Apollo

**Comment by enuggetry** [comment]
using language: perl work, but 
```
node_js:
  - "iojs"
  - "8"
  - "7"
```
seems to be ignored

**Comment by rbuels** [comment]
travis builds seem to be OK now

**Comment by rbuels** [comment]
Sigh, travis builds are still failing intermittently.

![image](https://user-images.githubusercontent.com/73749/35476589-4fd65d50-0367-11e8-95d3-d279811ff2af.png)

**Comment by nathandunn** [comment]
If it’s a Travis system error I wouldn’t worry about it.  Or do you think it’s possibly some locking condition?  

Either way if you run it 5 more times and it’s green each time it may have just been a network system blip.  


Nathan

**Comment by rbuels** [comment]
Yeah, I want to see if there's something that can be done on our end to
make it more robust running on travis. Because having builds that aren't
reliable is a big drag on a project.

**Comment by nathandunn** [comment]
They’ve moved their default images so I had to do some stuff with Apollo.  Otherwise I expect network or Travis related dependency issues about every other month. 

Nathan
