### ISSUE TITLE
refSeqOrder preservation from input fasta file

### ISSUE THREAD

**Issue by dsenalik** [GMOD/jbrowse#925]
In reference to previous closed issue #867 "Custom Sorting Reference Sequence" and open issue #919 "The refSeqOrder is not customisable", I propose a new parameter to prepare-refseqs.pl of "--unsorted" which will use the sequence order from the input FASTA file or gff file to control the order in the generated json output file. Currently the output is always alphabetically sorted. I have a pull request (#924) hopefully implementing this new feature (this is my first pull request so be gentle).

**Comment by liub1993** [comment]
It' a good solution! But also, in some cases, the sequence order from FASTA file was sorted by ascii and not by common sense.

**Comment by rbuels** [comment]
Great! Incorporating this and reconciling with other suggestions. Doing this in the refSeqOrder branch. https://github.com/GMOD/jbrowse/compare/refseqorder

**Comment by rbuels** [comment]
oops meant to put that on the pull req

**Comment by rbuels** [comment]
working branch: https://github.com/GMOD/jbrowse/compare/refseqorder
