### ISSUE TITLE
plugins with desktop version

### ISSUE THREAD

**Issue by bhofmei** [GMOD/jbrowse#927]
I'm not sure what's going on or what I'm doing wrong, but I can't load any plugins when using the electron desktop version of JBrowse (osx). I either get a "no such file or directory" error for the trackList.json with the sample data or syntax error with a custom data directory.

**Comment by enuggetry** [comment]
Did the pre-installed plugins work?

**Comment by bhofmei** [comment]
So I narrowed down the problem a bit more. When using the sample data, no plugins can be loaded. The sample data already loads the pre-installed plugins, so when I try to load them again, I get an error. This could be from just loading it again since JBrowse sometimes does weird things when the same plugin is declared multiple times. With the sample data, loading a custom plugin causes the same error though.

Using a custom data directory, everything seems to be working okay now. I had a sorta syntax error in the trackList.json causing a problem (it was a hanging comma, which isn't flagged when running it in the browser but caused an issue for the desktop version).
