### ISSUE TITLE
"outrons" not rendered with neat features

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse#931]
For features that start and/or end with introns (apparently called "outrons" sometimes), NeatCanvasFeatures doesn't render them at all, though JBrowse is aware that there is more to the feature, since it draws the strand arrows in the right place (which is visually confusing, since the strand arrow is sitting out there in nowheresville).  This may also be an issue with NeatHTMLFeatures but I haven't tested it.  Example screenshots are below.

"regular" features"
<img width="737" alt="regular features" src="https://user-images.githubusercontent.com/274751/31294349-8da5041e-aaa8-11e7-8712-dfbe130fe4bd.png">

Neat features:
<img width="735" alt="neatfeatures" src="https://user-images.githubusercontent.com/274751/31294375-a52caa7e-aaa8-11e7-8e17-70d8fa141932.png">

**Comment by nathandunn** [comment]
@rbuels  I'm happy to test this, but I think its is more of @enuggetry 's code.

**Comment by enuggetry** [comment]
I can address it.

**Comment by enuggetry** [comment]
![image](https://user-images.githubusercontent.com/10053377/36293636-0a9f7e8c-1290-11e8-8c25-d9e611c311f9.png)

Red is HTML
Yellow is Canvas

**Comment by nathandunn** [comment]
👍   Looks great.
