### ISSUE TITLE
Force track refresh in javascript

### ISSUE THREAD

**Issue by Kador-phd** [GMOD/jbrowse#934]
I have inserted some inputs field in the feature detail box to update the database.
I would like to be able to reload/refresh some tracks in javascript.
I am not a dojo specialist so if you can tell how to do it.

**Comment by nathandunn** [comment]
I would shoot an email to the list:

https://sourceforge.net/p/gmod/mailman/gmod-ajax/ <https://sourceforge.net/p/gmod/mailman/gmod-ajax/>

and look in the archives:

http://gmod.827538.n3.nabble.com/JBrowse-Support-f815920.html <http://gmod.827538.n3.nabble.com/JBrowse-Support-f815920.html>

I would maybe look through here first:

https://github.com/GMOD/jbrowse/tree/master/src/JBrowse/View/TrackList <https://github.com/GMOD/jbrowse/tree/master/src/JBrowse/View/TrackList>


Nathan

**Comment by Kador-phd** [comment]
Ok I found it. I am not sure thats the best way to do it but it works.
I beautified dojo.js and fonud the method. 
There is a method in the jbrowse object that refreshes all the tracks.
So you have created our Jbrowse object:
<var JBrowse = new Browser( config );>
the method is:
<JBrowse.view.redrawTracks();>
which call the method in dojo.js
< 
redrawTracks: function() {
      this.trackIterate(function(a) {
               a.hideAll()
      });
      this.showVisibleBlocks(!1)
}
>
I added a method based on this method to refresh only one track with the track name:
<
redrawATrack: function(trackname) {// ADDED BY DIDIER CROES redraw a specific track
            this.trackIterate(function(a) {
                  if (a.key==trackname){
                         a.hideAll();
                  }
             });
             this.showVisibleBlocks(!1)
      }
>
I added this method bellow the other one and you can call this method:
< 
JBrowse.view.redrawATrack("My Track To Refresh");
>
and voilà...
Didier
