### ISSUE TITLE
Automate GFF3Tabix Feature Density

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#935]
Is it possible to show a feature density histogram once the feature density or zoom level exceed some threshold for the `GFF3Tabix` `storeClass`?

This is possible for BAM files and also works when importing GFF3 using `flatfile-to-json.pl` but I can't figure out if it's possible for `GFF3Tabix`.

**Comment by nathandunn** [comment]
That storeClass does support globalStats in theory.   Might be better to ask on the mailing list: http://gmod.org/wiki/JBrowse#Contacts_and_Mailing_Lists to see if anyone has had success configuring it to show densities.  

This is something that we'll also want, so this would be great info to have.

**Comment by cmdcolin** [comment]
Technically any canvas features track can use an external bigwig file as a feature density histogram

See http://gmod.org/wiki/JBrowse_Configuration_Guide#Configuring_Summary_Histograms

Could use bedtools genomecov on the gff perhaps to help create it

**Comment by nathanhaigh** [comment]
That's the way I was heading @cmdcolin. However, this raises another question:

- How do I get the histogram to autoscale locally?

This is possible using the `BigWig` `storeClass` with `XYPlot` `type` and using `autoscale = true`. If possible, this would be great for tracks with more variable coverage without the need for a separate coverage track e.g. RNA-Seq tracks where you might have `BAM` files and an accompanying `BigWig` file.

**Comment by nathandunn** [comment]
![screen shot 2018-01-18 at 1 58 20 pm](https://user-images.githubusercontent.com/751274/35123572-afa3b42e-fc57-11e7-810a-44093190a099.png)

**Comment by nathandunn** [comment]
Moving the default screenHistoryDensity down, it shows up.   I think we should be able to implement store.getRegionFeatureDensities and it should work.  If users choose to use their own histogram store it should be called first (or we can make sure it does)

                    else if( this.config.histograms.store || this.store.getRegionFeatureDensities ) {
