### ISSUE TITLE
Color descriptions according SNP effect

### ISSUE THREAD

**Issue by shenweima** [GMOD/jbrowse#937]
Hi, jbrowse,

I have a vcf file, I want to achieve this: Single Nucleotide Variants (SNVs) are color-coded depending on the severity of the variant effect and SNVs that are most severe are colored in RED (stop_gained, stop_lost, splice_site changes), medium severity SNVs are colored in PURPLE (missense/amino acid change), the least severe SNVs are colored in GREEN (synonymous/no amino acid change).

Like the this website:https://dubcovskylab.ucdavis.edu/jbrowse/?data=data%2Fjson%2Fiwgsc-2BL&loc=IWGSC_CSS_2BL_scaff_8049180%3A1..13754&tracks=tgacannot%2Cmipsannot%2CsnpsgenomeHC%2CcadsnpsHC%2Cmulticontigs%2Ccadmulticontigs%2Cblast%2CDNA&highlight=IWGSC_CSS_2BL_scaff_8049180%3A13574..13927&addFeatures=%5B%7B%22seq_id%22%3A%22IWGSC_CSS_2BL_scaff_8049180%22%2C%20%22start%22%3A%2013574%2C%20%22end%22%3A%2013927%2C%20%22name%22%3A%20%22MyBLASTHit_1%22%2C%20%22description%22%20%3A%20%22evalue%204e-180%22%7D%5D&addTracks=%5B%7B%22label%22%3A%22blast%22%2C%22store%22%3A%22url%22%2C%22type%22%3A%22JBrowse%2FView%2FTrack%2FHTMLFeatures%22%2C%20%22key%22%3A%22BlastHSP%20Results%22%7D%5D%0A

I build a local jbrowse and I also want to show the SNVs by its effect. Can you tell me how to set this?

This is my vcf tracks setting.

{
"storeClass" : "JBrowse/Store/SeqFeature/VCFTabix",
"urlTemplate" : "tracks/marker/90k_snp.eff.vcf.gz",
"tbiUrlTemplate":"tracks/marker/90k_snp.eff.vcf.gz.tbi",
"label" : "wheat_90K",
"category" : "Marker",
"type" : "JBrowse/View/Track/CanvasVariants",
"key" : "wheat_90K"
},

 And the SNP annotation using snpEff,the format is like below.

  #CHROM POS     ID        REF  ALT   QUAL FILTER
  ##SnpEffVersion="4.3p (build 2017-06-06 09:55), by Pablo Cingolani"
  ##SnpEffCmd="SnpEff  IWGSCv1.0 data/90k_snp.vcf "
  ##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO' ">
  ##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
  ##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
  chr1A   798845  BobWhite_c1859_469  T   C   1000.0  PASS    ANN=C|missense_variant|MODERATE|TraesCS1A01G002000LC|TraesCS1A01G002000LC|transcript|TraesCS1A01G002000LC.1|protein_coding|1/1|c.226A>G|p.Ile76Val|226/426|226/426|76/141||,C|upstream_gene_variant|MODIFIER|TraesCS1A01G001900LC|TraesCS1A01G001900LC|transcript|TraesCS1A01G001900LC.1|protein_coding||c.-721A>G|||||511|,C|downstream_gene_variant|MODIFIER|TraesCS1A01G002100LC|TraesCS1A01G002100LC|transcript|TraesCS1A01G002100LC.1|protein_coding||c.*312A>G|||||312|
  chr1A   1145448 BS00000713_51   A   G   1000.0  PASS    ANN=G|synonymous_variant|LOW|TraesCS1A01G001800|TraesCS1A01G001800|transcript|TraesCS1A01G001800.1|protein_coding|2/2|c.270A>G|p.Gln90Gln|406/892|270/420|90/139||,G|intron_variant|MODIFIER|TraesCS1A01G002200LC|TraesCS1A01G002200LC|transcript|TraesCS1A01G002200LC.1|protein_coding|1/1|c.116+52T>C||||||
  chr1A   1145499 BS00023176_51   C   T   1000.0  PASS    ANN=T|splice_donor_variant&intron_variant|HIGH|TraesCS1A01G002200LC|TraesCS1A01G002200LC|transcript|TraesCS1A01G002200LC.1|protein_coding|1/1|c.116+1G>A||||||,T|synonymous_variant|LOW|TraesCS1A01G001800|TraesCS1A01G001800|transcript|TraesCS1A01G001800.1|protein_coding|2/2|c.321C>T|p.Tyr107Tyr|457/892|321/420|107/139||;LOF=(TraesCS1A01G002200LC|TraesCS1A01G002200LC|1|1.00)
  ​

**Comment by enuggetry** [comment]
Hi,
There is an example that Hayes gives in here that may help:
http://gmod.827538.n3.nabble.com/Gmod-ajax-custom-color-vcf-tracks-with-cgi-bin-script-url-callback-td4050969.html

**Comment by rdhayes** [comment]
Hi,

Here's a more recent version that handles EFF or the more recent ANN
attributes and is a little more robust in handling array value access:

variation_color = function(feature) {
    var effArray = feature.get('EFF') || effArray = feature.get('ANN') ||
feature.get('effect');
    if ( effArray && typeof effArray == 'object' && 'values' in effArray )
        effArray = effArray.values;
    if( effArray && ! Array.isArray( effArray ) )
        effArray = [effArray];
    var isHigh = false;
    var isModerate = false;
    for ( var i in effArray ) {
        if ( /HIGH/.test ( effArray[i] ) ) { isHigh = true; }
        if ( /MODERATE/.test ( effArray[i] ) ) { isModerate = true; }
    }
    if ( isHigh ) { return 'red'; }
    if ( isModerate ) { return 'goldenrod'; }
    if (feature.get('type') != 'SNV') {
        return 'green';
    }
    else {
        return 'blue';
    }
  }

Richard D. Hayes, Ph.D.
Joint Genome Institute / Lawrence Berkeley National Lab
http://phytozome.jgi.doe.gov

**Comment by thomasvangurp** [comment]
For anyone googling, in jbrowse 2 you can achieve this filtering using:
```javascript
 const variation_color = feature => {
          var info = feature.get('INFO');
          var effArray = info && (info['EFF'] || info['ANN'] || info['effect']);
          if (effArray && typeof effArray == 'object' && 'values' in effArray) {
            effArray = effArray.values;
          }
          if (effArray && !Array.isArray(effArray)) {
            effArray = [effArray];
          }
          var isHigh = false;
          var isModerate = false;
          for (var i in effArray) {
            if (/HIGH/.test(effArray[i])) { isHigh = true; }
            if (/MODERATE/.test(effArray[i])) { isModerate = true; }
          }
          if (isHigh) { return 'red'; }
          if (isModerate) { return 'goldenrod'; }
          if (feature.get('type') != 'SNV') {
            return 'green';
          } else {
            return 'blue';
          }
        };

        // If the feature has 'EFF', 'ANN', or 'effect' attributes in its 'INFO' object, assume it's a VCF file
        var info = feature.get('INFO');
        if (info && (info['EFF'] || info['ANN'] || info['effect'])) {
          return variation_color(feature);
        }
```

in a custom plugin, as described in https://jbrowse.org/jb2/docs/config_guides/jexl/

**Comment by cmdcolin** [comment]
thanks for adding this @thomasvangurp we could probably add this to our docs as an example
