### ISSUE TITLE
Access Localstorage with function defined in tracks.conf

### ISSUE THREAD

**Issue by thomasvangurp** [GMOD/jbrowse#938]
I would like to open a popup for a custom cgi script that needs to know the current range (start and end position) of the chromosome being viewed. This information is stored in the local storage of the browser, but how can I access this? 
<img width="900" alt="solynta_jbrowse_chr07_18265949__18648036" src="https://user-images.githubusercontent.com/1284722/32676863-74e38106-c65c-11e7-837c-4b2905dd5ada.png">

**Comment by vivekkrish** [comment]
Hi @thomasvangurp - Just a thought, have you tried invoking `JSON.parse(localStorage.getItem('GenomeBrowser-location-potato'))` in your function definition?

**Comment by vivekkrish** [comment]
Also, the LocalStorage item `GenomeBrowser-refseq-potato` should give you the name of the currently visible reference sequence, which could be used to extract the coordinates from the JSON object in the `location` LocalStorage item.

**Comment by rbuels** [comment]
Sorry for the slow response!

Try the following one-liner for grabbing the current location from `localStorage`:

```
JSON.parse(localStorage.getItem('GenomeBrowser-location-volvox'))[localStorage.getItem('GenomeBrowser-refseq-volvox')].l
```

Closing this issue for now, reopen if we can be of further assistance!
