### ISSUE TITLE
Client side phantomjs + jasmine tests broken against master

### ISSUE THREAD

**Issue by keiranmraine** [GMOD/jbrowse#941]
Hi,

I've just discovered that running my plugin tests will not run against the master branch of jbrowse.  It's fine for the 1.12.3-release.  By will not run I mean it doesn't get as far as loading the test spec and I see the following error:

```
Error: timeout
  http://localhost:8000/test/dojo/dojo.js:1893
src: dojoLoader
info: [object Object]
.
...
No specs found
```

Have you considered using a more gitflow style development structure where all features are merged to a develop branch and master only ever has code merged on release?

**Comment by nathandunn** [comment]
I think that makes a lot of sense for the next release as well.    Maybe something we can talk about next week @enuggetry? 

Nathan

**Comment by enuggetry** [comment]
yes, thank you.  I think it makes sense to use the git-flow model moving
forward.
