### ISSUE TITLE
Unable to load */jbrowse/jbrowse.conf status:0

### ISSUE THREAD

**Issue by maolingfengZJU** [GMOD/jbrowse#942]
What's the problem with that?
The JBrowse version is 1.12.3, and the JBrowse can be successfully visited in the internal net of our school,
but not the external network. 
So anyone who have experienced this problem can give me some  advices?
Thanks a lot in advance!!!

**Comment by nathandunn** [comment]
Maybe good to post on the list as well as provide more detail.

**Comment by maolingfengZJU** [comment]
thank you for suggestions!!
The JBrowse web can be visited successfully in the local network, but outside the local network, 
the detailed information of the problem in the web is below,
Congratulations, JBrowse is on the web!
However, JBrowse could not start, either because it has not yet been configured and loaded with data, or because of an error.

If this is your first time running JBrowse, click here to follow the Quick-start Tutorial to show your data in JBrowse.

However, it appears you have successfully run ./setup.sh, so you can see the Volvox test data here.

Otherwise, please refer to the following resources for help in setting up JBrowse to show your data.

Quick-start tutorial - get your data visible quickly with minimum fuss
JBrowse Configuration Guide - a comprehensive reference
JBrowse wiki main page
biodb-to-json.pl configuration reference
HTMLFeatures CSS class reference - prepackaged styles (CSS classes) for HTMLFeatures tracks
Error message(s):
RequestError: Unable to load http://localhost/jbrowse/jbrowse.conf status: 0.

**Comment by nathandunn** [comment]
This isn’t really a GitHub issue, though.  Please post the same information to the jbrowse list to get help:

http://gmod.org/wiki/JBrowse#Contacts_and_Mailing_Lists <http://gmod.org/wiki/JBrowse#Contacts_and_Mailing_Lists>

Nathan

**Comment by cmdcolin** [comment]
Just an idea but could be a firewall blocking requests ".conf" files? If you just view the http://yoursite.com/jbrowse/jbrowse.conf from outside and get some sort of error, then this could be the case. The firewall is just an idea since it seems like it only affects your users outside the network and since the web says firewalls can result in status code 0 from ajax calls https://stackoverflow.com/questions/872206/http-status-code-0-what-does-this-mean-for-fetch-or-xmlhttprequest

If this is the case your could possibly rework the config to not use the .conf files but it would be a little tricky(can add my ideas if there is interest). Alternatively you can use an older jbrowse version from before .conf files were used (anything like 1.10 and before might work)

**Comment by maolingfengZJU** [comment]
Thank you so much for your advices @nathandunn

**Comment by nathandunn** [comment]
I think you meant @cmdcolin.   Both of us browse the mailing list as well.   

I'm going to close this for now as its appears to be a bug in your server configuration.   However, feel free to send to the email list (gmod-ajax@lists.sourceforge.net) with these details.

**Comment by maolingfengZJU** [comment]
Thank you for your advices.  I have try to close the filewall, but it doesn't work. I have tried several version of jbrowse, from 1.10.1 to 1.12.3, it's a good news that the 1.10.1 didn't have the file 'jbrowse.conf', but the web "you JBrowse is on the web "can even appear until 1.11.6 with the problem "jbrowse.conf status : 0".  And the system of my server is CentOS6.7, CentOS6.8 and CentOS 7.3, i tried  all these 3 server, but the same problem appears in all of them. 

In another way to not use the *.conf file,  maybe just configure all the file from the first without *.conf file, but i cannot figure it out. And the version 1.10 or before, i get that there is no *.conf in them, but it cannot be on the web from the visit of outside network!

**Comment by cmdcolin** [comment]
What error message appears with 1.10? It seems like it could not be jbrowse.conf related because it doesn't have that file.

**Comment by maolingfengZJU** [comment]
yeah, the jbrowse with version 1.10 or lower doesn't have the jbrowse.conf, but i don't know why, the homepage of the  jbrowse with version 1.16 or lower appear nothing. And just "hello,world" can appear in the index.html.

**Comment by maolingfengZJU** [comment]
this is just the website of jbrowse 1.10: http://ibi.zju.edu.cn/test10/
and the website of jbrowse 1.12.3:http://ibi.zju.edu.cn/jbrowse/
and the website of jbrowse 1.11.2:http://ibi.zju.edu.cn/test11/
you can just see hello,world! in the top of test10 and test11.

**Comment by maolingfengZJU** [comment]
The version 1.10 works now, we failed before as we tested it in my phone, and it works in the PC, thank you so much @cmdcolin
