### ISSUE TITLE
biodb-to-json.pl runs indefinitely while it creates large temp files

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/jbrowse#946]
While running setup.sh, the `biodb-to-json.pl` step keeps running indefinitely while it generates large temp files to the point of filling all available disk space.

The behavior is observed only on **MacOS High Sierra**.

This definitely makes `setup.sh` impossible to run unless you comment out `biodb-to-json.pl` for Volvox and Yeast.

More comments and details can be found [here](https://github.com/GMOD/Apollo/issues/1820).

**Comment by deepakunni3** [comment]
@nathandunn FYI

**Comment by hsiaoyi0504** [comment]
Just want to reference the issue correctly, GMOD/Apollo#1820

**Comment by hsiaoyi0504** [comment]
Related to PR #945.

**Comment by rbuels** [comment]
This is fixed with #945 and 7b2f7a4d268e07ebf0036d1306c18c6878f5060f
