### ISSUE TITLE
Issue with IndexedFasta

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#947]
I'm trying to set up a JBrowse VM and use an indexed FASTA file for the reference. However, no matter what I do the web browser just wants to download the huge FASTA file instead of displaying just the bit in view.

What's annoying me is that I've set this up before earlier this year and have it working on another VM, but this new one is driving me crazy by not working!

Any pointers would be much appreciated!

**Comment by nathandunn** [comment]
Can you post both the trackList’s and the respective directories they should be hitting (just the files and sizes, not necessarily the contents)?

**Comment by nathanhaigh** [comment]
`trackList.json`:

```json
{
   "tracks" : [
      {  
         "label" : "DNA",
         "category" : "Reference sequence",
         "key" : "Reference sequence",
         "storeClass" : "JBrowse/Store/Sequence/IndexedFasta",
         "urlTemplate" : "seq/my.fasta",
         "faiUrlTemplate" : "seq/my.fasta.fai",
         "type" : "SequenceTrack",
         "showForwardStrand": true,
         "showReverseStrand": false,
         "showTranslation": false,
         "useAsRefSeqStore" : true
      }
   ],
   "formatVersion" : 1
}
```

`tracks.conf`:

```
# empty
```

Files:

```bash
$ tree -s data/seq/
data/seq/
├── [14789716499]  my.fasta
├── [       1672]  my.fasta.fai
└── [       5798]  refSeqs.json

0 directories, 3 files
```

**Comment by nathanhaigh** [comment]
I have the same entries on another VM which does work! Could it be an `apache2` configuration issue? If so, any ideas!?

**Comment by cmdcolin** [comment]
It could be a thing where there is a weird interaction with mod_deflate. Here is another user with the same issues. You could turn off the module or selectively disable it for the FASTA file types https://github.com/GMOD/jbrowse/issues/818

**Comment by nathanhaigh** [comment]
It sounds like the same issue, however disabling the `deflate` module did not fix the issue. Some further debugging does suggest an `apache2` configuration difference, but I can't seem to find the difference between my two setups.

Due to time constraints I'm going to use the `--fasta` argument to `bin/prepare-refseqs.pl` as this seems to work fine. I'll try to come back to this in the new year.

**Comment by rbuels** [comment]
Is the non-working server discarding or ignoring the `Range` HTTP header? JBrowse uses range requests to fetch chunks of IndexedFasta files. If a server ignores the `Range` header, it typically responds to a request for the file with the whole file.

**Comment by cmdcolin** [comment]
Maybe close issue?

**Comment by cmdcolin** [comment]
Can add comments here or open new issue if there are updates
