### ISSUE TITLE
Support for CSI index instead of BAI

### ISSUE THREAD

**Issue by sagnikbanerjee15** [GMOD/jbrowse#954]
Hello,

I work with Barley where most of the sequences are longer than 2^29-1. I have RNA-Seq data which map to regions beyond 2^29 on the chromosomes. I generally provide the .bam file to JBrowse. For this I need to generate the .bai file using samtools index. But this command fails since the there are regions which cannot be included in the bai index. Instead samtools recommends me to generate a .csi index file. Can JBrowse work with CSI index files instead of BAI? Please help.

Thank you.

**Comment by keiranmraine** [comment]
FYI: https://github.com/GMOD/jbrowse/issues/926

**Comment by rbuels** [comment]
Duplicate of #926.  Closing.
