### ISSUE TITLE
track metadata should be able to override the track's "key"

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#957]
When a "key" attribute is set in a track's metadata, I think that should be used for the track label if a key is not already used in the track configuration.

On Sun, Jan 14, 2018 at 4:11 PM Loraine Guéguen <lgueguen@sb-roscoff.fr> wrote:
> Hi,
> 
> I have a JBrowse instance (1.12.1) with >500 tracks.
> I use faceted trackSelector, and the metadata are stored in a CSV file
> loaded with JSON attribute "trackMetadata".
> 
> Each track has a short name (defined in the CSV file) which is a
> human-readable name. I would like that this short name is displayed as
> track "title" when the track is displayed on the browser, that is to
> say, I'd like that this short name is used as "key" for the track.
> 
> Is it possible ?
> (naming the short-name CSV column as "key" is not working)
> 
> And the best would be, for a track, that the key defined in the CSV file
> overrides the key defined in the trackList.json file.
> 
> Looking forward to reading your answers.
> Thanks
> 
> Loraine

**Comment by loraine-gueguen** [comment]
It would be great to have this in the codebase!
Yes, I guess it is better to keep the current behavior by making the "key" in the track metadata only be used if the key in the trackList.conf is missing. I will delete the "key" attributes in my trackList.json.
FYI, I send the same question on the apollo list. Deepak Unni answered and created a JBrowse plugin with this functionality. See here:  http://gmod.827538.n3.nabble.com/add-track-key-attribute-from-CSV-metadata-file-td4059024.html, https://github.com/deepakunni3/RenameTracks
@deepakunni3

**Comment by deepakunni3** [comment]
@rbuels @loraine-gueguen I agree. If we can have this functionality out of the box, even better 👍

**Comment by loraine-gueguen** [comment]
When is planned the next JBrowse release ?

**Comment by rbuels** [comment]
@loraine-gueguen we are still setting up our release schedule, so things are a little bit in flux, but right now it's scheduled to be on February 14, and then every two weeks after that

**Comment by loraine-gueguen** [comment]
@rbuels ok, great! thanks
