### ISSUE TITLE
make a useful error message when a glyph class can't load

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#968]
![image](https://user-images.githubusercontent.com/73749/35590318-4f895df6-05bb-11e8-88db-e5db63c4689e.png)

the `GlyphClass` ends up being the string "not-a-module" if it can't load the class.  We need to print a useful error in this case like "could not load module "+glyphClassName

**Comment by cmdcolin** [comment]
Maybe similar to https://github.com/GMOD/jbrowse/pull/915

**Comment by rbuels** [comment]
@cmdcolin care to add error messages to this to your #915?  ;-)
