### ISSUE TITLE
fix gff3tabix for HTMLFeatures genes and histograms

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#969]
- [ ] test against HTMLFeatures, as well apply current fixes to #780 
   - [ ] fix retrieving feature densities
   - [ ] apply current fixes in projection from #780 and projection
 add volvox example with BigWig if not there

 add volvox exmple without BigWig

 adjust feature density to sane default, confirm adjustment

Based on #956

**Comment by cmdcolin** [comment]
You might consider looking at the code here https://github.com/GMOD/jbrowse/tree/allow_gene_htmlfeatures (also referenced here #974)

This allows rendering transcript subfeatures from a parent gene


![screenshot-localhost-2018 02 17-23-48-01](https://user-images.githubusercontent.com/6511937/36348412-56b2f778-143d-11e8-9de1-31cca4d5769f.png)


The current code on this branch appears to render like this

![screenshot-localhost-2018 02 17-23-48-28](https://user-images.githubusercontent.com/6511937/36348416-654155dc-143d-11e8-9df6-afcae9809e6a.png)

**Comment by rbuels** [comment]
I think all of this is taken care of in the dev branch now, please have a look and reopen if not
