### ISSUE TITLE
range calls for express server

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#970]
The built-in express server is probably not setup for range requests.

**Comment by rbuels** [comment]
Been working fine for me so far testing the Volvox data. Is breaking for you?

**Comment by enuggetry** [comment]
Just wanted to double check because I didn't believe express did this by default, as would be needed by indexed format.

**Comment by rbuels** [comment]
Seems good.  This is the express server running on my local, it's properly producing the Accept-Ranges and Content-Range headers, seems to be accepting the Range header.
