### ISSUE TITLE
load a specific type of feature from gff3tabix

### ISSUE THREAD

**Issue by Yating-L** [GMOD/jbrowse#974]
I can use the --type argument for flatfile-to-json.pl to only load mRNA/transcript from source gff3 file. Now I'd like to use gff3tabix instead. Are there any equivalent methods to load a specific type of features?  Thank you!

**Comment by nathandunn** [comment]
@Yating-L  You should just point to the gff3 tabix file.  If you look at the in-memory GFF3Tabix adapter for volvox it should work.   Keep in mind, there are still a few issues (#969),  #780, #935. 

Hope to have some fixes for those, soon.  However, if its a limited range and you are using Canvas tracks (and are JBrowse only) it should work fairly well.

**Comment by Yating-L** [comment]
@nathandunn It works when "mRNA" is in column 3 of the GFF. But not work when "transcript" is in column 3. It looks like loading "mRNA" is the default setting for HTMLFeatures [load subfeatures](http://gmod.org/wiki/JBrowse_FAQ#My_HTMLFeatures_don.27t_show_up_with_subfeatures.2C_why_not.3F). I might be wrong. 

Where can I find "the in-memory GFF3Tabix adapter for volvox"? Thanks!

**Comment by cmdcolin** [comment]
You can set "transcriptType": "transcript" in your config to fix that particular issue of transcript instead of mRNA in column 3

**Comment by nathandunn** [comment]
I think that is definitely the fix if there is only the one type of type, but if you have both mRNA and transcripts (as well as other transcript types)?   Or is it possible to provide multiple transcript types?   (we’ll have to fix this eventually)

**Comment by Yating-L** [comment]
@cmdcolin I think this only works for CanvasFeature. I need to use HTMLFeature for Apollo/JBrowse.

**Comment by nathandunn** [comment]
@Yating-L  This is on my list of things to fix.  I have a partial fix for HTMLFeatures here (though I'm going to abandon this PR): https://github.com/GMOD/Apollo/pull/1822/files#diff-09b50a85a7f9125fad0738f4dc234797R1031  probably when solving this issue #969.   

I think #956  (Canvas GFF3Tabix histograms) might need to be integrated first (hopefully this week).  Feel free to take a stab at the fix, though.   

The other problem with HTMLFeatures was that if you include a gene in the GFF3 it ONLY shows the top-level by default.   I try to incorporate that fix, as well, but I doubt it covers all types or is sufficiently configurable.    

The code for both Tabix and HTMLFeatures is pretty readable.  I hope to get them both out this month, but feel free to start fixing the HTMLFeatures code for tabix (I think they are small fixes relative to the PR).

**Comment by cmdcolin** [comment]
I see. I guess for HTMLFeatures, the fundamental problem is that HTMLFeatures doesn't display the individual transcripts when loaded at the gene level. Anything sort of aside from that like filtering on type for gff3tabix is sort of a workaround to that fundamental issue


I have looked into a fix for this fundamental problem and I think it could be done


For example here is an example

```
diff --git a/src/JBrowse/View/Track/HTMLFeatures.js b/src/JBrowse/View/Track/HTMLFeatures.js
index 5465c30..a2cb740 100644
--- a/src/JBrowse/View/Track/HTMLFeatures.js
+++ b/src/JBrowse/View/Track/HTMLFeatures.js
@@ -696,14 +696,36 @@ define( [
              */
             addFeatureToBlock: function( feature, uniqueId, block, scale, labelScale, descriptionScale,
                                          containerStart, containerEnd ) {
-                var featDiv = this.renderFeature( feature, uniqueId, block, scale, labelScale, descriptionScale,
-                    containerStart, containerEnd );
-                if( ! featDiv )
-                    return null;
+                var thisB = this;
+                if( feature.get('type') == 'gene') {
+                    var d = dojo.create('div');
+                    var feats = feature.get('subfeatures');
+                    if(!feats) {
+                        return null;
+                    }
+                    var featDivs = feats.map(function( feat ) {
+                        return thisB.renderFeature(feat, uniqueId + '_' + feat.get('id'), block, scale, labelScale, descriptionScale, containerStart, containerEnd);
+                    });
+                    featDivs.forEach(function( featDiv ) {
+                        d.appendChild( featDiv );
+                    });
+                    block.domNode.appendChild( d );
+                    if( this.config.style.centerChildrenVertically ) {
+                        featDivs.forEach(function( featDiv ) {
+                            thisB._centerChildrenVertically( featDiv );
+                        });
+                    }
+                    return d;
+                } else {
+                    var featDiv = this.renderFeature( feature, uniqueId, block, scale, labelScale, descriptionScale,
+                        containerStart, containerEnd );
+                    if( ! featDiv )
+                        return null;

-                block.domNode.appendChild( featDiv );
-                if( this.config.style.centerChildrenVertically )
-                    this._centerChildrenVertically( featDiv );
+                    block.domNode.appendChild( featDiv );
+                    if( this.config.style.centerChildrenVertically )
+                        this._centerChildrenVertically( featDiv );
+                }
                 return featDiv;
             },
```

This now allows you to load flatfile-to-json.pl on a GFF with --type gene and all individual transcripts can be displayed. Or, similarly, just use a gff3tabix with gene type features in it.

I'd be curious what @rbuels thinks about this type of approach

**Comment by nathandunn** [comment]
I think this would be good.   The other issue was that when block sizes didn't line up (with HTMLFeatures) it would only render exons for one block or the other.  The fix was to create alternate blocks so that there was no intersection of the block query and the transcripts.  Again, doesn't affect the canvas, but it should be in GFF3Tabix Histogram PR (if not, I'll put it there).

**Comment by nathandunn** [comment]
@cmdcolin  I merged this in (https://github.com/GMOD/jbrowse/pull/996/commits/d19f4e4ffcc647958d767553bf9463e1af35f7a9), which is similar to another fix I had in my client-side project branch (though sort of in tatters), but I can't remember what:

https://github.com/GMOD/jbrowse/issues/974#issuecomment-363218802

Its definitely better, but it seems to ignore Genes entirely.  I think we still want them in the model, if possible, but we don't want to render them.    It does something screwy to the introns, as well. 

![screen shot 2018-02-19 at 10 04 27 pm](https://user-images.githubusercontent.com/751274/36409588-2835c170-15c1-11e8-99ca-2aef794b68b3.png)

**Comment by nathandunn** [comment]
Either way its a step in the right direction.   My solution had them all stacked as you have shown here: https://github.com/GMOD/jbrowse/issues/969#issuecomment-366492627   

so it definitely fixed that problem.

**Comment by nathandunn** [comment]
@cmdcolin  Of course, this might be due to a weird interaction with neat features.    Granted, I had sort of gotten it working based on the Apollo code in branching where it was able to explicitly render the exon segments: https://github.com/nathandunn/Apollo/blob/2.1.0/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L947

**Comment by rbuels** [comment]
in the dev branch now, which is going into the 1.14.0 release, there is support for a `topLevelFeatures` configuration variable.

so if you have a GFF3+Tabix file with gene models, that you have to use with HTMLFeatures, you can set `topLevelFeatures = mRNA` and the mRNAs in the gene models will be treated by HTMLFeatures as top-level, and it can render them using its normal two-level rendering.

Sound good? Feel free to reopen if this turns out not to work.
