### ISSUE TITLE
add dot-object addFeatures

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#976]
From https://github.com/GMOD/jbrowse/pull/952#issuecomment-362000737

   https://apollo.nal.usda.gov/Drosophils%20bipectinata/jbrowse/?loc=scf7180000394085:914360..917628&tracks=DNA,Annotations,BlastResults&addTracks=[{"style": {"renderClassName":"blast-hit-20pct"},"label":"BlastResults","store":"url","type":"JBrowse/View/Track/HTMLFeatures"}]&addFeatures=[{ "seq_id":"scf7180000394085", "start": 914360, "end": 914389, "strand": "1", "name": "HSP:"},{ "seq_id":"scf7180000394085", "start": 917599, "end": 917628, "strand": "1", "name": "HSP:"}]

   need to interpret this:

    &addFeatures=[{ "seq_id":"scf7180000394085", "start": 914360, "end": 914389, "strand": "1", "name": "HSP:"},{ "seq_id":"scf7180000394085", "start": 917599, "end": 917628, "strand": "1", "name": "HSP:"}]

The dot-object library will handle this automatically.  The test-case will be:

    addFeatures.1.seq_id=scf7180000394085&addFeatures.1.start=914360&. . . . 

    addFeatures.2.seq_id=scf7180000394085&addFeatures.2.start=917599&. . . . 

So, here we need to interpret an array for this.

**Comment by rbuels** [comment]
@nathandunn does merging #978 close this?  Could you close if so
