### ISSUE TITLE
No call samples are displayed as reference homozygous ref(x) / ref (x)

### ISSUE THREAD

**Issue by carrere** [GMOD/jbrowse#980]
Dear JBrowse team, 
I noticed that sample without variant calling (GT = ./.) are not well displayed in the detail table . Column GT is set to ref(x) /ref(x) where x is the reference nucleotide.

I think the problem must be around this line (default value is refseq when a splitter is found).
https://github.com/GMOD/jbrowse/blob/33f932a02c0d8114b073079557778bdfcef17c15/src/JBrowse/View/Track/_VariantDetailMixin.js#L148

If I use GT = . il my VCF file, the GT column is well formed (i.e. empty) but no-call summary number is now false (because gt is no more an array https://github.com/GMOD/jbrowse/blob/33f932a02c0d8114b073079557778bdfcef17c15/src/JBrowse/View/Track/_VariantDetailMixin.js#L168)

Thanks for your help !

Sebastien

**Comment by rbuels** [comment]
@carrere could you also attach a screen shot of what the problem looks like in the detail box?

**Comment by cmdcolin** [comment]
I guess the idea is that having a genotype ./. means NO_CALL but jbrowse currently makes it just say reference allele e.g. ref(x)/ref(x) where x is the current letter of the reference genome in the View details popup. 

Note that I think ./. was sort of glitchy before this commit https://github.com/GMOD/jbrowse/commit/68e8845646952ca9e06cec4dd86726f382934571 but I guess still needs a little work.

**Comment by carrere** [comment]
@rbuels here is the problem:
![nocall](https://user-images.githubusercontent.com/1142779/35963579-796a479c-0cb5-11e8-8293-def59c425141.png)

**Comment by carrere** [comment]
Thanks @rbuels  and @cmdcolin  ! Works perfectly
