### ISSUE TITLE
npm installable jbrowse plugin model

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#981]
Develop a framework for an npm installable client-side plugin.

This might include:
1) copying or symlinking files/directories into the necessary locations.
Or perhaps JBrowse could be extended to recognize node_modules that are jbrowse plugins.
2) framework for injecting test data/tracks to showcase the plugin features.
3) a test harness for building `npm test` cases, with pre-baked phantomjs/selenium.
4) mechanism for auto inclusion into the plugin registry.

**Comment by erasche** [comment]
Happy to help this! Since @nathandunn owns "gmod" on there, we could have the travis job that's building our registry website automatically publish the modules however is best.

If you could develop some way that the npm module/directory/etc should be laid out, I'll gladly add that feature to the registry job!

**Comment by nathandunn** [comment]
I think now @rbuels and @enuggetry also own it.   I like the idea of an npm publish . . . 

I’m also wondering if we should add a template npm job.

**Comment by erasche** [comment]
You've fixed this @rbuels? Can you give us an example of how such an npm installable plugin should look?

**Comment by nathandunn** [comment]
Hopefully like this ;) 

https://github.com/GMOD/Apollo/pull/1870

**Comment by erasche** [comment]
Perfect, thanks. I bet I can auto-build that format for everything under gmod plugin registry.

**Comment by nathandunn** [comment]
I haven’t tested it yet but I think rob tested it with the plugins via npm.

Nathan
