### ISSUE TITLE
Fix Gradients - NeatCanvasFeatures

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbrowse#982]
gradient code was removed.

**Comment by rbuels** [comment]
Could you put some more detail here?  When and why was the gradient code removed?

**Comment by nathandunn** [comment]
@rbuels   For Apollo, we don't want the Gradient code there by default.   Visually it is initially nice, especially for screen shots, but we felt, as it didn't correlate to data values, that it was unnecessarily distracting.   

Either way, it should be configurable either way.  The default on or off is fine, as we don't activate by default.

**Comment by enuggetry** [comment]
I do recall the gradient features are configurable and disableable.
https://github.com/GMOD/jbrowse/tree/dev/plugins/NeatCanvasFeatures

Perhaps we should move the introns into the core.

It was done as a plugin for sake of demonstrating a plugin.

**Comment by nathandunn** [comment]
Yes.  I think there were problems with the configuration and unfortunately it didn’t get fixed properly.  

Moving it to the core (esp for canvas) would be a great idea, or as another track entirely (the old one could be canvasblockfeatures or something).

Nathan

**Comment by rbuels** [comment]
@enuggetry @nathandunn could one of you guys submit a pull req for this, it's currently assigned to 1.12.4, which is releasing on Wednesday morning

**Comment by nathandunn** [comment]
@rbuels   I'm not going to be able to get to it by Wednesday, but I'm happy to test someone else's PR.

**Comment by enuggetry** [comment]
I can do this.
