### ISSUE TITLE
can not turn on gradient for neatcanvasfeatures

### ISSUE THREAD

**Issue by nathandunn** [GMOD/jbrowse#993]
Went and tested #988   Definitely works well for NeatHTMLFeatures. 

For Canvas, I can't get them to turn at all now.   The flag seems to be set properly, but it never gets processed. 

We should probably also cleanup the doc for both https://github.com/GMOD/jbrowse/blob/dev/plugins/NeatHTMLFeatures/README.md and https://github.com/GMOD/jbrowse/blob/dev/plugins/NeatCanvasFeatures/README.md once they are both working.  

We may also want to fix it so the feature options are the name (linearGradient or gradientFeatures, etc.)

**Comment by nathandunn** [comment]
I thinks I gots a fix for this.

**Comment by rbuels** [comment]
This is an issue with #988, might have been better to just have this in that thread

**Comment by nathandunn** [comment]
I would, have but its already merged.

**Comment by nathandunn** [comment]
I hadn't a chance to test it.

**Comment by rbuels** [comment]
Sigh I mean #992

**Comment by nathandunn** [comment]
Ahh . . okay, I'll just put my patch notes and close this.

**Comment by nathandunn** [comment]
Closing in favor of #992
